### ISSUE TITLE
Problemas conectandose a postgresql con psycopg2 (Ubuntu 20.04)

### ISSUE THREAD

**Issue by jordonezp** [IIC2413/Syllabus-2020-2#1]
Hola, 
Estoy siguiendo la [Instalación Local de PostgreSQL y psycopg2](https://github.com/IIC2413/Syllabus-2020-2/wiki/PostgreSQL-y-psycopg2), pero en la parte ``Probando que todo funciona bien!`` me tira un error. Cuando intento colocar la clave del usuario me arroja el error:
```
FATAL:  password authentication failed for user "jorge"
```
Intenté creando nuevos roles y buscando en internet pero lo que encontré es basicamente lo mismo que lo que sale en el instructivo que menciono y no me funcionó nada. ``psycopg2`` parece estar correctamente instalado, al igual que ``Postgresql``. Adjunto algunas imagenes para que se entienda major mi situación.
Espero que me puedan ayudar! De antemano muchas gracias

![Screenshot from 2020-08-13 11-17-06](https://user-images.githubusercontent.com/53804102/90153140-9a11b880-dd56-11ea-9c02-70548b7ffea7.png)
![Screenshot from 2020-08-13 10-56-20](https://user-images.githubusercontent.com/53804102/90150488-b7915300-dd53-11ea-86ba-28417301ff1e.png)

**Comment by danustilovsky** [comment]
Hola, generalmente el usuario que se crea por default es "postgres" y la password es la que te pidio durante la instalacion. Podrias intentar con esos datos y ver si funciona!

**Comment by jordonezp** [comment]
Gracias por la pronta respuesta! Lamentablemente esto tampoco funcionó. Dejo de imagenes de lo que obtengo:
![Screenshot from 2020-08-13 12-01-07](https://user-images.githubusercontent.com/53804102/90158318-de07bc00-dd5c-11ea-87c2-d8ad8b4ec263.png)
Al ingresar la clave correspondiente nuevamente me arroja el error: (estoy segurisimo que es la clave correcta)
``
FATAL:  password authentication failed for user "postgres"
``

**Comment by juanreutter** [comment]
Entonces te puedes meter a psql por fuera con el usuario postgres y tu clave? Si es asi, quiza tienes postgres seteado para bloquear todas conexiones.

**Comment by danustilovsky** [comment]
Esta tratando en mi computador y pude arreglarlo.

* Primero tienes que levantar el localhost de postgres: **_sudo service postgresql start_**
* Despes debes crear un usuario con clave:

1. **_sudo su - postgres_**
2. **_createuser --interactive --pwprompt_**
Primero te va a pedir el usuario, luego la password y finalmente te va a preguntar si quieres que sea super user y respodes "y"

* Una vez creado el usuario, puedes utilizar esos datos para conectarte desde python

Avisame si te funciona!

**Comment by jordonezp** [comment]
Ahora me funciona. Muchísimas gracias por tu ayuda!!
