### ISSUE TITLE
Join sobre relacion hecha con join.

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2413/Syllabus-2020-2#10]
Hola, tengo una duda, si tengo una tabla con atributos hechos de dos relaciones y todos mis atributos son del tipo "algo1.algo2" y necesito hacer join de dicha tabla con otra, como tengo que expresar los atributos en la condicion del join?... se me ocurre asi "algo3.algo1.algo2".

De antemano, muchas gracias.

**Comment by arpincheira** [comment]
Hola, 
para poder evitar eso yo te recomendaría renombrar la tabla que creas a partir del Join, así evitarías tener que hacer referencias con el estilo que indicar(que al final de cuentas solo complican las cosas). Con respecto a lo de expresar los atributos, si bien eso no es estrictamente necesario(dado que se pueden intuir) yo te recomiendo hacerlo por temas de orden, dado que así facilitarías de cierta forma lo que vendría siendo la corrección y a su vez puedes visualizar de mejor manera los elementos de unión.

Espero haberte ayudado.

**Comment by DiegoPibe** [comment]
Entendido, muchas gracias de nuevo.
