### ISSUE TITLE
Borrar carpeta vacía en el servidor

### ISSUE THREAD

**Issue by dweinstein1** [IIC2413/Syllabus-2020-2#100]
Hola,

Quería saber como borrar una carpeta vacía que cree en el servidor con el comando ```mkdir``` .
No puedo borrarla utilazando el comando ``` git rm -r Entrega1 ``` ni tampoco ``` git rm -r Entrega1/ ```
Quiero borrarla porque no sé como subir mi entrega a esa carpeta en el servidor y es más facil crear la carpeta en mi repositorio privado, y luego hacer git pull en el servidor. 

Saludos! 

![image](https://user-images.githubusercontent.com/53883154/91763536-b8274780-eba3-11ea-9cda-e1dea146cb76.png)

**Comment by arpincheira** [comment]
Hola, probaste usando el comando ```rm -R -F Entrega1```?

**Comment by dweinstein1** [comment]
Acabo de probarlos y no me funcionaron 
Adjunto pantallazo

![image](https://user-images.githubusercontent.com/53883154/91764022-8cf12800-eba4-11ea-95f8-e1a6d8d6a4fc.png)

**Comment by arpincheira** [comment]
Hola, perdón, el comando es ```rm -R -f Entrega1``` por accidente puse una f mayúscula cuando debería ser minúscula

**Comment by dweinstein1** [comment]
Ahí si funcionó! Muchas gracias!
