### ISSUE TITLE
Base de datos del servidor 

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2413/Syllabus-2020-2#101]
Hola! Una consulta como se puede visualizar la base de datos del servidor desde pgAdmin4 ????
Lo que pasa es que al ingresar me muestra solo estas:
![Captura de pantalla (62)](https://user-images.githubusercontent.com/62029138/91768530-b9f50900-ebab-11ea-9cdb-4046b45cb137.png)

**Comment by danustilovsky** [comment]
Hola!

Para poder ver las bases de datos que estan en el servidor debes conectarte a este. Aqui te dejo un tutorial en el que muestran como se puede hacer.

https://docs.bitnami.com/aws/apps/noalyss/administration/configure-pgadmin/

**Comment by RonaldoSosa** [comment]
Yaaaa muchas gracias !!!!
