### ISSUE TITLE
Error en el pull del servidor

### ISSUE THREAD

**Issue by YoGandalf** [IIC2413/Syllabus-2020-2#102]
Después de hacer [git remote add origin] quise hacer el [git pull origin master] pero me tira este error:
[fatal: unable to access 'http://codd.ing.puc.cl/~grupo18/index.php/': Failed to connect to codd.ing.puc.cl port 80: Connection refused]
He tratado de averiguar como solucionarlo pero no he encontrado nada

**Comment by arpincheira** [comment]
Hola, podrías mandar una captura de pantalla de tu error, es muy extraño dado que no deberían tener un index.php creado en el servidor

**Comment by YoGandalf** [comment]
Ya lo solucione! Habia conectado las cosas al reves.
