### ISSUE TITLE
Ingreso al servidor

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2413/Syllabus-2020-2#103]
Hola!No he logrado ingresar al servidor recientemente esto es debido a que ya paso la fecha de entrega de la "Entrega1"?

**Comment by arpincheira** [comment]
Hola, efectivamente, el servidor estará bloqueado hasta nuevo aviso

**Comment by RonaldoSosa** [comment]
Entendido!Gracias!!!

**Comment by arpincheira** [comment]
Hola, el servidor está desbloqueado actualmente, aviso para cerrar el hilo de la issue más que nada
