### ISSUE TITLE
Diagramas ER

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#107]
Hola, pueden recomendar alguna aplicación o página web que permita crear Diagramas ER como lo hacen en las slides de las clases¿?. debemos seguir la misma estructura?
![image](https://user-images.githubusercontent.com/59337116/92164708-c6739e80-ee03-11ea-85ee-0df70dffb34f.png)

**Comment by pbyoma** [comment]
Te recomiendo draw.io Y a que te refieres con seguir la misma estructura?

**Comment by arpincheira** [comment]
Hola, una de las que más recomiendo es [draw.io](draw.io). De todas formas hay varias otras aplicaciones, creo que [lucichart](https://www.lucidchart.com/pages/es/ejemplos/herramienta-ERD) te podría servir. 

Espero haberte ayudado

**Comment by mariajesusbraun** [comment]
En draw.io igual puedes ponerle colores!!

**Comment by Camila-sty** [comment]
Gracias!!

**Comment by castrillini** [comment]
También serviría la página web diagrams.net :)
