### ISSUE TITLE
Duda diagrama ER

### ISSUE THREAD

**Issue by edovtp** [IIC2413/Syllabus-2020-2#108]
Hola, tengo una duda sobre "buenas prácticas" para el diagrama ER. Suponiendo que tengo una entidad A que tiene atributos a1, a2, a3, y que de esa entidad puedo sacar dos entidades B y C, pero que ningua de estas entidades tenga atributos nuevos, si no que más bien necesito que ambas se relacionen con alguna otra entidad X, pero de manera diferente, ¿entonces es necesario colocar la entidad A y luego hacer el _is a_ a ambos?, o, en este caso, al no tener atributos nuevos, ¿debiera colocarlos ambos por separado, cada uno con los mismos atributos, sin la necesidad de A?

**Comment by arpincheira** [comment]
Hola, en ese caso específico te recomiendo fuertemente pensar en el caso de que, eventualmente, alguien podría pensar en añadirle un atributo adicional a las entidades B y C, dado que son de tipos diferentes. Entonces, considerando eso, podrías entonces simplemente crear las entidades B y C que tuvieran solo su identificador y una A que posea los atributos que ambas tengan en común. 

Por otro lado, si no realizas herencia, tendrías dos tablas que comparten atributos y que no están conectadas entre si, entonces, si quieres realizar un cambio en uno de los atributos, deberías entonces encontrar el atributo en ambas tablas para poder realizar este cambio, lo que sería altamente ineficiente, mientras que al decender de A, solo deberías realizar cambios en una única tabla.

Espero haber contestado tu duda.
