### ISSUE TITLE
Duda Control 1 [Formato]

### ISSUE THREAD

**Issue by josejimenezp** [IIC2413/Syllabus-2020-2#11]
Hola, quería saber si es que hago un renombramiento, por ejemplo en la pregunta 2, y la quiero ocupar en otras preguntas posteriores ¿debo copiarlo en cada pregunta que lo use o se da por definido anteriormente?

**Comment by arpincheira** [comment]
Hola,
con respecto a la situación que mencionas, puedes definirla varias veces a lo largo de las preguntas o poner un apartado en el que indiques que las tablas definidas ahí serán utilizadas a lo largo de las distintas consultas. Lo que no debería pasar es que des por hecho que al definirlo en una consulta específica se pueda seguir utilizando para las otras, esto principalmente porque dificulta la corrección y es de cierto modo una mala práctica, dado que tus respuestas no serían tan fáciles de comprender por terceros(lo que es el objetivo al realizar operaciones en álgebra relacional).

Espero haber respondido tu duda.
