### ISSUE TITLE
Diagrama E/R - Foreign Key

### ISSUE THREAD

**Issue by vblopez** [IIC2413/Syllabus-2020-2#110]
Hola, una relacion puede tener varias foreign keys? o podría tener una primary key y a la vez una foreign key?, en el ejemplo del control 1 de las viñas, en SeVisita habia una primary key y a la vez habian 2 foreign Key o no, de ser cierto esto, como se escribiria el esquema? Gracias

**Comment by danustilovsky** [comment]
Hola! lo que dices esta bien. En el diagrama simplemente se agregan dos Fk por ejemplo _SeVisita( sid int Primary key, tid int Foreign Key, vid int Foreign key)_
