### ISSUE TITLE
Dudas sobre como subir archivo php a Sites

### ISSUE THREAD

**Issue by mafernandez9** [IIC2413/Syllabus-2020-2#116]
Hola! como grupo estamos viendo como subir archivos con github al servidor y no entendemos como subir el archivo .php para que se vea en sites. Muchas gracias de antemano!

**Comment by danustilovsky** [comment]
Hola, Para subir archivos a su servidor deben realizar el mismo proceso que para la entrega 1. Dado que ya deberian tener el github linkeado con su carpeta en el servidor, basta con que agreguen sus archivos .php a una carpeta Sites y que hagan push a github. Luego ingresan al servidor, hacen pull y deberia aparecer sus archvios en Sites.
