### ISSUE TITLE
Entrega 2

### ISSUE THREAD

**Issue by CataSudo** [IIC2413/Syllabus-2020-2#117]
Hola! Si queremos crear algo tipo id de Atraques pero no se encuentran en los datos, ¿Se puede hacer o sólo se pueden ocupar los datos entregados?
Muchas gracias

**Comment by arpincheira** [comment]
Hola, efectivamente en el caso de que un id que encuentren necesario no aparezca explícitamente en el dataset, lo pueden crear ustedes.

Les recomiendo crearlo en el orden en el que aparecen en los datasets eso si, y ojo con las repeticiones de datos, pues si se repiten el id que debería prevalecer es el primer id asignado.

Espero haber contestado su duda
