### ISSUE TITLE
Postgres.app MacOS

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2413/Syllabus-2020-2#118]
Hola! Estoy intentando crear un nuevo servidor como dice en el tutorial de Postgres.app en MacOS, pero me tira un error cada vez que intento inicializa. He buscado en muchas partes y ninguna solución me ha servido :(
![Captura de pantalla 2020-09-08 a la(s) 16 14 38](https://user-images.githubusercontent.com/48481963/92518294-78d5a800-f1ee-11ea-8059-5f836e7582b6.png)

**Comment by arpincheira** [comment]
Hola, no es estrictamente necesario que crees un nuevo servidor dado que tu aplicación ya posee uno denominado postgres que es el causante de tu error.

Lo que si puedes hacer para poder probarlo, es crear bases de datos con el comando ```CREATE DATABASE <nombre>;``` y trabajar desde ahí.

De todas formas voy a dejar los pasos para hacerlo:

#### Desde la consola
1. abres la consola de tu computador
2. ejecutas el comando ```psql```
3. una vez ahí escribes ```CREATE DATABASE <nombre>;``` (**Ojo** que no se te olvide el ;)
4. usas el comando ```\c <nombre>``` una vez ahí puedes trabajar con tu database.

#### Usando Postgressapp
1. abres la Postgressapp
2. seleccionas una de las database que vienen por defecto(los cilindro).
3. una vez ahí se te abrirá una terminal y en ella escribes ```CREATE DATABASE <nombre>;``` (**Ojo** que no se te olvide el ;)
4. usas el comando ```\c <nombre>``` una vez ahí puedes trabajar con tu database.

La gracia de postgres app es que para acceder a las databases solo necesitas un click y listo, además te permite manejar de mejor manera aquellas databases que tienes creadas en tu computador.

Espero que esto te sirva.

**Comment by beatrizacuna** [comment]
Sii! muchas graciaaas, lo que pasaba es que nunca cerré el que había iniciado en otro ramo (ingeniería de software).
