### ISSUE TITLE
Llaves foráneas

### ISSUE THREAD

**Issue by smrebolledo** [IIC2413/Syllabus-2020-2#119]
Si en un esquema (A) ocupo la llave de un esquema (B) pero en el esquema (A) no la estoy ocupando como llave igual debo escribirla como llave foranea?
Por ejemplo tengo una tabla Personas donde la llave es "rut" y luego otra tabla Mascotas donde la llave es "nombre mascota" pero lo asocio al rut de una Persona.

**Comment by mariajesusbraun** [comment]
Hola! Sí, esa es la idea de las llaves foráneas.

**Comment by smrebolledo** [comment]
Y si en un esquema (C) ocupo llaves de los esquemas (A y B) lo escribo como FOREIGN KEY (idA, idB) o separados?

**Comment by mariajesusbraun** [comment]
Separados!

**Comment by smrebolledo** [comment]
Graciaas
