### ISSUE TITLE
Duda con renombrar Tablas (rho)

### ISSUE THREAD

**Issue by based-on-what** [IIC2413/Syllabus-2020-2#12]
Hola, en el sitio web de RelaX (el que usó el profesor Vrgoc durante la clase de hoy), he estado intentado renombrar **una tabla** para poder usarla, así lo hago yo:
![relax](https://user-images.githubusercontent.com/62000495/90714319-69a9ad00-e275-11ea-96b3-5724dd9f8b23.PNG)

La primera línea cuando no hay nada más escrito funciona bien (entrega la misma tabla con los atributos cambiados al nombre que escribí), pero al momento de escribir cualquier otro código debajo me entrega el mensaje de error, ¿en qué estoy fallando en la sintaxis que me impide continuar con la operación?

Saludos y gracias.

**Comment by danustilovsky** [comment]
Hola! 

Haz intentado escribir todo en una sola linea?

**Comment by agustin-rios** [comment]
Hola! En Relax el codigo toma todo como si fuera una misma linea, o como una misma operación, por lo que ese tipo de operaciones no se puede hacer más que por separado.

**Comment by agustin-rios** [comment]
Lo que puedes hacer es meter ambas lineas en la misma operacion

**Comment by based-on-what** [comment]
@danustilovsky @agustin-rios 

¡Gracias! Con el primer comentario funcionó como quería.
