### ISSUE TITLE
Duda sobre navieras PAR

### ISSUE THREAD

**Issue by mariagonthier** [IIC2413/Syllabus-2020-2#120]
Hola! ¿Existe la posibilidad que dos navieras distintas se llamen igual?

**Comment by pbyoma** [comment]
No existen dos navieras que se llamen igual, sin embargo, si lo preguntas para ocuparlo como PK, no te lo recomiendo ya que es poco realista y se les puede complejizar tarea futura

**Comment by mariagonthier** [comment]
Gracias por el tip!!!!!

**Comment by BenjaLepe** [comment]
Hola, pero entonces si el nombre no sirve como Primary Key, sería posible utilizarlo para una dependencia funcional? Por ejemplo,  que el país de origen dependa del nombre de la Naviera. Porque siento que muchas cosas podrían depender del nombre también y no solo del ID de la Navieras.

**Comment by DiegoPibe** [comment]
Claro, pienso igual que @BenjaLepe, en el fondo agregar un id seria la única otra forma pero vimos en clases que llenar de id's no es buena idea.
