### ISSUE TITLE
Duda Entrega 2 

### ISSUE THREAD

**Issue by BenjaLepe** [IIC2413/Syllabus-2020-2#121]
Hola!

Que tan recomendable es utilizar una Patente o un RUT como llave primaria? Creo que ambos se consideran como varchar. 

Otra duda que tengo, es que, si elijo el ID como primary key pero la Patente sigue siendo un atributo único. Todos los atributos son funcionalmente dependientes del  ID y la patente, pero como la patente no es una primary key, entonces habría una incongruencia en la tabla. En este ultimo caso debería crear una tabla con las patentes aparte o hacer tablas apartes con los demás atributos? 

PD: Estamos haciendo la justificación en 3nf

**Comment by arpincheira** [comment]
Hola, 
efectivamente podrías considerar tanto la patente como rut como llaves primarias, el único tema es que ocuparías más espacio en memoria al momento de almacenarlos dado que son varchar, pero en un problema como el del proyecto esto no debería influir mucho tampoco.

Con respecto a tu segunda pregunta, efectivamente ocurrriría un problema, dado que la patente no depende necesariamente del id. En este caso según mi parecer posees dos opciones, subordinar de cierto modo la patente al id, creando una relación 1 es a 1 entre ellas o considerar al conjunto  id, patente  como una primary key en conjunto, pues ninguna de las dos por si sola sería minimal, dentro de una misma tabla, así que al considerar **solo** una de ellas como primary key dentro de la tabla donde exista la otra estaría incumpliendo 3nf.

Así que queda a tu criterio, en lo personal recomendaría modelarlo con bcnf y elegir una de las dos como llaves primarias o dejar patente como llave primaría única y basar los datos según esto.
