### ISSUE TITLE
Llaves Foraneas

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2413/Syllabus-2020-2#122]
Hola, como represento una llave foránea en los esquemas relacionales ?
Así como las llaves clave se ponen subrayadas.

De antemano, muchas gracias.

**Comment by mariajesusbraun** [comment]
Hola! `FOREIGN KEY <(atributo)> REFERENCES <entidad>`

**Comment by DiegoPibe** [comment]
Ahhh Ok, es igual que en SQL gracias.

**Comment by pbyoma** [comment]
También podrían ocupar un código de color para las distintas llaves o pueden ponerles FOREING KEY como con las primary keys, ahí vean ustedes, solo deben dejar claro en el informe lo que van a ocupar y que sea el mismo criterio para todas las tablas
