### ISSUE TITLE
Duda relación instalaciones/personal

### ISSUE THREAD

**Issue by lewebe** [IIC2413/Syllabus-2020-2#123]
Hola, es buen diseño poner dos relaciones distintas que unan las entidades "instalaciones" con "personal" considerando que una indica el jefe de la instalación (cuya mutiplicidad es uno a uno) y la otra indica todo el personal que trabaja en esa instalación (multiplicidad uno a varios)? O sería mejor dejarlo con una sola relación y a esa darle un atributo booleano que indique si la persona es jefe de esa instalación o no?

**Comment by pbyoma** [comment]
Hola!! Si se podría poner dos relaciones entre dos entidades, tengan ojo con las cardinalidades eso si. Las dos opciones son correctas, ahí tienen que ver cual les funciona mejor.
Espero que les ayude mi respuesta :)
