### ISSUE TITLE
Representar un IsA en BCNF

### ISSUE THREAD

**Issue by mariagonthier** [IIC2413/Syllabus-2020-2#124]
Hola! ¿Cómo se representan en dependencias BCNF cuando una entidad es 'madre' de más de una entidad?
Ej. Perro y Gato heredan de Mamíferos. ¿Cómo se representa que Mamífero implica Gato o Perro pero no ambos a la vez?
Gracias :)

**Comment by arpincheira** [comment]
Hola, en este caso se representaría de la siguiente manera
**Mamíferos**
**mamifero_id** -> atributos_directos
**Gato**
**mamifero_id, gato_id** -> atributos gato
**Perro**
**mamifero_id, perro_id** -> atributos perro

Lo otro que podrías hacer es poner en la justificación de dependencias solo el perro_id/gato_id, dado que así justificarías las dependencias de la tabla misma.

**Comment by mpbascunan** [comment]
Pero si mamifero_id es Foreign key,  entonces habría que ponerla explicitamente como primary key en las tablas perro/gato, quedando mamifero_id y perro_id/gato_id como una tupla que es llave?

**Comment by tavalenzuelag** [comment]
Tengo la misma duda! No sé si poner la foreign key también como Primary key o si se puede obviar en cuanto a la dependencia funcional.

**Comment by arpincheira** [comment]
Hola, la desición a su pregunta siempre va a recaer en ustedes y en como lo justifiquen en el informe. De todas formas lo más recomendable por lejos es utilizar siempre una sola llave primaria dado que así evitas poner tuplas como llaves foráneas a aquellas tablas que posean algún tipo de relación en este caso con perro o gato. En resumen, **prefieran una llave primaria y una llave foránea** cuando hagan herencia, antes que asignar dos llaves primarias a una tabla.

**Comment by tavalenzuelag** [comment]
Gracias! De todas formas mi pregunta va un poco más enfocada al problema de las dependencias funcionales. Qué pasaría si las foreign key fueran capaces de explicar al resto de los atributos? Tendría que separar en más tablas?
