### ISSUE TITLE
Representación BCNF en Diagrama

### ISSUE THREAD

**Issue by mariagonthier** [IIC2413/Syllabus-2020-2#125]
Hola! ¿Hay que representar todas las descomposiciones BCNF en el diagrama?
Por ejemplo, en clases vimos que la entidad MAL tenía atributos cine, película, director, dirección, precio, teléfono , horario
y como esto no cumplía las normas BCNF lo descompusieron en 3 relaciones. Entonces, ¿Estas tres relaciones reemplazan a MAL en el diagrama, o se puede dejar MAL asumiendo que en la justificación de la entrega se descompone?

**Comment by arpincheira** [comment]
Hola, MAL es una tabla que se encuentra mala, por ende dejarlo en el diagrama implicaría un problema en el como modelas el problema, dado que lo que posees en el diagrama corresponde a como lo vas a modelar finalmente en la base de datos. 

Lo que se debe hacer en este caso es generar 3 tablas a partir de las relaciones que se acaban de formar y estas además estarían por defecto en BCNF, que es lo que finalmente se quiere para tu base de datos.
