### ISSUE TITLE
Falta Instalación 122 grupo impar

### ISSUE THREAD

**Issue by hebusch** [IIC2413/Syllabus-2020-2#126]
Hola buenas, al importar los datos a la base de datos me saltó un error de FOREIGN KEY al decirme que no existe la instalación 122, sin embargo, si hay personal que trabaja en él.
Esta instalación tenemos que completarla nosotros?

De antemano, muchas gracias

**Comment by arpincheira** [comment]
Hola, efectivamente faltaba incluir ese dato, muchísimas gracias por notarlo.

Para solucionar el caso que mencionas debes añadir la siguiente línea al archivo puertos.csv
```
122,astillero,3,Penco,Penco,Biobio,18902520-3,2019-12-09 12:58:40,2019-12-20 22:22:29,25844754-9
```
Pronto actualizaremos los archivos en el repositorio y mandaremos un anuncio indicando el error.

Gracias nuevamente

**Comment by hebusch** [comment]
Muchas gracias!😁
