### ISSUE TITLE
Puerto que ha recibido más barcos Consulta 6 Grupo Impar

### ISSUE THREAD

**Issue by GabrielAguirre3** [IIC2413/Syllabus-2020-2#127]
Buenas, con mi compañero nos preguntamos, si en esta consulta que dice "Muestre el puerto que ha recibido más barcos en Agosto del 2020", que pasa si un barco atraca más de una vez en el mismo puerto, esto se cuenta o solo es una vez en el recuento.

De antemano, muchas gracias

**Comment by arpincheira** [comment]
Hola, que bueno que preguntaste, la respuesta es: **solo cuentan si son distintos**.

Lo sucede para **la consulta 6 de los grupos pares** por si es que están viendo esta respuesta.

Saludos

**Comment by GabrielAguirre3** [comment]
Muchas gracias!

**Comment by naviera** [comment]
Hola! No entiendo cómo esto aplica para la consulta 6 de los grupos pares.
Saludos

**Comment by arpincheira** [comment]
Hola, es en parte error mío, en ese momento tenía sentido jajaja, me refería a que cuando dice más personas trabajando, se buscara más personas distintas trabajando, pero en ese caso es indiferente porque una persona no puede trabajar dos veces en el mismo buque pesquero jajaja. Lamento las molestias que pudo causar este error.
