### ISSUE TITLE
Consultas case-insensitive

### ISSUE THREAD

**Issue by jaimecoloma** [IIC2413/Syllabus-2020-2#128]
Hola! Se debe poder diferenciar las consultas, pero esto solo para efectos de la pagina y todo lo relacionado a php o no? Las consultas en Postgres que se entregan importan?

**Comment by arpincheira** [comment]
Hola, efectivamente esto lo deben considerar tanto para las consultas SQL que se entregan en el informe como en lo que respecta al funcionamiento en la página. Aunque la verdad si son capaces de hacer las consultas del informe lo más probable es que logren hacer fácilmente las consultas de la página(dado que son las mismas).
