### ISSUE TITLE
Duda clase dependencias

### ISSUE THREAD

**Issue by fbarrosalcalde** [IIC2413/Syllabus-2020-2#129]
Hola, tengo una duda respecto a la clase de dependencia. El profesor dijo que si uno tiene dos entidades y una relación como en el siguiente caso: entidades: supermercado y bodega, relación: tiene, uno puede agregar el atributo de la patente del supermercado a la entidad bodega y eliminar la tabla de la relación tiene. Mi pregunta es: la relación “tiene” en el modelo E/R también se elimina (osea habría solo una flecha que apunte de bodega a supermercado), o solo se elimina la tabla de la relación, pero la relación sigue existiendo(bodega—tiene—>supermercado?

**Comment by arpincheira** [comment]
Hola, tal como dices, la relación “tiene” ya no debería tener una tabla propia, pero debería seguir existiendo en el diagrama e/r para mostrar la relación existente entre las entidades.

**Comment by fbarrosalcalde** [comment]
Perfecto, gracias!
