### ISSUE TITLE
[Control 1] Vid 5

### ISSUE THREAD

**Issue by Baelfire18** [IIC2413/Syllabus-2020-2#13]
![image](https://user-images.githubusercontent.com/50716449/90715449-43d1d780-e278-11ea-8b55-f4d92efd7a73.png)
Hola, es un erro de la base de datos? Debemos nosotros rellenar esta tupla?

Otra cosa, podrian porfavorcin tirase un HINT para la 3? Ya que si usar el coun() es dificil

**Comment by arpincheira** [comment]
Hola, 
efectivamente es un typo, esto se menciona en la issue #8 con mayor claridad. Con lo que respecta a un **Hint** para la consulta 3... esta es una de las consultas más difíciles del control a mi parecer, yo solo puedo decir que una de las maneras para poder solucionarla es considerando el uso del operador - en conjunto con otros operadores, decir más información sería darte la respuesta a mi parecer.

Espero haberte ayudado aunque sea un poco.
