### ISSUE TITLE
itinerarios.csv (Par)

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2413/Syllabus-2020-2#130]
Hola, no entiendo bien la interpretación que tengo que hacer de este excel, las filas que no tienen fecha de salida tienen la fecha estimada del próximo atraque y el próximo puerto y las que si tienen fecha de salida son registros de atraque ??

de antemano, muchas gracias.

**Comment by arpincheira** [comment]
Hola, efectivamente la idea es que ustedes deben procesar los datos, para esto deben crear nuevos archivos csv con los atributos que a ustedes les interesan obtener(que vienen definidos por los modelos que han decidido crear en su esquema) y una vez creados estos, deben poblar las tablas creadas en la base de datos del servidor con los datos que consideraron en los csv.

Saludos

**Comment by arpincheira** [comment]
Y con respecto a tu pregunta misma, tienes razón, lo que puedes suponer es que todos los barcos que lleguen van a salir idealmente exactamente a la semana siguiente en la que llegan(dado que en ningún momento se mencionó que existiera un historial y un próximo atraque o próximo puerto). Lo que puedes suponer es que todos esos atraques poseen como fecha de salida una fecha equivalente a **un día después de la fecha del atraque**, como tiempo ideal. 

De todas formas vamos a corregir esto en los datos, muchas gracias por notarlo.

**Comment by DiegoPibe** [comment]
Ok gracias, creo que no entendí muy bien, intentare explicar lo que hice para ver si es correcto.

El archivo itinerarios.csv tiene fecha_atraque, fecha_salida y nombre_puerto (independiente del buque). Tengo 2 tablas una para atraques y otra para el itinerario, lo que hago es decir que las filas que si tienen fecha de salida son un atraque que ya pasó, en donde el buque llego al nombre_puerto en la fecha_atraque y se fue en la fecha_salida, mientras que las filas que no tienen fecha de salida son itinerarios, en donde existe un buque (da igual donde este) que tiene como destino el nombre_puerto y se espere que llegue en la fecha_atraque.

Es eso correcto?

De antemano, muchas gracias. (sorry lo largo).

**Comment by arpincheira** [comment]
Hola, lamento mucho la confusión, fue un error mio jajajaja, lo que decías inicialmente es correcto, existe efectivamente un atraque que posee fecha atraque y fecha salida y un prox itinerario que no posee fecha salida, solo fecha llegada. Es por esto mismo que lo que haces efectivamente es correcto. A lo que me refería en mi primer comentario era que tu debes hacer un script que lea los archivos csv y cree nuevos archivos csv solo con la información que te interesa, para poder así poblar tu base de datos(esto es el procesamiento de los datos al que me refería anteriormente).

Nuevamente, lamento mucho mi equivocación jajajaja, ya eliminé de cierta forma mi comentario anterior para evitar confusiones futuras.

**Comment by DiegoPibe** [comment]
sisi gracias eso lo habia entendido, de todos modos aclaraste mi duda y gracias jaja.
