### ISSUE TITLE
Duda con framework para procesamiento de los csv

### ISSUE THREAD

**Issue by nicoguz** [IIC2413/Syllabus-2020-2#131]
Hola!
Tengo una duda sobre que herramientas se pueden usar para el procesamiento de los datos. Es necesario que sea algo de SQL? o se puede usar algo como pandas?

**Comment by arpincheira** [comment]
No es necesario que sea algo de SQL. Pandas es una muy buena herramienta que puedes utilizar, cuidado eso si con el uso de dropna(), dado que hay **algunos archivos csv que intencionalmente poseen filas con campos vacíos** para que ustedes los identifiquen y clasifiquen los datos de esas filas correctamente. 

Espero haber contestado tu duda.

**Comment by nicoguz** [comment]
Perfect, graciassss!!!
