### ISSUE TITLE
Consulta 4 Grupo Impar Ha atracado en 'Arica'

### ISSUE THREAD

**Issue by GabrielAguirre3** [IIC2413/Syllabus-2020-2#132]
Buenas, con mi compañero nos preguntamos, si en esta consulta que dice "Muestre todas las veces en que el barco 'Calypso' ha atracado en 'Arica' ", con Arica se refieren al nombre del Puerto, de la Ciudad o de la Región, o una unión de estos tres, ya que en el caso de Arica, el nombre de puerto y ciudad coinciden, pero con otros nombres esto no pasa.

De antemano, muchas gracias

**Comment by arpincheira** [comment]
Muy buena pregunta, **se refiere a la ciudad**, pues la región se llama Arica y Parinacota.

**Comment by GabrielAguirre3** [comment]
Muchas gracias!

**Comment by smrebolledo** [comment]
En este caso atracar implica que llega a un astillero o tambien puede ser a un muelle?
