### ISSUE TITLE
Duda dependencias

### ISSUE THREAD

**Issue by fbarrosalcalde** [IIC2413/Syllabus-2020-2#133]
Hola, si tengo una entidad como la siguiente:
A(a(llave),b,c,d), donde las dependencias son las siguientes:
a->b,c,d
d->a
En este caso, la entidad “A” cumpliría con 3NF? Si es que no, qué puedo hacer para que cumpla con 3NF o con BCNF?
Y otra cosa, para la entrega, me tengo que preocupar que al hacer un join entre entidades, se cumpla también que la tabla resultante este en 3NF o BCNF? Gracias!

**Comment by arpincheira** [comment]
Hola, con respecto a su primera pregunta, ese es un caso muy genérico por lo que tendrían que detallarlo un poco más para entender a lo que se refieren de manera correcta. De todas formas voy a tratar de explicar lo que sucedería en ese caso:

Supongamos que tenemos un ejemplo más aterrizado con ciudades, países y continentes. En este caso tenemos una tabla ciudades que posee lo siguiente

A(a(PK), b, c, d)
y que d -> a

En este caso se da lo denominado **dependencia transitiva**, esto implicaría que tienes
d -> a -> b,c

Ahora, la idea de 3NF(mejor conocido como la tercera forma normal) es que no existan estas dependencias transitivas. 
Cómo solucionan esto?

Lo que deberían hacer en este caso es crear dos tablas, la primera que sea d -> a y la segunda que sea a -> b, c  dado que tanto d como a son llaves candidatas. Así también estarían disminuyendo lo que viene siendo la redundancia.

Si quieren más información al respecto les recomiendo (este link)[http://mysql.conclase.net/curso/?cap=004b#:~:text=Dependencia%20funcional%20transitiva&text=Definici%C3%B3n%3A%20Supongamos%20que%20tenemos%20una,pero%20Y%20no%20determina%20X.] dado que explican paso por paso como normalizar una tabla a partir de un ejemplo práctico como lo son las ciudades, los países y los continentes.

Espero haber contestado tu duda

**Comment by fbarrosalcalde** [comment]
Oka muchas gracias!

**Comment by fbarrosalcalde** [comment]
Mi caso concreto era el siguiente:
Instalaciones(id(llave), nombre_puerto, tipo, capacidad, rut_jefe). En este caso, si yo sé el id de la instalación, conozco: nombre_puerto, tipo, capacidad y rut_jefe. También, si yo sé rut_jefe, conozco el id de la instalación. Cuál sería la mejor forma de modelarlo en este caso?

**Comment by arpincheira** [comment]
Hola, en primer lugar, tu respuesta fue censurada para no dar respuestas de la entrega, más cuidado a la próxima.

En primer lugar no te recomendaría utilizar el nombre del puerto como llave primaria pues nada te puede asegurar de perseguir que sea único(aunque en este caso lo sea) y es mucho más fácil trabajar con ints como id que con varchars pues ocupan menos espacio en memoria y pueden implicar menos errores.

En tu caso específico te recomiendo fuertemente pensar en el uso de herencia envés de utilizar el atributo tipo, en el caso del rut del jefe no puedes saber si es jefe de solo una, por lo que en este caso si cumplirías con BCNF. Mucho ojo en lo que dije sobre el tipo.

Espero haberte ayudado

**Comment by fbarrosalcalde** [comment]
Ya perfecto, es que en el enunciado de la primera entrega salía que cada persona trabajaba en una sola instalación, entonces pensé que una persona podía ser jefe de una sola instalación. Osea una persona puede trabajar en una sola instalación, pero ser jefe de más de una?

**Comment by fbarrosalcalde** [comment]
Ya gracias!

**Comment by arpincheira** [comment]
O.o muy buena acotación, efectivamente se puede suponer que una persona sea jefe/a de más de una instalación, lo que no sucede en nuestro caso, pero en un contexto real si se puede dar esto, además, en lo que respecta realmente a la distribución de datos no es el jefe mismo, pues este posee los atributos directos en la tabla de empleados, sino un atributo tal que sea capaz de describir de manera íntegra los datos de la instalación, en este caso su id.

**Comment by benjaguiloff** [comment]
Hola! En el enunciado de la entrega 1 dice en la sección de grupos impares 

> _Personal. El personal que trabaja en el puerto tiene un nombre, rut, edad y sexo._ **Cada persona trabaja en una sola instalación**_, y cada instalación tiene un jefe._

Aún así podríamos suponer que una persona puede ser jefe/a de más de una instalación?
