### ISSUE TITLE
Duda Poblar tablas

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2413/Syllabus-2020-2#134]
Hola, estoy intentando poblar las tablas que creamos pero me sale un error para algunas tablas (no todas)...

grupo110e2=> \COPY Atraques from 'Atraques.csv' DELIMITER ',';
ERROR:  invalid input syntax for integer: "﻿1"
CONTEXT:  COPY atraques, line 1, column aid: "﻿1"

Y no cacho que puede ser, porque me fije en python como modifique los csv y esta todo bien, aparte que me pase solo con algunas tablas. (Hay otras tablas que me pasa lo mismo pero con patentes que no son INT).

De antemano, muchas gracias.

**Comment by arpincheira** [comment]
Hola, tengo una duda, podrían mandar temporalmente una foto de un print de la primera línea de sus archivo csv con python?

**Comment by arpincheira** [comment]
Uff, lo que está sucediendo ahí es que tu archivo está codificado con UTF-8 y lo que puedes ver en este caso es lo denominado **UTF8 BOM**, que consiste en una secuencia de caracteres que permite identificar que tu archivo se encuentra codificado.

Por lo que tengo entendido hay varias maneras de solucionarlo, pero una de las que es más rápida y sencilla es que vuelvas a escribir la primera línea de tu archivo y que en el primer elemento de esta(en este caso el 1) omitas los primeros tres caracteres. Esto lo puedes hacer con

```python
# Si tu primera linea es una lista
primera_linea[0] = primera_linea[0][3:]
# Si tu primera linea es un string
primera_linea = primera_linea[3:]
```

De todas formas, si quieres investigar otras maneras de solucionar el problema eres libre de hacerlo, yo solo ofrezco una de las maneras más sencillas de hacerlo(a mi parecer).

Espero haberte ayudado.
