### ISSUE TITLE
Consulta sobre tabla E1

### ISSUE THREAD

**Issue by burgosibarra** [IIC2413/Syllabus-2020-2#135]
Hola!
¿Podemos eliminar la tabla que se creo en la entrega 1 o cambiar su nombre? Esto porque su nombre coincide con la tabla de nuestra entrega 2 y no queremos que sea problema para próximas evaluaciones.
Desde ya, muchas gracias!

**Comment by arpincheira** [comment]
Hola, si, no hay problema en que la borren, al final de cuentas están trabajando con la Database **grupoxxe2** que es independiente de la Database en la que trabajaron para la entrega 1
