### ISSUE TITLE
Duda de una consulta

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#136]
Hola, me surge una duda de la siguiente consulta:
![image](https://user-images.githubusercontent.com/59337116/93794947-26917f80-fc0f-11ea-88a7-6b86bfcd993e.png)
El jefe también se considera parte del personal?, ósea se podría pensar que por cada instalación hay dos trabajadores?

**Comment by arpincheira** [comment]
Hola, efectivamente en este caso **el jefe es parte del personal.** Con respecto al supuesto de dos trabajadores por instalación, este no es necesariamente correcto, pues, pese a que una persona solo trabaje en una instalación, al interior de esta última puede trabajar 1 o más personas(pueden ser 2,3,4,....)

**Comment by Camila-sty** [comment]
Ah ya entiendo, gracias...
