### ISSUE TITLE
Duda de consulta

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#137]
Hola, tengo una duda con respecto a la siguiente consulta:
![image](https://user-images.githubusercontent.com/59337116/93799130-1bd9e900-fc15-11ea-9ae9-c28ab27a60fa.png)
Cuando dice que queda a cargo de "algún trabajador", éste podría ser el jefe?

**Comment by castrillini** [comment]
Podría darse el caso en que, en alguna instalación, el jefe de ésta, también sea la persona que estará a cargo en su cierre.  Sin embargo, no hay nada que te pueda asegurar que esto pase para todas las instalaciones. Lo correcto es no asumir que ocurre esto para ningún caso.
