### ISSUE TITLE
Duda de consulta

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#138]
Hola, tengo una duda de la siguiente oración destacada:
![image](https://user-images.githubusercontent.com/59337116/93799686-dd90f980-fc15-11ea-9225-883bb281e0b1.png)
Con esto, se refiere a que es un permiso por instalación-barco ó un permiso para una instalación y otro permiso para un barco?

**Comment by castrillini** [comment]
Hola, esto quiere decir que cada permiso existente está asociado a sola una instalación en particular y, **al mismo tiempo**, a solo un barco en particular.
