### ISSUE TITLE
Cómo normalizar una tabla con id y patente

### ISSUE THREAD

**Issue by gustavo-toro** [IIC2413/Syllabus-2020-2#139]
Hola, lo que nos pasa es que habíamos hecho un esquema donde usábamos patente como llave primaria. En el feedback de la primera entrega nos sugirieron utilizar un id en vez de patente como llave para reducir la memoria. Tenemos la duda de cómo normalizar las relaciones porque tenemos dos llaves candidatas y quizás tendríamos que hacer una tabla aparte para relacionar patentes con ids y no violar BCNF.

Muchas gracias.

**Comment by arpincheira** [comment]
Hola, resulta ser que teóricamente los profes me explicaron que tener ID y patente únicos si estaría normalizado, dado que BCNF plantea que:

<img width="1201" alt="Captura de Pantalla 2020-09-21 a la(s) 17 45 25" src="https://user-images.githubusercontent.com/37157550/93819561-44241080-fc32-11ea-897a-2835332d0d56.png">

es decir, si hay una dependencia X -> Y, X tiene que ser superllave para que esté normalizado.

La definición de superllave dice que:

<img width="1210" alt="Captura de Pantalla 2020-09-21 a la(s) 17 46 26" src="https://user-images.githubusercontent.com/37157550/93819676-67e75680-fc32-11ea-965f-f2b7ee4d590d.png">

Entonces en este caso el par (ID, patente) es superllave, porque tiene la capacidad de determinar todo lo demás de manera inequívoca. Por lo tanto la dependencia es id, patente -> otros y la tabla sí está normalizada.

Finalmente puedes escoger cualquiera de los 2 como Primary Key, porque cada uno es llave candidata (superllave minimal). En general quieres escoger un ID numérico porque es más eficiente.
