### ISSUE TITLE
Duda tabla países

### ISSUE THREAD

**Issue by nicoguz** [IIC2413/Syllabus-2020-2#140]
Hola!
En el feedback de la entrega 1 nos recomendaron crear una tabla países pero hasta ahora solo tenemos como atributos los nombres de los países y las nacionalidades. Mi duda con esto es que la única forma de relacionar las nacionalidades con los países es 'a la mala' (crear un diccionario asociando cada nacionalidad a cada país) pero dado que son 157 nacionalidades es un tanto lento y siento que está mal modelado porque podrían aumentar las nacionalidades. Hay alguna otra forma de hacerlo asumiendo que no nos dan una tabla relacionando países con sus nacionalidades??

**Comment by pbyoma** [comment]
Holaa! Se te recomienda hacer una tabla país aparte ya que, las navieras y los buques tienen su pais correspondiente. La nacionalidad por su parte corresponde al personal. No te recomiendo mezclar la tablea pais con las nacionalidades, quizás te estas complicando más de la cuenta. 
Espero que te haya servido mi respuesta :)

**Comment by nicoguz** [comment]
Perfect, graciasss!!
