### ISSUE TITLE
Duda con archivo itinerarios.csv GRUPO PAR

### ISSUE THREAD

**Issue by nicoschwend** [IIC2413/Syllabus-2020-2#141]
Hola! 
En el archivo itinerarios.csv aparecen unos puertos con nombre "nombre", esas tuplas las eliminamos o las dejamos y las trabajamos así nomás.  
Gracias!

**Comment by arpincheira** [comment]
Hola, efectivamente existe un puerto con el nombre puerto, en este caso deben considerarlo y trabajar así nomás.
