### ISSUE TITLE
Herencia de entidades

### ISSUE THREAD

**Issue by Baelfire18** [IIC2413/Syllabus-2020-2#143]
Hola, si tengo una herencia (hecha según el modelo de entidad/relacion con Is A) a la hora de pasarla a SQL, ¿como se hace? ¿Se debe repetir la llave primaria y en el 'hijo' se toma como primaria y foranea a la vez? ¿O como es que s ehace con el tema de la 'herencia'?

**Comment by danustilovsky** [comment]
Hola! Lo que dices esta bien. En postgres se puede ocupar una Foreign key como primary key.

**Comment by Baelfire18** [comment]
Entonces es buena practica hacer que las entidades hijas tengan como primary y foren key la primary de la madre? Ok gracias

**Comment by danustilovsky** [comment]
En realidad la relacion IsA no esta estandarizada en SQL, por lo que no hay una unica forma correcta de hacerlo. Pero dado que simplemente es una especializacion, no hay problema que esta tabla tenga primary y foreign key iguales.
