### ISSUE TITLE
Ingresar al servidor

### ISSUE THREAD

**Issue by CataSudo** [IIC2413/Syllabus-2020-2#144]
Hola soy del grupo 30, y no puedo entrar al servidor desde mi computador pero mi compañero puede. ¿A que se debe este problema?

**Comment by danustilovsky** [comment]
Hola! Que error te aparece cuando intentas entrar?

**Comment by CataSudo** [comment]
<img width="439" alt="Screen Shot 2020-09-22 at 15 52 02" src="https://user-images.githubusercontent.com/62016215/93924884-bad11480-fceb-11ea-994f-ae38c9a1d844.png">
No me acepta la contraseña

**Comment by danustilovsky** [comment]
Estas segura que la contraseña con la que estas probando es la correcta? Porque si tu compañero puede entrar y tu no, tomando en cuenta el error, se puede deber a que tu compañero haya cambiado la contraseña o que la estes ingresando mal.

**Comment by CataSudo** [comment]
Sii, la contraseña no ha cambiado y revise con mi compañero para ver la constraseña que escribi bien.

**Comment by arpincheira** [comment]
Hola, han logrado solucionar el problema?

**Comment by CataSudo** [comment]
No, aun no se porque no me deja entrar.

**Comment by arpincheira** [comment]
Podrías intentar ingresar ahora?

**Comment by CataSudo** [comment]
Aun no, aun no me acepta la clave.

**Comment by arpincheira** [comment]
antes de hacer algo... estás segura de que estás usando bien el comando?
En la foto que mandaste pones:
```
grup30@codd.ing.puc.cl
```
y deberías poner
```
grupo30@codd.ing.puc.cl
```

**Comment by CataSudo** [comment]
<img width="452" alt="Screen Shot 2020-09-22 at 19 41 44" src="https://user-images.githubusercontent.com/62016215/93944708-d0563680-fd0b-11ea-9bfe-c0e2a6d09e20.png">
Aun no, pero un error menos 😂

**Comment by arpincheira** [comment]
ahora prueba con la clave que venía por defecto y avísame si logras entrar(les volví a poner la clave original)

**Comment by CataSudo** [comment]
Si, ahora me deja

**Comment by arpincheira** [comment]
Buenísima, recuerda cambiar nuevamente la contraseña y avisarle a tu compañero de todas formas del cambio. 

Suerte con la entrega

**Comment by CataSudo** [comment]
<img width="455" alt="Screen Shot 2020-09-24 at 11 07 13" src="https://user-images.githubusercontent.com/62016215/94156328-5b434800-fe56-11ea-9880-a2b0c9dc542d.png">
Hola, volví, tengo otro problema con ingresar a la servidor. Ahora no se connecta ni me pide la contraseña.
