### ISSUE TITLE
Datos Aperturas (Impar) 

### ISSUE THREAD

**Issue by smrebolledo** [IIC2413/Syllabus-2020-2#145]
Podemos considerar que el encargado del cierre de una instalación será el mismo para la apertura?

**Comment by arpincheira** [comment]
Hola, yo te recomiendo que pienses en el cierre como un proceso más que como un evento, cuyo inicio es la fecha de cierre(el comienzo de este) y su final es la fecha de apertura, es por esto mismo que el encargado del cierre es el encargado de todo el evento, es decir, del cierre mismo y de la apertura.

Espero haber contestado tu duda.

**Comment by smrebolledo** [comment]
Sii Gracias
