### ISSUE TITLE
Duda atraques

### ISSUE THREAD

**Issue by amparostevens** [IIC2413/Syllabus-2020-2#146]
Hola! 
Se puede asumir que un buque va a haber atracado como mínimo 1 vez? Y se puede poner esta restricción de integridad en el diagrama E/R?

**Comment by arpincheira** [comment]
Hola, dada la base de datos entregada este es un supuesto válido, de todas formas no se si sea estrictamente necesario anotarlo en el diagrama E/R pues a futuro se puede dar que se añada un buque sin que este haya atracado necesariamente, de todas formas lo ideal siempre es que añadas tu supuesto en tu informe, para facilitar los procesos de corrección y recorrección.
