### ISSUE TITLE
Comando OVER en consultas

### ISSUE THREAD

**Issue by Juampisaez** [IIC2413/Syllabus-2020-2#147]
Hola, queria saber si es posible ocupar el comando OVER al hacer las consultas en sql? para la entrega 2
Saludos,

**Comment by arpincheira** [comment]
Hola, dado que el comando OVER no se vio en clases **no recomiendo su uso, a menos de que sean capaces de explicar dentro de su informe el uso y su utilidad**(comparando su funcionamiento con respecto al uso de GROUP BY).  Piensen que la idea es que, con lo visto en los notebooks, ustedes deberían ser capaces de responder las consultas, por lo que no es la idea que ocupen cosas adicionales encontradas por internet a menos de que sepan como funcionan y sean capaces de explicarlo.

A modo de **hint**, otro de los motivos por los que no recomiendo usar OVER es que su performance es mucho menor que aquel del uso de  GROUP BY.
