### ISSUE TITLE
Ingresar a base de datos grupoXXe2 correctamente

### ISSUE THREAD

**Issue by vsantelicest** [IIC2413/Syllabus-2020-2#148]
Hola! 
La instrucción para esta entrega indica que debemos ingresar a una base de datos del servidor distinta para cada entrega, y quería confirmar que este ingreso se debe hacer usando el comando "psql -d grupoXXe2" luego de haber ya ingresado al servidor con el comando "ssh grupoXX@codd.ing.puc.cl".
Mi segunda duda viene ligada a la primera, porque al hacer un ingreso a la base de datos de la manera descrita previamente, me sale todavía una tabla que creé para la entrega anterior, y no se si esta tabla hay que borrarla o se deja ahí y no será tomada en cuenta para esta nueva entrega.
Gracias!

**Comment by jfuentesg26** [comment]
Hola! Nosotras tenemos la misma pregunta! Nos aparece la tabla de la entrega 1 :(

**Comment by arpincheira** [comment]
Hola, efectivamente poseen las tablas en la entrega pasada debido a que esta nueva base de datos es una copia de la base de datos de la entrega1, lo mismo va a pasar para la Entrega3, normalmente el objetivo es que no deban crear ni poblar nuevamente las tablas de las entregas anteriores. 

Es por esto que no hay ningún problema en que borren las tablas anteriormente creadas pues su nueva base de datos es un espacio aislado y no influye para nada con aquella de su entrega anterior.

**Comment by vsantelicest** [comment]
Gracias!!
