### ISSUE TITLE
Duda sobre normalizar los datos de los archivos .csv

### ISSUE THREAD

**Issue by based-on-what** [IIC2413/Syllabus-2020-2#149]
Hola, tengo una duda con respecto a lo que dice el enunciado en "Una vez que tengas el modelo preciso, es tiempo de importar los datos. Junto con esta entrega se subirán archivos CSV con todos los datos que debes guardar en tu base de datos.
Ojo: esos datos no están normalizados, por lo que deberás trabajar un poco para importarlos"

Lo que hice yo fue ordenarlos según la id correspondiente, en orden ascendente (desde 0 hasta el último número), pero no estoy seguro si con eso ya tengo "normalizados" los datos o si tengo que hacer algo más aparte de ordenarlos por id.

Saludos y gracias.

**Comment by danustilovsky** [comment]
Hola! el enunciado se refiere a que probablemente los datos no esten en el formato de las tablas que tu definiste, por lo tanto debes trabajarlos (usando python por ejemplo) para que queden en el formato de tus tablas y que lo puedas importas a postgres.

**Comment by based-on-what** [comment]
> Hola! el enunciado se refiere a que probablemente los datos no esten en el formato de las tablas que tu definiste, por lo tanto debes trabajarlos (usando python por ejemplo) para que queden en el formato de tus tablas y que lo puedas importas a postgres.

Entiendo, pero es probable que lo haga al revés, es decir, adaptar las tablas al contenido de los archivos .csv?

Saludos

**Comment by based-on-what** [comment]
> Hola! el enunciado se refiere a que probablemente los datos no esten en el formato de las tablas que tu definiste, por lo tanto debes trabajarlos (usando python por ejemplo) para que queden en el formato de tus tablas y que lo puedas importas a postgres.

¿Y es posible crear nosotros archivos .csv propios para separar los que están en los datos que nos dieron?

Saludos

**Comment by castrillini** [comment]
La idea es que los grupos puedan subir toda la información presente en los archivos .csv a su respectivo postgres **sin pérdida de información**. Cada grupo puede jugar, adaptar y trabajar con los archivos .csv a su antojo antes de importarlos a postgres.
Para poder importar, a postgres, primero se necesita tener las tablas ya creadas en éste. Estas tablas están creadas según el diagrama E/R de cada grupo. Y cada grupo modela su propio diagrama de la forma que prefiera y que encuentre que es la correcta. Mientras esta modelación sea pertinente al enunciado y se base en el feedback que los profesores y ayudantes estamos entregando, todo estará bien :)

**Comment by based-on-what** [comment]
Muchas gracias a ambos.
