### ISSUE TITLE
Control 1 Corrección

### ISSUE THREAD

**Issue by jaimecoloma** [IIC2413/Syllabus-2020-2#15]
Hola! Me surgió la duda sobre si para cuando se corrijan las consultas, se analiza el tipo de respuesta. Es decir si fui redundante en una consulta pero esta de todos modos funciona y lograría correctamente lo pedido, recibo algún tipo de descuento?

**Comment by arpincheira** [comment]
Hola, 
la idea es que trates de ser lo más claro posible al momento de responder la preguntas del control, principalmente con el objetivo de que la persona que te corrija pueda entender aquello a lo que querías llegar y vea si llegaste o no a la respuesta correcta.

Por lo general, se asigna puntaje completo si la consulta es correcta y no posee errores, un mini descuento si posee errores menores y 0 puntos en el caso de que no se entienda o sea errónea. En todo caso, siempre existe la instancia de recorrección en donde, según el comentario que deje tu ayudante, podrías explicar aquello que no haya quedado claro de tu consulta para ver si efectivamente es correcta o no. **Ojo**, también puede existir un puntaje intermedio según el **criterio del corrector**(que obviamente debe ser consultado con la ayudante jefe de cátedra), pero eso también va a ser relativo según lo que se pueda interpretar de tu respuesta y es apelable en una instancia de recorrección.

Espero que esto conteste tu duda

**Comment by jaimecoloma** [comment]
Yaa gracias!
