### ISSUE TITLE
Duda de archivos en repositorio de proyecto

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#150]
Hola!!

Resulta que desde el servidor hice _"git add,commit,push"_ para subir los cambios a mi repositorio creado para el proyecto. Y al ver los archivos veo que no sólo se subió la carpeta de Entrega1 y Entrega2, si no que otros archivos;
![image](https://user-images.githubusercontent.com/59337116/94021509-76488600-fd8a-11ea-893d-c1d99e90882e.png)
Esto es normal? qué hago con estos archivos?

Gracias!!

**Comment by danustilovsky** [comment]
Hola! esos archivos son parte de la configuracion de git y cache de postgres. Para que no se suban debes de generar un .gitignore donde especificas que archivos quieres que git ignore al momento de hacer add. Me parece que si se subieron no hay problema, mas alla de que te van aparecer archivos extra en tu repositorio. Tambien podrias borrarlos y agregar el .gitignore.

Aqui te dejo un [link](https://www.pluralsight.com/guides/how-to-use-gitignore-file) con mas informacion sobre el gitignore y como usarlo!

**Comment by Camila-sty** [comment]
Gracias 😃

**Comment by Camila-sty** [comment]
Me queda una duda con esto. Lo que pasa es que estos archivos aparecieron en el repositorio, pero yo no lo tengo en mis documentos, por ende, no puedo ignorarlos o si?, se supone que al hacer un archivo gitignore debo escribir los archivos que quiero ignorar pero estos archivos no está en mi repositorio personal ...

**Comment by danustilovsky** [comment]
Son archivos que estan ocultos en general, por eso no los ves. Con el comando "ls -a", seberian aparecerte.
