### ISSUE TITLE
Error al subir gitignore

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#151]
Hola. Hice un archivo ```gitignore```, luego quise subirlo al repositorio, pero me tira un error que no entiendo por qué sucede;
![image](https://user-images.githubusercontent.com/59337116/94024996-69c62c80-fd8e-11ea-9da2-9aac2e2a9d71.png)
Tendrá que ver con los archivos que consideré en el ```gitignore``` ?

**Comment by danustilovsky** [comment]
Hola, ese error dice que alguien pushio algo al repositorio remoto, por lo que tu repositorio local no esta actualizado. Debes hacer git pull antes de poder pushear. Probablemente tengas que hacer uso de git stash para asi poder hacer pull.

[Aqui](https://git-scm.com/docs/git-stash) hay informacion de como funciona el git stash.
