### ISSUE TITLE
Problemas con gitignore

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#153]
Hola, cree un archivo ```gitignore``` y lo subí al repositorio remoto, pero no hizo su función...
Estos son los archivos que quiero ignorar:
![image](https://user-images.githubusercontent.com/59337116/94029655-684b3300-fd93-11ea-896e-8ca508d49677.png)
Y así se ve mi repositorio:
![image](https://user-images.githubusercontent.com/59337116/94029729-7bf69980-fd93-11ea-9dab-fc6ec435b5a8.png)
Qué hice mal?

**Comment by danustilovsky** [comment]
El gitignore solo hace que tu repositorio local ignore esos archivos (como si no existieran) para no agregarlos al remoto. Pero si ya estan subidos, no los elimina. Eso tendrias que hacerlo tu a mano. Para eso puedes seguir los siguientes pasos:
1. git rm --cached <Nombre Archivo>
2. git commit -m "<mensaje>"
3. git push origin <nombre branch (master)>

**Comment by Camila-sty** [comment]
Entiendo.
Me tira un error en el paso 3.
![image](https://user-images.githubusercontent.com/59337116/94031616-71d59a80-fd95-11ea-9a8f-ef4cfa4ae267.png)

**Comment by danustilovsky** [comment]
los pasos se mostraron mal, pero lo que esta entre <>, debes cambiarlo por la informacion de tu branch, o archvio.

1. git rm --cached <nombre archivo>
2. git commit -m "<mensaje>"
3. git push origin <nombre branch (master)>

**Comment by Camila-sty** [comment]
hay alguna manera de eliminar todos los archivos? sin tener que hacerlo uno por uno?
