### ISSUE TITLE
Problemas con la funcion MAX() en psql

### ISSUE THREAD

**Issue by Juampisaez** [IIC2413/Syllabus-2020-2#155]
Hola, estoy hace rato intentando armar la consulta 6 de los grupos impares y por algun motivo no funciona la consulta en psql (probe en sqlite online y si funciona). Hice algo del estilo que esta en la foto, pero en vez de retornar la tupla que posee el valor maximo, retorna toda la tabla que esta en el FROM.
![image](https://user-images.githubusercontent.com/48323752/94047045-eadded80-fda7-11ea-9fd4-c0bb330672d3.png)

Si es posible que nos den un Hint de porque no esta funcionando, lo agradeceriamos mucho.
Gracias de ante mano

**Comment by juanreutter** [comment]
Tirense el error de postgres po

**Comment by Juampisaez** [comment]
No es un error precisamente, lo que pasa es que al ocupar Max() sobre un columna COUNT(), retorna toda la tabla completa que aparece al ocupar solamente el COUNT(). No sé si me explico mejor ahora. En el ejemplo de la foto seria lo siguiente:
```
SELECT nombre,  MAX(eventos) AS maxeven 
FROM (SELECT Autor.nombre, COUNT(*) AS eventos 
            FROM Autor, Documento, Escribe 
            GROUP BY Autor.nombre) AS FOO;
```
retorna la misma relacion que
```
SELECT Autor.nombre, COUNT(*) AS eventos 
FROM Autor, Documento, Escribe 
GROUP BY Autor.nombre;
```
Por algun motivo no retorna la relacion solo con el maximo, y no tira ningun error

**Comment by juanreutter** [comment]
El problema creo es que para hacer un MAX necesitas agrupar por algo, por que si no no hay nada sobre lo que hacer el MAX
