### ISSUE TITLE
SQL uso de LIMIT

### ISSUE THREAD

**Issue by Baelfire18** [IIC2413/Syllabus-2020-2#156]
Hola, a la hora de hacer las consultas se puede usar la función LIMIT "n" para obtener los n valores de una tabla?

**Comment by juanreutter** [comment]
Si quieres n valores, si. Pero no puedes esperar que ese LIMIT te entregue los n primeros o los n ultimos, por que no necesariamente va a hacer eso el motor de la base de datos.

**Comment by Baelfire18** [comment]
Claro claro, para eso se usaria otro comando. Pero muchas gracias profe!!
