### ISSUE TITLE
Entrega 2

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2413/Syllabus-2020-2#157]
Hola!!!Tengo una duda respecto a la parte de consultas , en el enunciado dice que debemos subir en el reporte "Todas las consultas en SQL que implementaron en su aplicación" , para que se cumpla esto significa de que debe estar ahi los comandos(en orden) que usamos para realizar las consultas o no es lo que se pide?

**Comment by arpincheira** [comment]
Hola, la idea es que pongan solamente la consulta que realizan a su base de datos y no toooodo el archivo, tomando como ejemplo los archivos de la ayudantía, su consulta.php se vería así en los archivos que suben a Sites:
```php
<?php include('../templates/header.html');   ?>

<body>
<?php
  #Llama a conexión, crea el objeto PDO y obtiene la variable $db
  require("../config/conexion.php");

  #Se obtiene el valor del input del usuario
  $altura = $_POST["altura"];
  $altura = intval($altura);

  #Se construye la consulta como un string
 	$query = "SELECT pid, nombre, altura FROM pokemones where altura>=$altura order by altura desc;";

  #Se prepara y ejecuta la consulta. Se obtienen TODOS los resultados
	$result = $db -> prepare($query);
	$result -> execute();
	$pokemones = $result -> fetchAll();
  ?>

  <table>
    <tr>
      <th>ID</th>
      <th>Nombre</th>
      <th>Altura</th>
    </tr>
  
      <?php
        // echo $pokemones;
        foreach ($pokemones as $p) {
          echo "<tr><td>$p[0]</td><td>$p[1]</td><td>$p[2]</td></tr>";
      }
      ?>
      
  </table>
```
y lo que ponen en su informe debería ser entonces esto:

```php
SELECT pid, nombre, altura 
FROM pokemones 
WHERE altura>=$altura ORDER BY altura DESC;
```

**Comment by RonaldoSosa** [comment]
Entendido!Me quedo claro , gracias :)
