### ISSUE TITLE
Duda consultas 

### ISSUE THREAD

**Issue by smrebolledo** [IIC2413/Syllabus-2020-2#158]
Si nos dicen "Muestre todos los puertos que...",  basta con mostrar el nombre o se debe ver toda la información de estos puertos?

**Comment by arpincheira** [comment]
Hola, **basta con el nombre y el identificador del puerto.** Pero si muestras más información también está bueno, aunque tienes que fijarte que **si la consulta pide un dato adicional debes entregarlo,** de lo contrario no se obtendrá puntaje en esa pregunta.

Por ejemplo, si dice:
muestre todos los puertos que cumplan con X, basta el nombre

Pero si dice: 
muestre todos los puertos junto con sus Y que cumplan con X, ahí debes mostrar lo que te piden y no solo el nombre.

Espero que se entienda

**Comment by smrebolledo** [comment]
Sii graciaas
