### ISSUE TITLE
Control 1 pregunta enunciado

### ISSUE THREAD

**Issue by amparostevens** [IIC2413/Syllabus-2020-2#16]
Hola! 
En las preguntas 2, 4 y 5 cuando dice “y visitan una viña de ( ) región” se refiere a sólo una o que simplemente tenga al menos un tour en esa región?

**Comment by agustin-rios** [comment]
Hola!  Para esto ravisa la issue #5. Avisame si te sirve!

**Comment by amparostevens** [comment]
Si la había leído pero no me quedó claro.
 Entonces aplica que visite al menos una vez la región para todas las preguntas?

**Comment by amparostevens** [comment]
Si la había leído pero no me quedó claro.
 Entonces aplica que visite al menos una vez la región para todas las preguntas?

**Comment by amparostevens** [comment]
Si la había leído pero no me quedó claro.
 Entonces aplica que visite al menos una vez la región para todas las preguntas?

**Comment by agustin-rios** [comment]
Lo que aplica es que al menos visites una viña para haber pasado por la region, y con eso filtrar lo que te piden

**Comment by amparostevens** [comment]
Gracias!
