### ISSUE TITLE
Consulta 6 grupo impar

### ISSUE THREAD

**Issue by smrebolledo** [IIC2413/Syllabus-2020-2#160]
En la consulta que dice "Muestre el puerto que ha recibido más barcos en Agosto del 2020", se consideran los barcos que han llegado a muelles y astilleros?

**Comment by arpincheira** [comment]
Efectivamente, considera ambas, pues tanto muelles como astilleros se encuentran como instalaciones de un puerto, es decir, ambas pertenecen/forman parte de un mismo puerto.
