### ISSUE TITLE
formatos de fechas en psql

### ISSUE THREAD

**Issue by javierzagal** [IIC2413/Syllabus-2020-2#161]
Hola! Ni **datetime** ni **txt** nos han funcionado al momento de crear las tablas, por lo que las fechas las dejamos con **timestamp** , pero al momento de importar datos nos tira error _out of range_ (en especifico con un dato que es 17-09-20 20:34, en el cual no hay ningún número que nos parezca 'out of range') . ¿Que otro formato de psql podemos usar para que nos funcione el importar datos, o nuestra unica opción es modificar los datos? Gracias de antemano

**Comment by arpincheira** [comment]
Hola, ese dato se encuentra en alguno de los archivos entregados o fue producto de tu procesamiento? No encuentro el dato del que estás hablando en los archivos.

**Comment by javierzagal** [comment]
Tenias razón, creo que al abrirlo en excel se cambió el formato, lo dejé en yyyy-mm-dd hh:mm:ss y timestamp funcionó correctamente, gracias!
