### ISSUE TITLE
Creación de archivos csv

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#162]
En el archivo "puertos.csv" no hay un id_puertos, solo su nombre. Esto significa que 2 puertos no pueden tener el mismo nombre ? Si no como diferencio uno de otro. En la entrega 1 hicimos una tabla puertos con atributos id_puerto y nombre, y nos lo pusieron bueno, esto significa que yo tengo que crear los id_puertos al generar el archivo csv (desde pyhton) correspondiente a esta ultima tabla que nombro ??

**Comment by arpincheira** [comment]
Hola, se recomienda fuertemente la creación de Ids para las entidades, es por esto que efectivamente en la entrega1 estaba correcto que lo hayas modelado así. Por ende, respondiendo a tu pregunta, si se recomienda crear los ido de los puertos al generar el archivo csv correspondiente a la tabla

**Comment by dsepulveda3** [comment]
Perfect. Claramente 1 puerto no puede estar en 2 instalaciones diferentes verdad? Si es así, crear el id_puerto sería simplemente agregar una columna id_puertos en el archivo "puertos.csv" y después hacer un for hacia abajo .. habiendo 890 id_puertos si es que la cantidad de columnas son 891 (+ header)

**Comment by arpincheira** [comment]
Hola, un puerto puede poseer 1 o más instalaciones de distinto tipo, por lo que, para el procesamiento de datos, te recomiendo asumir que dos puertos no pueden tener el mismo nombre y escribir este supuesto en tu informe.

**Comment by dsepulveda3** [comment]
Perfecto. Ultima pregunta, el encargado de la instalación es SIEMPRE quien la "abre" y la "cierra"?? Nosotros teníamos para la entrega1 dos tablas, Instalaciones y Operaciones, en estas pusimos id_jefe_instalación y id_persona_que_cierra_instalacion respectivamente .. esto está mal entonces ??

**Comment by arpincheira** [comment]
Hola, con respecto a esto te recomiendo ver la issue #145, dado que ahí explico con más detalle el como deberías interpretar el cierre, en el caso de que no te quedase claro avisa por aquí nomás.

**Comment by dsepulveda3** [comment]
Dale, si entendi que el que "cierra" siempre es el mismo que "abre", mi pregunta es, el que hace este proceso siempre sera el jefe de la instalación o puede ser cualquier trabajador ??

**Comment by arpincheira** [comment]
No necesariamente tiene que ser el jefe, dado que este podría delegar esta tarea a otro trabajador.
