### ISSUE TITLE
Duda consultas página web

### ISSUE THREAD

**Issue by Skablop** [IIC2413/Syllabus-2020-2#163]
Hola,

No entiendo bien cómo se deben visualizar las consultas en la página web. ¿Deben verse solamente las 6 consultas que nos piden? ¿O el usuario debe ser capaz de cambiar las variables dentro de esas consultas (por ejemplo en vez de buscar los buques que atracaron en el puerto Valparaiso como dice la consulta en el pdf, que mediante un input se pueda buscar por otro puerto)?

Saludos.

**Comment by arpincheira** [comment]
Hola, con respecto a tu segunda pregunta, efectivamente esa era la idea original pero se nos pasó al añadir las consultas al enunciado, en todo caso, con el objetivo de facilitar el trabajo yo recomiendo fuertemente que lo implementen así y lo verifiquen múltiples veces(con el objetivo de adelantar trabajo y/o investigar más del tema de los inputs en php).

Ahora, con respecto a tu primera consulta, efectivamente la idea es que tengan una página de inicio que posea solamente las consultas y un botón que te lleve a la respuesta de esta. 

**Reitero, tanto que se pueda ingresar inputs como solo contestar lo solicitado por la consulta es correcto.** Pero recuerda que en ambos casos la consulta debe ser CASE-INSENSITIVE y debe soportar MATCHING-PARCIAL.(pese a que el dato esté ya predeterminado) y el resultado debe ser correcto para poder obtener el puntaje correspondiente a la pregunta
