### ISSUE TITLE
Consulta 3 Grupo Par

### ISSUE THREAD

**Issue by Skablop** [IIC2413/Syllabus-2020-2#164]
Hola,

La consulta 3 para los grupos pares es "Muestre todos los buques que hayan atracado en ‘Valparaiso’ el 2020". Cuando dice atracar, ¿se deben considerar aquellas tuplas de itinerarios.csv que no tienen fecha de salida? Yo asumí que no porque según la info. de la Entrega 1 esas tuplas representan el itinerario a futuro, pero no estoy seguro.

Saludos.

**Comment by arpincheira** [comment]
Hola, efectivamente ese supuesto es correcto, es decir, como dicen hayan atracado, significa que solo corresponden a los datos de los itinerarios y no de los futuros itinerarios. Es decir, aquellos que poseen fecha de atraque y de salida y no solo los que tengan fecha de atraque.
