### ISSUE TITLE
Tabla País Grupos Pares

### ISSUE THREAD

**Issue by jchernandez22** [IIC2413/Syllabus-2020-2#165]
Hola,
Con mi compañero tenemos una duda respecto a un consejo que nos dieron en la revisión de la Entrega 1, y es que nos recomiendan usar la tabla/relación País en nuestro modelo  pero no nos hace sentido ya que estaríamos generando  una nueva tabla sin contribuir a la normalización del modelo

**Comment by arpincheira** [comment]
Hola, la idea es que no les de una respuesta como tal sobre la normalización porque la idea es que ustedes mismos lo justifiquen en su informe, de todas formas voy a mostrarte un ejemplo por el cual es bueno tener la tabla países.

En primer lugar, debes saber que el costo de almacenar un marchar dentro de lo que viene siendo la memoria es mucho mayor a lo que cuesta almacenar un int, entonces, el costo de tener una tabla que repita en reiteradas ocaciones el nombre de un país es muchísimo más costoso que una tabla que contenga int respectivos a los países y otra que posea solo una vez por país un id y el nombre del país al que le corresponde.
