### ISSUE TITLE
Error de atributos en psql

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#166]
Hola.
Con mi compañera estuvimos probando las consultas después de haber creado las tablas en psql, pero tenemos un problema con los nombres de región, ciudad, puerto. Queremos seleccionar la columna de un puerto en particular pero nos dice que no existe, pero debería existir ya que la tabla muestra el dato.
![image](https://user-images.githubusercontent.com/59337116/94156249-436bc400-fe56-11ea-94de-cd03fb9fa9e2.png)
Cuál podría ser el error?
Gracias!!

**Comment by Camila-sty** [comment]
Ya lo resolví, tenía que usar las comillas simples 😄

**Comment by arpincheira** [comment]
Hola, felicitaciones por haber resuelto tu error. Eso si, te recomiendo tener cuidado de como defines la tabla puerto y cuidado con la normalización de esta. Te recomiendo ver el feedback de la entrega 1 para hacerte la idea de que podría estar faltando.

**Comment by Camila-sty** [comment]
En el feedback de la entrega 1 no nos dicen nada con respecto a la tabla puerto. Te refieres a leer la recomendación de los otros grupos?

**Comment by arpincheira** [comment]
Oh... tienes razón, mala mía, bueno... a modo de pista te puedo recomendar la issue #133, para que veas la pregunta en si y el **link** que ahí aparece, en una de esas puedes ver a lo que buscaba llegar con mi comentario anterior

**Comment by Camila-sty** [comment]
Una consulta, tu viste todas las tablas que hicimos? aparte de puerto?

**Comment by arpincheira** [comment]
Hola, em... no, no he visto el resto de sus tablas(y no deben mandarlas por aquí tampoco), pero si he visto aquella que muestras en la foto que enviaste sobre tu consulta, de ahí viene mi comentario.

**Comment by Camila-sty** [comment]
Ah entiendo, es que si se trata de un tema de normalización ya lo implementamos, pero en otra tabla...
