### ISSUE TITLE
Llaves foráneas a entidades heredadas

### ISSUE THREAD

**Issue by edovtp** [IIC2413/Syllabus-2020-2#167]
Hola, tengo una duda sobre la referencia que se debe usar al momento de declarar llaves foráneas en SQL para entidades que heredan de otra. Por ejemplo, si tengo una entidad A, de la cual sale B y C, en ambas debo hacer referencia de sus llaves a las de A, ahora, si ambas se relacionan con otra entidad X, no sé si en estas relaciones R1 y R2 correspondientes a B con X y C con X debo hacer referencia a las llaves de B y C, o a A. Me parece correcto que la referencia deba ser a B y C, ya que si no podría colocar el id de alguien de C en R1 o de B en R2, pero no esto muy seguro.

Muchas gracias!

**Comment by arpincheira** [comment]
Hola, con respecto a esto, efectivamente lo que deben hacer es relaciones a los hijos (en este caso a B y a C) y no al padre, dado que los hijos poseen una referencia(llave foránea) al padre y no al revés(así puedes recorrer de mejor manera las tablas del modelo que han creado.

Espero haber contestado tu duda.
