### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#168]
Si subo un archivo csv  con datos repetidos a SQL me los elimina automáticamente como pasa en Relax ?? O sea si tengo solo una columna de nombres y tengo 2 Diego, al subir el archivo csv solo se sube 1 Diego ??

**Comment by arpincheira** [comment]
Hola, para que querrías subir un archivo con datos repetidos a SQL?. Según tengo entendido, si posees  primary keys repetidas te va a tirar un error y si insertas la misma fila múltiples veces creo que te lo va a insertar igual.

En el caso de que lo hayas probado avisa por aquí que pasó, para que otras personas con la misma duda puedan saber que pasaría si haces eso.
