### ISSUE TITLE
contenido relación 'próximo itinerario' (pares)

### ISSUE THREAD

**Issue by AgustinZalaquett** [IIC2413/Syllabus-2020-2#169]
Hola, una pregunta, en la relación 'próximo itinerario' no queda claro si tiene que ser solamente él próximo atraque o los próximos atraques, por que hay buques que tienen mas de un próximo itinerario,  y si ponemos solo el que sigue, se perderían los datos sobre los siguentes atraques.
Gracias

**Comment by castrillini** [comment]
En el archivo Itinerarios.csv, como bien dices, hay buques que tienen más de un próximo itinerario. Al pasar estos datos a su postgres, siempre lo correcto es importar **sin pérdida de información**. Si es que utilizan solamente el próximo itinerario que sigue habría pérdida de información.
