### ISSUE TITLE
¿Dónde se entrega el PDF de la Entrega1?

### ISSUE THREAD

**Issue by burgosibarra** [IIC2413/Syllabus-2020-2#17]
Hola!
según el enunciado hay que dejar el archivo en la siguiente ruta /grupoXX/Entrega1, lo que no me queda claro es si dentro del servidor de grupo XX (repositorio) hay que crear una carpeta grupoXX y dentro de esta la carpeta Entrega1, o solo debemos crear la carpeta Entrega1.

**Comment by arpincheira** [comment]
Hola, **solo deben crear la carpeta Entrega1** para esta entrega y en ella poner los archivos.

Saludos

**Comment by burgosibarra** [comment]
Gracias!
