### ISSUE TITLE
Duda sobre consulta con input

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#170]
Hola.
Tengo una duda con respecto a que si la siguiente consulta debe ser con input o no (en la app)?
![image](https://user-images.githubusercontent.com/59337116/94192749-c0626200-fe85-11ea-8de2-f061be07d236.png)
En el caso de ser con input, las opciones de input serían "astillero" o "muelle"?

**Comment by pbyoma** [comment]
Holaa!! Te recomiendo revisar la issue [https://github.com/IIC2413/Syllabus-2020-2/issues/163](url). Respondiendo igual tu pregunta, no es necesario que sea con input, pero se recomienda que lo hagan ya que, les va a servir para proximas entregas saber cómo se hace. Por lo mismo, si es que implementas inputs, queda a tu criterio, preocúpense solo de que quede claro y que muestre al menos lo que te piden (los puertos que tienen astillero).
Espero que te sirva mi respuesta :)
