### ISSUE TITLE
Duda procesamiento de datos

### ISSUE THREAD

**Issue by fbesoainp** [IIC2413/Syllabus-2020-2#171]
Podemos procesar los datos en python? habría que explicar como procesamos los datos en el reporte?

**Comment by pbyoma** [comment]
Hola!! Pueden procesar los datos como más les acomode, no es necesario que expliquen cómo lo hicieron, sino que por qué hicieron lo que hicieron, es decir, justificar su modelo. 
Espero que te sirva mi respuesta :)
