### ISSUE TITLE
PHP uso de scrollbar

### ISSUE THREAD

**Issue by Baelfire18** [IIC2413/Syllabus-2020-2#172]
Hola, una pregunta. Para el uso de las consultas estamos usando en unos casos "Scrollbar" tal como se mostró en un ejemplo de la ayudantia. Pero queremos saber si existe la opción de mostar un "All" para mostrar todas las opciones:
![image](https://user-images.githubusercontent.com/50716449/94205064-d62d5280-fe98-11ea-8b50-c2503c7082f1.png)
Por ejemplo que acá queremos que exista la opcion en cada uno de mostar un all

**Comment by arpincheira** [comment]
Hola, en primer lugar, no recomiendo el uso de scroolbars para la entrega pues, si bien es mucho mejor en términos visuales, no ayuda a verificar que sus consultas sean case-insensitive o que soporten matching parcial. De todas formas, dado que en el enunciado no sale explícito que se deben poder cambiar los Fields de las preguntas(corrígeme si me equivoco en todo caso), para lo que respecta a esta entrega da lo mismo.(lo importante es que la consulta que pongan en el informe si sea capaz de ser útil para esos casos).

Ahora, respondiendo a tu pregunta, en la creación de la scrollbar de la ayudantía utilizan el siguiente código:
```php
 <form align="center" action="consultas/consulta_tipo.php" method="post">
    Seleccinar un tipo:
    <select name="tipo">
      <?php
      #Para cada tipo agregamos el tag <option value=value_of_param> visible_value </option>
      foreach ($dataCollected as $d) {
        echo "<option value=$d[0]>$d[0]</option>";
      }
      ?>
    </select>
    <br><br>
    <input type="submit" value="Buscar por tipo">
  </form>
```

En este, como puedes ver, lo que hacen con el scrollbar es añadir opciones de valores a la consulta en ```consultas/consulta_tipo.php``` y no modificar la consulta como tal, por lo que es muy difícil utilizar un select all a menos de que busquen una manera de hacer que, al seleccionar dicha alternativa se haga una consulta y al seleccionar otras alternativas se haga la consulta original.

De todas formas, si quieres añadir una opción adicional a tu consulta debes poner:
```php
 <form align="center" action="consultas/consulta_tipo.php" method="post">
    Seleccinar un tipo:
    <select name="tipo">
      <?php
      # AÑADIMOS ESTA LINEA
       echo "<option value=valor>variableQueLoRepresente</option>";
      #Para cada tipo agregamos el tag <option value=value_of_param> visible_value </option>
      foreach ($dataCollected as $d) {
        echo "<option value=$d[0]>$d[0]</option>";
      }
      ?>
    </select>
    <br><br>
    <input type="submit" value="Buscar por tipo">
  </form>
```

**Comment by Baelfire18** [comment]
Claro entiendo, con los comandos que me entregaste creo poder crear un All que entregue todas las opciones gracias!!

Eso sí, lo de la recomendación de no usar una scroll bar es recomendación o tendrá una penalización no hacerlo, pues nuestra página ([grupo31](http://codd.ing.puc.cl/~grupo31/index.php?)), cumple con todas las funcionalidades a pesar de tener las scroll bars e hicimos que todas las consultas de nuestras "consultas/consulta_tipo.php" respectivamentente sean case-insensitive y soportan matching parcial (a pesar claramente de no ser tan necesario a la hora de llamar con un scroll bar de opciones).
Si es que estan 2 cosas vienen implementadas con el código de consulta de todas formas, ¿no se pueden usar scrollbars igual?

**Comment by arpincheira** [comment]
Hola, para esta entrega se pueden usar igual(además se pueden ver mejor a veces jajaja), era solo una recomendación en este caso.

**Comment by Baelfire18** [comment]
1) Ahhh genial entonces si son case-insensitive y soportan matching parcial a pesar de tener scrollbar esta bueno igual. Grax

2) Otra pregunta de los mismo Andrés, lo de case-insensitive y soportar matching parcial debe ser solo en el php o en al consulta del pdf tambien? Que con mi compañero entendimos cosas distintas y nos serviría mucho si nos aclararas si para la consulta del pdf tambein debe sportar estas cosas. Muchas grcias
