### ISSUE TITLE
Consulta 4 PAR

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2413/Syllabus-2020-2#173]
Hola! 
Cuando dice "Muestre todos los buques que hayan estado en Mejillones al mismo tiempo que el buque Magnolia"  se debe incluir solo a los buques que su tiempo de llegada y salida es el mismo que el magnolia o también se debe incluir a aquellos buques que, por ejemplo, llegaron antes que el Magnolia y se fueron después de la llegada del Magnolia? Es decir estuvieron un tiempo los dos buques en el puerto. 
Gracias!

**Comment by arpincheira** [comment]
Hola, se supone que deben considerar cualquier buque que haya atracado en el puerto durante el tiempo en que Magnolia estaba atracado(es decir, **cuyo atraque esté durante su atraque y antes que su salida** )y **aquellos que hayan salido durante el tiempo en que Magnolia haya estado atracado**. En otras palabras, **todo buque que haya estado en el puerto durante el tiempo en que Magnolia haya estado en el puerto de Mejillones**.

**Comment by jfuentesg26** [comment]
Perfecto, gracias!!
