### ISSUE TITLE
Duda con las patentes en archivos de grupos pares

### ISSUE THREAD

**Issue by mafernandez9** [IIC2413/Syllabus-2020-2#175]
Hola! Como grupo tenemos la duda acerca de si las patentes son únicas e irrepetibles en el caso de los buques, ya que nos entregan una id de buque de igual forma. Muchas gracias de antemano!

**Comment by arpincheira** [comment]
Hola, efectivamente las patentes son únicas e irrepetibles, en el caso de que tengas dudas sobre como normalizar en el caso de tener dos llaves candidatas, te recomiendo ver la issue #139

**Comment by mafernandez9** [comment]
Perfecto, muchas gracias!!
