### ISSUE TITLE
Consulta 4 par

### ISSUE THREAD

**Issue by aundurraga** [IIC2413/Syllabus-2020-2#177]
Hola! Nos piden que busquemos los buques que hayan estado en Mejillones al mismo tiempo que el buque Magnolia, pero viendo las tablas, el buque Magnolia nunca estuvo en Mejillones. Esto es un error? O debemos entregar una tabla vacía?

**Comment by arpincheira** [comment]
Hola, efectivamente es un error de los datos(pero es muy tarde para cambiarlo), la idea de todas formas es que sean capaces de realizar la consulta solicitada. En el caso de que quieras probar si su consulta funciona siempre existe la posibilidad de que planteen la pregunta en su página web de modo que se puedan variar los parámetros de la consulta, tal como se hizo en la ayudantía.(de hecho, recomiendo hacer esto)
