### ISSUE TITLE
[Control 1] Duda consulta 3

### ISSUE THREAD

**Issue by macavarelau** [IIC2413/Syllabus-2020-2#18]
Cuando nos dicen, "Encuentre los tours..." se refiere a filtrar la tabla verdad? No a buscar los nombres de los tours... Me quiero asegurar porque quiero usar esa tabla posteriormente! Gracias!

**Comment by danustilovsky** [comment]
Hola!

Si no especifican que informacion entregar, se debe mostrar toda la informacion disponible de los tours que cumplan con la condicion pedida.
