### ISSUE TITLE
"herencia" de relaciones

### ISSUE THREAD

**Issue by iankreisberguc** [IIC2413/Syllabus-2020-2#180]
Tengo una duda, en clases el profesor explico que cuando un grupo de datos de una relación era necesario que tuvieran una información extra, como por ejemplo la relación vehículos, pero en el caso de los vehículos todo terreno, me interesa a demás de todos los atributos de vehículo, la cantidad de luces que trae(por ejemplo), entonces creo otra relación que se llama todo terreno que solo contiene el id del vehículo y el atributo extra, en este caso, la cantidad de luces. Mi duda es como agrega esta sub relación o relación hija en el diagrama de E-R ?

**Comment by castrillini** [comment]
La relación que tu nombrás es del tipo IsA
