### ISSUE TITLE
Duda con matching parcial

### ISSUE THREAD

**Issue by nicoguz** [IIC2413/Syllabus-2020-2#181]
Hola!!
Tengo una duda. Cuando nos piden que implementemos matching parcial por ejemplo con esta consulta:
"Muestre todos los buques de la naviera 'Francis Drake S.A.'" Se refieren a que el input que ingresa el usuario es 'Francis Drake S.A.' (y por lo tanto debemos buscar toda naviera que contenga ese string) o que para un input cualquiera (como 'Francis D' por ejemplo) debemos arrojar la consulta que tenga la naviera 'Francis Drake S.A.'?

**Comment by mariajesusbraun** [comment]
Hola! La idea del matching parcial es encontrar términos parecidos o solo algunos fragmentos del input ingresado, es decir, que no tenga que coincidir exactamente con éste. Por lo tanto, es como dices en tu segundo ejemplo.
