### ISSUE TITLE
Duda consulta 6 Pares

### ISSUE THREAD

**Issue by fbesoainp** [IIC2413/Syllabus-2020-2#182]
Si hay dos buques que tienen la mayor cantidad de personal tengo que mostrarlos a los dos?
En la pagina, tengo que poder dar opciones para realizar esta consulta? como buscar por buques de carga en vez de pesqueros?

**Comment by pbyoma** [comment]
Hola! Efectivamente, si es que hay dos con la misma cantidad y esta es la máxima, deben aparecer los dos. Respondiendo tu otra pregunta, no es necesario que hagan las consultas con inputs, pero se les recomiendan que lo hagan para facilitar tareas futuras, eso si deben preocuparse de que quede claro y que **al menos muestre lo que se pide** (buque pesquero con más personal). Les recomiendo revisar la issue #163 
Espero que te sirva mi respuesta :)
