### ISSUE TITLE
Duda consultas

### ISSUE THREAD

**Issue by edovtp** [IIC2413/Syllabus-2020-2#183]
Hola, tengo una duda con la consulta 3 de los grupos pares, y es que si un buque ha atracado más de una vez el año 2020 debe entonces aparecer la cantidad de veces que ha atracado, o solamente una vez?

**Comment by pbyoma** [comment]
Holaa! Debe aparecer solo una vez, sin importar la cantidad de veces que ha atracado, si es mayor o igual a uno aparece. Si quieren pueden ponerle un contador al lado (en otra columna) mostrando la veces que ha atracado
Espero que te sirva mi respuesta :)

**Comment by edovtp** [comment]
Muchas gracias, y en la consulta 4, si es que el buque ha estado en el puerto dado, se debe entregar también? O queda a elección de nosotros? Me refiero a que por ejemplo, si el buque magnolia ha estado en mejillones, entonces podría considerarlo como un buque que ha estado en mejillones al mismo tiempo que magnolia (siempre se incluye a uno mismo), o solo se deben entregar buques diferentes a magnolia?

**Comment by pbyoma** [comment]
Hola! Queda a criterio de ustedes, aun que por un tema de lógica les recomiendo no poner el buque magnolia, en cualquier caso, preocúpense de que quede claro en el reporte, lo pueden poner como un supuesto :)
