### ISSUE TITLE
Hora Cierre Operaciones

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#184]
En el documento que nos dieron las fechas de cierre de operaciones traen fecha y hora. La hora importa ? Si es así tendría que crear una columna "hora_apertura" y "hora_cierre"?? Que tipo de dato se usa DATE ? O es algo asi como TIME.}
La duda nos surgió porque subimos a la base de datos la misma columna que nos dieron "fecha_apertura" de tipo DATE y nos elimino la hora psql al subir el archivo csv con el comando copy

**Comment by arpincheira** [comment]
Hola, la idea era que añadan toda la información dada en las tablas, no te puedo decir exactamente el tipo de datos pero te recomiendo que busques [aquí](https://www.w3schools.com/sql/sql_datatypes.asp) y [aquí](https://www.postgresql.org/docs/11/datatype-datetime.html) para más información sobre los tipos de datos que soporta postgres.
