### ISSUE TITLE
consultas SQL en el reporte

### ISSUE THREAD

**Issue by lzalaquett** [IIC2413/Syllabus-2020-2#185]
Hola, en el reporte tenemos que poner el código de las consultas que hicimos en la aplicación. Pero para el caso de las que dependen de un input, tenemos que poner un valor arbitrario, dejarlo abierto o poner el del enunciado?

Por ejemplo:  para la consulta 2 del grupo par, la hago para buscar los buques de la naviera `'Francis Drake S.A.'` o para `'nombre_naviera'`?

saludos

**Comment by arpincheira** [comment]
Hola, cualquiera de **las dos serán permitidas en el informe**, la idea es que igual indiquen que notación ocuparon y que significa en el caso del que hablas, para que no hayan malentendidos al momento de realizar la corrección.

**Comment by lzalaquett** [comment]
muchas gracias
