### ISSUE TITLE
Duda sobre información necesaria de mostrar consultas

### ISSUE THREAD

**Issue by tamarabend** [IIC2413/Syllabus-2020-2#186]
Hola! Para las consultas 2, 3 y 4 de los grupos pares se pide mostrar los buques que (...). Mi duda es si es necesario mostrar toda la información de los buques, o simplemente el nombre o algún atributo que encontremos que sea relevante para mostrar cuál es.

Gracias!

**Comment by arpincheira** [comment]
Hola, tan como se dijo en la issue #158, aplica lo mismo para los buques en este caso, la idea es que muestren cosas que permitan identificar al buque como tal(por ejemplo el nombre y el id). Idealmente les pido que no muestren solo el ID pues este es una convención que depende únicamente de ustedes y un usuario externo no debe buscar cosas y que le aparezcan solo los ids en su búsqueda(pues no sabe a que corresponden)

**Comment by arpincheira** [comment]
Hola, tan como se dijo en la issue #158, aplica lo mismo para los buques en este caso, la idea es que muestren cosas que permitan identificar al buque como tal(por ejemplo el nombre y el id). Idealmente les pido que no muestren solo el ID pues este es una convención que depende únicamente de ustedes y un usuario externo no debe buscar cosas y que le aparezcan solo los ids en su búsqueda(pues no sabe a que corresponden)

**Comment by tamarabend** [comment]
Gracias!!
