### ISSUE TITLE
Duda respecto a formato de un rut

### ISSUE THREAD

**Issue by Cadutodalcielo** [IIC2413/Syllabus-2020-2#187]
hola :D,

Si tengo un una columna de rut en una tabla, ¿el código verificador tiene que ser necesariamente 0 o K, o se puede mantener los 2?.

Gracias

**Comment by arpincheira** [comment]
Hola, no se si entiendo tu pregunta. De todas formas, según tengo entendido los RUT si pueden tener -0 y -k pues ambos existen y NO, no son equivalentes
