### ISSUE TITLE
Duda justificación de modelo

### ISSUE THREAD

**Issue by lewebe** [IIC2413/Syllabus-2020-2#188]
Hola, al momento de listar dependencias para cada tabla quería saber si lo debo hacer con las relaciones también. Por ejemplo, yo tengo una relación "RelacionInstalacionesPuertos" que solo tiene puertoid y instalacionid como atributos. En este caso, no me queda muy claro cual es la dependencia entre estos atributos, aunque estoy suponiendo que cumple BCNF. Mis preguntas son
* Cuál sería la dependencia en el ejemplo que dí?
* Es necesario listar las dependencias de las relaciones (pues todas las que tengo se comportan como en el ejemplo que di)?

**Comment by arpincheira** [comment]
Hola, no es necesario justificar la dependencia en tablas intermedias como la del ejemplo que mencionas.

Asumiremos que ya están normalizadas. De hecho lo están porque al no tener atributos no primarios cumplen todas las formas normales. Es el caso borde.
