### ISSUE TITLE
Se puede borrar la carpeta Sites?

### ISSUE THREAD

**Issue by FelipeSrojas96** [IIC2413/Syllabus-2020-2#189]
Hola, al estar trabajando con git tenemos un problema con la carpeta sites, porque aparecio un archivo que antes no estaba. Es posible poder borrar esta carpeta, o es necesaria para la evaluacion ?

**Comment by arpincheira** [comment]
Hola, la carpeta Sites es necesaria para la evaluación, por lo que no pueden borrarlas, de todas formas, me podrían decir que archivo les apareció a todo esto?

**Comment by Viperez6** [comment]
Es que al hacer git pull nos tiraba error, pero borramos todos los archivos que estaban de más y listo, eso si parece que borramos algo que no debíamos por que ambos perdimos el color en la consola del servidor :/

**Comment by arpincheira** [comment]
digan que grupo son para tomarlos en consideración por si hay algunos error al recolectar sus entregas

**Comment by Viperez6** [comment]
grupo131
