### ISSUE TITLE
Duda pregunta 6 control

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#19]
En el enunciado dice "Encuentre los nombres de las viñas que participan en el/los tour/s más caro/s". ¿ Qué precio vendría siendo "más caro"? ¿Sobre cuanto dinero?

**Comment by danustilovsky** [comment]
Hola! 

Deberias ver la issue #4, ahi respondieron tu duda y dieron un hint que podria servirte!
