### ISSUE TITLE
Error git pull en el servidor

### ISSUE THREAD

**Issue by JaviGuzman** [IIC2413/Syllabus-2020-2#190]
Hola!

Tenemos un problema al hacer git pull en el servidor. Ya creamos las carpetas Entrega2 y Sites en el repositorio de GitHub, y además eliminamos unos archivos extras que habíamos subido probando antes, para la Entrega 1.
El problema es que al hacer git pull en el servidor aparece el siguiente error:
![Captura de Pantalla 2020-09-27 a la(s) 00 18 57](https://user-images.githubusercontent.com/48359777/94355054-0a4e7200-0057-11eb-87c4-5f1811229f83.png)

En internet busque y me salieron algunas opciones para hacer, pero nada resulta. 😥

Alguien sabe como podemos solucionar esto?

Gracias de antemano

**Comment by arpincheira** [comment]
Hola, probaste haciendo el commit que te dice el error?

**Comment by JaviGuzman** [comment]
Sii, tampoco funcionó. Finalmente tuve que hacer add, commit y pull en el servidor, pero antes eliminando del servidor los archivos que habia eliminado de git. Con eso funcionó bien y quedó todo conectado! :D
