### ISSUE TITLE
Consulta 4 grupo Impar 

### ISSUE THREAD

**Issue by vblopez** [IIC2413/Syllabus-2020-2#191]
Hola! :) En la consulta cuatro, a qué se refiere cuando dice "muestre todas las veces"? No me queda claro si debería mostrar alguna entidad entera, si basta con listar las fechas en las que atracó o si debería mostrar el numero de cuantas veces atracó

Gracias :)

**Comment by pbyoma** [comment]
Hola!! Debes mostrar algo que identifique cada atraque del barco en ese puerto (no sirve poner el numero), queda a su criterio qué mostrar, lo importante es que quede claro y lo registren en su reporte. Personalmente, les recomiendo poner las fechas con la instalación en la atracó. 
Espero que les sirva  :)

**Comment by zaertis0** [comment]
#132 En la issue 132 se dice que se busca los barcos que atracan en la ciudad "Arica" no el puerto "Arica". Puede alguien confirmar esto??

**Comment by pbyoma** [comment]
Hola! efectivamente es así, perdón si eso te generó alguna confusión
