### ISSUE TITLE
Insertar string con espacios en base de datos psycopg2

### ISSUE THREAD

**Issue by cncosta** [IIC2413/Syllabus-2020-2#192]
Hola, He querido insertar un string con espacios en mis relaciones pero no puedo. 
Dejo la manera en lo que lo estoy haciendo y el error que me aparece.
```python
cursor = conn.cursor()
query_datos = 'INSERT INTO Relacion VALUES ({atributo1},{atributo2},{atributo3});'

for row in namedTuple:
    cursor.execute(query_datos.format(
                  atributo1 = row.dato1,
                  atributo2 = row.dato2,
                  atributo3 = row.dato_en_string_con_espacios))
```
y me aparece el siguiente error:
```Shell
syntax error at or near "con"
LINE 1: INSERT INTO Relacion VALUES (dato1,dato2,string con espacios);
```

**Comment by arpincheira** [comment]
Hola,  probaste poniendo comillas sobre las variables? algo como :
```php
"INSERT INTO Relacion VALUES ('{atributo1}','{atributo2}','{atributo3}');"
```
o algo como:
```php
'INSERT INTO Relacion VALUES ("{atributo1}","{atributo2}","{atributo3}");'
```

**Comment by cncosta** [comment]
Eso Funciona! eso si en la base de datos se guardará el archivo como 
| Atributo 1 | Atributo 2 | Atributo 3            |   
|:----------:|------------|-----------------------|
| "dato1"    | "dato2"    | "string con espacios" |   
|            |            |                       |   

o va a quedar?


| Atributo 1 | Atributo 2 | Atributo 3            |   
|:----------:|------------|-----------------------|
| dato1   | dato2    | string con espacios |   
|            |            |                       |

**Comment by arpincheira** [comment]
Debería insertarse hipotéticamente de la segunda forma que dices
