### ISSUE TITLE
Dependencia BCNF 3NF

### ISSUE THREAD

**Issue by vblopez** [IIC2413/Syllabus-2020-2#193]
Hola! Estoy un poco confundida con las dependencias

Si por ejemplo tengo nombres de aviones, paises y continentes, y quisiera agregarle un id tendria
R(id, nombre, pais, continente) 

1. mi relacion R estaria mal?

1. deberia necesariamente crear una relacion 1 donde R1 (id, nombre, pais) y relacion 2 donde R2(pais, continente) ? para no violar nada?

2. mi relacion R1 estaría en 3NF y no en BCNF? 
por el hecho de que: id -> nombre, pais 
pero tambien:  nombre, pais -> id 

3. ya de manera más general, es necesario reducir lo maximo cada tabla para ser BCNF?
por ejemplo R(id, nombre) R(id, pais) R(pais, continente)

Gracias!

**Comment by TamaraCucumides** [comment]
Hola!

> Si por ejemplo tengo nombres de aviones, paises y continentes, y quisiera agregarle un id tendria
R(id, nombre, pais, continente), mi relacion R estaria mal?

No esta mal, pero no esta normalizada, por lo mismo que mencionas despues, dado que el pais -> continente

> mi relacion R1 estaría en 3NF y no en BCNF? por el hecho de que: id -> nombre, pais, pero tambien: nombre, pais -> id
En el caso que nombre, pais -> id entonces quizás no es necesario usar el id, ya que la combinación nombre + pais es suficiente. 

> ya de manera más general, es necesario reducir lo maximo cada tabla para ser BCNF? por ejemplo R(id, nombre) R(id, pais) R(pais, continente)
Esto depende de las dependencias funcionales por ejemplo: puede haber 2 aviones con igual nombre e igual pais? si la respuesta es NO, entonces lo que planteas de separar en 3 tablas es, siendo purista, lo correcto. Si la respuesta es si, entonces puedes dejarla como R1(id, nombre, pais) R2(pais, continente)
