### ISSUE TITLE
Llave foranea como parte de un primary key (compuesta)

### ISSUE THREAD

**Issue by jaimecoloma** [IIC2413/Syllabus-2020-2#195]
Hola! Me surgió la duda de si una llave foránea puede ser parte de una llave compuesta, por ejemplo tengo una tabla sobre registro de autos en un estacionamiento y es tipo R(hora_llegada, hora_salida, patente), en donde patente es llave foranea, proveniente de otra tabla. Para cumplir BCNF necesito listar dependencias, pero con los atributos dados, estos se repiten o no me permiten saber toda la información (por ejemplo un auto podria ingresar dos veces en distintos horarios), entonces podria hacer una llave compuesta con los atributos hora_llegada y patente, pero considerando que patente es una llave foránea? Esto esta mal? O sigue cumpliendo con BCNF??

**Comment by arpincheira** [comment]
Hola, lo que yo te recomendaría sería generar un id del que dependan todos los atributos, dado que, tal como dices, dos autos distintos podrían entrar y salir a la misma hora del estacionamiento(especialmente si este posee dos salidas paralelas por ejemplo). Considerar el par de atributos patente y hora llegada como primary key podría funcionar dado que sería una relación 1 es a 1 por ambos lados, pero no lo recomiendo pues añade complejidad al momento de realizar consultas e incluso, si la base de datos considerara solo hora y no día podrían llegar a existir casos en donde el registro repita la primary key y tu base de datos no lo soportaría

**Comment by jaimecoloma** [comment]
Ya gracias! Pensaba que podia ser medio innecesario agrgar un id de registro pero si me ahorra posibles problemas con las consultas mejor eso. 😄
