### ISSUE TITLE
Case insensitive y matching parcial

### ISSUE THREAD

**Issue by josejimenezp** [IIC2413/Syllabus-2020-2#196]
Hola, quería saber si tenemos que hacer que las consultas cumplan esto solo en la página web o si también es necesario hacerlo para las consultas en postresql. Esto último me parece que no es necesario ya que las consultas debiesen ser específicas y no requieren de un 'input' a diferencia de la página web. Gracias!

**Comment by arpincheira** [comment]
Hola, la idea es que cumplan en ambas partes, dado que no se les solicitó que se pudiera ingresar un input en las consultas, no hay manera de probar que sean realmente CaseInsensitve dentro de su página web. Es por esto que se les solicita que las consultas SQL  que entreguen en el informe sean case Insensitive y permitan un matching parcial
