### ISSUE TITLE
post en php

### ISSUE THREAD

**Issue by iankreisberguc** [IIC2413/Syllabus-2020-2#197]
Hola tengo una dudo, en la pagina web tengo una lista desplegable que se supone le asigna ese valor a la variable y la envía por post, el problema es que al hacer la consulta me di cuenta que el post que recibe la parte de la consulta solo tiene la primera palabra, ej: la opción era "Naviera Ejemplo 1" y solo llega "Naviera", Alguna idea de donde esta el error?

**Comment by arpincheira** [comment]
Hola, probablemente tu problema sea muy parecido al de la issue #192, en una de esas es pista te puede ayudar

**Comment by iankreisberguc** [comment]
si, eso lo soluciona muchas gracias!!
