### ISSUE TITLE
Pregunta sobre enunciado Entrega2 (Pagina Web)

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#198]
Hola, tengo una duda sobre esta parte
![image](https://user-images.githubusercontent.com/62180259/94487865-025a1380-01b8-11eb-9df0-bc4edbb0383c.png)

Dice se requiere que cada consulta despliegue el resultado en la misma pagina, o un link de ruta relativa. No entendí bien lo de ruta relativa ("Por ejemplo, link a /resultado1.php y no link a http://codd.ing.puc.cl/ grupoXX/resultado1.php" dice en el pie de pagina pero no cache bien). Esto significa que no puedo usar el botón BUSCAR con este link:

![image](https://user-images.githubusercontent.com/62180259/94488138-74caf380-01b8-11eb-99c9-0f5cb35cfefc.png)

Y que me re dirija a este link con la respuesta y botón de volver:

![image](https://user-images.githubusercontent.com/62180259/94488237-9e841a80-01b8-11eb-81a7-07ce5e7829e1.png)

Esto esta correcto o incorrecto?

**Comment by ridiazcampos** [comment]
¡Hola @dsepulveda3! A lo que se refiere esta parte del enunciado es que, por ejemplo, la ruta que lleve el botón **buscar** sea: `"./consultas/consulta_tipo_nombre.php"` (**ruta relativa**) y no por ejemplo `"codd.ing.puc.cl/~grupo15/consultas/consulta_tipo_nombre.php"` (**ruta absoluta**) 😄. 

Si bien **ambas consultas llevarían al mismo sitio**, si se movieran tooodos los archivos a una nueva dirección, por ejemplo, `codd2.ing.puc.cl/`, entonces la ruta relativa podría llevarnos a la dirección `codd2.ing.puc.cl/~grupo15/consultas/consulta_tipo_nombre.php`, sin embargo con ruta absoluta, nos redirigiría a la versión anterior con `codd.ing.puc.cl`.  🍀

Entonces, ¡está súper bien que **buscar** lleve a esa dirección! Sin embargo, lo importante es que la **ruta especificada en el botón esté de la forma relativa**, es decir, redirigiendo desde el archivo en donde se está actualmente por ejemplo.

¡Saludos! Cualquier cosa nos puedes comentar por aquí de nuevo si quieres!🎉

**Comment by dsepulveda3** [comment]
Perfecto. Entendido ! Muchas gracias
