### ISSUE TITLE
Duda con id_instalacion y nombre_puerto

### ISSUE THREAD

**Issue by vtunon7** [IIC2413/Syllabus-2020-2#199]
Hola! Tengo una duda sobre si es que un puerto es lo mismo que una instalación? y si el id_instalacion es único? Porque me aparecen puertos con el mismo nombre y distinto id_instalacion. Debo juntar todos esos id en un mismo puerto? Foto para ejemplo.
![image](https://user-images.githubusercontent.com/48421226/94498760-4f96af00-01d1-11eb-8688-0d5217c627dc.png)
Es el mismo puerto o son distintos?

**Comment by arpincheira** [comment]
Hola, no es lo mismo un puerto que una instalación. **Un puerto puede contener en su interior múltiples instalaciones** de distinto tipo. La idea es que sean capaces de modelar esta relación haciendo los procesos de normalización de los datos entregados.

**Comment by vtunon7** [comment]
Gracias!
