### ISSUE TITLE
Entrega 1 - Instalaciones

### ISSUE THREAD

**Issue by JosefaPaz** [IIC2413/Syllabus-2020-2#2]
¡Hola!

Respecto a la entrega 1, sección impar, al hablar sobre las instalaciones dice:

 _"Los puertos tienen dos tipos de instalaciones: pueden tener uno o más muelles de carga/descarga, y uno o más astilleros."_ 

El atributo sería el tipo, donde sería carga/descarga o astillero, o puede tener carga/descarga y astillero a la vez una instalación?

Gracias 😸

**Comment by arpincheira** [comment]
Hola, 
Con respecto a tu pregunta, los 2 tipos de instalaciones a los que se refiere el enunciado son **muelles** y **astilleros**.  Además, un puerto efectivamente puede tener en su interior ambos tipos de instalaciones a la vez.

Espero haberte ayudado
