### ISSUE TITLE
Duda con filtrar luego de renombrar un join

### ISSUE THREAD

**Issue by amparostevens** [IIC2413/Syllabus-2020-2#20]
Hola! 
No se cómo debo referirme a los atributos de una tabla que se formó a partir de un join. Por ejemplo:

- Si tengo tabla __actores__  y hago un join con __actuó_en__ y con __películas__ y renombro ese resultado como __cruce__.

Luego si quiero hacer una proyección o filtro de __cruce__ tengo que llamar a los atributos como _cruce.actores.nombre_ o sólo _cruce.nombre_? Considerando que todos los nombres de los atributos son únicos. 

Y si hay nombres que son iguales? Por ejemplo nombre en __películas__ y nombre en __actores__

**Comment by agustin-rios** [comment]
Hola! La segunda opción debería  ayudarte para lo que quieres una vez definida la tabla cruce.

Respecto a los nombres de películas y actores no deberia pasar mucho, ya que si por ejemplo tienes una pelicula llamada 'Thor' en Peliculas no sera lo mismo que referirse al personaje Thor. Las columnas entre tablas no se fusionaran.

Si lo que quieres es hacer join entre tablas con mismos atributos no deberias poder renombrar ese join, ya que tendrias dos atributos iguales en una misma tabla.

**Comment by amparostevens** [comment]
La verdad no te entiendo. Por ejemplo si tengo esto:
![image](https://user-images.githubusercontent.com/53883653/90830235-4e8b7b80-e30f-11ea-94d1-7d91bac54a4f.png)

Ahora, si renombro esa tabla como __cruce__ y quiero hacer alguna proyección o selección, cómo puedo llamar a los atributos? Como cruce.actores.nombre?

**Comment by agustin-rios** [comment]
No, lo que puedes hacer es cambiar el nombre de actores.nombre por actores.apodo por ejemplo para poder nombrar eso como tabla cruce. Esto porque no puedes crear la tabla cruce si es que tienes dos atributos (en este caso el atributo es nombre) que se llaman igual

**Comment by amparostevens** [comment]
Aah perfecto, entiendo.
Y en el caso de cambiarle el nombre, después lo llamo como cruce.actores.apodo?

**Comment by agustin-rios** [comment]
No, una vez tengas la tabla cruce definida esta sera una tabla nueva con los mismos atributos y datos de las anteriores, esto quiere decir que lo podras llamar solo con cruce.apodo

**Comment by amparostevens** [comment]
Yaa muchas graciaaas!! 😄
