### ISSUE TITLE
Duda con procesamiento de datos: ID BUQUES

### ISSUE THREAD

**Issue by pedroherreraj** [IIC2413/Syllabus-2020-2#200]
Hola,
en el archivo que se nos da de buques, estos poseen un id, pero mí entidad buque no tiene un atributo id. Al normalizar los datos puedo ignorar los id de los buques? O lo consideran como pérdida de información

**Comment by arpincheira** [comment]
Hola, mientras respetes las relaciones y tu primar y key esté bien justificada no importa que no consideren el id de los buques. Estos fueron puestos en la base de datos con el objetivo de dar una **pista** de una primary key potencial que es bastante buena debido a su eficiencia(un int ocupa muy poco espacio en memoria). Espero que esto conteste tu duda.

**Comment by pedroherreraj** [comment]
Vale gracias!
