### ISSUE TITLE
Llaves foraneas

### ISSUE THREAD

**Issue by pedroherreraj** [IIC2413/Syllabus-2020-2#201]
Hola,

Un atributo de una entidad puede ser llave foránea? O solo los las llaves foráneas pertenecen a los atributos de las relaciones?(rombo)

**Comment by arpincheira** [comment]
Hola, en el diagrama entidad relación no es necesario que muestren las llaves foráneas, pero en el esquema si. En este último deben poner la llave foránea a la entidad que le corresponde. Un ejemplo de esto puede ser:

Imagina que tienes libros y autores:
- Un libro en este caso puede ser escrito por solo un autor(supuesto)
- Un autor puede haber escrito múltiples libros

En este caso es mucho mejor que el libro guarde el id del autor a que el autor guarde el id de los libros que escribió, siendo entonces autor_id un atributo de los libros y que debes marcar en el esquema pero no en el diagrama entidad relación

**Comment by pedroherreraj** [comment]
Vaale gracias!
