### ISSUE TITLE
Servidor no me funciona

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#202]
Hola, cuando hago producto cruz entre 2 tablas el la base de datos me funciona perfecto, pero al incluir una 3ra el powershell queda dando vueltas y no me devuelve nada. Que debo hacer en este caso ??

![image](https://user-images.githubusercontent.com/62180259/94577977-8b6f5a00-024d-11eb-96ad-8c4874a783bc.png)

**Comment by juanreutter** [comment]
Puedes calcular, en base al tamaño de puertos, instalaciones y personal, el tamaño de la respuesta que esperas. Luego de eso, ¿por qué querrías hacer ese producto cruz?

**Comment by dsepulveda3** [comment]
Lo hice para sacar los nombres de los jefes de las instalaciones del puerto mejillones. Cruzo los 3 y después agrego 3 condiciones en where para retornar lo pedido. Está mal hacer esto ?
Al final en vez de * puse personal.nombre_persona y me retorno bien la respuesta. Habrá sido que la consola NO me retornaba el producto cruz en entre las 3 (sin las condiciones where y con el *) ya que la tabla quedaba muy grande ?

**Comment by juanreutter** [comment]
cuando pones el where, ¡está bien! Pero por lo general las consolas se pierden cuando los resultados son muy grandes (y el producto cruz puede ser muuuy grande). Y también haces trabajar al servidor innecesariamente (yo creo que si todos los grupos se mandan ese producto cruz al mismo tiempo, la maquina se cae si o si)

**Comment by dsepulveda3** [comment]
Jajaj ya dale, muchas gracias profe !
