### ISSUE TITLE
Consulta 4 grupo impar

### ISSUE THREAD

**Issue by smrebolledo** [IIC2413/Syllabus-2020-2#204]
Cuando dice "Muestre todas las veces que el barco "Calypso" ha atracado en Arica.", con atracar implica que llega algún puerto de esta ciudad, independiente de la instalación?

**Comment by mariajesusbraun** [comment]
Hola! Exacto, es todas las veces que ha atracado en un puerto de esta ciudad, en cualquiera de las instalaciones.
