### ISSUE TITLE
Consultas en php

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2413/Syllabus-2020-2#206]
Hola! Con mi compañero nos hemos dado cuenta que muchas cosas de las consultas no nos funcionan en php, po ejemplo poner paréntesis en algunas partes y poner el = (sólo funciona el LIKE). No sabemos qué hacer porque no nos deja avanzar

**Comment by allullk** [comment]
Tenemos un problema muy parecido con mi compañero, ¿será que el sitio web PHP funciona con SQLite y no pSQL como lo hace el servidor?
