### ISSUE TITLE
foreign keys como primary keys

### ISSUE THREAD

**Issue by jac-34** [IIC2413/Syllabus-2020-2#207]
Hola, si para una tabla A defino una foreign key X, es X tambien primary key de A o si quiero que sea primary key tengo que definirlo aparte?

gracias

**Comment by mariajesusbraun** [comment]
Hola! Debes definirlo aparte. De todos modos, no es muy usado y no te lo recomiendo. Te recomiendo crear un id como PRIMARY KEY para esa tabla y dejar X solamente como FOREIGN KEY.

**Comment by jac-34** [comment]
ya gracias, me queda una duda. Si tengo una entidad `juguetes(jid, nombre)` donde `jid`es la PK y tengo otra subentidad `juguetes_guagua`. En este caso que seria lo ideal para `juguetes_guagua`, poner `jid`como PK o ponerla como FK y definir otra llave aparte? O que sea PK y FK al mismo tiempo? Siento que es natural que `jid` sea llave primaria pero tambien llave foranea al mismo tiempo

gracias
