### ISSUE TITLE
Entrega 2 PHP ¿pSQL o SQLite? pSQL de servidor funcionando perfecto pero sitio web PHP no

### ISSUE THREAD

**Issue by allullk** [IIC2413/Syllabus-2020-2#208]
Con mi compañero, hemos resuelto la consulta 4 impar muy bien en el servidor con variados inputs  de manera exitosa, pero a la hora de intentarlo en la pagina web no ha funcionado. ¿Esto tendrá que ver con que PHP utiliza un SQL distinto al del servidor, algo del estilo PHP utiliza SQLite y el servidor pSQL?¿Es este el caso? Como información adicional, mientras estudiaba los notebooks me di cuenta de que la utilización de paréntesis en SQLite, que es el programa que usamos en los notebooks, es por decir medio mañoso con la utilización de paréntesis, a veces requiere que estén en lugares que no son necesarios para funcionar. Creo que este no es el caso de nuestro actual problema, pero para estar seguros ¿PHP utiliza pSQL o SQLite?

**Comment by arpincheira** [comment]
Hola, si no estoy mal el servidor debería estar corriendo en su interior pSQL. 

Con respecto a lo que sucede con SQLite, resulta ser que este lo que hace es tomar una consulta y la interpreta para luego reordenarla y hacerla de forma correcta en SQL, por eso puede ser un poco más permisivo en ese sentido.

Una de las cosas que puede estar pasando es que a su archivo php no le estén pasando el input de manera correcta y por eso no retorna un resultado.
