### ISSUE TITLE
Error llaves foraneas

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#209]
Hola, deje de ultimo hacer las llaves foraneas y estoy teniendo problemas. Cuando agrego me tira este error

![image](https://user-images.githubusercontent.com/62180259/94633510-e338b000-02a3-11eb-81e0-71c53985d703.png)

En cierre instalaciones tengo varias llaves foraneas, un corresponde a la primary key que hace referencia al id del personal y otro al primary key que referencia al id de las instalaciones. Que estoy haciendo mal ? En caso de que tenga que eliminar lo que muestro en la foto en función de hacerlo bien, como deshago esto ?

**Comment by arpincheira** [comment]
Hola, ese error se da porque entregas el mismo constrain dos veces a una misma tabla, yo te recomiendo que pruebes cambiando el nombre del constraint  a uno más significativo según la operación que quieres hacer
