### ISSUE TITLE
Definición de intersección power

### ISSUE THREAD

**Issue by allullk** [IIC2413/Syllabus-2020-2#21]
![2020-08-20 (2)](https://user-images.githubusercontent.com/53882974/90836176-b6948e80-e31c-11ea-931b-13846eeee632.png)

En la diapositiva que se define el operador de intersección aparece un R sub n siendo que anteriormente solo se ha definido R1, R2 y R; ¿Rn debería ser R1?

**Comment by agustin-rios** [comment]
Por lo que veo en la segunda linea no deberia ser Ri sino que solo R y lo que hace es llamar a todos los atributos de la tabla R siendo estos atributos lo que comparten R1 y R2. En otras palabras: deberia salir (R.a1 ^.......^R.an)

**Comment by allullk** [comment]
Gracias Agustín
