### ISSUE TITLE
 id puertos

### ISSUE THREAD

**Issue by cotefon** [IIC2413/Syllabus-2020-2#210]
Hola! :grinning: puedo suponer que cada puerto tiene un nombre diferente? esto es para no tener que hacer un atributo que sea id_puerto y así usar el nombre del puerto como llave :scream: :boom:

**Comment by arpincheira** [comment]
Hola, la idea es que ustedes sean capaces de justificar todas las decisiones de diseño que tomen, como por ejemplo la que mencionas, de todas formas recomendamos fuertemente que usen el **id** envés de usar el nombre del puerto por temas de eficiencia de almacenamiento. Te recomiendo ver las issues  #200 #133 #139 en donde se habla también del tema con más detalle.
