### ISSUE TITLE
Error del servidor

### ISSUE THREAD

**Issue by iankreisberguc** [IIC2413/Syllabus-2020-2#211]
Hola, tengo un problema con el servidor, no se pq me sale un JOIN q SELECT como si fueran archivos o carpetas, como aparece mas abajo:
![Captura de pantalla 2020-09-30 095013](https://user-images.githubusercontent.com/62029738/94687342-83252680-0302-11eb-9c1b-5db21de5730c.png)

![Captura de pantalla 2020-09-30 095058](https://user-images.githubusercontent.com/62029738/94687308-7a345500-0302-11eb-84fb-93afd555d23c.png)

**Comment by arpincheira** [comment]
Hola, la verdad eso es muy raro, nunca había escuchado que pasara algo como eso... solo por curiosidad, que tienen en el interior esos archivos?(puedes verlo haciendo nano <nombreArchivo>)
