### ISSUE TITLE
Consulta notebook Psycopg2

### ISSUE THREAD

**Issue by burgosibarra** [IIC2413/Syllabus-2020-2#212]
Hola!
En el siguiente código (extraído del notebook de la semana Psycopg2)
![Captura](https://user-images.githubusercontent.com/53795389/94719406-7d8f0700-0329-11eb-87ec-0debed250e49.PNG)
¿no se debería escribir después de `print(t[1])`    `visited.append(t[1])`? De no ser así, ¿por qué funcione la condición `t[1] not in visited`, es decir, como el código identifica que la consulta ya está repetida?
Desde ya, muchas gracias!

**Comment by TamaraCucumides** [comment]
Hola!!

si toda la razon, lo agrego altiro :)

**Comment by burgosibarra** [comment]
gracias! 😄

**Comment by TamaraCucumides** [comment]
Ya lo arreglé, gracias a ti!
