### ISSUE TITLE
Instalar psycopg2 en el servidor AYUDA

### ISSUE THREAD

**Issue by cncosta** [IIC2413/Syllabus-2020-2#213]
Hola hice unos archivos Python para procesar los datos .csv y crear las tablas, pero no puedo correrlos en el servidor porque no esta la librería psycopg2 instalada, que hago? me sale que no puedo instalarla ya que no cuento con permiso del asministrador.

**Comment by arpincheira** [comment]
Hola, efectivamente la librería psycopg2 no se encuentra instalada en el servidor, yo te recomiendo que crees tus cdv de forma local, los subas y luego, una vez que te hayas conectado a la base de datos del servidor correspondiente a esta entrega, utilices el comando \COPY  [aquí](https://www.postgresql.org/docs/9.2/sql-copy.html) te dejo un enlace a la documentación de Postgres en donde podrás encontrar más información al respecto

**Comment by cncosta** [comment]
y no es posible que puedan instalar pandas y psycop2 en el servidor?
 no creo que alcance a cambiar mis archivos python para la entrega

**Comment by arpincheira** [comment]
Instalar psycopg2 podría generar problemas de memoria al interior de un servidor que tiene bastante concurrencia por lo que no es una opción considerable.

Lo que podrías hacer es utilizar pandas para pasar tus dataframes (supongo que estás trabajando con eso) a archivos csv.
