### ISSUE TITLE
Hora entrega 2 del proyecto

### ISSUE THREAD

**Issue by josefeliuf** [IIC2413/Syllabus-2020-2#214]
Hola! 
Quería saber si hay algún problema en haber subido la entrega a las 20:00:05 (literalmente 5 segundos) al servidor.
Pasa que habiamos pusheado al repositorio personal que creamos al inicio del proyecto, pero justo al final nos acordamos que debiamos pushearlo al servidor igualmente.
De antemano,
Gracias

**Comment by arpincheira** [comment]
Hola, No se preocupen por eso, lo tendré en consideración al momento de recolectar las entregas
