### ISSUE TITLE
Problema con PostgreSQL al crear una base de datos.

### ISSUE THREAD

**Issue by based-on-what** [IIC2413/Syllabus-2020-2#216]
Hola a todos, finalmente logré instalar PostgreSQL, la versión 13 acorde a la wiki del curso, sigo las instrucciones, pero en la consola SQL Shell obtengo estos mensajes:
![Problemadatabase](https://user-images.githubusercontent.com/62000495/95218871-2080ce80-07cb-11eb-9f2c-1123a2ca6e45.PNG)
¿Qué está fallando?

Saludos y gracias.

**Comment by based-on-what** [comment]
Abrí la consola nuevamente, presioné "enter" cuatro veces hasta llegar al input de la contraseña, en donde escribí la contraseña durante la instalación de postgresql:
![DASDASD](https://user-images.githubusercontent.com/62000495/95219417-ba487b80-07cb-11eb-8480-0e8737b45b4d.PNG)

**Comment by danustilovsky** [comment]
Hola, puedes probar con el comando CREATE DATABASE <NOMBRE>. Createdb es un wrapper que cumple la misma función que el comando que te recomiendo.

**Comment by based-on-what** [comment]
> Hola, puedes probar con el comando CREATE DATABASE . Createdb es un wrapper que cumple la misma función que el comando que te recomiendo.

Gracias, ahora tengo esto:
![Captura](https://user-images.githubusercontent.com/62000495/95220935-5cb52e80-07cd-11eb-94bc-73841ca3ad81.PNG)
Cuando trabajé con PowerShell no había mayor problema.

**Comment by based-on-what** [comment]
Intenté con "\connect" pero ahora me arroja este mensaje:
![Captura](https://user-images.githubusercontent.com/62000495/95221223-9ab25280-07cd-11eb-9811-7da9098780ab.PNG)

**Comment by based-on-what** [comment]
Intenté de la siguiente forma, tampoco pude:
![Captura](https://user-images.githubusercontent.com/62000495/95226873-d223fd80-07d3-11eb-924c-891bc09b8b97.PNG)

**Comment by danustilovsky** [comment]
Hola, el tema es que cuando estas dentro de postgres psql no es un comando por eso te tira el error. Una vez conectado a postgres, el comando para cambiar la db con la que estas trabajando es \c "nombredb". En caso que quieras ver una lista de las db disponibles puedes ocupar \list.

**Comment by based-on-what** [comment]
> Hola, el tema es que cuando estas dentro de postgres psql no es un comando por eso te tira el error. Una vez conectado a postgres, el comando para cambiar la db con la que estas trabajando es \c "nombredb". En caso que quieras ver una lista de las db disponibles puedes ocupar \list.

Muchísimas gracias por tu ayuda, ahora me conecté a exampleDB.
