### ISSUE TITLE
Problema al conectarse a una base de datos desde python

### ISSUE THREAD

**Issue by josefeliuf** [IIC2413/Syllabus-2020-2#217]
Hola!
La consola me tira el siguiente error: 
![image](https://user-images.githubusercontent.com/62085104/95242336-6ba7db00-07e5-11eb-8446-74c98df5d886.png)

Seguí la wiki del curso al pie de la letra, logré crear una base de datos llamada "ejemplodb", me conecté a ella desde la SQL shell y despues probe el codigo que se aprecia justo arriba. Para 'user' además probé poner el nombre 'postgres' pues al conectarme por la SQL shell me decia 'usuario 'postgres' se ha conectado a 'ejemplodb''
adjunto la imagen de eso también

![image](https://user-images.githubusercontent.com/62085104/95244635-9b0c1700-07e8-11eb-97e2-4a9da24c62d6.png)

Gracias!

**Comment by josefeliuf** [comment]
Ya lo solucioné, el problema estaba en que mi port predeterminado es 5433 (no tengo idea por qué) y yo usaba el port 5432 (como indica en la guía)

**Comment by arpincheira** [comment]
Hola, lamento mucho no haber contestado esta issue a tiempo, efectivamente me he estado dando cuenta de que muchas personas al trabajar con windows, se les instala postgres en el puerto 5433 y no en el 5432(que es el que se considera como puerto por defecto). Muchas gracias de todas formas por completar esta issue comentando el error que estaba sucediendo.

Por cierto, si alguien más ve esta issue, para corroborar el puerto en el que tiene instalado Postgres debe ingresar el comando ``` \connifo ``` desde la consola de postgres y verificar que el puerto que este comando retorna sea el mismo que están llamando en sus archivos al momento de realizar la conexión

**Comment by Juampisaez** [comment]
Hola tengo exactamente el mismo problema, solo que mi puerto es el 5432 (lo revise con el comando que pusiste), y no entiendo que es lo que no resulta. Tengo lo siguiente:
![image](https://user-images.githubusercontent.com/48323752/95782318-0866ee80-0ca6-11eb-9072-3e578b1962ed.png)
 No entiendo cual es el problema
