### ISSUE TITLE
Consulta 3 Control 1

### ISSUE THREAD

**Issue by maxcorvalan** [IIC2413/Syllabus-2020-2#22]
Hola!
La duración de la tabla es la cantidad de viñas que visita o está en horas? Por otra parte, puedo renombrar columnas como "buena práctica"?
Saludos y gracias!

**Comment by agustin-rios** [comment]
Hola!
La duración es el tiempo en horas que hace el tour, no la cantidad de viñas.

**Comment by maxcorvalan** [comment]
Perfecto, muchas gracias!
