### ISSUE TITLE
Form recorrección entrega 1

### ISSUE THREAD

**Issue by rieg-ec** [IIC2413/Syllabus-2020-2#220]
Hola, quisiera saber si puedo tener acceso al form de la recorrección 1 con el comentario que hice, para revisar algo.

**Comment by arpincheira** [comment]
Hola, lo lamento no puedo darte acceso a eso, pero podrías darme tu mail y te reenvío tu solicitud de recorrección por correo.

**Comment by rieg-ec** [comment]
Parece que ya no lo necesito. Muchas gracias de todas formas!
