### ISSUE TITLE
Problema conexión python y bases de datos

### ISSUE THREAD

**Issue by JavaBravo** [IIC2413/Syllabus-2020-2#221]
Hola! Estaba intentando conectarme a la base de datos como lo dice la wiki, entonces dejé definida la conexión de esta manera:

<pre><code>conn = psycopg2.connect(
        database='exampleDB',
        user='user',
        host='localhost',
        port=5432,
        password=''
    )
</code></pre>

Pero al correrlo me tira un error, pidiendo que entregue una contraseña, a pesar que en la wiki dijeron que no era necesario:

<pre><code>Hubo un problema :c
fe_sendauth: no password supplied
</code></pre>
¿Qué debería hacer?

**Comment by arpincheira** [comment]
Hola, una recomendación sería que crearas un usuario en postgres y le dieras acceso a tu base de datos, para esto podrías ejecutar los siguientes comandos en la consola de postgres:
```psql
CREATE ROLE 'nombre del usuario' WITH LOGIN PASSWORD 'tu contraseña';
CREATE DATABASE 'nombre de tu base de datos';
GRANT ALL PRIVILEGES ON DATABASE 'nombre de tu base de datos' TO 'nombre del usuario';
```
entonces tu conexión ahora si tendría una contraseña que sería la que acabas de definir con los comandos anteriores

**Comment by JavaBravo** [comment]
Hola! Acabo de crear el nuevo rol, asignándole una contraseña y una base de datos. Pero ahora me arroja un error sin descripción!

<pre><code>Hubo un problema :c


[Done] exited with code=0 in 0.194 seconds
</code></pre>

**Comment by arpincheira** [comment]
O.o que raro, podrías probar modificando el código a:
>```py
>except Exception as e:
>    print('Hubo un problema :c')
>    print(str(e))
>```

**Comment by JavaBravo** [comment]
Lo intenté, pero no mostró el error

**Comment by IvaniaArias** [comment]
Holaa! Estoy teniendo el mismo problema :(
Hice todos los pasos que dijeron y me arroja "Hubo un problema :c"
No se que mas hacer :(

**Comment by IvaniaArias** [comment]
Ahora me sale estooo, la linea 10 es la password :(
No se si será un error de donde rellené los datos, como ahora tengo dos usuarios y dos bases de datos quedé media enredada :( jaja

![Captura de pantalla (699)](https://user-images.githubusercontent.com/61998881/95875869-deb2d380-0d48-11eb-8047-69d3574d4791.png)

**Comment by JavaBravo** [comment]
Me ocurre lo mismo que @IvaniaArias!

**Comment by arpincheira** [comment]
uf... ya... lo más probable es que tengan que cambiar la configuración de postgres para que acepte conexiones "externas". Para poder hacer esto deben primero detener postgres, luego ir al archivo denominado ```pg_hba.conf```, creo que una de las rutas frecuentes de este archivo es: 

```/etc/postgresql/SuVersion/main```

y para editarlo simplemente deben poner

```nano /etc/postgresql/SuVersion/main/pg_hba.conf```

una vez hagan esto les va a aparecer en consola un archivo y al final de este van a tener algo como esto: 

![image](https://user-images.githubusercontent.com/37157550/95884098-170adf80-0d52-11eb-9823-d8e3921b12ab.png)

lo que deben hacer entonces es simplemente modificar la quinta línea y poner free envés de peer, lo que les quedaría algo como :
![image](https://user-images.githubusercontent.com/37157550/95884331-5802f400-0d52-11eb-86a1-25349945be53.png)

una vez hayan realizado el cambio deben guardar la información con ````control + o``` y una vez realizado el cambio volver a iniciar postgres en su computadora.

**Comment by IvaniaArias** [comment]
Con hacerlo en Linux o Windows estaría bien? O debe ser en los dos?
Lo hice en Linux (porque en Windows no encontré donde cambiar esa parte) y me sigue saliendo lo mismo D:
Podría ser que quizás estoy ingresando mal algo?
En el código acá, debería completar con la BD, usuario y contraseña que cree ahora cierto?  O quizas correr el py desde algun lugar especifico?
`conn = psycopg2.connect(
        database='exampleDB',
        user='user',
        host='localhost',
        port=5432,
        password=''
    )` 

O en la SQL Shell, que antes era todo por defecto, no debo cambiar el username o algo? 

![Captura de pantalla (701)](https://user-images.githubusercontent.com/61998881/95889841-5be64480-0d59-11eb-913d-2daf573d061e.png)

He probado varias opciones y nada :(((

**Comment by arpincheira** [comment]
Es muy peculiar la verdad, aunque con el cambio que acabas de realizar puedes probar con otro usuario(no necesariamente el que creaste anteriormente sino el que dice en la wiki). Con respecto a lo del cambio, todo va a depender de donde hayas instalado Postgres puesto que lo que haces es modificar su conexión. A todo esto, estás trabajando con partición o con wsl? y si es esto último me podrías indicar donde instalaste postgres y cual versión estás utilizando de wsl?

**Comment by IvaniaArias** [comment]
Ahí me mataste, la verdad la verdad no se jaja, postgres lo había instalado para otro ramo, no se como saber donde esta :(
Para ejecutarlo ahora lo hice directamente desde SQL Shell, y funciona, puedo ver las bases de datos, crear tablas y todo pero al correr el py muere

**Comment by IvaniaArias** [comment]
Ya pudeeee 😭😭😭 Al final era algo de la conexión.
Muchas muchas gracias por la ayudaaaa <3 y perdon lo chata jaja

**Comment by arpincheira** [comment]
Hola, perdón por responder antes no vi la notificación :/, que bueno que lo hayas podido solucionar, a todo esto, que era exactamente?(para saber más que nada)

**Comment by IvaniaArias** [comment]
jaja no te preocupes, me ayudaste mucho!
Me da plancha igual ajaj dejé postgres en el user, puse la constraseña que cree y escribí la database en minuscula 🙃
Creo que lo último era el problema jajaja
Gracias por la paciencia jajaa

**Comment by svaldes99** [comment]
Hola, también me paso, y al correr el comando que dices, se me abre un block de notas, y no me sale nada parecido a lo que hay que cambiar, ¿que puede ser?

**Comment by IvaniaArias** [comment]
@svaldes99 El pantallazo es corriendo 
`/etc/postgresql/SuVersion/main`  y 
`sudo nano /etc/postgresql/SuVersion/main/pg_hba.conf`
pero en linux, en windows tampoco me salia nada parecido

**Comment by svaldes99** [comment]
@arpincheira como puedo editar eso en windows? Corro lo que me dices, y no me aparece nada parecido. Solo se me abre un block de notas

**Comment by arpincheira** [comment]
Efectivamente windows no posee nano instalado, por lo que notepad es de cierta forma "equivalente", pero te abre un archivo .txt en el que puedes ver y editar la información del archivo al que hiciste la referencia.

Ahora, en tu caso deberías probar cambiando ```scram-sha-256``` por ```free``` en la línea que indica que el type es local.

**Comment by svaldes99** [comment]
Lo hice, y al cambiarlo, no me deja volver a iniciar el servidor de postgres, y se de un par de compañeros más que les pasa lo mismo, ¿por que podrá ser? Y el link que me dejaste está vacío.

**Comment by arpincheira** [comment]
Hola, efectivamente ese link está vacío(es raro porque me funcionó antes jajaja),  [este](https://www.postgresql.org/docs/9.3/auth-pg-hba-conf.html) si debería funcionar. Lo que tengo entendido es que es un tema de permisos de windows, pero no me manejo mucho con eso como para poder solucionarlo :/

**Comment by arpincheira** [comment]
A todo esto, podrías revisar estos dos links que dejaré a continuación, uno de ellos podría eventualmente servirte(prueba lo que dicen en orden eso si)
- [Foro sobre dudas de postgres](https://github.com/PostgresApp/PostgresApp/issues/313)
- [Issue sobre problemas con postgres y windows](https://stackoverflow.com/questions/28276706/postgresql-error-fatal-role-username-does-not-exist)
