### ISSUE TITLE
Cambios en servidor

### ISSUE THREAD

**Issue by josejimenezp** [IIC2413/Syllabus-2020-2#222]
Hola, quisiera saber si es que se pueden hacer cambios en el servidor, ya que aún no tenemos las notas de la entrega 2. Saludos.

**Comment by arpincheira** [comment]
Hola, efectivamente pueden realizar cambios en el servidor, nosotros los ayudantes poseemos una copia de sus entregas a partir de las cuales hacemos la corrección así que no se preocupen. De todas formas debes recordar que las cosas de esta entrega deben hacerse en la base de datos correspondiente y los entregables deben estar en la capeta Entrega3.

Saludos y mucho éxito en esta nueva entrega
