### ISSUE TITLE
Problema con puertos [grupo par]

### ISSUE THREAD

**Issue by jg-tuna** [IIC2413/Syllabus-2020-2#223]
Hola~ El día de hoy estabamos viendo como abarcar la nueva entrega entre los grupos pares e impares de lo cual revisando encontré que en los puertos de grupo par existe uno llamado "nombre" lo que hace que el grupo par tenga 44 puertos y los impares 43 puertos. Aiuda :worried:

**Comment by arpincheira** [comment]
Hola, no entiendo bien cual es el problema de esto? simplemente deben considerar que es un puerto "fantasma" en lo que respecta a los datos, la única diferencia existente es que este no ha recibido atraques y los otros si.

**Comment by jg-tuna** [comment]
Hola, lo que pasa es que este puerto "fantasma" si tiene un atraque. Mi pregunta va mas que nada en que si el elemento de "conexión" entre los grupos pares e impares son los puertos y los barcos (buques), si es ese el caso que debemos hacer si el numero de tuplas entre un grupo y otro no calzan.
Espero que haya quedado clara mi duda 😿

**Comment by DanielaCorral** [comment]
Hola, tengo exactamente la misma duda. Existe un puerto de la base de datos de los pares que se llama nombre y tiene id=1, el cual no se encuentra en la base de datos de los impares y aún así tiene 21 atraques y 13 próximos itinerarios, por lo tanto no es de ignorar. ¿Qué se hace en este caso? ¿Lo insertamos manualmente en la base de datos de los impares?

**Comment by arpincheira** [comment]
Hola, lamento mucho la demora @jg-tuna  no vi el comentario antes :/, em... con respecto a esa pregunta, efectivamente deben insertar esa tupla a la tabla de los grupos impares

**Comment by DanielaCorral** [comment]
Ok muchas gracias :+1:
