### ISSUE TITLE
Uso de jupyter notebooks de procedimientos almacenados

### ISSUE THREAD

**Issue by DanielaCorral** [IIC2413/Syllabus-2020-2#224]
Hola, me gustaría utilizar los notebooks que se subieron de procedimientos almacenados de manera de poder ejecutarlos en el mismo jupyter en vez de ocupar el servidor del curso para eso. Pero aparece que debemos cambiar la celda que muestro a continuación con los datos correctos para que funcione en nuestro computador:
![duda](https://user-images.githubusercontent.com/48497669/95632289-b5016000-0a5b-11eb-9eec-62401f976441.png)
Si yo no tengo mi propio usuario y uso el que viene por defecto (postgres), ¿cómo se tiene que llenar esta celda? (intenté buscar en internet cuál es la clave del usuario por defecto y me terminé enredando más) e intenté poniendo lo siguiente pero sale error:
![duda2](https://user-images.githubusercontent.com/48497669/95632628-71f3bc80-0a5c-11eb-8078-922894b951a5.png)
De antemano gracias! :smile_cat:

**Comment by arpincheira** [comment]
Hola, lo que podrías hacer es crear un usuario asociado a tu base de datos y por ende ocupar esa información, en la issue #221 puse los comandos necesarios para hacerlo, por si le quieres echar un vistazo.

**Comment by DanielaCorral** [comment]
Ok muchas gracias!
