### ISSUE TITLE
Duda Enunciado Entrega 3

### ISSUE THREAD

**Issue by nbarriav** [IIC2413/Syllabus-2020-2#225]
En la parte de sistema de usuarios se señala: "... Se le debe asignar un ID único a este nuevo usuario, para ello puede tomar el sucesor del máximo ID en su bases de datos"

Me entra la duda de si es necesario agregar este ID dado que cuando alguien se registra incluye su N° de pasaporte el cual es único

Saludos

**Comment by arpincheira** [comment]
Las aplicaciones reales normalmente asignan un id numérico a los usuarios(distinto al número de pasaporte) porque es mucho más eficiente en términos de memoria y tiempo de consulta(piensa que el número de pasaporte es un varchar y se compara como tal, mientras que el id que solicitamos es un int que probablemente no va a ser mayor a 3 dígitos), por lo que recomiendo fuertemente que ocupen un id aparte, aunque no hay ninguna restricción con respecto a eso, lo que si les voy a pedir es que en los documentos que entreguen indiquen por que optaron por utilizar el número de pasaporte y no el id numérico.

Saludos
