### ISSUE TITLE
Duda En Discord 

### ISSUE THREAD

**Issue by CataSudo** [IIC2413/Syllabus-2020-2#226]
Hola, no buena usando Discord por lo que no encuentro el lugar para hacer dudas generales. Al abrir el Discord del grupo de aparece esto. 
<img width="475" alt="Screen Shot 2020-10-10 at 16 08 51" src="https://user-images.githubusercontent.com/62016215/95663151-00c31080-0b13-11eb-942c-d58b1ebc531c.png">

**Comment by arpincheira** [comment]
Hola, me podrías decir tu usuario de discord para cambiarte manualmente la categoría de tu usuario en el servidor y que puedas acceder a los otros canales. 

Además, recuerda que el canal oficial de dudas generales es GitHub, en discord solo responderemos dudas durante los periodos de consultas(y publicaremos las dudas frecuentes en el caso de que las haya)

**Comment by CataSudo** [comment]
Sii, muchas gracias! Porque no podía ver los otros canales?

<img width="242" alt="Screen Shot 2020-10-10 at 16 22 49" src="https://user-images.githubusercontent.com/62016215/95663344-e427d800-0b14-11eb-85ee-5cf456c0d56e.png">

**Comment by arpincheira** [comment]
Se añadieron Roles al canal de discord para asegurar de cierta forma que están de acuerdo con las Reglas del Servidor, normalmente reaccionar al comentario de nuestro ayudante/bot SubZero debería dar automáticamente el rol de estudiante a aquella persona que lo haga, pero puede ocurrir a veces que esto no suceda y por eso te añadí manualmente
