### ISSUE TITLE
Ayudantia Control 2

### ISSUE THREAD

**Issue by CataSudo** [IIC2413/Syllabus-2020-2#227]
Hola! ¿Cuando se sube la ayudantía realizada el 9 de Octubre?
Muchas gracias!

**Comment by TamaraCucumides** [comment]
Hola! Durante hoy o mañana en la mañana a mas tardar va a estar subido el video :)

**Comment by TamaraCucumides** [comment]
Subido! Pueden encontrar el link en la carpeta ayudantias 📁
