### ISSUE TITLE
Control 2: Duda Clase Page método insert_into_pos(pos,tuple)

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2413/Syllabus-2020-2#228]
Hola!No me quedo claro a que posición hace referencia el parámetro "pos" para usar este método se refiere a una posición en el "data" me refiero al dato "data" de la página?

**Comment by TamaraCucumides** [comment]
Hola! Es la posicion de la tupla dentro de la pagina (en este caso como tenemos 5 slots la posición va del 0 al 4)

**Comment by RonaldoSosa** [comment]
Entendido!Gracias
