### ISSUE TITLE
Entrega 3 manejo de dos bases de datos en un servidor

### ISSUE THREAD

**Issue by MFMG99** [IIC2413/Syllabus-2020-2#229]
¡Hola! No entendemos muy bien cómo hay que acceder desde el servidor de uno de los dos grupos a la base de datos del servidor del otro... ¿Tenemos que acceder a la base de datos del otro servidor de la misma manera como si accediéramos a la base de datos local (de mi servidor) o debemos hacer otra cosa? 🤔

**Comment by arpincheira** [comment]
Hola, efectivamente el modo de conexión es muy parecido, lo que podrían hacer es definir una segunda variable bd en su archivo de conexión con un nombre descriptivo que les permita identificar que base de datos corresponde a que grupo.(esto último es más una recomendación que un requisito eso si)
