### ISSUE TITLE
Duda Pregunta 5 Control 1

### ISSUE THREAD

**Issue by mpbascunan** [IIC2413/Syllabus-2020-2#23]
Holaa, en la consulta 5 me surgió una duda en la parte donde dice "y visitan una
viña de la Décima Región." Se refiere a sólo 1 o al menos 1?

**Comment by arpincheira** [comment]
Hola, tal como respondieron en la issue #5, "que un tour visite más de una viña en la misma región no deberia excluirlo de la consulta". Es decir, la consulta se refiere a **al menos 1** viña. 

Espero haberte ayudado
