### ISSUE TITLE
Registro de nuevos usuarios

### ISSUE THREAD

**Issue by dchahuan** [IIC2413/Syllabus-2020-2#230]
Hola,
Va a ser posible registrar nuevos usuarios que no esten en mi base de datos de personal por ejemplo. Y si ese es el caso como  cuando este se registre va a tener que especificar su labor como si trabaja en un buque o un puerto??

**Comment by arpincheira** [comment]
Hola, tal como dice el enunciado: "Dentro de los usuarios de la aplicación se encuentran los capitanes de buques y los jefes de instalaciones en los puertos(**pero pueden haber más**)". Esto implica que **SI** va a ser posible registrar nuevos usuarios que no formen parte de su base de datos de personal.  No es necesario que especifique su labor, dado que estos usuarios forman parte de una nueva tabla y son independientes de las tablas anteriores(a excepción de los jefes de instalaciones y capitanes según lo que menciona el enunciado).

**Comment by dchahuan** [comment]
Gracias!!
