### ISSUE TITLE
Migración de usuarios

### ISSUE THREAD

**Issue by edovtp** [IIC2413/Syllabus-2020-2#231]
Hola, tenemos una duda con el requerimiento de usuarios y accesos, en específico con la parte de migración. No sabemos si esta migración se debe realizar una única vez, o esta migración debe ser posible realizarla cuantas veces se quiera, a través de un botón por ejemplo, revisando que no se agreguen capitanes o jefes que ya estén incluidos en la base de datos.

**Comment by arpincheira** [comment]
Sería ideal que se pudiera hacer múltiples veces, pero dado que el enunciado no especifica el como deben realizarlo va a depender de ustedes solamente. De todas formas, que se pudiera hacer múltiples veces no sería malo como parte(no completamente eso si) del puntaje de funcionalidad creativa... solo digo...

**Comment by rieg-ec** [comment]
Hola, no me queda claro para que serviria migrar mas de una vez, si el objetivo de la migracion es que los capitanes y jefes se conviertan en usuarios, y al registrar nuevos usuarios estos claramente son usuarios.

**Comment by arpincheira** [comment]
Hola, imagina que por problemas técnicos tuviste que añadir manualmente nuevos capitanes/jefes o hay una actualización de jefes y debes cambiar esa información en tu base de datos, por lo que sería ideal que el procedimiento que utilizaste anteriormente pueda ser usado denuevo para evitar tener que añadir estos nuevos cambios uno por uno.

Ahora, como dije anteriormente, esto **no es obligatorio** en lo que respecta a la entrega como tal, pero dada su utilidad sería bueno añadirlo como una funcionalidad adicional.

**Comment by rieg-ec** [comment]
ah si, pero mi pregunta iba mas hacia esto como una funcionalidad de la pagina, no de la entrega. Claramente es util en el contexto de la base de datos, pero como boton para que se pueda hacer repetidamente desde la pagina no me hacia mucho sentido. Gracias!

**Comment by edovtp** [comment]
Muchas gracias por la respuesta. Lo que no me queda muy claro, y que es parte de mi duda, es que si los ayudantes deben tener alguna forma de poder revisar que se realizó la migración utilizando php o procedimientos almacenados, ya que por ejemplo podríamos hacer la migración usando los csv.
