### ISSUE TITLE
Capitanes Base de datos entrega par

### ISSUE THREAD

**Issue by anvaldes** [IIC2413/Syllabus-2020-2#232]
Hola! Una consulta, dada la información que se dio en la entrega 2 de bases de datos, solamente tenemos usuarios sin especificar sus cargos. Entonces me pregunto como podemos seleccionar solo a los capitanes? considerando que no hay un identificador de ellos?

Gracias!

**Comment by arpincheira** [comment]
Hola, eso depende solamente de su implementación de la entrega anterior, la base de datos que les entregamos poseían información que efectivamente incluía el rut o número de pasaporte de los jefes y capitanes, por lo que deben ingeniarse ustedes como conectan aquella información a los trabajadores para obtener la información de aquellos que eran jefes o capitanes respectivamente.
