### ISSUE TITLE
Control 2 <EMPTY>

### ISSUE THREAD

**Issue by jitorralba** [IIC2413/Syllabus-2020-2#233]
Hola!
Respecto al control 2. ¿Pueden existir valores <EMPTY> entremedio de dos tuplas de una página? Algo así como esto:

11 33 
32 98
`<EMPTY>`
65 75
23 14
`<NEXT><NULL>`

**Comment by TamaraCucumides** [comment]
Hola, si eso es posible de hecho las paginas de la relacion S son ejemplo de ello

**Comment by jitorralba** [comment]
Aaaah no las había cachado jajaja
