### ISSUE TITLE
Usuarios Entrega 3

### ISSUE THREAD

**Issue by rieg-ec** [IIC2413/Syllabus-2020-2#234]
Hola, no me queda muy claro la informacion de usuarios. Por lo que entiendo, hay que hacer una nueva relacion y migrar los jefes y capitanes a esta, con una contrasena al azar. Que debemos hacer con los atributos que son distintos? los jefes tienen rut y no nacionalidad, y los capitanes tienen nacionalidad y pasaporte.

**Comment by arpincheira** [comment]
Hola, dado que todos los puertos se encuentran en Chile y el número de pasaporte es equivalente al rut según el enunciado, puedes asumir que **todos los jefes son Chilenos y que su número de pasaporte es el RUT**

**Comment by rieg-ec** [comment]
yaa muchas gracias!

**Comment by mariagonthier** [comment]
Hola! eso también corre para las personas que no son jefes? (En la información de los grupos impares)
