### ISSUE TITLE
Control 2: solo integers?

### ISSUE THREAD

**Issue by bpardobravo** [IIC2413/Syllabus-2020-2#235]
Hola, se puede asumir que para las funciones del database.py se trabajará solo con integers?
O pueden existir relaciones que tienen strings?

**Comment by TamaraCucumides** [comment]
Hola, tal como indica el enunciado los tipos soportados son int y string así que tu solución debe soportar ambos. 

Saludos!

**Comment by bpardobravo** [comment]
Y cuando se ejecuta filtered_tuples('R','a = 01') por ejemplo, cómo sé si se quiere comparar como string o como int? En strings  1 != 01, pero en ints 1=01
