### ISSUE TITLE
Control 2: Bonus método get_iterator()

### ISSUE THREAD

**Issue by JosefaPaz** [IIC2413/Syllabus-2020-2#236]
¡Hola! 

Espero que estén muy bien 😸. No entendí muy bien qué debía hacer el método que debemos implementar en el primer bonus ```get_iterator()```. Solo entiendo que debe devolver un objeto con los mismos métodos que ya tiene una relación, por lo que me confunde un poco el punto de implementarlo y qué diferencia tiene con hacer R = Relations[R].

Gracias 😄 🦋

**Comment by TamaraCucumides** [comment]
Hola! el principal problema de tener un iterador y una relación en el mismo objeto es que no puedes hacer operaciones que impliquen tener dos iteradorws en la misma relacion (ej. un self join).

Por esto el bonus es crear un iterador que funcione independiente del objeto relacion. Por ejemplo: podrías hacer una clase Iterador con los métodos mencionados.

**Comment by JosefaPaz** [comment]
Perfecto, ahora me queda super claro, gracias Tamara!!
