### ISSUE TITLE
duda para método insert_tuple C2

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#238]
Hola, tengo una duda sobre si yo sé que existen las páginas S y R ? o tengo que encontrar todas las páginas que tiene el buffer?

**Comment by TamaraCucumides** [comment]
Hola, no entiendo la pregunta. Las paginas deben pedirse necesariamente a traves del buffer, puedes revisar que pasa si le pides una pagina que no exista

**Comment by Camila-sty** [comment]
No, nada, yo me enredé gracias
