### ISSUE TITLE
Duda en insert_tuple de control 2

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#239]
Hola. Cuando tengo que agregar otra página  a la relación, el nombre debe ser de la misma manera? por ejemplo si ya está `R-1, R-2, ...., R-5`, el próximo debe ser` R-6`? y así sucesivamente?

**Comment by TamaraCucumides** [comment]
Hola, es buena idea mantener la nomenclatura de las páginas para que sea consistente con los datos de ejemplo

**Comment by Camila-sty** [comment]
Ok, gracias
