### ISSUE TITLE
Guia - Procedimientos Almacenados

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2413/Syllabus-2020-2#240]
Hola he intentado abrir la guía desde que se subió, pero cuando lo hago me dice "Perdón, algo salió mal. ¿Recargar?", converse con mi grupo de proyecto y les pasa lo mismo.

De antemano, muchas gracias.

**Comment by arpincheira** [comment]
Efectivamente pasa eso pero probablemente es un problema de la herramienta de visualización de jupyter Notebooks en GitHub, para poder visualizar los archivos sin tener que descargarlos recomiendo la página https://nbviewer.jupyter.org.

 Ahora, si accedes a [este link](https://nbviewer.jupyter.org/github/IIC2413/Syllabus-2020-2/blob/master/Notebooks/ProcedimientosAlmacenados/Procedimientos%20Almacenados%20-%20Gu%C3%ADa.ipynb) vas a poder acceso a la visualización del archivo.

Saludos
