### ISSUE TITLE
duda de filtered_tuples(R,cond) en control 2

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#242]
Hola, en el método `filtered_tuples(R,cond)`  qué vendría siendo especificamente `cond`? es una tupla?

**Comment by based-on-what** [comment]
En `databse.py` dice que `# cond is if the form 'attr = value'`, así que sumo que se trata de un `string`

**Comment by Camila-sty** [comment]
no entiendo.... qué es `cond`? que tiene que ver esto `'attr = value'`?
