### ISSUE TITLE
Cross Data en PostgresSQL

### ISSUE THREAD

**Issue by CataSudo** [IIC2413/Syllabus-2020-2#243]
Hola, para la entrega 3, ¿Cómo podemos hacer un cross data (queremos usar información de una base de datos en otra base de datos) en postgress para hacer procedimientos almacenados ? Encontramos soluciones pero todas requieren instalar una extensión.

**Comment by CataSudo** [comment]
Hola, aún tenemos esta duda en mi grupo, ¿Nos pueden ayudar por favor?

**Comment by Vicerc** [comment]
Holaa!
Pueden utilizar extensiones para esta entrega, les dejo estos links que explican bien cómo funcionan:
- postgres_fdw: https://medium.com/better-programming/postgresql-and-the-foreign-data-wrapper-2f5c5aaf20d4
- db link: https://medium.com/@techrandomthoughts/setting-up-db-link-in-postgresql-d196468b43f8
Cualquiera de estas debería servirles para poder conectarse a otras bases de datos

**Comment by jdlarrain** [comment]
Hola, trate de hacerlo pero me dice que debo ser superusuario :/

**Comment by arpincheira** [comment]
Ahora deberían ser capaces de utilizar dblink en el servidor, aparentemente cuando creé la base de datos para esta entrega no habilité dblink para ella :/ disculpen las molestias

**Comment by csmeneses** [comment]
Hola, intentando establecer la conexión con la base de datos del otro grupo nos encontramos con el mismo problema de que hay que ser superuser. Por lo que entiendo, nosotros no tenemos el poder de hacernos superuser :(

![image](https://user-images.githubusercontent.com/48298696/96519234-e986d000-1242-11eb-9656-6e9e0bb13a19.png)

**Comment by CataSudo** [comment]
Hola, parece que no paso nada, no se pueden seguir las instruciones de los links. Parece que no esta habilitado para dblink. 
<img width="631" alt="Screen Shot 2020-10-20 at 16 44 18" src="https://user-images.githubusercontent.com/62016215/96636342-8e60e600-12f3-11eb-8df8-b618e1a446f6.png">

<img width="363" alt="Screen Shot 2020-10-20 at 16 43 59" src="https://user-images.githubusercontent.com/62016215/96636336-8c972280-12f3-11eb-8487-b6ec0f6eb5fd.png">

**Comment by arpincheira** [comment]
Hola, ahora si, para poder utilizar dblink deben poner las siguientes credenciales de conexión:
```sql
public.dblink('dbname=grupoXXe3 port=5432 password=XXX user=grupoXX');
```

**Comment by AgustinZalaquett** [comment]
Hola, sigo sin entender como tenemos que hacer el cross data, trate con distintos metodos pero en todos me pide superUsuario o me no me reconoce el servidor.
Por favor si me pueden ayudar a enlazar las bases de datos con un metodo sin ser super usuario, gracias de antemano.

**Comment by castrillini** [comment]
Hola, prueben con:
SELECT * FROM dblink('host=localhost user=grupoXX dbname=grupoXX password=XXX port=5432', 'SELECT nombre FROM Perros')

Por si acaso la consulta en sí es un ejemplo cualquiera. Lo importante es que miren el modo de uso de "dblink".

**Comment by CristobalUrzua** [comment]
@castrillini intenté lo que pusiste pero me sale:
ERROR:  a column definition list is required for functions returning "record"

Agradecería si me puedes ayudar.
