### ISSUE TITLE
Control 2  insert_tuple(tup) en relation.py

### ISSUE THREAD

**Issue by MINGOD24** [IIC2413/Syllabus-2020-2#244]
Hola, no me queda claro si las funciones:
    -buffer.get_page(pname) -- para conseguir las páginas
    - page.insert_into_pos(emptyPos,tup)  -- para insertar un dato en una posición vacia
    - buffer.evict_page(pname) -- para forzar al buffer escribir una página al disco (una vez insertada la tupla nueva)
    - buffer.create_page(pname) -- si necesitan crear una página nueva
    - page.set_next_page(pname) -- para setear next_page
son las únicas que puedo utilizar, o son las mínimas?

**Comment by TamaraCucumides** [comment]
Hola! no deberías necesitar otros métodos. Recuerda que el trabajo con paginas se hace siempre a través del buffer y el único momento en que debes usar directamente algo de la clase Page es cuando quieres escribir la tupla () y/o cuando debes linkear una nueva pagina.

**Comment by TamaraCucumides** [comment]
Es para revisar si la tupla ya existe en la pagina? si es así no hay problema con el uso de ese método :)

**Comment by MINGOD24** [comment]
Sii es para eso! No sabia si podía decir para que la quería ocupar jajajajaj. Muchas gracias!

**Comment by MINGOD24** [comment]
Me surgió otra duda, puedo crear un atributo extra a la clase Relation? No afectaría a la clase en si pero me ayudaría a manejar información.

**Comment by TamaraCucumides** [comment]
Si obvio, eso puedes documentarlo en un pequeño readme para que no hayan confusiones luego con la corrección.

**Comment by naviera** [comment]
Se pueden usar los métodos de Relation open(), close(), has_next() y next() para recorrer la relación buscando la tupla? Gracias :)

**Comment by Ajbarros1** [comment]
Se pueden usar los datos de todas las clases? Como page.data o relation.current_pos, por ejemplo

**Comment by TamaraCucumides** [comment]
> Se pueden usar los métodos de Relation open(), close(), has_next() y next() para recorrer la relación buscando la tupla? Gracias :)

Si, no hay problema



> Se pueden usar los datos de todas las clases? Como page.data o relation.current_pos, por ejemplo

Sip
