### ISSUE TITLE
Problema para correr el servidor de psql

### ISSUE THREAD

**Issue by svaldes99** [IIC2413/Syllabus-2020-2#245]
Hola, cuando corro el servidor de psql me tira este error:

![image](https://user-images.githubusercontent.com/62103274/95902110-b1771d00-0d6a-11eb-91d6-5c04551e9213.png)

Por que puede ser?

**Comment by Vicerc** [comment]
Disculpa la tardanza!
Si aún no lo puedes solucionar es porque ya tienes un proceso corriendo en el puerto 5433. Para cambiar el puerto de postgresql te recomiendo ver este link https://stackoverflow.com/questions/187438/change-pgsql-port. Por la imagen supongo que estás usando wsl, de ser así puede ser que tengas postgresql corriendo en windows, lo que no te permite correrlo en wsl, si quieres cerrar el servidor de postgres en windows puedes seguir los pasos de este link https://tableplus.com/blog/2018/10/how-to-start-stop-restart-postgresql-server.html.
