### ISSUE TITLE
Python y Google Colab

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2413/Syllabus-2020-2#246]
Hola, tengo un problema, cuando corro el programa con los mismos test, en python si me funciona, pero en google colab no, me dice que le estoy dando un atributo extra, si bien cree un atributo extra, la clase esta bien definida, en el fondo de la misma manera que en el python.

De antemano, muchas gracias.

**Comment by TamaraCucumides** [comment]
Prueba reiniciando el entorno de ejecución a fábrica y cargando de nuevo los archivos .py
