### ISSUE TITLE
Control 2 nested_loop_join

### ISSUE THREAD

**Issue by josejimenezp** [IIC2413/Syllabus-2020-2#247]
Para el retorno de la función es necesario que no se repitan los atributos o da lo mismo? Me explico: por ejemplo con R(a,b) y S(b,c) se obtiene a,b,b,c. Es necesario que sea de la forma a,b,c o también sería correcto mostrar el resultado como a,b,b,c donde ambos b son iguales? Gracias!

**Comment by TamaraCucumides** [comment]
Hola! idealmente no debiese estar repetido, pero no hay problema si aparece dos veces el atributo sobre el cual se hace el join
