### ISSUE TITLE
block_nested_loop_join

### ISSUE THREAD

**Issue by Baelfire18** [IIC2413/Syllabus-2020-2#248]
Hola no entiendo y creo que no sale explicado que hace el `block_nested_loop_join(R, S)`
Feliz si me explican!

**Comment by TamaraCucumides** [comment]
Hola, 
la explicacion del algoritmo block nested loop join está en [este video de clases](https://drive.google.com/file/d/1A5EVhvymgFOMfmXRlCzxKumHnWdWi_uF/view)

Luego de que lo revises puedes escribir por aqui si te quedan dudas :)
