### ISSUE TITLE
Lugar de entrega control 2

### ISSUE THREAD

**Issue by mpbascunan** [IIC2413/Syllabus-2020-2#250]
Hola, ¿dónde se entrega el control 2?

**Comment by TamaraCucumides** [comment]
Hola!
voy a abrir el cuestionario en siding en unos minutos :)

**Comment by mpbascunan** [comment]
Gracias!

**Comment by DiegoPibe** [comment]
Holaa, como lo hago para subir los 2 archivos ??, no se si no se hacerlo o tienen que habilitar dos casilleros para agregar los archivos. Gracias de antemano.

**Comment by TamaraCucumides** [comment]
Hola!
debes comprimir **todos** los archivos necesarios para ejecutar tu solución en un archivo .zip.

Deben incluir:
- todos los archivos .py
- los archivos de las relaciones originales
- el jupyter notebook con su demo

**Comment by DiegoPibe** [comment]
oka, graciaaas.
