### ISSUE TITLE
Tuplas relación T

### ISSUE THREAD

**Issue by zaertis0** [IIC2413/Syllabus-2020-2#251]
Las 7 tuplas que se insertan en T se crean al azar o tienen que ser algunas en específico?

**Comment by TamaraCucumides** [comment]
Hola, puedes intentar crear tuplas que sean razonables para hacer el join con `S` y `R` y para hacer el filtrado de `a=1`. 

Con razonable me refiero a tuplas tales que el resultado de esas consultas que menciono no sean vacio.
