### ISSUE TITLE
Demo nested_loop_join()

### ISSUE THREAD

**Issue by mpbascunan** [IIC2413/Syllabus-2020-2#252]
Hola, en la demo del nested_loop_join() es pide hacer nested_loop_join('R', 'T') y nested_loop_join('S', 'T'), sin embargo, no se explicita el tercer argumento que recibe este método que sería el atributo (attrib), ¿nuestro algoritmo debe ser capaz de reconocer el primer atributo que tengan igual o todos? o simplemente hacemos el demo entregando el atributo que sabemos que tienen igual para los casos particulares de las relaciones R, T y S? En este último caso utilizaríamos nested_loop_join('R', 'T', 'a') y nested_loop_join('S', 'T', 'c')

**Comment by TamaraCucumides** [comment]
Hola! debes especificar el atributo sobre el cual se hace el join como un argumento `attr` tal como mencionas :)

**Comment by CataSudo** [comment]
Hola, ¿Puedes darme un ejemplo del argumento attr? Tipo va a ser == o =, o para mayor igual, etc.

**Comment by mpbascunan** [comment]
Gracias!
