### ISSUE TITLE
Duda Control 2

### ISSUE THREAD

**Issue by lewebe** [IIC2413/Syllabus-2020-2#253]
Hola, no entiendo si por ejemplo para la primera actividad solo podemos usar los métodos que ahí nos dice y ninguno más.  Si ese es el caso, no entiendo cómo revisar las tuplas de cada página, pued los metodos indicados solamente me sirven para manipular páginas con el buffer, y no para leer lo que tienen dentro

**Comment by TamaraCucumides** [comment]
Issue #244
