### ISSUE TITLE
Control 2 pregunta 2 y 3

### ISSUE THREAD

**Issue by CataSudo** [IIC2413/Syllabus-2020-2#255]
Cuando se nos pasa R, asumimos ¿Que es  R = Relations[R] o hay que implementar esto?

**Comment by CataSudo** [comment]
Que vi en otras funciones que cuando pasan R dentro de ella como en cross, hacen R = Relations[R], entonces no se si en la pregunta 2 y 3 del control tenemos que hacer eso o asumimos que es dado.

**Comment by TamaraCucumides** [comment]
Ahh ya entiendo. Si, en ese sentido puedes asumir que te pasan el nombre de la relacion (asi que debes inicializar tu misma la relacion dentro de tu funcion tal como hacen en la funcion cross)
