### ISSUE TITLE
control 2 filtered_tuples()

### ISSUE THREAD

**Issue by allullk** [IIC2413/Syllabus-2020-2#256]
En el método filtered_tuples(self, cond)
la condición de prueba dada en el archivo es cond: 'a = 1' que es para el caso de que el atributo a sea de tipo int
en el caso de que a sea de tipo str, ¿Cual de los siguientes valores de cond deben funcionar con nuestra implementación? 
'a = "hola"', 'a = 'hola'', o 'a = hola'
personalmente, creo que la tercera forma es la mejor para implementar.

**Comment by TamaraCucumides** [comment]
Hola, deberia ser `'a = hola'` tal como intuyes :D

**Comment by allullk** [comment]
Muchas gracias Tamara! :^D

**Comment by dsepulveda3** [comment]
Hola Tamara. Finalmente el método filtered_tuples debe funcionar solo para la condición de = (igualdad). O también para condiciones de mayor y menor ??

**Comment by TamaraCucumides** [comment]
> 
> 
> Hola Tamara. Finalmente el método filtered_tuples debe funcionar solo para la condición de = (igualdad). O también para condiciones de mayor y menor ??

Solo igualdades :)

**Comment by dsepulveda3** [comment]
Dale, gracias !
