### ISSUE TITLE
Problema con insert_tuple en Control 2

### ISSUE THREAD

**Issue by vsantelicest** [IIC2413/Syllabus-2020-2#258]
Hola! 
Para la pregunta 1 del Control 2, armé la función insert_tuple y funciona perfecto salvo que nunca se me escribe la última tupla que trato de meter.
Por ejemplo, si tengo en la parte inferior del código:
`buff = Buffer()
R = Relation('R',['a','b'],['int','int'],buff)

R.insert_tuple('11 15') # New tuple
R.insert_tuple('27 1329') # Create a new next_page
R.insert_tuple('11 153') # Insert existing tuples`
Se me agregan las tuplas '11 15' y '27 1329' correctamente en las posiciones que deberían, pero la tupla '11 153' no se agrega en ninguna parte.
Revisando el código mediante prints, pude ver que efectivamente el código "pasa" por la parte donde inserto esta última tupla, sin embargo esta no se inserta.

**Comment by TamaraCucumides** [comment]
Hola!

Difícil saber donde puede estar el error sin ver el código. Lo único que se me ocurre a priori es que no estas escribiendo la pagina en disco. Para esto debes hacer un `evict_page` sobre la pagina en la que estas escribiendo la nueva tupla.

**Comment by vsantelicest** [comment]
Ahh perfecto. Ese evict_page se pone después de insertar la tupla?

**Comment by vsantelicest** [comment]
Ahi me funcionó, gracias!!

**Comment by TamaraCucumides** [comment]
Bacan!! Sii, el `evict_page` saca la pagina del buffer y la escribe si es que sufrió algún cambio  :D

**Comment by vsantelicest** [comment]
Pucha, ahora me surgió otro problema. Solamente se me escribe la primera de las tuplas que trato de insertar, el resto no, y el código se queda corriendo eternamente. No se que podrá ser

**Comment by TamaraCucumides** [comment]
Cual es el flujo que estas usando para insertar? Debería ser algo como: 

1. Revisar si la tupla esta, mientras hacemos esto buscamos el primer lugar vacío
2. Si la tupla no esta, la insertamos en el primer lugar vacío que encontramos (puede que necesites crear una pagina nueva)
3. Luego de la inserción, hacemos evict_page a la pagina que sufrió el cambio. Con esto el cambio se materializa en el archivo de la relacion

**Comment by vsantelicest** [comment]
Sii ahí me salió, usé el método de flush_buffer. Gracias!!!

**Comment by rieg-ec** [comment]
Tengo una duda respecto a eviction. No he podido encontrar informacion, y en el libro guia busque la palabra y no sale. Solo lo he escuchado una vez y por lo que entendi es cuando no queda espacio en el buffer y tenemos que guardar en disco algun frame del buffer para hacer espacio. Pero si es asi, esto se ocupa para leer paginas, mi duda es porque seria necesario ocupar evict aca, si una vez que hayamos hecho el cambio lo que debemos hacer es escribir la pagina en disco. No deberia ser write_page()?

**Comment by TamaraCucumides** [comment]
El evict lo que hace es devolver la pagina y la escribe si sufrió cambios, de hecho si revisas el código del evict hace dentro un `write_page()`.

Hacer el evict te asegura que vas a guardar los cambios. También puedes hacer un flush_buffer() o directamente un write_page() aunque en teoría uno no debería poder hacer eso directamente, ya que las paginas solo se escriben cuando salen del buffer.

**Comment by rieg-ec** [comment]
Ahora entiendo mejor, gracias :D una ultima duda, esta bien que podamos directamente ocupar page.insert_into_pos? no debiese ser a traves del buffer cualquier interaccion con las paginas?

**Comment by DomagojVrgoc** [comment]
Lo que ocurre es que el buffer te devuelve un puntera a una página en alguno de sus frames. Cuando modificas esta página (usando insert_into_pos(i,val)) se modifica el contenido en el buffer, pero no en el disco. Esto está permitido. Para reflejar los cambioa en el disco, hay que escribir la página, ahora usando el buffer manager (con evict_page(pname)).
