### ISSUE TITLE
Problema Discord

### ISSUE THREAD

**Issue by jerrazuriz99** [IIC2413/Syllabus-2020-2#259]
Al meterme al link del discord (https://discord.gg/8SNTvw) me sale esto:
(estoy con mi mail uc en discord)
![discordf](https://user-images.githubusercontent.com/53884268/96033807-f799b280-0e36-11eb-88b6-c2f2bf01dfa1.JPG)

**Comment by TamaraCucumides** [comment]
Hola, intenta este link

https://discord.gg/JVrzW7
