### ISSUE TITLE
Problema corriendo código Control 2

### ISSUE THREAD

**Issue by CataSudo** [IIC2413/Syllabus-2020-2#260]
<img width="746" alt="Screen Shot 2020-10-14 at 16 22 00" src="https://user-images.githubusercontent.com/62016215/96035424-6710a180-0e39-11eb-8b9d-5760a868e5c2.png">
Al testear el codigo me dan errores del codigo entregado. ¿Porque pasó esto?

**Comment by TamaraCucumides** [comment]
Hola!

estas usando python 3? creo que el error que muestras es de python 2. En caso de que estes usando python 2, debes cambiarte a 3.

**Comment by CataSudo** [comment]
Hola! Creo que estoy usando python 3.

**Comment by DomagojVrgoc** [comment]
Hmm. Si entiendo bien, tu editor no reconoce accentos.

Puedes borrar todo que está escrito en español/con accentos y ver si se arregla?

**Comment by TamaraCucumides** [comment]
@DomagojVrgoc ya solucionamos esto! :) era por el acento y se arreglo al usar python 3

**Comment by mmunoz12** [comment]
hola! tenia el mismo problema (con el mismo error), borré los tildes y ya no me aparece ese error si no que me aparece:
`  diskPage = open(self.pname, 'r', encoding='utf-8')
TypeError: 'encoding' is an invalid keyword argument for this function`
Al principio no tenía problemas corriendo el código con los tildes, no sé bien que fue lo que paso que comenzó a lanzar el error. Como podría solucionarlo?
