### ISSUE TITLE
Duda tipo de atributos

### ISSUE THREAD

**Issue by nicoguz** [IIC2413/Syllabus-2020-2#261]
Hola!!
En la 2 nos piden hacer un `filtered_tuples` pero tengo la duda de que aceptar como los valores. Por ejemplo, evidentemente si 'a' es `int` y me entregan un '5' debería pasar pero si 'a' es `str` debería aceptar '5'? o algo como 'ejemp10'?

**Comment by DomagojVrgoc** [comment]
Si, si a es str, '5' está bien, y cualquier otro string sin espacios.

Se recomienda usar split('=') y strip() para sacar los valores desde el string de la tupla.

**Comment by nicoguz** [comment]
Perfecto, graciaass!!

**Comment by cotefon** [comment]
puedo asumir que solo trabajaremos con strings e int?

**Comment by TamaraCucumides** [comment]
> puedo asumir que solo trabajaremos con strings e int?

Tal como sale en el enunciado, si. Solo strings e int.

**Comment by rodrigobj99** [comment]
Hola, una duda, puede pasar que se nos haga comparar atributos de distintos tipo en el join? Me refiero a que sí en una relación el elemento 'a' es str y en otra 'a' es int el join entre las dos relaciones con respecto a 'a' quedaría vacío. Es esto posible o se puede asumir que no pasara?

**Comment by TamaraCucumides** [comment]
Pueden asumir que no pasara

**Comment by sebaelsaca** [comment]
Hola, una duda. Solo pueden haber 2 columnas por cada relación o pueden haber más de 2? @TamaraCucumides

**Comment by TamaraCucumides** [comment]
Hola, pueden haber mas de dos (aunque lo vamos a probar solo con 2, tu solución debiese soportar una cantidad arbitraria de columnas)
