### ISSUE TITLE
Control 2: Open()/close() y páginas cargadas en buffer

### ISSUE THREAD

**Issue by GbPoblete** [IIC2413/Syllabus-2020-2#262]
Holaa! 

Tengo una duda con el demo que tenemos que escribir, en particular si el método open() y close() de la relación debe ir en el demo o en la función que yo haga en el archivo .py

Otra duda es en relación a la clase buffer, es que no entiendo muy bien cómo el buffer sabe cuando ya cargó todas las páginas de la relación. Es para el caso de que no encuentre ningún empty.

Muchas gracias!

**Comment by TamaraCucumides** [comment]
Hola! 

> Tengo una duda con el demo que tenemos que escribir, en particular si el método open() y close() de la relación debe ir en el demo o en la función que yo haga en el archivo .py

Te recomiendo seguir la estructura de los demás métodos, es decir, hacerle open y close dentro de la función

> Otra duda es en relación a la clase buffer, es que no entiendo muy bien cómo el buffer sabe cuando ya cargó todas las páginas de la relación. Es para el caso de que no encuentre ningún empty.

No entendí muy bien esta duda :( el buffer va cargando las paginas pero es la clase Relation la que le dice que paginas tiene que ir cargando.

**Comment by DomagojVrgoc** [comment]
Hola.

open() y close() ya deberían estar en el python. Tu metodo (e.g. join('R','S')) simplemente imprime todas las tuplas en el resultado.

El buffer ha cargado todas las páginas cuando ya no hay un next (es NULL) en una página. Si no, tienes que seguir recorriendo tuplas y páginas.
