### ISSUE TITLE
CONTROL 2: Algunos tips

### ISSUE THREAD

**Issue by TamaraCucumides** [IIC2413/Syllabus-2020-2#263]
- Puede pasar que al probar la demo con jupyter notebook, los archivos de las relaciones no se actualicen. Para verificar que sus insert sean correctos tienen dos opciones:  

1.  Revisar directamente los archivos en los que quedan guardadas las tuplas
2. Hacerle un restart al jupyter (se hace con el icono que es una flechita redonda, al lado del cuadrado de interrumpir) e importar de nuevo los archivos (a veces no basta con ejecutar de nuevo la celda de los import)

- El flujo para insertar una tupla debiese ser el siguiente: 
 
1. Con un ciclo revisar si la tupla ya existe en la relacion. Al mismo tiempo (en el mismo ciclo for) revisar cual es el primer espacio vacío que encuentren. GUARDEN este espacio vacío, es decir, guarden la pagina y la posición en la que esta. 

2. Si la tupla no estaba en la relacion inserten la tupla en la pagina y posición que ustedes saben que esta vacia. No es necesario que hagan otro ciclo for para esto. Para asegurarse del cambio, hagan un evict_page de la pagina en la que acaban de insertar

3. Si no habían encontrado un espacio vacío, creen una pagina nueva, inserten la tupla en esta nueva pagina y linkeenla a la ultima pagina de la relacion. Hagan evict de las dos paginas (la nueva y a la que linkearon)

- Para la entrega deben comprimir todos los archivos necesarios para ejecutar tu solución en un archivo .zip. Esto incluye:
1. todos los archivos .py
2. los archivos de las relaciones originales
3. el jupyter notebook con su demo

* Para crear las relaciones deben usar el comando create_table(). Varios de ustedes la estan creando haciendo R = Relation(...). Si hacen eso no se les crea la relacion en la base de datos y luego no podrán ocupar los metodos de all_tuples, cross, filtered_tuples, nested_loop_join. **DEBEN** crear las tablas con create_table. Ojo que create_table por defecto inicializa un buffer, asi que no es necesario que creen un buffer "por fuera"

**Comment by Camila-sty** [comment]
Hola el archivo en vez de .zip puede ser .WinRAR ?
