### ISSUE TITLE
Entrega 3 usuarios

### ISSUE THREAD

**Issue by nbarriav** [IIC2413/Syllabus-2020-2#264]
Hola!
Cuando en el enunciado en la parte de Sistema de usuarios se señala: "Dentro de los usuarios de la aplicación se encuentran los capitanes de buques y los jefes de instalaciones en los puertos (pero pueden haber más)..." 
Los otros usuarios que pueden existir son netamente del personal o puede ser una persona externa?

Saludos

**Comment by arpincheira** [comment]
Hola, efectivamente pueden ser personas extras, en la issue #230 respondí esto con un poco más de detalle para que le des un vistazo
