### ISSUE TITLE
Error al insertar tupla en nueva relación T - Control 2

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#265]
Holaa, tengo duda de cómo crear una relación T para luego insertar tuplas, yo lo hice de la siguiente forma:
![image](https://user-images.githubusercontent.com/59337116/96055412-5cb2cf80-0e5a-11eb-8eeb-49f20e153348.png)
Pero al intentar inserta esa tupla me tira este error:
![image](https://user-images.githubusercontent.com/59337116/96055445-794f0780-0e5a-11eb-86c0-7492755c6e06.png)
![image](https://user-images.githubusercontent.com/59337116/96055462-82d86f80-0e5a-11eb-8910-e2e0b84796ec.png)
![image](https://user-images.githubusercontent.com/59337116/96055474-8a981400-0e5a-11eb-821d-8e7b3bcdf3db.png)
Y pienso que el problema podría ser porque no estoy creando bien la relación T, ya que el método` insert_tuple` funciona bien para la relación `R` que ya estaba creada por ustedes....
Qué podría estar haciendo mal?

**Comment by TamaraCucumides** [comment]
Hola, puedes ejecutar la creacion de la tabla al reve,? 

primero crear la relación y luego llamarla con la base de datos :D

**Comment by TamaraCucumides** [comment]
Hola!

primero debes crear la relacion, es decir, hacer el create table. Revisa la documentacion del codigo ya que esta dice: 
_def create_table(rName, attributes, types, buff = Buffer):
    # Creates a relation with rName, and attributes as its attributes with respective types_

luego de eso puedes hacer un T = relation ...

Lo que esta pasando es que al hacer el T = ... antes, estas con una relacion que no tiene asociada ninguna pagina, entonces el buffer al intentar buscar T-1 no la encuentra y tira error

**Comment by Camila-sty** [comment]
Hola, cambie el orden;:
![image](https://user-images.githubusercontent.com/59337116/96128652-04b4b100-0ecc-11eb-8415-d0f84666ee12.png)
y me tira el mismo error que mencioné arriba,,,

**Comment by Camila-sty** [comment]
Se supone que la relación ya existe, pero me tira ese error cuando voy a insertar una tupla... no entiendo por qué, ya que en las otras relaciones si me funciona

**Comment by Camila-sty** [comment]
Ya encontré el error, estaba llamand a self.current_page sin haber hecho open() antes, pero en todo caso mi error con la tabla nueva T no me funciona bien, ya no me tira error, pero me funciona, lo voy a exponer en otra issue. Gracias!

**Comment by TamaraCucumides** [comment]
Hola Camila! asi no es como deberias crear la relacion debes hacer:

```
create_table(...)
T = Relations["T"]
```

y luego T.insert_tuple

la instancia de database te crea un buffer, no es necesario que lo crees tu

**Comment by Camila-sty** [comment]
> Hola Camila! asi no es como deberias crear la relacion debes hacer:
> 
> ```
> create_table(...)
> T = Relations["T"]
> ```
> 
> y luego T.insert_tuple
> 
> la instancia de database te crea un buffer, no es necesario que lo crees tu

Pero dentro de create_table que debo poner?

**Comment by TamaraCucumides** [comment]
Tal cual como lo tienes

**Comment by Camila-sty** [comment]
sí, gracias, ahora se crea la relación, aparece una página T-1 , pero cuando voy a agregar un tupla, me crea otra página T-2 sin leer T-1, me refiero a que dentro de mi método insert_tuple, al principio tengo 
`self.open()
		while (self.has_next()):
                   ...........
self.close()`
Pero no lee eso para T-1, y por eso me crea una segunda página, pero esto no se si tiene que ser con mi código o con haber creado mal la página? quizás falta agregar otra cosa?

**Comment by TamaraCucumides** [comment]
Al hacer create_table se te deberia crear aautomaticamente la pagina T-1. Eso está bien!
tu solucion deberia:
recorrer T hasta encontrar el primer espacio vacio (deberia ser justo el primero), creo que estas fallando en eso.

**Comment by TamaraCucumides** [comment]
Corre estas lineas de codigo:

```
create_table('N',['a','b','c'],['int','int','int'])
N = Relations["N"]
N.open()
print(N.has_next())
N.close()
```

Eso te deberia entregar False, yo lo acabo de intentar y funciona bien (entrega False altiro)

**Comment by Camila-sty** [comment]
> Corre estas lineas de codigo:
> 
> ```
> create_table('N',['a','b','c'],['int','int','int'])
> N = Relations["N"]
> N.open()
> print(N.has_next())
> N.close()
> ```
> 
> Eso te deberia entregar False, yo lo acabo de intentar y funciona bien (entrega False altiro)

Sí, me entrega False

**Comment by Camila-sty** [comment]
> Sí, es que me funciona el método `insert_tuple `para todos los casos con la relación `R` y `S`. Pero al crear `T` se crea la página `T-1`, luego inserto una tupla, pero nunca entra a` while (self.has_next()):` porque tengo `prints` dentro de ese `while` y nunca se ejecutan.... entonces como no entra a ese `while` no me funciona el código, ya que mas abajo el código cree que no hay ninguna linea vacía y por eso crea una segunda página.... (nunca entra a `while`, por lo tanto no encuentra la posición vacía)

Incluso al crearse `T-2` no se linkea con` T-1 `no agrega la tupla que debía agregar....
![image](https://user-images.githubusercontent.com/59337116/96134833-c02c1400-0ed1-11eb-8d8a-c557c51e0eb5.png)
![image](https://user-images.githubusercontent.com/59337116/96135128-d33ee400-0ed1-11eb-8dff-c93975cc733b.png)

**Comment by TamaraCucumides** [comment]
Entonces es tema de tu implementacion. Basicamente tu implementacion del insert_tuple no soporta tablas vacias, tienes que arreglarla para que funcione. 

No puedo saber por qué no se está linkeando sin revisar tu implementacion directamente. Pero para linkear tienes que hacer page.set_next_page(pname)

**Comment by Camila-sty** [comment]
> Entonces es tema de tu implementacion. Basicamente tu implementacion del insert_tuple no soporta tablas vacias, tienes que arreglarla para que funcione.
> 
> No puedo saber por qué no se está linkeando sin revisar tu implementacion directamente. Pero para linkear tienes que hacer page.set_next_page(pname)
> 
> Revisa la issue pinneada: #263

Es que si funciona, porque lo probé con la relación `R`, agregé tuplas hasta que se acabaran las lineas vacías, y luego agregé otra para crear una nueva página (`R-6`) y esta se agrega y linkea sin ningún problema.... incluso agrega la tupla. Entonces esto no me hace pensar que el error es de mi código :( .
Volviendo al problema, no entiendo por qué al existir ya `T-1 `y ejecutar` insert_tuple(tup) `no entra a `while (self.has_next()):`

**Comment by TamaraCucumides** [comment]
Porque tu while es while T.has_nexr() y el T no tiene has_next porque esta vacio. No es problema del codigo base, sino de tu implementacion ya que no estas considerando el caso de la relacion vacia (relacion vacia != pagina vacia)

**Comment by TamaraCucumides** [comment]
Fijate de nuevo en tu implementacion y en los metodos que tienes disponibles: al entrar a una relacion vacia tienes

create_table('N',['a','b','c'],['int','int','int'])
N = Relations["N"]
N.open()
print(N.has_next())
print(N.current_page)
print(N.current_pos)
N.close()

EL current page sera N-1 y el current pos sera -1 (antes del inicio), en este caso sabes que es una relacion vacia, entonces tienes que ahcer insert en la pagina N-1 en la posicion 0. Tienes ese caso en tu codigo?

**Comment by TamaraCucumides** [comment]
Avísame si lo solucionas, si no podemos ver como te puedo ayudar de mejor manera (quizás por discord o en un zoom)

**Comment by Camila-sty** [comment]
Yaaa, después de leer tus recomendaciones agregué todo lo que me faltaba, y ahora sí funciona, muchas gracias!!
😄

**Comment by TamaraCucumides** [comment]
Bacan!! que bueno que te funciono :D
