### ISSUE TITLE
Control 2 preguntas 2 y 3

### ISSUE THREAD

**Issue by srhernandez1** [IIC2413/Syllabus-2020-2#266]
Tengo 2 dudas sobre las funciones filtered_tuples y nested_loop_join:
1.- ¿Ambas funciones sólo deben hacer print, o deben retornar algo?
2.- ¿Para estas funciones también hay que considerar que la información se obtiene desde el buffer?

**Comment by TamaraCucumides** [comment]
Hola!
efectivamente para ambas funciones basta con hacer print de las tuplas. Ninguna de las dos funciones requiere trabajar con el buffer  :)
