### ISSUE TITLE
[Control 2] - Entregar Solo sección de demo (sin los ejemplos anteriores)

### ISSUE THREAD

**Issue by ceosorio** [IIC2413/Syllabus-2020-2#267]
Hola! 

quería saber si el jupyter notebook que tenemos que entregar, puede ser solo la sección de los **import + los demos**. Ocurre que, por alguna razón, si intento correr todo lo del jupyter notebook mis demos tiran errores. Pero si solo corro los import, y después mis demos, funcionan sin problemas 😢 

Si no se puede, podría dejar esta observación en mi readme?

Saludos!

**Comment by TamaraCucumides** [comment]
Hola, si obvio. De hecho es buena idea, así queda mas ordenado :)

**Comment by ceosorio** [comment]
Perfecto, muchas gracias!
