### ISSUE TITLE
CONTROL 2: all_tuples ( ) 

### ISSUE THREAD

**Issue by dcastillo5** [IIC2413/Syllabus-2020-2#268]
Hola
Estoy teniendo un problema. Implemente `insert_tuple()` y logre actualizar el disco, sin embargo, al llamar `all_tuples('')` se muestra tan solo la primera tupla, pero si utilizo los metodos de la clase Relaciones funciona y se imprimen todas las tuplas.

![Captura de pantalla 2020-10-14 a las 8 32 07 p m](https://user-images.githubusercontent.com/61330735/96057869-4c055800-0e60-11eb-97ff-1df77963993d.png)

Creo que ambas son prácticamente iguales así que no entiendo cual puede ser el error

**Comment by FelipeA7** [comment]
Estoy teniendo el mismo problema y no entiendo muy bien por qué. Estuve probando y la única manera en que funciona bien el all_tuples('T') es reiniciando el kernel, luego crear la relación de nuevo y ejecutando nuevamente el all_tuples
Antes de reiniciar el kernel lo que hice fue crear la relación T e insertar las 7 tuplas
Es como si all_tuples no considerara las tuplas creadas con insert_tuple a menos a que reinicies el kernel

**Comment by TamaraCucumides** [comment]
Puedes revisar si te sirve la solución de @FelipeA7. Igual si la función insert te modifica los archivos, con eso estás listo. Voy a pedir a los ayusantes que revisen directamente los archivos en vez del all_tuples

**Comment by TamaraCucumides** [comment]
Solo para complementar, fijate en el codigo de create_table
```

def create_table(rName, attributes, types, buff = Buffer):
    # Creates a relation with rName, and attributes as its attributes with respective types

    # First we check that the relation does not exist
    if (rName in Relations.keys()):
        print('Relation already exists')
        return False

    Rel = Relation(rName, attributes, types, buff)
    Relations[rName] = Rel

    # If all went well e return True
    return True
```

si usas el create table y luego creas una isntancia de relacion, basicamente estas creando dos relaciones distintas. Los inserts se los estas haciendo a una, mientras que el all_tuples se ejecuta sobre la otra

**Comment by dcastillo5** [comment]
Lo pude solucionar  cambiando el create_table() tal como lo sugirió Felipe. 
Gracias a ambos!

**Comment by mmunoz12** [comment]
Hola! también tengo un problema con esto, pero lo que me pasa es que se imprimen infinitas duplas de las dos primeras paginas (siendo que son 5). No entiendo bien porqué ocurre esto. Las duplas están bien escritas en cada página y en la pagina 5 hay EMPTY, por lo tanto debiese parar ahí.

**Comment by TamaraCucumides** [comment]
> 
> 
> Lo pude solucionar cambiando el create_table() tal como lo sugirió Felipe.
> Gracias a ambos!

cambiaste el archivo buffer.py a la version actualizada? eso puede arreglar tu problema

**Comment by CataSudo** [comment]
Hola! Estoy teniendo el mismo problema con el all_tuples('T')
<img width="520" alt="Screen Shot 2020-10-15 at 22 17 55" src="https://user-images.githubusercontent.com/62016215/96201947-49743280-0f34-11eb-9a9f-39999184c44f.png">

<img width="595" alt="Screen Shot 2020-10-15 at 22 16 55" src="https://user-images.githubusercontent.com/62016215/96201911-319cae80-0f34-11eb-88c5-b3a777165874.png">

**Comment by TamaraCucumides** [comment]
Hola @CataSudo estas creando mal la relacion. El orden es:

1. haces create_table
2. haces T= Relations["T"]

eso te va a solucionar el problema

**Comment by TamaraCucumides** [comment]
> 
> 
> De todos modos, lo correcto para crear la relacion es:
> 
>     1. hacer primero create_table(...)
> 
>     2. luego hacer R = Relations["R"]
> 
> 
> De esta manera, es database la que le pasa el buffer a la relacion y asi te aseguras que se esta usando el mismo buffer para todo.
> 
> Puedes mostrarme como estas inicializando la relacion "N" ?

@CataSudo

**Comment by CataSudo** [comment]
No funciono 
<img width="679" alt="Screen Shot 2020-10-15 at 22 28 41" src="https://user-images.githubusercontent.com/62016215/96202517-d1a70780-0f35-11eb-9b9a-eebd52e50763.png">

**Comment by TamaraCucumides** [comment]
> No funciono
> <img alt="Screen Shot 2020-10-15 at 22 28 41" width="679" src="https://user-images.githubusercontent.com/62016215/96202517-d1a70780-0f35-11eb-9b9a-eebd52e50763.png">

Hola Cata, claro que no funciono porque no hiciste lo que te dije. 

hay varios errores en tu codigo:
1. estas poniendole T a la relacion R
2. estas creando la relacion R y luego estas buscando la relacion T, que nunca creaste

Borra las 3 primeras lineas de tu codigo y escribe las que te voy a poner textuales:

create_table('T',[''a','c'], ['int','int'])
T = Relations["T"]

en la primera estaras creando la relacion T y en la segunda la estas asignando a la variable T. 

Yo se que estamos todos medios cansados, pero es bueno que revises un poco tu codigo antes de escribir una issue :)

**Comment by CataSudo** [comment]
Oh, muchas gracias.

**Comment by TamaraCucumides** [comment]
@CataSudo te funciono?

**Comment by dsepulveda3** [comment]
Hola Tamara ! Estoy teniendo un error parecido al de mi compañera pero tengo todo bien definido como dices:
![image](https://user-images.githubusercontent.com/62180259/96286715-2f2f6880-0fb7-11eb-8bb0-239ad13f6be8.png)

**Comment by TamaraCucumides** [comment]
> Hola Tamara ! Estoy teniendo un error parecido al de mi compañera pero tengo todo bien definido como dices:
> ![image](https://user-images.githubusercontent.com/62180259/96286715-2f2f6880-0fb7-11eb-8bb0-239ad13f6be8.png)

Hola, no estas definiendo bien la relacion T. Tienes que hacrlo a traves de create_table, como ya puse en reiteradas ocasiones en esta misma issue

**Comment by dsepulveda3** [comment]
Ahi si jeje. Me pasa por leer rapido, mil disculpas :(. Gracias por todo
