### ISSUE TITLE
Control 2: insert_tuple() error "Position not empty"

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2413/Syllabus-2020-2#269]
Hola!Tengo un problema lo que pasa es que cuando intento agregar una segunda tupla a una nueva página que ya cree me apece el error: "Position not empty" ,sin embargo no entiendo por qué pasa esto ya que mi página anterior a la nueva página si tiene como next a la página que yo cree.
Para ponerlo más claro mi página R-5 que era la última antes de crear la página R-6  se ve así
![Captura de pantalla (158)](https://user-images.githubusercontent.com/62029138/96061591-02ba0600-0e6a-11eb-9a75-086757f86fc9.png)
Y mi página R-6 se ve así:
![Captura de pantalla (159)](https://user-images.githubusercontent.com/62029138/96061609-11082200-0e6a-11eb-966c-206341553eb2.png)
 
Por lo que pude analizar de mi problema es que cuando llamo al método para insertar la segunda tupla a mi nueva página el next de R-5 no se actualiza sin embargo cuando hice un :
R.open()
while  R.has_next():
	print(R.next())
R.close() 
Esto me mostro las tuplas de todas las páginas incluyendo la de la página R-6

**Comment by TamaraCucumides** [comment]
Hola! revisa bien que estés escribiendo los cambios en disco mediante un evict_page o un flush_buffer. 

Puedes intentar agregar algunos prints a tu insert tuple para ver en que posición esta intentando agregar la tupla ya que el error dice que lo esta intentando agregar en una posición que no esta vacia.

**Comment by RonaldoSosa** [comment]
Entendido!verificare esa parte , gracias!
