### ISSUE TITLE
Control 2: tuplas EMPTY

### ISSUE THREAD

**Issue by smrebolledo** [IIC2413/Syllabus-2020-2#270]
Hola, podemos asumir que las tuplas vacías siempre estarán al final? O puede que aparezcan entre medio de las otras tuplas?

**Comment by TamaraCucumides** [comment]
Hola, no pueden asumir eso. Te recomiendo ver el video de la ayudantia y/o revisar issues anteriores ya que esta pregunta ya la habían hecho.
