### ISSUE TITLE
Consulta evict_page y error

### ISSUE THREAD

**Issue by Skablop** [IIC2413/Syllabus-2020-2#271]
Hola, estaba probando el código del Control 2 y me surgió el siguiente error.
Al ejecutar este código:

```
R.open()
while R.has_next():
	print(R.next())
R.close()

R.buffer.evict_page('R-4')

R.open()
while R.has_next():
	print(R.next())
R.close()
```

En el primer while se ejecuta sin problemas, pero luego de hacer el evict_page se queda en un loop infinito. 
Asumo que es algo que tiene que ver con los punteros o algo así, ¿pero que es lo que está pasando detrás?

**Comment by TamaraCucumides** [comment]
Hola, cómo estás creando la relación R? 
Por otra parte se queda pegado en el for de abajo? qué imprime?

**Comment by Skablop** [comment]
Hola,

Es la misma relación R que entregan para probar las funciones, sin hacerle ningún cambio.

Sí, se queda pegado en el while de abajo imprimiendo eternamente las tuplas de la página R-1.

**Comment by TamaraCucumides** [comment]
Hola, si pero como estas inciializando R?

**Comment by Skablop** [comment]
Copiando la parte del test case de relation.py (lo que esta puesto como comentario al final del archivo).

**Comment by TamaraCucumides** [comment]
Perfecto, ya logre replicar el error, sin embargo, no entiendo por que quisieras hacer eso que estas haciendo... lo que sospecho que esta pasando es un tema del buffer. Estás intentando hacer el insert?

Si es asi revisa la issue que deje pinneada. Para hacer el insert solo necesitan recorrer la relación una sola vez :) 

Ya descubri la fuente del error, estoy viendo como lo puedo solucionar, pero o debería afectar tu solucion para el insert_tuple

**Comment by Skablop** [comment]
O sea no tengo problema al momento de insertar solo una tupla, pero si quiero insertar más de una en el mismo archivo (corriendo dos veces el método) no me deja a menos que cambie los evict por un flush. Ocurre esto mismo del loop infinito.

**Comment by TamaraCucumides** [comment]
Ya mira, el error se origina por esto: 

```
R.open()
while R.has_next():
	print(R.next())
R.close()

R.buffer.evict_page('R-4')

R.open()
print(R.buffer.pages_dict)
R.close()
```

Aqui lo que esta pasando es que en el diccionario de paginas esta como que la pagina R-1 y la R-2 estan guardadas en la posicion 1, entonces se entra al loop infinito porque se esta leyendo todo el rato la pagina R-1

**Comment by TamaraCucumides** [comment]
Dame 5 minutos, tengo una solucion lista y quiero ver si funciona

**Comment by Pablok98** [comment]
Hola! Yo tuve este mismo error y también lo identifiqué pero me dió miedo modificar el archivo del buffer, por lo que lo solucioné haciendo flush antes de insertar una tupla (por lo que hago flush al principio y evict al final), y ya hice todo con así :( . Estaría esto incorrecto, pensando que podría ser medio ineficiente?

**Comment by TamaraCucumides** [comment]
> Hola! Yo tuve este mismo error y también lo identifiqué pero me dió miedo modificar el archivo del buffer, por lo que lo solucioné haciendo flush antes de insertar una tupla (entonces hago flush al principio y evict al final), y ya hice todo con así :( . Estaría esto incorrecto, pensando que podría ser medio ineficiente?

No te preocupes, dejalo tal como esta. Efectivamente se bypasseaba el error al hacer un flush en vez de un evict :D

**Comment by Pablok98** [comment]
Gracias!
