### ISSUE TITLE
Formato demo

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2413/Syllabus-2020-2#272]
Hola!No me queda claro como se debe entregar la demo si es con los códigos ejecutados mostrando los resultado o solo lescritos para que el ayudante los ejecute por primera vez?

**Comment by Camila-sty** [comment]
A qupe se refieren con demo? al código del método?  o a los resultados del metodo?

**Comment by TamaraCucumides** [comment]
Hola!
Puedes dejarlos ejecutados pero al mismo tiempo si el ayudante considera necesario ejecutarlo de nuevo, debe poder hacerse :)

**Comment by TamaraCucumides** [comment]
> A qué se refieren con demo? al código del método? o a los resultados del método?

Al jupyter notebook que deben entregar con la demo de su código. Esta todo explicado en el enunciado y en la issue #263

**Comment by Camila-sty** [comment]
Sí, si lo había visto, pero no entiendo aún, debo escribir sólo el código del método? o el método junto a su código?

> > A qué se refieren con demo? al código del método? o a los resultados del método?
> 
> Al jupyter notebook que deben entregar con la demo de su código. Esta todo explicado en el enunciado y en la issue #263

**Comment by TamaraCucumides** [comment]
> código del método? o el método junto a su código?

No entiendo la diferencia entre esto.
El metodo de insercion debe ir en el archivo relation.py . Los metodos de filtro y join en el archivo database.py

El demo, tal como su nombre lo dice, debe hacer una demostración de estos métodos (como usarlos)

**Comment by Camila-sty** [comment]
sí el código para cada método que piden están en archivos `.py`, pero no entiendo que quieren que ponga, aún no entiendo qué es "demo" debo explicar cómo usarlo? o simplemente se refieren a llamar al método para que se ejecute?

**Comment by TamaraCucumides** [comment]
Precisamente es llamar el método y luego mostrar la ejecución (no el codigo base) . 

Por ejemplo para el insert, tal como pide el enunciado deben hacer un demo que: 
```
## Escriba aqui el demo de uso del metodo insert_tuple(tup)

# Crear la relacion T
# Hacer 7 inserciones
# Mostrar all_tuples('T')
```

De igual modo para el filtered tuples y el join, deben ejecutar el metodo y que queden los prints en el notebook

**Comment by Camila-sty** [comment]
sí, entiendo, es que me había confundido con "demo" pensé que quería que pusiéramos el código del método. Gracias!!

**Comment by RonaldoSosa** [comment]
Entendido!Gracias!!!!!!!
