### ISSUE TITLE
Forma del print en nested_loop_join - pregunta 3

### ISSUE THREAD

**Issue by francisca0308** [IIC2413/Syllabus-2020-2#273]
Hola!
Una consulta de la forma en que se espera que se impriman las tuplas de ```nested_loop_join('R', 'S', 'b')```:
- R.a | R.b | S.b | S.c
- R.a | b | S.c

Claramente el R debe aparecer a la izquierda si la función es de la forma dicha o no?
Muchas gracias

**Comment by TamaraCucumides** [comment]
Hola, puede ser de cualquiera de las dos formas que indicas, aunque la segunda es la "mas correcta". 

> Claramente el R debe aparecer a la izquierda si la función es de la forma dicha o no?
Sii, sean consistentes por eso para que no hayan confusiones
