### ISSUE TITLE
Formato notebook

### ISSUE THREAD

**Issue by bdiaz3** [IIC2413/Syllabus-2020-2#274]
Hola! Al abrir el archivo Actividad_2.ipynb en googlecolab se me abre como si fuera código y no como se muestra en la ayudantía. ¿Hay que hacer algo para cambiarle ese formato? Dejo una foto de como se me ve:
![image](https://user-images.githubusercontent.com/62037243/96163973-f2993980-0ef0-11eb-8458-1203cc1b7bf3.png)

**Comment by TamaraCucumides** [comment]
Hola! lo que pasa es que lo subiste como archivo. Para abrir el notebook tienes dos opciones:

1. subirlo a google drive y en abrir con poner abrir con colab
2. subirlo apretando lo que te adjunto
![imagen](https://user-images.githubusercontent.com/26121579/96168413-1495ba80-0ef7-11eb-8a22-af76ecb63cdd.png)
