### ISSUE TITLE
Out of Index

### ISSUE THREAD

**Issue by CataSudo** [IIC2413/Syllabus-2020-2#275]
<img width="564" alt="Screen Shot 2020-10-15 at 16 55 59" src="https://user-images.githubusercontent.com/62016215/96179496-4f9fea00-0f07-11eb-9ac0-9b36992c52bd.png">

He intentado editar mi codigo varias veces, pero aun no logro entender bien  porque occure este error.

**Comment by TamaraCucumides** [comment]
Hola, el error lo que dice es que estas intentando buscar una posición que no existe en la lista.

En particular para la lista lines la posicion que le estas pidiendo no existe.

Es como si tuvieramos una lista con tamaño 2 
`lista = [1,2]`
y pidieramos 
`lista[3]`
eso te tirara el mismo error: list index out of range

**Comment by CataSudo** [comment]
Hola, si entiendo eso, pero no se porque se sale del tamaño, he buscado desde ayer el mismo error con otro ayudante.

**Comment by TamaraCucumides** [comment]
Puedes revisar tus archivos de la relacion y ver que todo este en orden?

**Comment by CataSudo** [comment]
Si, los he estado actualizando cada vez, es raro se cae en la pagina R-5. Como que no llega ahi.

**Comment by TamaraCucumides** [comment]
Me puedes mostrar como se ven tus archivos?

**Comment by CataSudo** [comment]
[Archive.zip](https://github.com/IIC2413/Syllabus-2020-2/files/5387540/Archive.zip)
Ahi van!

**Comment by TamaraCucumides** [comment]
No veo nada extraño. 

Que pasa si haces un all_tuples(R) ?

**Comment by CataSudo** [comment]
Parece que se soluciono, creo que se subieron mal los archivos orginiales.

**Comment by TamaraCucumides** [comment]
Si, debio haber sido algo con los archivos ya que ese lines es un arreglo con las líneas de los archivos entonces si alguna linea faltaba o si la linea del next quedaba mas corta, se iba a caer. 

Que bueno que se soluciono :D !
