### ISSUE TITLE
Como recorrer todas las paginas en insert_tuples()

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#276]
Hola, estoy medio confundido con el metodo. 
Como me dan la instancia de 
buff = Buffer()
R = Relation('R',['a','b'],['int','int'],buff)
me base en esto para hacer el codigo. Eso significa que estuve usando R.metodo en todos los casos, por lo tanto, si me ponen una hoja S no funcionaria el insert_tuples. Como soluciono esto ? Hay algún metodo que me retorna que paginas existen actualmente para asi, si quiero poder escoger cual recorrer.

**Comment by TamaraCucumides** [comment]
No entiendo mucho tu pregunta, pero puedes hacer: 

`S = Relation('S',['a','b'],['int','int'],buff)`
y luego haces

`S.insert_tuple(...)`

Te refieres a que tienes hardcodeado R dentro de tu metodo?

Si haces 

`S = Relation('S',['a','b'],['int','int'],buff)
S.root_page`

eso te entregara la pagina raiz de tu relacion y de ahi se itera normal.

**Comment by dsepulveda3** [comment]
Es que por ejemplo si dentro de insert_tuples() uso para todo R.open() R.next(), etc que pasa cuando me den una instancia que sea S ? o sea que tenga que trabajar con S.open(), S.next(), etc .. en ese ultimo caso no correra.
Entonces lo que quiero saber es si hay una función que me diga que paginas existen para poder trabajar con ellas. 
Ejemplo: 
Que exista paginas_existentes() y que retorne [R, S] y asi scuando uso el metodo open() o next() puedo usarlo como paginas_existentes()[0].open() o paginas_existenes()[1].open()

**Comment by TamaraCucumides** [comment]
> Es que por ejemplo si dentro de insert_tuples() uso para todo R.open() R.next(), etc que pasa cuando me den una instancia que sea S ? o sea que tenga que trabajar con S.open(), S.next(), etc .. en ese ultimo caso no correra mi funcion insert_tuples.
> Entonces lo que quiero saber es si hay una función que me diga que paginas existen para poder trabajar con ellas.
> Ejemplo:
> Que exista paginas_existentes() y que retorne [R, S] y asi scuando uso el metodo open() o next() puedo usarlo como paginas_existentes()[0].open() o paginas_existenes()[1].open()

La solucion que planteas no es viable. Recuerda que el metodo insert_tuple es un metodo de la clase Relation, entonces no debes hacer R.open() sino que self.open() ya que estas en un metodo de la clase.

**Comment by dsepulveda3** [comment]
oooh que soy pastel dale. Es que esta medio confuso el codigo jajaj, pero toda la razon, ahora me hace sentidoo. Gracias
