### ISSUE TITLE
Duda general

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#277]
Porque desde insert_tuples debo recorrer R-1, R-2, R-3 y asi metiendo estos al buffer y en las funciones filtered_tuples() y nested_loop_join() no ? En los últimos dos simplemente se usan los open(), has_next() y close()

Sumado a esta pregunta. Esta bien si uso open.() y has_next() para buscar si la tupla esta o no en R (por ejemplo), y si uso el buffer para buscar posiciones vacias (<EMPTY>) en las paginas y asi insertar una tupla si no existe en R ?

**Comment by dsepulveda3** [comment]
Sumado a esta pregunta. Esta bien si uso open.() y has_next() para buscar si la tupla esta o no en R (por ejemplo), y si uso el buffer para buscar posiciones vacias (<EMPTY>) en las paginas y asi insertar una tupla si no existe en R ?

**Comment by TamaraCucumides** [comment]
Hola!

El insert_tuple es funcion de la relacion mientras que el filtered y el join son de la base de datos. Para las ultimas dos el uso de manejo es interno y se esconde en las funciones open, close y next de la relacion. Para la insercion debes usar el buffer ya que debes trabajar con las paginas. 

Puedes usar open close y has_next para tu metodo de insercion.
