### ISSUE TITLE
Problemas crear T-2 en el Demo

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2413/Syllabus-2020-2#278]
Hola! Por alguna razon, al crear la relacion T en el demo no se me está creando la segunda pagina con las tuplas (lo que se me hace raro, porque en el testcase con la relacion R se me crean las paginas nuevas sin ningún problema). Alguna idea de porque puede pasar esto? no se como corregirlo porque ya me funciona con otras relaciones, entonces no entiendo que puede estar pasando :(

**Comment by TamaraCucumides** [comment]
Hola!

La pagina T-1 se te crea bien? puedes insertarle tuplas a la pagina T-1 correctamente?

Lo primero que puedes hacer es el update de buffer.py que subimos hace un rato. No se precisamente a que se debe tu problema pero partiria por ahi. Luego haria lo siguiente:

* Crear T y revisar que la pagina T-1 se crea correctamente
* Insertar 5 tuplas en T y ver que el archivo T-1 sea lo esperado

 Si ambos pasos anteriores son correctos, entonces hay que entrar a revisar como se esta creando T-2. Que problema tienes? Te tira algún error o simplemente no se crea la pagina?

**Comment by maggiemunoz** [comment]
Si! las primeras 5 tuplas se me agregan perfectamente a T-1, tengo el buffer.py actualizado tambien. El error es que una vez que agrega las tuplas de T-1, en vez de crear T-2 y seguir agregando, intenta agregar tuplas en las posiciones 5, 6, 7 y asi, lo que claramente no se puede, entonces llega como hasta el infinito en vez de agregar otra pagina.

(Lo que es raro porque como dije, R-6 se me crea perfecto en el testcase)

**Comment by TamaraCucumides** [comment]
> intenta agregar tuplas en las posiciones 5, 6, 7

efectivamente agrega estas tuplas? 

Como estas creando la relacion T?

**Comment by maggiemunoz** [comment]
Osea, no las agrega porque T-1 solamente tiene las posiciones 0-4. Y... no se como explicarlo, te muestro mi codigo? Porque lo que hace mi codigo es que revisa todas las paginas, y si no encuentra un espacio vacío, crea otra

**Comment by TamaraCucumides** [comment]
Primero corroboremos que estas creando bien la relación T

**Comment by maggiemunoz** [comment]
ya.. como lo corroboramos jajajaj

**Comment by TamaraCucumides** [comment]
muestrame el codigo de como la estas creando, deberia ser algo como

create_table("T", ...)
T = Relations["T"]

**Comment by maggiemunoz** [comment]
ahh eso puede ser, pero el codigo que crea las relaciones ya lo tenemos escrito o no? yo en el notebook tengo esto

create_table('T',['a','c'],['int','int'])
T = Relations['T']

T.insert_tuple("1 15")
(...)

**Comment by TamaraCucumides** [comment]
yap, parece que no es eso entonces. Te tinca si nos conectamos a discord cortito ahora a ver si lo solucionamos rapido?

**Comment by maggiemunoz** [comment]
yaa! feliz, mi discord es Meggs#9758 :)

**Comment by TamaraCucumides** [comment]
resuelto!
