### ISSUE TITLE
Duda modificación métodos Control 2

### ISSUE THREAD

**Issue by JavaBravo** [IIC2413/Syllabus-2020-2#280]
Hola, quería saber si es posible modificar los métodos de las clases definidas

**Comment by TamaraCucumides** [comment]
Hola, que tipo de cambios quieres hacer?

**Comment by JavaBravo** [comment]
Quería cambiar el funcionamiento de `get_next_pos()` para cuando `age.get_element_from_page(pos) == '<EMPTY>'`

**Comment by TamaraCucumides** [comment]
Dale, si bien no es necesario, si te simplifica la vida puedes hacerlo.

Lo que si ten cuidado de que no te cree algún bug extraño porque en ese caso no te vamos a poder ayudar :(

**Comment by JavaBravo** [comment]
Dale gracias!
