### ISSUE TITLE
Problema con permisos en jupyter notebook

### ISSUE THREAD

**Issue by matiasone** [IIC2413/Syllabus-2020-2#281]
Estimados, estaba trabajando en mi control cuando cerré el cmd. Al volver a abrir jyputer e intentar entrar a Actividad_2.ipynb sucede lo siguiente.
![problema jupyter](https://user-images.githubusercontent.com/62085564/96222030-ec8f7100-0f61-11eb-858e-0776bc13918d.PNG)
Llevo bastante rato y no he podido solucionar para seguir trabajando, espero me puedan ayudar 🗡️

**Comment by TamaraCucumides** [comment]
Hola, hice una budqueda rápida de googlr y hay varias cosas que puedes intentar. Te dejo un link;

https://github.com/jupyter/notebook/issues/4907
