### ISSUE TITLE
Revisión Control

### ISSUE THREAD

**Issue by IvaniaArias** [IIC2413/Syllabus-2020-2#282]
Holaa! Quería consultar cómo será el método de revisión, me refiero a solo si corre el programa o hay puntaje parcial por el código?
Además, los bonus son un todo o nada?
Gracias de antemano!

**Comment by TamaraCucumides** [comment]
Hola! si todo corre bien tienen puntaje completo. 

Si alguno de sus métodos tiene problemas miraremos el código. Si logramos encontrar el bug y es pequeño, habrá puntaje parcial o total. Si el código no se entiende o no hace lo que debería, no habrá puntaje. 

Para los bonus también hay puntaje parcial bajo las mismas políticas que menciono arriba.
