### ISSUE TITLE
Problema con la relación T

### ISSUE THREAD

**Issue by tomasur** [IIC2413/Syllabus-2020-2#283]
Hola, mi código lo tengo corriendo y todas los test case funcionan bien para la relación R, si la tupla no está se agregan al primer EMPTY que encuentren y si es necesario crea una página nueva, con varias inserciones al mismo tiempo. Sin embargo, cuando prueba ahora para la relación T, cuando le pido que me ingrese tuplas, solo hace esto de a 1 tupla. ¿Qué puede estar pasando? Me llama mucho la atención ya que para las otras relaciones esto no me pasa

**Comment by TamaraCucumides** [comment]
Hola!

Revisa algunas issues anteriores, a varios les ha pasado lo mismo. Segun recuerdo los errores mas comunes eran:
1. algo con el buffer que se soluciona con la actualizacion que hicimos hace poco en buffer.py
2. no estas creando bien la relacion T
3. quizas entre inserciones necesitas un restart o, al menos, hacer la primera en un bloque y luego hacer las siguientes. 
4. revisa que al crear una pagina 1 (para una relacion nueva), esta se crea sin problemas y se escribe en disco

Hay como 3 issues alusivas a temas similares, revísalas y si no te sirven las soluciones, podemos seguir viendo que pasa :)

**Comment by TamaraCucumides** [comment]
En ultimo caso, si ninguna solución funciona. Escribe en el readme que las inserciones hay que hacerlas de a una, quizás reiniciando el kernel. No te compliques tanto con eso :)

**Comment by tomasur** [comment]
gracias! voy a revisar todo esto
