### ISSUE TITLE
Actualización de archivos utilizando método insert_tuple( )

### ISSUE THREAD

**Issue by JaviGuzman** [IIC2413/Syllabus-2020-2#284]
Hola! He estado teniendo problemas para que se actualice el archivo en donde agrego una tupla. Cuando utilizo el método insert_tuple, me entrega bien el resultado que espero, añadiendo la tupla en la página correspondiente donde hay un espacio en blanco, pero estos cambios no se relfejan en los archivos en sí.
He revisado otras issues y nada me ha servido.
A grandes rasgos mi función primero ve si existe la tupla que quiero ingresar, si no existe, guardo la posición donde está vacío. Luego reviso si debo agregar una nueva página o no, inserto la tupla y finalmente hago evict_page. Es más o menos lo que he rescatado de otras issues, pero de esta forma, no se actualizan los archivos :(
Qué podría estar haciendo mal? Gracias!

**Comment by TamaraCucumides** [comment]
Hola!
como sabes que el insert tuple esta funcionando bien si no se añade la tupla al archivo?

* Revisa que estes usando bien el page.insert_into_pos
* Revisa que estes haciendo evict_page a la pagina en la que hiciste los cambios. Quizas le estas haciendo evict a otra pagina :s

**Comment by JaviGuzman** [comment]
Es que hago prints de los resultados para ir viendo el proceso, y agrega la tupla en donde debería ir, y si ya existe no la agrega.
Luego de utilizar page.insert_into_pos pongo print(page.data) y aparece la tupla agregada, pero no se ven los cambios en los archivos.
Cambie evict por flush buffer y aun asi no veo cambios en los archivos.

Volvi a dejarlo con evict y printié el evict y me sale 
"Page not in the buffer
None"
Qué es lo que hice mal?

**Comment by TamaraCucumides** [comment]
Lo que te esta diciendo es que le estas haciendo evict a una pagina que no esta en el buffer.

Como lo estas haciendo para obtener la pagina en la que vas a hacer la insercion?

**DEBES** (si o si) hacerlo con el buffer.get_page(). Si lo estas haciendo con page.read_from_disk() esta mal

Te digo esto porque si la pagina no esta en el buffer, entonces hay dos opciones:
1. estas haciendole evict a otra pagina
2. la pagina en la que estas haciendo los cambios no esta en el buffer, entonces la estas obteniendo mal

**Comment by JaviGuzman** [comment]
Primero hago open() para posicionarme en la primera posicion y recorrer los archivos para ver si esta la tupla, si no está entonces hago self.buffer.fetch_page(self.current_page) y self.buffer.get_page(self.current_page)

**Comment by TamaraCucumides** [comment]
Perfecto, asumo que haces algo asi como:

pag =  self.buffer.get_page(self.current_page)  ## obtienes la pagina desde el buffer
y luego 
pag.insert_into_pos() ?

**Comment by JaviGuzman** [comment]
Entonces elimino el fetch y get? Y lo que hago despues de eso es page = Page(self.current_page).
Al escribir lo que me dices aparece esto:

![Captura de Pantalla 2020-10-16 a la(s) 11 52 40](https://user-images.githubusercontent.com/48359777/96273781-19fe0e00-0fa6-11eb-9bbb-7fbe8dca900e.png)

**Comment by TamaraCucumides** [comment]
Tu error es hacer el 
page =Page(current page)

debe ser page = self.buffer.get_page(current_page)

**Comment by JaviGuzman** [comment]
Buenisimaa, ahí si me funciona! :D pero una duda, al hacer el print del evict despues, me sigue saliendo que la pag no esta en el buffer, por que sucede esto? Está bien?

**Comment by TamaraCucumides** [comment]
Hm que raro, estas haciendo el flush antes del evict? si es asi borra el evict y deja solo el flush (o al reves)

**Comment by JaviGuzman** [comment]
No, solo deje el evict

**Comment by TamaraCucumides** [comment]
ahh ya, en el primer evict estas sacando la pagina entonces en el segundo, cuando le haces print  la pagina ya no esta jiji

**Comment by JaviGuzman** [comment]
Bacaaan! Graciaaas! Ahora descubrí que tengo un error al crear la nueva página, pero trataré de resolverlo yo sola. Muchisimas gracias por tu ayuda!!
