### ISSUE TITLE
Obtener archivos originales

### ISSUE THREAD

**Issue by Pedrowach** [IIC2413/Syllabus-2020-2#286]
Holaa! como puedo traer denuevo los archivos originales? que haciendo git pull no me cambia nada ( modifique los de la carpeta). gracias!

**Comment by TamaraCucumides** [comment]
Hola!
y si los borras y haces git pull?

Igual si no funciona, puedes ver los archivos en el mismo preview de github y hacer los cambios respectivos

![image](https://user-images.githubusercontent.com/26121579/96283174-2d16db00-0fb2-11eb-884a-6bc98adfdf28.png)

O aun mas parche, puedes descardar el repo como zip y extraer los archivos que desees :)

**Comment by Pedrowach** [comment]
lo de borrar y git pull , no funciona :( pero lo descargue como zip nomas gracias!
