### ISSUE TITLE
Problema con pages_dict

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2413/Syllabus-2020-2#287]
Hola! Estoy teniendo problemas con pages_dict en insert_tuple, no se si tengo un error o no entiendo como funciona pages_dict, porque al hacer print(self.buffer.pages_dict) solo me aparece R-1, cuando también deberían aparecer del 2 al 5. Qué puede ser?

**Comment by TamaraCucumides** [comment]
Hola!

El pages_dict te muestra las paginas que se encuentran actualmente en el buffer. Por que dices que deberian aparecer todas?

Al abrir una relacion las paginas se traen de a una al buffer. Por otra parte el buffer solo puede teenr 4 paginas al mismo tiempo, asi que de ningun modo te van a aparecer desde la 1 a la 5. 

Para traer una pagina a buffer debes hacer buffer.get_page(pname) donde pname es el nombre de la pagina que deseas cargar en el buffer

**Comment by beatrizacuna** [comment]
Gracias!!
