### ISSUE TITLE
Guardado Google Colab

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#288]
Hola! Como guardo los cambios hechos en google colab ? 
Trate apretando guardar y apretando descargar.ipynb y cuando vuelvo a abrirlo no hay nada de lo que habia escrito (ejemplos codigo) :/

**Comment by TamaraCucumides** [comment]
Hola! debería funcionar al guardarlo o descargar el .ipynb. 

Que te dice en el entorno de ejecución? Esta conectado?

**Comment by TamaraCucumides** [comment]
Cuando le pones guardar te llega el mensaje que se guardo correctamente?
