### ISSUE TITLE
Test case relations.py

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2413/Syllabus-2020-2#290]
Hola! Tengo una duda con el test case 2 de relations.py, no entiendo por qué " R.insert_tuple('27 1329') # Create a new next_page" debería crear una nueva página si R-5 aún tiene espacios vacíos. Muchas gracias de antemano!! 😄

**Comment by TamaraCucumides** [comment]
Hola!

si hay un espacio vacio en alguna pagina, no es necesario crear una nueva. No te preocupes por los comentarios del test case
