### ISSUE TITLE
Error con la demo insert_tuple( )

### ISSUE THREAD

**Issue by JaviGuzman** [IIC2413/Syllabus-2020-2#291]
Hola!! Estoy teniendo problemas con la demo. El archivo me funciona bien por si solo con los test, pero en la demo no se qué estoy haciendo mal.
Escribi:
create_table('T',['a','c'],['int','int'])
T = Relation('T' ,['a','c'], ['int','int'], buffer)
print(buffer.frames)
T.insert_tuple('14 24')

Pero esto no me modifica el archivo T-1 :(

**Comment by TamaraCucumides** [comment]
Hola, estas inicializando mal la tabla. En particular
`T = Relation('T' ,['a','c'], ['int','int'], buffer)`
esta linea esta mal

debes hacer

`T = create_table('T',['a','c'],['int','int'])`

**Comment by JaviGuzman** [comment]
Leyendo las issues que pusiste me queda la duda si hay que hacer:
```
T = create_table('T',['a','c'],['int','int'])
T = Relation('T' ,['a','c'], ['int','int'], buffer)
```
o
```
create_table('T',['a','c'], ['int','int'])
T = Relations["T"]
```
De todas formas, con ninguno de las dos formas se modifica el archivo ni aparecen las tuplas con el metodo all_tuples()

**Comment by TamaraCucumides** [comment]
Perdon, ahi lo rectifique. 

Si no se estan modificando los archivos entonces el problema es de tu metodo insert_tuple

**Comment by TamaraCucumides** [comment]
ijiji bacan!!

**Comment by TamaraCucumides** [comment]
Ambos metodos deben hacer el print de las tuplas, no es necesario retornarlas ni contarlas, solo haerles print tal como el metodo cross y el metodo all_tuples

**Comment by beatrizacuna** [comment]
Hola! me surgió una duda, es que mi código está hecho para insertar tuplas en el primer lugar vacío de las relaciones que esten actualmente en el buffer, no sé por qué pero al principio siempre esta R-1, entonces en el demo cuando intento insertar en la relación T, algunas se insertan en R-5 y otras se insertan en T-1. Se me ocurrió sacar en un principio a R-1 del buffer y poner a T-1 (en el código del demo), eso estaría bien?

**Comment by JaviGuzman** [comment]
> Ambos metodos deben hacer el print de las tuplas, no es necesario retornarlas ni contarlas, solo haerles print tal como el metodo cross y el metodo all_tuples

Entonces para filtered_tuples(R,cond) se debería printear una lista de tuplas iguales que cumplan la condición?

**Comment by TamaraCucumides** [comment]
Lo que puedes hacer es al comenzar el insert, hacer un flush del buffer, asi te aseguras que no quedan paginas remanentes de otras relaciones. 

De todos modos, lo que deberia hacer tu codigo es partir en la root_page de la relacion y de ahi ir yendo a la proxima pagina, solo iterando por las paginas de la relacion (no por las paginas del buffer, ya que en el buffer puede haber cualquier cosa).

Creo que lo que te planteo te va a solucionar el problema, pero hay un error ahi ya que estas mezclando las paginas de una relacion con las paginas del buffer

**Comment by TamaraCucumides** [comment]
> > Ambos metodos deben hacer el print de las tuplas, no es necesario retornarlas ni contarlas, solo haerles print tal como el metodo cross y el metodo all_tuples
> 
> Entonces para filtered_tuples(R,cond) se debería printear una lista de tuplas iguales que cumplan la condición?

Claro, igual que el all_tuples(). Igual no es necesario que imprimas una lista, puedes ir imprimiendo una a una las tuplas mientras las vas encontrando
