### ISSUE TITLE
Duda consulta por navieras y buques

### ISSUE THREAD

**Issue by Skablop** [IIC2413/Syllabus-2020-2#293]
Hola,

En el proyecto, la parte 3.2 dice que en el sitio web  "Los usuarios deben poder ver un listado con todas las
navieras. Al hacer click en una naviera, deben ver todos los buques (su patente y su nombre), ordenados por tipo."

No se si mis funciones están malas, pero me resulta que siempre para una naviera los buques son todos del mismo tipo. 

Algo así como:
Naviera 1 --- todos pesqueros
Naviera 2 --- todos petroleros
...

¿Efectivamente los datos estan repartidos así o es un error mío?

Saludos.

**Comment by arpincheira** [comment]
Hola, creo que efectivamente ocurre eso jajaja es una coincidencia del dataset aparentemente

**Comment by Skablop** [comment]
¿En ese caso es necesario implementar la segregación por tipo de buque?

**Comment by arpincheira** [comment]
El enunciado solicita que se encuentren ordenados por ende **es necesario** implementar una consulta que resuelva este problema o en su defecto **una separación**, aunque en su interior no posea ningún dato pues la consulta retornaría vacío.
