### ISSUE TITLE
Tabla de usuarios 

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2413/Syllabus-2020-2#295]
Hola!Tengo una duda acerca de la tabla de usuarios , en ella se debe agregar los nombres de los capitanes de buques y los jefes de instalación junto a un determinado id , también es necesario o recomendable agregar los otros datos correspondientes al usuario , en la tabla , me refiero a edad , sexo , rut ,etc.Además de esto al crear esta tabla se le debe asignar una contraseña a los capitanes de buques y jefes de instalaciones también? de ser así su contraseña podría ser su RUT o debe ser una en especifica?

**Comment by arpincheira** [comment]
efectivamente le deben añadir una contraseña a los jefes de instalaciones y a los capitanes de buque, idealmente la idea es que la contraseña que elijan la indiquen en su reporte. Como preferencia personal pondría la misma contraseña por defecto para estos usuarios, un ejemplo de contraseña podría ser _qwerty123_

**Comment by RonaldoSosa** [comment]
Entendido!Y otra cosa el archivo csv del cual voy a copiar la tabla puede estar en la carpeta de Entrega 3?

**Comment by arpincheira** [comment]
Em... si, creo que no hay problema en eso, igual si quieren experimentar, les dejo [este link](https://docs.google.com/document/d/1BK5jutfd8bJsQE6lgmwaSgYe11ix3YgVOdjaZJOgDfM/edit?usp=sharing) en donde dan ejemplos de como poblar tablas a partir de un procedimiento almacenado

**Comment by RonaldoSosa** [comment]
Yaaa!!!!! Graciasss!!!!!!

**Comment by arpincheira** [comment]
Hola, perdón por la demora... bueno... dado que no se especifica en el enunciado hipotéticamente si se podría hacer con copy, de todas formas recomendaría lo otro porque es mejor a mi gusto(pues sería un procedimiento de cierta forma estándar que serviría para futuras ejecuciones sin tener que necesariamente conocer los comandos de la base de datos)

**Comment by Skablop** [comment]
Hola, 

Antes mencionaste que se podría dejar como contraseña algo como qwerty123 para los capitanes y jefes, pero en el enunciado dice que la contraseña creada debe ser aleatoria. ¿Con cuál me quedo?

Saludos.

**Comment by arpincheira** [comment]
qwerty123 sigue siendo una contraseña aleatoria, yo lo digo como ejemplo, dado que cuando probemos su aplicación vamos a tener que ingresar como usuario capitán y como usuario jefe (principalmente para poder probar las cosas), por eso dije que podían utilizar una contraseña estándar para los usuarios ya existentes. De todas formas, dado que el enunciado dice que deben ser aleatorias, no va a existir ningún tipo de descuento con respecto a esto. En otras palabras, ambas son correctas y queda a su criterio cuál de las dos cosas deben seguir

**Comment by Skablop** [comment]
Ahh ok, yo lo interpreté como que el sistema le entregaba contraseñas aleatorias diferentes a los usuarios que se migraban.

Muchas gracias!
