### ISSUE TITLE
Homepage proyecto

### ISSUE THREAD

**Issue by vblopez** [IIC2413/Syllabus-2020-2#296]
Hola! 
En Detalles academicos > Ubicacion de la entrega, se dice la nueva version de la entrega debe estar ubicada en el directorio /home/grupoXX/Sites y por tanto el home page debe ser /home/grupoXX/Sites/index.php.

Para esto eliminamos nuestra entrega anterior de Sites? Pregunto para no comenzar a editar esos archivos, y que la entrega 2 que actualmente se ve en codd.ing.puc.cl/~grupoxx/index.php no pueda ser corregida.

Gracias

**Comment by arpincheira** [comment]
Hola, no hay ningún problema con eso, nosotros tenemos una copia de su entrega anterior guardada en el servidor, por lo que las modificaciones realizadas no repercutirán en la corrección de esa entrega

**Comment by Baelfire18** [comment]
@arpincheira una pregunta del homepage del proyecto, este debe de estar en index.php, pero al momento de volver con un boton por ejemplo se debera volver a `http://codd.ing.puc.cl/~grupoXX/` o a `http://codd.ing.puc.cl/~grupoXX/index.php`, para fines practicos es lo mismo, pero como buena parctica que mejor mencionar el index o emitirlo en el homepage?

**Comment by arpincheira** [comment]
Bueno... en primer lugar la idea es que se usen rutas relativas, por lo que debes recordar que no necesariamente debe redirigirlo a esa página web, sino que a algo genérico que posea el mismo orden de los archivos, ahora... con respecto si a redirigirlo a index o a “root” o al index... creo que muchas páginas web redirigen al usuario directamente a la homepage envés de a un index pues dejan predeterminado un archivo de rutas que define cuál página utilizar como homepage(normalmente usan index pero podría darse el caso en que quieran cambiar el nombre de los archivos)
