### ISSUE TITLE
Conexión entre páginas

### ISSUE THREAD

**Issue by Baelfire18** [IIC2413/Syllabus-2020-2#297]
Feliz domingo! Les tengo una pregunta para hacer la página se deberá hacer en la de menor número, pero las consultas en si se deben llegar cambiando la vista de un grupo a otro? O por el contrario todas las vistas debe´ran estar solo en el grupo menor y del mayor solo de debee acceder a la dbe2?

**Comment by arpincheira** [comment]
Hola, se espera que todas las views de esta nueva entrega deberían estar en el sites del grupo de menor número y que la interacción que hagan con el otro grupo sea principalmente con el acceso a su base de datos y la interacción con esta.

Espero haber contestado tu duda.

**Comment by Baelfire18** [comment]
Si gracias!
