### ISSUE TITLE
Duda capitanes y jefes de instalaciones

### ISSUE THREAD

**Issue by zaertis0** [IIC2413/Syllabus-2020-2#298]
Hola, para poder saber si un usuario es capitán o jefe de instalación podemos hacer la suposición de que siempre los jefes serán los que tienen rut y los que tienen pasaporte serán los capitanes ya que ninguno de estos últimos tiene rut.

**Comment by arpincheira** [comment]
Hola, recuerda que el rut en chile es el equivalente al número de pasaporte, por lo que la suposición que se puede(y deben hacer) es que **los jefes de instalación son de nacionalidad chilena y que su número de pasaporte es su rut**. Lo que no pueden hacer es crear una columna usuarios que posea el dato rut y que su valor sea nulo, pues esto no sería correcto.
