### ISSUE TITLE
Alerta al registar usuario

### ISSUE THREAD

**Issue by Baelfire18** [IIC2413/Syllabus-2020-2#299]
Hola, al crer un nuevo usuario, chrome me tira esta advertencia, hay alguna forma de evitarlo (corregirlo)?
![image](https://user-images.githubusercontent.com/50716449/96455155-32169d00-11f3-11eb-9284-3e84777dcfd1.png)

**Comment by arpincheira** [comment]
Hola, eso es meramente una advertencia propia de tu navegador, yo te recomendaría que cambies la configuración de los permisos de seguridad o que intentes utilizando la aplicación en un navegador con el modo oculto activado(por si no quieres cambiar las opciones del navegador que usas).
