### ISSUE TITLE
No puedo reproducir los videos de clase 0

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#3]
Hola cuando trato de reproducir los videos me aparece esto:
![image](https://user-images.githubusercontent.com/62180259/90586125-701c2400-e1a4-11ea-95e6-ba39f187255f.png)
Hay algún otro link para verlos ??

**Comment by arpincheira** [comment]
Hola, lamento mucho la demora, creo que ahora se pueden ver bien los videos a partir del [link](https://drive.google.com/file/d/16iRzLBkNtZJQ2ktnhOqVPFt-a1xFd5b_/view?usp=sharing) que se encuentra al interior de la sección de [*videos de materia* ](https://github.com/IIC2413/Syllabus-2020-2/tree/master/Videos%20de%20materia) dentro del repositorio del curso.
