### ISSUE TITLE
Conectar PHP con procedimientos almacenados

### ISSUE THREAD

**Issue by anvaldes** [IIC2413/Syllabus-2020-2#300]
Hola! tengo la siguiente duda:

Cree un procedimiento almacenado que efectivamente me toma el sucesor de la id mas grande ya registrada. El archivo se llama: "insertar_usuario_nuevo.sql" y por otro lado la función asociada se llama:

"insertar_nuevo (atributo1, atributo2, ...., etc)"

El punto es que me funciona bien si ejecuto todo desde consola, es decir, si pongo:

\i insertar_usuario_nuevo.sql
SELECT insertar_nuevo(atributo1, atributo2,...);

Mi problema es como conecto esto con php? porque en php pense en ejecutar 2 querys que sean:

query1 = '\i insertar_usuario_nuevo.sql'
query2 = 'SELECT insertar_nuevo(atributo1, atributo2,...);'

Y la verdad es que no me convence mucho. De esta forma mis 2 preguntas son:

1. El archivo insertar_usuario_nuevo.sql debería estar en la misma carpeta del php asociado cierto?
2. Como llamo en php a mi procedimiento almacenado?

Desde ya, muchisimas gracias!!

**Comment by arpincheira** [comment]
Hola, la verdad no entendí mucho tu primera pregunta :/ pero con respecto a la segunda, te recomiendo que visites [este link](https://www.mysqltutorial.org/php-calling-mysql-stored-procedures/) que podría ayudarte
