### ISSUE TITLE
[Corrección proyecto E2]

### ISSUE THREAD

**Issue by fivaldivia** [IIC2413/Syllabus-2020-2#301]
Hola, quería saber qué es el puntaje de FKs. Se que se refiere a las llaves foráneas, pero se referían a ponerlas en el esquema relacional? Estas que van en la entidad de las relaciones (rombos)? Gracias!

**Comment by castrillini** [comment]
Como bien dices, el puntaje de las FKs se refiere a haberlas puesto en el esquema relacional. Había que señalarlas de alguna manera clara que se entienda. A manera de ejemplo:

Perros (id: int PK, nombre: varchar(50), edad: int, id_dueño: int FK, peso: float)
