### ISSUE TITLE
Creación de nueva tabla Entrega 3

### ISSUE THREAD

**Issue by CatalinaFloresP** [IIC2413/Syllabus-2020-2#302]
Hola, tenemos la duda de si al hacer login la información del usuario se debería guardar en la tabla personal o hay que crear una nueva tabla?
Gracias

**Comment by arpincheira** [comment]
Hola la idea es que creen una nueva tabla Usuarios para poder manejar la información de estos nuevos usuarios que están llegando a tu aplicación.

**Comment by dsepulveda3** [comment]
Hola, para crear la nueva tabla de usuarios en el servidor del grupo MENOR, esta información posera info tanto de jefes de instalaciones (info grupo IMPAR) y información de capitanes de buque (info grupo PAR). Mi pregunta es con repecto a la creacion de esta tabla de usuarios: puedo ocupar pyhton para limpiar los datos y juntar la info de los jefes de instalaciones con los capitanes de buques y luego hacer un \copy en la tabla creada en el servidor del grupo MENOR ??

**Comment by arpincheira** [comment]
Si, no hay ningún problema con hacer eso
