### ISSUE TITLE
Migración con Python

### ISSUE THREAD

**Issue by nachobascar** [IIC2413/Syllabus-2020-2#303]
Hola!! 

La migración de jefes y capitanes a Usuarios, ¿tiene que ser con php y/o procedimientos almacenados, o se puede usar python para esto?

**Comment by arpincheira** [comment]
El servidor si no me equivoco no posee Python en su interior, si tu pregunta va más dirigida a crear un csv con Python y poblar la tabla a partir de ello, eso está permitido

**Comment by nachobascar** [comment]
Me refería más a usar psycopg2 para hacer un python que se conecte a las bases de datos y se preocupe de la migración al ejecutarlo

**Comment by arpincheira** [comment]
Si, no hay ningún problema en eso
