### ISSUE TITLE
Acceder tabla de segunda base de datos

### ISSUE THREAD

**Issue by nachobascar** [IIC2413/Syllabus-2020-2#304]
Hola!!

Como puedo acceder desde Procedimientos almacenados a una tabla de una base de datos externa?
Porque para migrar los valores de los jefes de las instalaciones a Usuarios debo acceder a la base de datos de otro grupo.

Gracias!!

**Comment by ridiazcampos** [comment]
¡Holaaaa!🎉 ¡Genial! Esto sí se puede hacer! En #243 hay información súper útil! :D

En particular si quieren utilizar `dblink`, en este caso como ambas bases de datos están en el mismo servidor, si necesitan especificar un `host`, con `localhost` funcionará! ¡Cualquier cosa nos comentan!🍀 

¡Saludines y mucho éxitoooo!🌱
