### ISSUE TITLE
Consultas Entrega 3 SQL

### ISSUE THREAD

**Issue by Baelfire18** [IIC2413/Syllabus-2020-2#305]
Hola tenemos varias dudas con respecto a la base de datos y las consultas.
1) Ambas bases de datos deben seguir separadas en grupoXXe2 cierto? Y en caso de ser así, la nueva tabla Usuarios puede estar en cualquiera cierto?
2) También de seguir separadas que hacemos con las tablas comunes como Barcos, Personas, etc
3) Y al hacer consultas que mezclen ambas tablas, ¿como hacemos para llegar de una a la otra?
4) También un detalle para el grupo par tenemos 240 buques y para el impar 250 ¿Con cuales nos quedamos?

**Comment by arpincheira** [comment]
Hola, voy a responder tu duda una por una para mayor claridad:

1. Efectivamente, ambas bases de datos deben seguir separadas pues una de las ideas de esta entrega es que logren trabajar con ellas de este modo. En este caso la tabla de usuarios puede quedar en cualquiera de las dos

2. En si las tablas como tal no son comunes, pues un grupo posee trabajadores y el otro personal o tripulantes(pueden cambiar los nombres con alter table en todo caso). El caso de los buques y barcos lo voy a explicar un poco más adelante

3. Eso se lo tienen que ingeniar ustedes, a modo de pista, para poder acceder a la conexión con la otra base de datos podrían extender su función de conexión original y tener variables tipo db1 y db2.

4. Con esta consulta has dado en el clavo jajajaj, efectivamente los buques son más que los barcos porque puede haber un buque que no haya atracado, pero no puede existir un barco que no forme parte de una naviera(o por lo menos así lo es en términos del proyecto), por lo tanto deben quedarse con la tabla de 250 datos(la de los impares si no me equivoco)

**Comment by Baelfire18** [comment]
2 y 4 Entonces no deben juntarse las tablas? (No me quedo en claro) Se nos ocurrió hacerlo para así faciltar consultas con bdd mixtas. 
3. iba efectivamente por eso mismo de pedir datos de ambas en la misma consulta, supongo que habrá que jugar con eso o buscar en internet.

**Comment by arpincheira** [comment]
Está estrictamente prohibido que creen las tablas de un grupo en la db de otro grupo(a eso me refiero a que NO PUEDEN JUNTARSE LAS TABLAS), ahora, al momento de realizar consultas eventualmente si las vas a tener que conectar a través de consultas para poder acceder a la información que deseas de una de las dos bases de datos.

Espero que haya contestado tu pregunta

**Comment by Baelfire18** [comment]
Me refería a hacer un diagrama que junte ambos diagramas y así relacionarse entre sí. Para  por ejemplo llamar a puertos de un grupo sobre otro o algo en ese estilo y para relacionar todo entre sí . No me refiera a migrar una base de datos entera a la de otro grupo (esas mayúsculas son de gritos 😢)

**Comment by arpincheira** [comment]
Oh... acabo de editarlo para ser más _family friendly_. La idea es que ese esquema sea más que nada propio de ustedes, pues ustedes deben buscar la manera de conectar las bases de datos a su manera, aunque igual ponemos restricciones típicas como la de que no se pierda información(en el caso de barcos y buques no se pierde) y que no se mezclen las bases de datos nomás

**Comment by Baelfire18** [comment]
Ya muchas gracias Andres!
