### ISSUE TITLE
Consulta sobre arreglar base de datos grupoXXe2

### ISSUE THREAD

**Issue by burgosibarra** [IIC2413/Syllabus-2020-2#306]
Hola! es posible arreglar la base de datos grupoXXe2 asociada a mi grupo (ninguna relación con la base de datos del grupo compañero) en función de los comentarios de la entrega 2? De esta manera, podría tener un mejor rendimiento para la entrega 3.

**Comment by Skablop** [comment]
Hola,

Es obligación cambiar las tablas según el feedback de la E2? Es que con mi grupo ya habíamos avanzado harto y tendríamos que alterar varias consultas.

Saludos.

**Comment by mariajesusbraun** [comment]
Hola! No es obligación, pero es recomendable, ya que seguramente se les va a hacer más fácil el trabajo, y puede que errores que hayan tenido en la E2 les perjudiquen después en esta entrega y las siguientes.
