### ISSUE TITLE
Importar usuarios usando php

### ISSUE THREAD

**Issue by mmunoz12** [IIC2413/Syllabus-2020-2#307]
hola! estamos intentando importar los usuarios con php pero no sabemos cuál es el problema ya que ningún dato se agrega en nuestra tabla `usuarios`. Hasta ahora tenemos un foreach que va ejecutando el `$query` que contiene el comando en psql para ingresar los usuarios a la tabla. Me parece que el problema surge luego de esto, en donde tenemos:
`$action = $db -> prepare($query);
$action -> execute();}`
Usando esto, no se obtienen errores pero no se agregan datos a la tabla `usuarios`. 

También intentamos poniendo el `$query` dentro de execute(), pero esto nos tira el error (un error por cada usuario):
Warning: PDOStatement::execute() expects parameter 1 to be array, string given in /home/grupo56/Sites/import.php on line 24

Por esta razón, intentamos darle a `execute()` un `array()` con los valores que se entregan en `$query` pero esto tampoco logra migrar los usuarios a la tabla. Cuál podría ser nuestro error?. Espero haberme explicado bien, de antemano muchas gracias!.

**Comment by arpincheira** [comment]
Hola, podría ser que cuando pasen los datos no entreguen los strings con comillas simples

**Comment by mmunoz12** [comment]
Ya intentamos poniendo strings con comillas simples pero tira el mismo error de Warning: PDOStatement::execute() expects parameter 1 to be array... 
Espero no estar dando mucha información, pero no se cómo explicarlo de mejor forma. Nuestro `INSERT INTO` es de la siguiente forma:
$query = "INSERT INTO usuarios(id_usuario, pasaporte, nombre, edad, sexo, nacionalidad, contraseña) VALUES('$id', '$cap[1]', '$cap[2]', '$cap[3]', '$cap[4]', '$cap[5]', '$password');";
Donde $cap es entregado al momento de hacer el foreach con el resultado de fetchAll() de la tabla capitán, en donde se encuentran los usuarios que queremos importar. ¿Quizás sea un problema con esto?. Hemos revisado mucho e intentado de todo pero aun así no nos funciona :(.

**Comment by mmunoz12** [comment]
Ya lo solucionamos! gracias!

**Comment by arpincheira** [comment]
O.o, que era finalmente?
