### ISSUE TITLE
Conexion bases de datos

### ISSUE THREAD

**Issue by vchauriye** [IIC2413/Syllabus-2020-2#308]
Estoy un poco confundido sobre como podriamos conectar las bases de datos de ambos grupos para formar la tabla usarios. Alguna ayuda?

**Comment by arpincheira** [comment]
Hola, para poder formar la tabla usuarios existen muchísimas maneras distintas y no les exigimos ninguna específica, lo que podrían hacer es simplemente crear un csv con la información de capitanes y de los jefes, luego crean la tabla y hacen \COPY  a la tabla con su nuevo csv en la base de datos que hayan decidido hacerla(si, usar copy es legal)
