### ISSUE TITLE
Duda Navegación Entrega 3

### ISSUE THREAD

**Issue by josefeliuf** [IIC2413/Syllabus-2020-2#309]
Hola!
En la página de puertos, para el primer botón donde se deben ingresar dos fechas, no me queda muy claro si el porcentaje promedio de ocupación en ese intervalo se refiere a tener un promedio por día en el cual la instalación tiene capacidad,
por ejemplo:

# Instalación 1

| dias_con_capacidad | ocupación |
|--------------------|----------|
| 20-20-2020         | 60%      |
| .                  | .        |
| .                  | .        |
 
 o si se refiere a un promedio general

# Instalación 1
* Promedio de ocupación entre el 20-10-2020 y el 22-10-2020: 60%

| dias_con_capacidad |
|--------------------|
| 20-20-2020         |
| .                  |
| .                  |

**Comment by Vicerc** [comment]
Hola!
El porcentaje de ocupación se calcula como la cantidad de buques con permiso para usar esa instalación ese día, por lo que se refiere a la primera opción.

Saludos :smiley:

**Comment by josefeliuf** [comment]
Pero entonces no sería un "promedio", cito:

> ii) el porcentaje promedio de
ocupación en ese intervalo

Si solo pongo el % de ocupación de ese día en específico, sería exactamente ese el valor, no sería un promedio. @Vicerc 

Saludos!

**Comment by Vicerc** [comment]
Tienes toda la razón, mala mía. Te recomiendo combinar ambos ejemplos, es decir, mostrar el % de ocupación de ese día en específico junto al promedio en el intervalo.

**Comment by mariajesusbraun** [comment]
Hola @josefeliuf ! Tienes toda la razón. Lo correcto es calcular el porcentaje de ocupación para cada día del intervalo como se especifica en la nota al pie [3] del enunciado: cantidad de buques con permiso para usar esa instalación ese día, dividido por la capacidad de esa instalación, y luego hacer un promedio de todos esos porcentajes. Por lo tanto, sería como el segundo ejemplo que proponen.

**Comment by josefeliuf** [comment]
@Vicerc @mariajesusbraun Perfecto muchas gracias!
