### ISSUE TITLE
Contraseñas usuarios 

### ISSUE THREAD

**Issue by pablogw** [IIC2413/Syllabus-2020-2#310]
Hola, con mi grupo tenias la duda que si las contraseñas son al azar (lo dice el enunciado) o podemos crear una contraseña "estándar" por ejemplo con los últimos 4 dígitos del rut o algo así.

**Comment by arpincheira** [comment]
Hola, efectivamente pueden hacer eso, igual yo recomendaría dejarlo explícito en el documento que entreguen junto a la entrega para poder facilitar la corrección
