### ISSUE TITLE
Navegación botón 1

### ISSUE THREAD

**Issue by Ignaciomendezp** [IIC2413/Syllabus-2020-2#311]
En el primer botón de navegación se nos piden todos los días en que no este agotada la capacidad de la instalación.
Cómo debemos entregar esta información?
En una misma celda se debe juntar las fechas como un string?

**Comment by Vicerc** [comment]
Holaa!
Creo que la issue #309 te puede ayudar!

**Comment by Ignaciomendezp** [comment]
Si había visto esa issue, ahí mismo sale solo 1 día, yo quiero mostrar muchos días, esa es mi pregunta, gracias!

**Comment by mariajesusbraun** [comment]
Hola! En la issue que te menciona @Vicerc hay un ejemplo de cómo mostrar la información. Como debes mostrar cada día en que no esté agotada la capacidad de la instalación y el porcentaje promedio de ocupación para ese día, debes poner cada fecha en una celda diferente.

**Comment by mariajesusbraun** [comment]
Hola @Ignaciomendezp ! El formato de entrega de la información queda a su criterio. Aún así, en la issue #309 se da un ejemplo, siendo el SEGUNDO EJEMPLO el CORRECTO, no el primero. OJO: lo correcto es calcular el porcentaje de ocupación para cada día del intervalo como se especifica en la nota al pie [3] del enunciado: cantidad de buques con permiso para usar esa instalación ese día, dividido por la capacidad de esa instalación, y luego hacer un promedio de todos esos porcentajes. Se debe entregar este porcentaje promedio, además de especificar todas las fechas en que no esté agotada la capacidad de la instalación.

**Comment by Ignaciomendezp** [comment]
Gracias!
