### ISSUE TITLE
Creación tabla usuarios

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#312]
Hola, para crear la nueva tabla de usuarios en el servidor del grupo MENOR, esta información poseera info tanto de jefes de instalaciones (info grupo IMPAR) y información de capitanes de buque (info grupo PAR). Mi pregunta es con respecto a la creación de esta tabla de usuarios: puedo ocupar pyhton para limpiar los datos y juntar la info de los jefes de instalaciones con los capitanes de buques y luego hacer un \copy en la tabla creada en el servidor del grupo MENOR ??

**Comment by arpincheira** [comment]
Hola, dado que el enunciado no indica una forma explícita de hacerlo, efectivamente podrían hacer eso que mencionas.
