### ISSUE TITLE
Base de Datos para Entrega 3 no existe

### ISSUE THREAD

**Issue by ceosorio** [IIC2413/Syllabus-2020-2#313]
Hola! 
Soy del grupo 17.  Pasa que cuando intentamos hacer conexión a la base de datos de la entrega 3, nos sale que no tenemos una. Revisé también con pgAdmin y tampoco nos sale la base de datos en la lista, solo la de las entregas anteriores 😢 

Que podemos hacer?

**Comment by arpincheira** [comment]
O.o efectivamente. no existe, lo cual es bastante extraño, al tiro la creo y añado los permisos

**Comment by ceosorio** [comment]
Gracias! 😄
