### ISSUE TITLE
Conexion entre bases de datos

### ISSUE THREAD

**Issue by tomasft0410** [IIC2413/Syllabus-2020-2#314]
Hola estoy tratando de conectar las bases de datos con el grupo impar, segun los enlaces que indicaba la issue #243, pero no hemos tenido ningún resultado. Con el primer enlace nos dice que debemos ser superusuario, y con el segundo enlace nos aparece acceso denegado.
Gracias de antemano!

**Comment by castrillini** [comment]
Estamos pendientes de esa issue, revísala de vez en cuando ;). Acabo de agregar un comentario. De todas maneras lo pondré aquí:

Prueben con:
SELECT * FROM dblink('host=localhost user=grupoXX dbname=grupoXX password=XXX port=5432', 'SELECT nombre FROM Perros')

Por si acaso la consulta en sí es un ejemplo cualquiera. Lo importante es que miren el modo de uso de "dblink".
