### ISSUE TITLE
Duda Permisos de Barcos

### ISSUE THREAD

**Issue by lewebe** [IIC2413/Syllabus-2020-2#315]
Hola, un mismo barco puede tener distintos permisos del mismo tipo (ej: carga/descarga) el mismo día en una misma instalación? O asumimos que esto no ocurre?

**Comment by mariajesusbraun** [comment]
Hola! Cuando se dio la descripción de Permisos en el enunciado de la entrega 1 dice que: "los barcos nunca están más de un día en el muelle", por lo que un barco sí podría hacer más de una cosa al día y en la misma instalación. Entonces, podrían hacer un supuesto del tiempo que van a estar haciendo dicha actividad (UNA hora preferentemente, para que la verificación y disponibilidad sea más fácil de implementar).

**Comment by lewebe** [comment]
Mm, no me queda claro. Puedo ignorar las horas a las que cada barco hace algo o no? Si al final solo me importan los días para calcular capacidad
