### ISSUE TITLE
Distintos Log In para cada tipo de usuario

### ISSUE THREAD

**Issue by csmeneses** [IIC2413/Syllabus-2020-2#316]
Hola, tengo una duda respecto a si es legal tener distintos forms de login para cada tipo de usuario (capitán, jefe de puerto, usuario común). Esto con el fin de redirigir a vistas que muestren la información que quiere saber cada uno, evitando realizar consultas para verificar a qué tipo de usuario pertenece.

Muchas gracias!

**Comment by Vicerc** [comment]
Hola! La idea es que el login sea el mismo para todos los usuarios y ustedes con un código en php verifiquen qué tipo de usuario es y así mostrar la información de Mi Perfil correspondiente. 

Saludos :smiley:
