### ISSUE TITLE
[Entrega 3] Duda tabla usuarios, usuarios nuevos y trabajadores existentes

### ISSUE THREAD

**Issue by Pablok98** [IIC2413/Syllabus-2020-2#317]
Hola, tengo dos dudas con respecto a la entrega 3 del proyecto.

1.  Siguiendo lo que hablaron en la Issue #295,  cuando dicen _'el enunciado dice que todos los usuarios registrados DEBEN tener lo siguiente'_, no me queda claro si este requerimiento es para la relación nueva que creamos con usuarios. Es decir, digamos que tenemos una relación "Usuarios", es necesario que tenga los atributos "nombre, sexo, edad, etc" obligatoriamente dentro de esa relación o basta con poder obtenerla a través de `joins` o similares.

2. Con respecto a la creación de nuevos usuarios, sus pasaportes y la existencia de trabajadores. Como manejamos cuando se ingresa un pasaporte de un trabajador que no es jefe ni capitán y no está registrado? En el enunciado se pide que el pasaporte no esté presente en la base de datos, pero esto es estrictamente en la de usuarios o en la de personal en general? Es válido que un usuario nuevo se registre con un nombre distinto y el mismo pasaporte de un trabajador de un barco cualquiera (que no tenga usuario aun)?

3. Si es que la respuesta de la pregunta anterior lo permite, podemos hacer una validación del pasaporte con la información de registro a partir de la información que tenemos de cada trabajador? Es decir, obligar a que el nombre sea igual al presente en Personal de buque, por ejemplo.

Muchas gracias.

**Comment by Vicerc** [comment]
Hola!
1 Esos atributos deben ser almacenados en la entidad Usuarios.
2 Ustedes deben realizar una importación de Usuarios, es decir, agregar a la tabla Usuarios los jefes de instalaciones y capitanes de barco y asignarles a estos una contraseña estándar (la cuál deben especificar en el informe), por lo que cuando se pide que el nuevo usuario tenga un pasaporte que no este en la base de datos, se refiere a Usuarios, pero esto es porque Usuarios ya contiene la información de Personal, por lo que no es válido el caso que proponen en la última pregunta. Finalmente, si el pasaporte no está en usuarios se va a poder registrar.
3 No necesitan hacer esa validación, si el pasaporte ya existe sólo debe aparecer una vista de error.

**Comment by Pablok98** [comment]
Hola! Gracias por la respuesta.
Creo que no deje muy claro un punto, me refiero el caso de trabajadores que **no son jefes o capitanes**, por ejemplo, un tripulante de un barco. Ellos no tendrían que estar necesariamente registrados como usuarios. Que hacemos en el caso de que haya alguien que se quiera registrar utilizando el pasaporte de una de estas personas?

**Comment by Vicerc** [comment]
Disculpa la demoraa, en el caso de que alguien se quiera registrar con el pasaporte de una de esas personas va a poder hacerlo y guardarlo en Usuarios con los atributos que entregue en la página (aunque difieran de los atributos guardados en Personal).

**Comment by Pablok98** [comment]
Ok, perfecto. 

Gracias!

**Comment by svaldes99** [comment]
Hola, y que pasa cuando registro un usuario? debo darle la opción de que elija si ser capitán o jefe? o puede no ser ninguna de las dos opciones?
