### ISSUE TITLE
Entrega 3 parte 3.2 segundo punto Página de puertos, descripcion_actividad

### ISSUE THREAD

**Issue by allullk** [IIC2413/Syllabus-2020-2#318]
En la entrega 3 parte 3.2 segundo punto de página de puertos, en algunos casos debemos crear permisos, en caso de que sean para instalaciones de tipo muelle requiere de una descripcion_actividad, no se indica en el enunciado cual debe ser específicamente, ni se le solicita al usuario de la página. Debido a lo anterior ¿debemos poner cualquier descripción que se nos ocurra? Como por ejemplo descripcion_actividad = 'descripción automatica'

**Comment by mariajesusbraun** [comment]
Hola! Dado que no se especifica en el enunciado, lo que podrían hacer es crear combinaciones a gusto para la descripción según el tipo de instalación y el tipo de buque para el que se crea el permiso, o simplemente dejar que el usuario ingrese una (y que no sea nula).
