### ISSUE TITLE
Iterar sobre fechas en PL/SQL (Procedimientos Almacenados)

### ISSUE THREAD

**Issue by lewebe** [IIC2413/Syllabus-2020-2#319]
Hola, para la 3.2 se nos pide lo siguiente  
![image](https://user-images.githubusercontent.com/62037289/96660240-730bd000-131f-11eb-8ddb-b5fcbe55ad31.png)
Lo que no entiendo es que, en el caso de astilleros, hay fecha de atraque y de salida. Sin embargo, no encuentro una manera de iterar (con un FOR por ejemplo) entre ese rango de días, para ver que en cada uno de ellos se cumpla que está dentro de las dos fechas que ingresó el usuario. Una ayudita por favor :(

**Comment by juanreutter** [comment]
No se si un for afuera es la mejor solución. Lo que yo recomendaba era buscar todos los permisos que cayeran en ese intervalo, y a partir de esos permisos ir construyendo los días. 
Pero para ir consiguiendo todos los días, en postgreSQL SELECT DATE + INTERVAL '1 day' te da el timestamp correspondiente a la fecha + 1 dia. Hay también hartas otras funciones (por ejemplo, para transformar timestamp a date o vice versa) que te pueden servir.
