### ISSUE TITLE
3.2 Navegacion menú desplegable

### ISSUE THREAD

**Issue by vblopez** [IIC2413/Syllabus-2020-2#320]
Hola! :)

Me gustaría saber si existe liberdad en como el usuario ingresa los inputs o si hay que seguir textual el enunciado, en especifico me gustaría saber si se puden hacer las siguientes cosas: 

1. En las **consultas por navieras y buques** y en **pagina de puertos**,  se puede hacer un menu desplegable que muestre la lista de navieras (lista actualizada, con query) y un boton para dar enter ? (pide poder ver una lista y que ocurra algo al hacer click )

2. En la pagina de puertos:
consulta 1. se puede pedir el puerto (menú desplegable) y el intervalo de fechas de una vez ?
consulta2. se puede pedir el puerto (menú desplegable), tipo de instalacion y fechas de una vez? 
o en ambas es necesario pedir el puerto y regirigir a una pagina con un boton para el intervalo de fechas , etc?

Gracias :)

**Comment by arpincheira** [comment]
Hola, con respecto a tu primera pregunta, la idea es que no hagan un menú desplegable con las navieras, pues el enunciado pide una lista de estas(**hint** usen tablas de html para esto), con respecto al botón, yo recomiendo más poner un link, pero si quieres poner un botón explícito y con diseño, esto sería ideal y se vería bien en la app.

Con respecto a la segunda consulta, nuevamente, el enunciado pide **listas**, por lo que se aceptan tablas o listas de html(aunque son un poco menos estéticas) y no un menú desplegable como tal, por lo que no pueden hacer esto con ninguna de las dos.(la de que tengan una View de puertos y para cada puerto poder entrar a esta nueva interfaz es para que puedan trabajar con las rutas y al hacer un menú desplegable no estarían cumpliendo lo solicitado).

Espero haber contestado tus dudas.
