### ISSUE TITLE
Duda: Manejo de bases de datos

### ISSUE THREAD

**Issue by Cadutodalcielo** [IIC2413/Syllabus-2020-2#321]
Hola,

¿se permite el uso de views para traspasar una base de datos a otra?

Gracias.

**Comment by juanreutter** [comment]
Una vista es simplemente una consulta que no materializas, si no que le das un nombre en particular, por ejemplo para poder usarla después. 
¿Cómo usarías eso para traspasar de una BD a la otra?

**Comment by Cadutodalcielo** [comment]
CREATE VIEW remote_buques AS SELECT * FROM ('dbname=grupoXXe3 port=5432 host=localhost user=grupoXX 
password=pass','SELECT * FROM buques') 
AS t1(id_buque int, nombre varchar, patente varchar, id_pais int, id_capitan int, id_naviera int);


algo asi

**Comment by castrillini** [comment]
Hola, efectivamente lo que mencionas es válido de utilizar.

P.D. creo que te faltó el "dblink" en tu consulta :)

**Comment by Cadutodalcielo** [comment]
> Hola, efectivamente lo que mencionas es válido de utilizar.
> 
> P.D. creo que te faltó el "dblink" en tu consulta :)

Cracias :D
