### ISSUE TITLE
Error al conectarse a base de datos

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#322]
Hola, me aparece este error al conectarme a la base de datos 

![image](https://user-images.githubusercontent.com/62180259/96909707-c7749400-1474-11eb-96b7-deb9a90530a5.png)

Asi estoy haciendo el requiere en el codigo (tal cual como se indico en la ayudantia 2):
![image](https://user-images.githubusercontent.com/62180259/96909840-f4c14200-1474-11eb-93a5-180fa7142262.png)

Y esto es lo que tengo en data (que es el archivo que se conecta con conexion.php):
![image](https://user-images.githubusercontent.com/62180259/96909952-1ae6e200-1475-11eb-9c25-c5a38f8c4ed2.png)

Estoy 100% seguro que la contraseña de mi servidor puesta en el código es la correcta

**Comment by castrillini** [comment]
Hola, prueba escribiendo 'grupo15' en la variable $password
