### ISSUE TITLE
Intervalo de dos fechas en la página de puertos

### ISSUE THREAD

**Issue by based-on-what** [IIC2413/Syllabus-2020-2#323]
![permisos](https://user-images.githubusercontent.com/62000495/96921935-93559f00-1485-11eb-8f16-5d481db2532d.PNG)
Con respecto a esta consulta, con el "para cada una de sus instalaciones", ¿se refiere a absolutamente TODAS las del sistema? ¿O solo las que tengan permisos emitidos dentro del intervalo que se escribió en el input?

Saludos.

**Comment by castrillini** [comment]
Se refiere a todas las instalaciones del puerto seleccionado.
