### ISSUE TITLE
Consulta por buques de naviera

### ISSUE THREAD

**Issue by csmeneses** [IIC2413/Syllabus-2020-2#324]
Hola, en la parte 3.2 del enunciado, en la consulta por navieras y buques, se pide: "Al hacer click en una naviera, deben ver todos los buques (su patente y su nombre), ordenados por tipo.".

Lo que pasa es que cada naviera se dedica a un tipo de actividad (pesca, carga o petrolera) entonces todos los buques de una naviera siempre son del mismo tipo, por lo que no tendría sentido la parte de "ordenados por tipo".

Lo estoy entendiendo bien o lo que se pide es otra cosa?
Muchas gracias!

**Comment by castrillini** [comment]
Hola, efectivamente todos los buques de una naviera siempre son del mismo tipo. Sin embargo, como el enunciado solicita algún tipo de orden, el usuario que está al frente de la pantalla, debe poder distinguir este orden de alguna manera.
Por ejemplo asignar un orden mediante columnas:
-Buques Pesqueros:

-Buques de Carga:

-Buques Petroleros:

Se sabe que en cada naviera, dos de estas tres columnas estarán siempre vacías. Pero como les menciono, aún así hay que mostrar un orden.
