### ISSUE TITLE
Error Redirect de Registro a Login

### ISSUE THREAD

**Issue by dweinstein1** [IIC2413/Syllabus-2020-2#325]
Hola!

Cuando trato de hacer el redirect cuando hago submit a mi form de registro, hacia mi página de login, me tira el siguiente error.  "_Warning: Cannot modify header information - headers already sent by (output started at /home/grupoXX/Sites/config/data.php:9) in /home/grupoXX/Sites/Usuarios/registro-pdo-format.php on line 145"_

El redirect lo estoy haciendo con el comando `header("location:  login.php")`.

En otros redirect he utilizado los comandos `ob_start();` y `ob_flush();` y luego ahí me funciona el comando `header("location: path")`. Lamentablemente no me han funcionado cuando trato de irme desde mi página de registro a mi página de login. 

Ojala me puedan ayudar! 
Muchas gracias

**Comment by arpincheira** [comment]
Hola, podrían probar con lo que aparece es [este link](https://uniwebsidad.com/foro/pregunta/128/como-solucionar-el-problema-headers-already-sent-de-php/)

Avisa como les va

**Comment by dweinstein1** [comment]
Si ahí lo arregle! Tenía unos espacios en blanco despues del tag `?>` en los archivos `data.php` y `conexion.php` ! 

Muchas gracias
