### ISSUE TITLE
Duda solicitud de permisos 

### ISSUE THREAD

**Issue by CatalinaFloresP** [IIC2413/Syllabus-2020-2#326]
Hola!
Para solicitar un permiso para que un buque vaya a una instalación ¿es necesario que el usuario sea capitan o da lo mismo?
Y es necesario recibir el id de la instalación para pedir el permiso?

**Comment by arpincheira** [comment]
Hola, con respecto a tu primera pregunta, dado que el enunciado no lo especifica  daría lo mismo, además, si fuera capitán no podría poner una patente cualquiera sino que tendría que poner la patente de su barco. 

Ahora, con respecto a la segunda pregunta, **no deben pedir** que ingrese el id de una instalación porque quieres ver si alguna instalación tiene capacidad para ese barco para poder generar el permiso.
