### ISSUE TITLE
Entrega 3.2 primer boton desplegar tablas

### ISSUE THREAD

**Issue by TutoSaez** [IIC2413/Syllabus-2020-2#327]
Holaa,
Tengo un procedimiento almacenado que necesita las fechas y la id de una instalación, y puede retornar una tabla con lo días solicitados. Basta con tener esto listo y luego implementar el código en el php para cada una de las instalaciones existentes en el puerto?, o debo modificar mi procedimiento almacenado para que de alguna forma se desplieguen todas las instalaciones del puerto con sus respectivos días en una sola ejecución de mi función?

Y si es esto último, cual es la manera mas optima para realizarlo, ya que no se me ocurre otra manera mas que crear tablas antes de ejecutar mi funcion, correr mi funcion para cada instalacion y luego borrar esas tablas de la base de datos (y siento que esto es muy poco eficiente).
Saludos!

**Comment by arpincheira** [comment]
Hola, no no basta con eso, porque dice el enunciado explícitamente : **_en php se debe invocar a ese procedimiento con los datos de entrada de la consulta (además de otros necesarios, como el puerto), y el procedimiento debe ejecutar y entregar una tabla con los días por cada instalación._**. Dado esto entonces la segunda opción que planteas es la correcta.

Ahora, con respecto a la manera óptima de hacerlo, no podría decírtela sin revelar de cierta forma la respuesta de lo que se les pide, de todos modos, no pedimos necesariamente que sea óptimo sino que funcione(lo digo por si están cortos de tiempo principalmente).

**Comment by TutoSaez** [comment]
Y esto que dice en la entrega:  **y ii) el porcentaje promedio de ocupación en ese intervalo**, también debo entregarlo en el mismo procedimiento almacenado, o es una consulta que puedo realizar en php?

**Comment by arpincheira** [comment]
Hola, todo debe estar en el procedimiento almacenado, pues eso también forma parte de la funcionalidad solicitada para ser realizada como procedimiento almacenado

**Comment by TutoSaez** [comment]
Gracias por la respuesta.
Y necesariamente debe estar todo en un mismo procedimiento almacenado, o puede estar en dos tipos de funciones distintas? Lo digo porque tengo entendido que un procedimiento solo puede retornar un objeto a la vez, que en este caso sería la tabla con los datos o el valor promedio.

**Comment by arpincheira** [comment]
La idea es que la funcionalidad esté autocontenida en la base de datos y la aplicación llame al procedimiento(parámetros) una única vez. Es decir, que todo se haga en lenguaje PLpgSQL.

Ahora bien, si quieres modularizar la lógica dentro de la BD y hacer que un procedimiento mayor llame a otros más pequeños, lo puedes hacer, es una buena práctica de programación. En este caso deberás entregar todos los archivos que definen cada procedimiento
