### ISSUE TITLE
Insert into de php a sql

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#328]
Hola estoy haciendo esta consulta desde la pagina web (php) al servidor y sol funciona cuando pongo un numero de pasaporte con numeros.
![image](https://user-images.githubusercontent.com/62180259/97032968-ff450f80-1538-11eb-8c5a-80724089ecfc.png)

Cuando cree la tabla prueba2, cree n_pasaporte como varchar.

**Comment by arpincheira** [comment]
Hola, podría deber a que no pones '' en $pasaporte. Avísame si te funciona
