### ISSUE TITLE
Procedimientos almacenados

### ISSUE THREAD

**Issue by smrebolledo** [IIC2413/Syllabus-2020-2#329]
Hola, quisiera saber si existe alguna forma de retornar más de una tabla en un mismo procedimiento almacenado (con solo  una función).

**Comment by arpincheira** [comment]
Hola, te recomiendo revisar la documentación de Postgres en [este link](https://www.postgresql.org/docs/13/plpgsql.html) y ver la issue #327 por si le quieres dar otro enfoque a tu procedimiento almacenado
