### ISSUE TITLE
Error insertando tupla a la tabla usuarios

### ISSUE THREAD

**Issue by FelipeA7** [IIC2413/Syllabus-2020-2#330]
Hola,
estaba revisando los datos de la tabla usuarios y me di cuenta que hay una tupla que no se puede insertar en psql porque hay un nombre que tiene el caracter ' que al parecer tira error.
Al tratar de agregar el jefe de instalación con nombre 'Lily-Mae O'Quinn' (rut 68147125-1) a usuarios como que psql se queda pegado y no me deja seguir escribiendo. Probé insertar la misma tupla pero sin el ' y ahí si funcionó.
 INSERT INTO usuarios(uid, nombre, edad, sexo, num_pasaporte, nacionalidad, contraseña) VALUES ('75', 'LilyMae OQuinn', '58', 'hombre', '68147125-1', 'chilena', '6814');
Qué puedo hacer con esto?

**Comment by arpincheira** [comment]
Para poder mantener el formato de la información podrías probar insertando:
```php
INSERT INTO usuarios(uid, nombre, edad, sexo, num_pasaporte, nacionalidad, contraseña) VALUES ('75', 'LilyMae O''Quinn', '58', 'hombre', '68147125-1', 'chilena', '6814');
```

**Comment by FelipeA7** [comment]
Gracias! eso funcionó
