### ISSUE TITLE
Creación Tabla Usuarios

### ISSUE THREAD

**Issue by fcsanchez** [IIC2413/Syllabus-2020-2#331]
Hola! Esta permitido crear y poblar la tabla Usuarios con los capitanes/jefes desde fuera de la aplicación? a partir de los .csv de ambos grupos y tratamiento con python?

**Comment by arpincheira** [comment]
Hola, en las issues #295 y #312 dije que **si se puede**, pero que de todas formas **NO** lo recomiendo, pues al hacerlo con procedimientos almacenados o PHP estarían aprendiendo otras formas de ir poblando las tablas(que es finalmente la idea), además en el enunciado dice que deberían hacerlo con estas otras alternativas(aunque dado el error anteriormente mencionado aceptamos usar el mismo método de las entregas pasadas)
