### ISSUE TITLE
Tablas de procedimiento almacenado

### ISSUE THREAD

**Issue by javierzagal** [IIC2413/Syllabus-2020-2#332]
Hola! En la entrega en el procedimiento almacenado para los puertos dice "el procedimiento debe ejecutar y entregar una tabla con todos los días por instalación". Esto quiere decir que la función debe necesariamente **RETORNAR** una tabla? O puede ser que cree/modifique una tabla en la base de datos (porque a mi parecer eso también sería entregar una tabla) . Gracias de antemano

**Comment by danustilovsky** [comment]
Hola, debe entregar una tabla con la informacion pedida. Esta tabla solo se retorna pero no se almacena en la base de datos, por lo que no sirve alterar otra tabla.
