### ISSUE TITLE
Duda Cierre Instalaciones y Consultas

### ISSUE THREAD

**Issue by Skablop** [IIC2413/Syllabus-2020-2#333]
Hola,

¿Se deben considerar los dias que las instalaciones cierran en las consultas de la página de puertos?
Es decir, ¿debo mostrar que la instalación está desocupada esos días o se muestra como ocupada? y además, ¿se pueden emitir permisos para esos días?

Saludos.

**Comment by arpincheira** [comment]
Hola, no se deberían poder considerar, podrías ponerla como **desocupada** esos días y no, no se pueden emitir permisos para esos días pues generaría problemas a los barcos el encontrarse con la instalación cerrada.
