### ISSUE TITLE
Duda Consulta Puertos sobre Procedimientos Almacenados

### ISSUE THREAD

**Issue by Gianluc139** [IIC2413/Syllabus-2020-2#334]
Hola, hicimos lo que se pide en la parte 3.2 del enunciado usando todo en php, en un archivo .php en lugar de usar procedimientos almacenados como lo dice en la parte 3.3. Por otra parte,  las importaciones de los datos, los registros, cambios de contraseña y creación de permisos las hicimos usando procedimientos almacenados.
Qué pasaría si entregamos esa resolución de la parte 3.2 en php tal como está?
Gracias.

**Comment by arpincheira** [comment]
Hola, lamentablemente la evaluación de procedimientos almacenados está pensada con el objetivo de que ustedes cumplan esta funcionalidad(**la 3.2**), en el caso de dejar la parte 3.2 como está se les asignará puntaje parcial por la funcionalidad y puntaje parcial por el procedimiento almacenado que entreguen(en su caso estarían subiendo aquello que si hicieron como procedimiento almacenado). De todas formas no podemos asignar puntaje completo a esos items pues no cumplirían con lo solicitado

**Comment by Gianluc139** [comment]
Ok, gracias!
