### ISSUE TITLE
Cálculo de capacidad de instalaciones.

### ISSUE THREAD

**Issue by jtcaraball** [IIC2413/Syllabus-2020-2#335]
Hola! Nos preguntamos si la capacidad de las instalaciones se llena solo a partir de la suma de sus permisos o si tambien se deben incluir los atraques e itinerarios? 

Saludos!

**Comment by arpincheira** [comment]
Hola, el enunciado dice lo siguiente: _El porcentaje de ocupación se calcula como la cantidad de buques con **permiso** para usar esa instalación ese día, dividido por la capacidad de esa intalación_. Entonces la capacidad de las instalaciones solo debe considerar permisos, no atraques ni itinerarios
