### ISSUE TITLE
Agregar datos a las tablas

### ISSUE THREAD

**Issue by Felopo** [IIC2413/Syllabus-2020-2#336]
Hola, tenía la duda de si se puede agregar valores a nuestras tablas de la entrega 3?.
Por ejemplo si quiero ver si se está agregando el permiso en la parte 3.2.2, se le puede agregar valores a la tabla permiso y luego dejarlos ahí? o tengo que borrarlos después?

**Comment by arpincheira** [comment]
Hola, si, puedes añadir los datos a tus tablas de entregas anteriores, ojo eso si con ponerlo en el readme(para así evitar posibles confusiones al momento de corregir)
