### ISSUE TITLE
Consulta intervalo por fechas

### ISSUE THREAD

**Issue by vtunon7** [IIC2413/Syllabus-2020-2#337]
Hola! Para la consulta en donde debemos ingresar un intervalo de fechas y revisar la capacidad y porcentaje de ocupación, ¿se puede crear una tabla de calendario? Para poder separar todo por día. 
Gracias!

**Comment by arpincheira** [comment]
Hola, debes recordar que la lógica de la consulta en su totalidad debe estar escrita en plpsql, fuera de eso si estaría permitido hipotéticamente crear una tabla calendario, de todas formas esto no lo recomiendo pues la consulta de prueba puede ser en cualquier fecha de cualquier año(puede incluso ir más allá del rango establecido), por lo que esta tabla debería adaptarse según lo solicitado hipotéticamente hablando, por lo que no veo  tan útil crearla
