### ISSUE TITLE
No entrega nada el SELECT * FROM y DROP de una tabla

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#338]
Hola, estoy trabajando con procedimientos almacenados, y dentro de lo que hemos necesitado hacer hemos creado una tabla la cual se utiliza dentro de uno de estos archivos `sql` . El problema que tenemos es que al querer eliminar (`DROP TABLE nombre_tabla)` o recorrer sus tuplas (`SELECT * FROM nombre_tabla`) se queda esperando infinito la consola, y no nos entrega nada, ni siquiera nos manda un error. Creemos que existe algún tipo de LOOP que se haya generado dentro del archivo `sql` donde se está agregando tuplas a esta tabla. Qué es lo que piensan ustedes? y cómo podríamos eliminar esta tabla que al final no nos entrega nada.

**Comment by smrebolledo** [comment]
(no soy ayudante) Quizás tengas que verificar si pusiste todos los end if; y end loop; correspondiente. Y tienes que poner ; al final del drop table o select.

**Comment by Camila-sty** [comment]
Ya lo solucionamos, muchas gracias! 😃
