### ISSUE TITLE
Segundo botón página de puertos

### ISSUE THREAD

**Issue by edovtp** [IIC2413/Syllabus-2020-2#339]
Hola, tengo una duda con respecto a la cantidad de información que se debe entregar en la segunda parte de la página de puertos. En el enunciado se indica que (i) indique si alguna de las instalaciones tiene capacidad para ese barco y (ii) en caso de que haya capacidad, generar el permiso. Para esto hemos tenido dos ideas:

1.- La primera idea es la que presenta más información, donde al apretar el botón se lleva a otra página que liste todas las instalaciones que tienen capacidad para ese día, y, si hay capacidad en alguna, que se indique a través de un mensaje "Se generó el permiso en ... en la fecha ... para el buque ...".

2.- La segunda idea es una que presente menos información, donde solo se indique a través de un mensaje dos opciones: "No hay capacidad para esa fecha", y "se generó el permiso en ... en la fecha ... para el buque ...", sin mostrar cuales instalaciones son. Según el enunciado esta opción igual serviría, pero creemos que quizás esperen que mostremos más información.

Saludos!

**Comment by arpincheira** [comment]
Hola, cualquiera de las dos opciones es igualmente válida pues tal como indicas, el enunciado no especifica como deben mostrar esta información, yo recomiendo de todas formas ir por la primera opción pues es la mejor en términos de visualización de la información.
