### ISSUE TITLE
Nacionalidad usuarios (jefes de instalaciones)

### ISSUE THREAD

**Issue by iifoeldes** [IIC2413/Syllabus-2020-2#341]
Hola! Cuando queremos cargar la tabla de usuarios, los jefes de instalaciones (bases de datos impares) no tienen información acerca de su nacionalidad. ¿Que hacemos en este caso?

**Comment by cotefon** [comment]
cps

**Comment by arpincheira** [comment]
Hola, les recomiendo ver la isse #298 en donde se habla más al respecto, de todas formas pueden suponer que todos los jefes de instalaciones poseen nacionalidad Chilena

**Comment by iifoeldes** [comment]
Perfecto, muchas gracias!
