### ISSUE TITLE
Botón 2 página de puertos

### ISSUE THREAD

**Issue by smrebolledo** [IIC2413/Syllabus-2020-2#342]
Hola, para el segundo botón de la página de puertos (revisar si hay capacidad y generar permiso). Para el caso de astilleros, tenemos que verificar que todos los días entre las fechas que se entregan estén libres o puede ser que al menos uno de esos días esté libre la instalación y con eso crear el permiso?

**Comment by arpincheira** [comment]
Hola, en el caso de los astilleros debe haber espacio durante todo ese período, pues de lo contrario ocurriría que un barco no podría entrar a dicha instalación siendo que si tendría permisos para hacerlo
