### ISSUE TITLE
Base de datos entrega 3

### ISSUE THREAD

**Issue by mpbascunan** [IIC2413/Syllabus-2020-2#343]
Hola, podemos usar nuestra base de datos de la entrega 2 para esta entrega? o es obligación utilizar la de la entrega 3?

**Comment by arpincheira** [comment]
Hola, la idea es que ocupen la base de datos de la entrega3, pues esta posee en su interior una copia de la base de datos de la entrega2.

**Comment by mpbascunan** [comment]
Es que resulta que nos equivocamos y creamos nuestras nuevas tablas en la base de datos de la entrega 2. Entonces, para no tener que gastar mucho tiempo migrando tablas, por eso preguntaba si no había problema con que usemos la de la entrega 2. O necesariamente debemos hacer el cambio?

**Comment by arpincheira** [comment]
En ese caso deben dejar explícito en el readme que utilizaron esa base de datos y no la de la E3, es muy importante que hagan eso para la corrección

**Comment by mpbascunan** [comment]
Graciaas
