### ISSUE TITLE
Formato tabla procedimiento almacenado

### ISSUE THREAD

**Issue by edovtp** [IIC2413/Syllabus-2020-2#344]
Hola, con mi grupo tenemos una duda sobre la parte de procedimientos almacenados en la entrega. 

No sabemos si los días en que la capacidad no está agotada y el porcentaje promedio de ocupación en el intervalo debe ser entregado por el procedimiento almacenado de manera directa, o el procedimiento almacenado puede entregarnos una tabla con todo lo necesario para obtener ambos resultados, teniendo que trabajar el array entregado para obtener lo pedido.

Por ejemplo, que la tabla entregue todos los días, junto a su porcentaje de ocupación, donde sabemos que si el porcentaje de ocupación no es 100% entonces el día tiene capacidad. En este caso no obtenemos una tabla con los días desocupados directamente.

Saludos!

**Comment by danustilovsky** [comment]
Hola, el trabajo debe ser realizado por el procedimiento almacenado, por lo que deberian filtrar dentro de este las fechas con ocupacion igua a 100%
