### ISSUE TITLE
Explicación funcionalidad extra 

### ISSUE THREAD

**Issue by mpbascunan** [IIC2413/Syllabus-2020-2#349]
Hola, resulta que con mi grupo tuvimos un problema de coordinación y en el readme pusimos que no implementamos una funcionalidad extra cuando sí lo hicimos. Qué podemos hacer para hacer llegar la explicación de esta funcionalidad y se nos pueda corregir?

**Comment by arpincheira** [comment]
Hola, me pueden mandar un mail explicando la funcionalidad adicional para tomarla en consideración al momento de realizar la corrección.
