### ISSUE TITLE
Conexion servidor gray

### ISSUE THREAD

**Issue by josefeliuf** [IIC2413/Syllabus-2020-2#350]
Hola! tengo una duda sobre la conexión con el servidor, quizás estoy haciendo algo mal, pero me tira error de contraseña y ningún integrante del grupo la cambió (grupo16).

![permisodenegado](https://user-images.githubusercontent.com/62085104/97897291-062c0900-1d15-11eb-9230-eff7c7c9d6d4.png)

**Comment by arpincheira** [comment]
Hola, la conexión al servidor de esta entrega no va a ser directa a través de un usuario usando ssh(principalmente para evitar el que suban los archivos de la entrega en este). Para poder conectarse en este caso deben usar el comando 

```mongo -u grupoXX -p grupoXX gray.ing.puc.cl/grupoXX --authenticationDatabase admin```

Para más información sobre la conexión y los comandos que puedes utilizar te recomiendo visitar la [wiki del curso](https://github.com/IIC2413/Syllabus-2020-2/wiki/Conexión-Remota-MongoDB-y-PyMongo).

Cualquier problema que tengas con respecto a la conexión luego de leer la guía avisa por aquí nomás

**Comment by josefeliuf** [comment]
ya buena gracias!
