### ISSUE TITLE
Error al conectar con el servidor :( 

### ISSUE THREAD

**Issue by SugarFreeManatee** [IIC2413/Syllabus-2020-2#351]
Hola! Tuve algunos problemas con mi OS y decidi volver a instalarlo, y ahora no logro conectarme al servidor. Sale que tengo la clave incorrecta, pero estoy poniendo la clave correcta. Ya probe con el usuario de mi grupo (30) y de nuestro grupo pareja en el proyecto (69).
Mi sitema operativo es linux basado en debian
[
![Screenshot from 2020-11-02 14-22-44](https://user-images.githubusercontent.com/53802498/97898723-05947200-1d17-11eb-8c98-ecc4310f4aba.png)
](url)

**Comment by arpincheira** [comment]
Hola, puedes probar conectándote ahora?

**Comment by SugarFreeManatee** [comment]
Wena pincho! Si ahora si
