### ISSUE TITLE
Instalar pipenv y mongo

### ISSUE THREAD

**Issue by vblopez** [IIC2413/Syllabus-2020-2#352]
Hola! se que próximamente tendremos una ayudantía, pero me estuve leyendo el enunciado y la wiki del curso para llegar mas o menos preparada y no estoy entendiendo :( 

En la pagina de "Efecutar flash en local" , dice que debo hacer **pipenv install flask pymongo**, pero cuando lo intento me dice que **"pipenv" no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable.**. Debería instalar algo antes? 
Luego en "Conexion remota MongoDB" se señala que:
Para conectarse desde la terminal al servidor dispuesto por la universidad, realizar el siguiente comando en cualquier consola bash con **mongo instalado**
mongo -u grupoXX -p grupoXX gray.ing.puc.cl/grupoXX --authenticationDatabase admin
Aquí mongo viene por defecto o deberia googlear MongoDB e instalarlo? 

Muchas gracias :)

**Comment by arpincheira** [comment]
Hola, efectivamente en la wiki faltan algunos detalles sobre la instalación de algunas cosas que deberías tener para poder iniciar con la entrega, para ser específicos faltan:

- Instalación de mongoDB
- Instalación de Pipenv

Esos temas normalmente se trabajan en la ayudantía y creo que lo más probable es que añada algo de eso en la wiki, de todas formas aquí va una explicación de como instalar aquello que falta:

### Instalación de mongoDB

Dado que existen diversas formas de instalarlo según tu sistema operativo yo te recomiendo que le des un vistazo a [esta guía](https://docs.mongodb.com/manual/administration/install-community/) ahí podrás encontrar el método de instalación para [Linux](https://docs.mongodb.com/manual/administration/install-on-linux/), [MacOS](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/) y [Windows](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/)

### PipEnv

Pipenv es una herramienta que te permite generar un entorno virtual al interior de tu computadora en el que podrás manejar e instalar diversas librerías de python e incluso manejar versiones distintas a aquellas que posees al interior de tu computadora, la idea de esto es que, en conjunto a tus compañeros de grupo puedas trabajar de forma indistinta en el proyecto utilizando las mismas versiones de las librerías e incluso podrás evitar problemas de compatibilidad de estas al momento de corrección(que se pueden llegar a producir). De todas formas, para saber un poco más sobre esto, cómo funciona y como instalarlo te recomiendo ver (esta página con su documentación)[https://docs.pipenv.org] o (esta guía)[https://thoughtbot.com/blog/how-to-manage-your-python-projects-with-pipenv]
