### ISSUE TITLE
Problemas mongo

### ISSUE THREAD

**Issue by Juampisaez** [IIC2413/Syllabus-2020-2#355]
Hola hice los pasos iniciales de la ayudantia para utilizar mongo, y al ejectutar "mongod" me sale lo siguiente:
![image](https://user-images.githubusercontent.com/48323752/98419522-ff2e2f00-2063-11eb-9afb-326f1e85fb63.png)

Luego ejecute "mongo" para conectarme, y me sale lo siguiente:
![image](https://user-images.githubusercontent.com/48323752/98419565-179e4980-2064-11eb-9df7-23e1d4038219.png)
Dice que no se puede conectar.

Alguna idea de como solucionarlo? Instale mongo como dijeron en la ayudantia (no lo instale como servicio). No se si me salte un paso. 
Gracias de todos modos

**Comment by arpincheira** [comment]
Hola, la verdad no me manejo mucho con el uso de MongoDb en windows, pero te recomiendo que veas la solución propuesta en [esta página](https://stackoverflow.com/questions/34608563/mongodb-error-in-localhost-windows)  o en [esta página](https://stackoverrun.com/es/q/6500720)

**Comment by Juampisaez** [comment]
Muchas gracias, ya lo solucione!

**Comment by based-on-what** [comment]
Tengo exactamente el mismo problema, pero la solución propuesta no me ha servido hasta ahora :/
![mongods](https://user-images.githubusercontent.com/62000495/98448510-3efc2180-210b-11eb-93c7-6a4da4abcde9.PNG)

**Comment by based-on-what** [comment]
Este es el directorio creado al instalar MongoDB
![nomomongods](https://user-images.githubusercontent.com/62000495/98448597-e5482700-210b-11eb-8114-20b76d44100b.PNG)
![nomongod](https://user-images.githubusercontent.com/62000495/98448599-e6795400-210b-11eb-8899-8363bad2c565.PNG)

**Comment by Juampisaez** [comment]
Primero tienes que definir la variable de entorno, luego ejecutar directamente en la carpeta mondod y luego mongo (se deberia conectar). Ahora probe desde la consola y me funcionan bien los comando que se ocuparon en la ayudantia. Al parecer (en mi caso), fue que habia que ejecutar el archivo manualmente y despues se podia hacer desde la consola

**Comment by tiaresagredo** [comment]
Hola!, tengo el mismo problema :( @based-on-what , lo pudiste resolver?

**Comment by Felopo** [comment]
Hola!, @tiaresagredo, yo tenía el mismo problema y lo solucioné con el primer link que mandó  @arpincheira. Creando la carpeta data en el disco C, y dentro creando la carpeta db.

**Comment by mpmunoz13** [comment]
Yo tenía el mismo problema y se me arregló al correr mongod como administrador la primera vez.

**Comment by bdiaz3** [comment]
@mpmunoz13 Hola! Como lo ejecutaste como administrador?

**Comment by mpmunoz13** [comment]
@bdiaz3 
![image](https://user-images.githubusercontent.com/62037731/98963921-f667ae00-24e6-11eb-8e02-69d3cd8a6345.png) 
Tienes que abrir powershell como administrador

**Comment by DanielaCorral** [comment]
Hola, tengo Ubuntu 20.04 y tengo el mismo problema :cry: 
![Captura de pantalla de 2020-11-14 21-24-36](https://user-images.githubusercontent.com/48497669/99159959-c8d65c80-26c0-11eb-8007-b491e122f890.png)

Intento correr el comando ```sudo service mongod start``` pero luego cuando verifico el status aparece esto:
![Captura de pantalla de 2020-11-14 21-34-58](https://user-images.githubusercontent.com/48497669/99160026-6f226200-26c1-11eb-966d-1a11893d9934.png)

¿Alguna ayuda? He buscado de todo en internet y no tengo resultado y seguí la guía de instalación al pie de la letra :disappointed:

**Comment by arpincheira** [comment]
Probaste usando esto?
```
sudo systemctl start mongod
```

De todas formas sitúan sigues con el problema te recomiendo ver [esta página](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/)

**Comment by DanielaCorral** [comment]
Hola @arpincheira 
> De todas formas sitúan sigues con el problema te recomiendo ver [esta página](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/)

Precisamente vengo de esa página y no me funcionó nada jaja igual intenté correr el comando que enviaste y tengo lo siguiente:
![Captura de pantalla de 2020-11-15 16-39-33](https://user-images.githubusercontent.com/48497669/99194943-7dc05600-2761-11eb-8a57-92a119299f48.png)

También intenté desinstalando e instalando mongoDB otra vez y tengo el mismo error. Quise revisar los logs pero no tengo permisos para verlos :sweat_smile: He buscado harto en internet ya y no puedo solucionarlo :cry: ¿alguna idea de qué puede estar pasando?

**Comment by arpincheira** [comment]
Podrías probar con lo que dicen [aquí](https://medium.com/@adhityad3v/mongodb-code-exited-status-14-f9f9f3d3e244) y si no te funciona probar con lo que dicen [aquí](https://stackoverflow.com/questions/53469608/mongo-db-mongodb-service-failed-status-14)

**Comment by DanielaCorral** [comment]
> Podrías probar con lo que dicen [aquí](https://medium.com/@adhityad3v/mongodb-code-exited-status-14-f9f9f3d3e244) y si no te funciona probar con lo que dicen [aquí](https://stackoverflow.com/questions/53469608/mongo-db-mongodb-service-failed-status-14)

Me funcionó con tu primera página! Muchas gracias @arpincheira ! :smile_cat:
