### ISSUE TITLE
Buenas practicas

### ISSUE THREAD

**Issue by rieg-ec** [IIC2413/Syllabus-2020-2#356]
Hola, espero que estén bien. Noté que en el enunciado dice que toda la aplicación debe ir dentro de un archivo main.py. Que tan obligatorio es esto? no se puede modularizar la aplicación? teniendo en cuenta que seremos 4 personas trabajando en esta entrega, me parece raro que esté ese requisito

**Comment by arpincheira** [comment]
Hola, efectivamente podría considerarse una "mala práctica" trabajar todos en un mismo main.py, pero este es un requisito principalmente hecho por motivos de facilitar la corrección. La idea finalmente es que el **archivo principal** de su aplicación sea el ```main.py```, es decir, este es el único archivo que nosotros debemos **ejecutar** al momento de realizar la corrección y **no pueden ponerle un nombre diferente**. Ahora, ustedes podrían eventualmente definir los decoradores y cada una de las funciones que sean necesarias para la api en archivos distintos con tal de seguir buenas prácticas de programación, pero deben asegurarse de que el archivo principal cumpla que, al ejecutarlo, se pueda utilizar la API que ustedes crearon.

Adicionalmente debo destacar que, en el caso de que ustedes creen diversos archivos, deberían especificar en el readme que funciones tiene cada archivo para poder facilitar la corrección en el caso de que alguna de sus rutas falle.

Espero haber contestado tu pregunta

**Comment by rieg-ec** [comment]
ok, me queda clarisimo, gracias!
