### ISSUE TITLE
Error de autentificacion al conectar con BD

### ISSUE THREAD

**Issue by SugarFreeManatee** [IIC2413/Syllabus-2020-2#359]
Hola! Me sale un error de autentificacion al usar pymongo para acceder a una base de datos. Probe acceder a la base de datos con el metodo de la ayudantia y tambien use db.authenticate(username, password) que encontre en  [este link de stackoverflow.](https://stackoverflow.com/questions/35985762/operationfailure-not-authorized-on-tracking-to-execute-command) 

Adjunto el error

![Screenshot from 2020-11-08 17-13-14](https://user-images.githubusercontent.com/53802498/98483315-e77eb400-21e5-11eb-956e-b66477101868.png)

**Comment by jerrymendoza** [comment]
@SugarFreeManatee Hola! que url ocupaste? termina con `?authSource=admin` ??

**Comment by SugarFreeManatee** [comment]
Hola @jerrymendoza ! Sipp, aca adjunto el url

![Screenshot from 2020-11-08 20-49-08](https://user-images.githubusercontent.com/53802498/98487788-de9cdb00-2203-11eb-830d-022f103de27e.png)

**Comment by jerrymendoza** [comment]
@SugarFreeManatee Y.. por casualidad desde la consola puedes entrar con esas credenciales?

**Comment by SugarFreeManatee** [comment]
Sipp

**Comment by fjlopez7** [comment]
Intenta con lo siguiente: 
```python
from pymongo import MongoClient

con = MongoClient("mongodb://grupo30:grupo30@gray.ing.puc.cl/grupo30",27017)
db = con.grupo30
mensajes = db.mensajes
resultado = mensajes.find_one()
print(resultado)
```

**Comment by SugarFreeManatee** [comment]
Con el port me funciona! Muchas gracias!
