### ISSUE TITLE
problemas con mongoimport

### ISSUE THREAD

**Issue by fbesoainp** [IIC2413/Syllabus-2020-2#360]
Hola, tengo un error ejecutando el comando mongoimport. Los comandos mongod y mongo si funcionan y el path esta agregado a las variables del sistema.
el error es el siguiente:
![image](https://user-images.githubusercontent.com/53845524/98628211-d2dd1180-22f4-11eb-8cd5-7de837e2f40b.png)

**Comment by arpincheira** [comment]
Hola, creo que al comando que pusiste le falta el _flag_ --uri. Debería ser así:

```console
mongoimport --collection mensajes --drop --file mensajes.json --jsonArray --uri "mongodb://grupo83:grupo83@gray.ing.puc.cl/grupo83?authSource=admin"
```

**Comment by fbesoainp** [comment]
sigue dando error :C 
el error es que no esta reconociendo el comando mongoimport, pero es super raro porque si puede reconocer los comandos mongo y mongod.

**Comment by arpincheira** [comment]
y si pruebas lo que dice en [esta página](https://stackoverflow.com/questions/31055637/getting-mongoimport-is-not-recognized-as-an-internal-or-external-command-ope)?

**Comment by fbesoainp** [comment]
hice eso mismo para agregar el path a las variables del sistema :c 
de lo contrario los comandos mongo y mongod no funcionarian afuera de la carpeta del programa.

**Comment by fbesoainp** [comment]
Ya lo solucione! habia que instalar mongo tools

**Comment by vsantelicest** [comment]
> Ya lo solucione! habia que instalar mongo tools

Hola! Como instalaste mongo tools?

**Comment by fjlopez7** [comment]
Este es el link de descarga de [mongo tools](https://www.mongodb.com/try/download/database-tools).
