### ISSUE TITLE
Consulta sobre cómo pedir recorreción

### ISSUE THREAD

**Issue by burgosibarra** [IIC2413/Syllabus-2020-2#361]
Hola! Vi que están publicadas las notas de la Actividad 2, quería saber como mandar a recorregir esta. Desde ya, muchas gracias!

**Comment by arpincheira** [comment]
Hola, aquí te dejo el link para el formulario de recorrección:

https://forms.gle/MJcs333B5v9jurji8

**Comment by burgosibarra** [comment]
Ese formulario es para entrega grupales o las individuales?
