### ISSUE TITLE
Entrega 4 Proyecto

### ISSUE THREAD

**Issue by mateofantoni** [IIC2413/Syllabus-2020-2#362]
Hola! Tengo un par de dudas con respecto a las rutas de búsqueda por texto para este entrega.

Primero: cada consulta va a tener necesariamente palabras "desired", "required" y "forbidden" además del "userId"? O es solo una de ellas?, o pueden ser algunas? Estoy medio confundido con eso.

Lo otro es sobre cómo probar este tipo de consultas. Por ahora en Postman estoy ingresándolas a través del body en formato JSON, pero no sé si se hace exactamente así.

Muchas gracias!

**Comment by danustilovsky** [comment]
Hola, las consultas pueden tener cualquier de los cuatro parametros, todos o ninguno de ellos. Las llamdas a la api deben soportar todas las combinaciones. 

Con respecto a la segunda pregunta, esta bien utilizar postman y agregar los parametros en el body del request.

**Comment by mateofantoni** [comment]
Buenísimo, muchas gracias!
