### ISSUE TITLE
Error al conectar con el servidor 

### ISSUE THREAD

**Issue by mjfontanet** [IIC2413/Syllabus-2020-2#363]
Hola para conectar con el servidor por wsl me tira el siguiente error:
![image](https://user-images.githubusercontent.com/53796237/98744036-cce83e80-238f-11eb-9d3b-1f6d7882bae0.png)
Y nadie de mi grupo ha cambiado la contraseña ni nada

**Comment by arpincheira** [comment]
Hola, resulta ser que su grupo es 2 no 02, adjunto el comando modificado

```
mongo -u grupo2 -p grupo2 gray.ing.puc.cl/grupo2 --authenticationDatabase admin
```

Saludos
