### ISSUE TITLE
Correr consulta de prueba de alumnos

### ISSUE THREAD

**Issue by Baelfire18** [IIC2413/Syllabus-2020-2#365]
Hola! Como se corren estas consultas de prueba? Gracias

**Comment by arpincheira** [comment]
Hola, una vez descargado el archivo con las consultas lo que debes hacer es abrir Postman e ir a la opción que dice import/importar, esta opción se ubica en la interfaz de macOS en la esquina superior izquierda de la pantalla, tal como se puede ver en la imagen:

<img width="521" alt="Captura de Pantalla 2020-11-11 a la(s) 11 45 58" src="https://user-images.githubusercontent.com/37157550/98825715-93591700-2413-11eb-8736-1a8b1bc6b1d0.png">

Una vez seleccionada esta opción aparecerá la siguiente interfaz:

<img width="810" alt="Captura de Pantalla 2020-11-11 a la(s) 11 47 26" src="https://user-images.githubusercontent.com/37157550/98825816-b388d600-2413-11eb-81c0-57fd852f892a.png">

Una vez ahí deberás seleccionar la opción de upload file y seleccionar el archivo de prueba, una vez lo hagas aparecerá lo siguiente:

<img width="810" alt="Captura de Pantalla 2020-11-11 a la(s) 11 49 26" src="https://user-images.githubusercontent.com/37157550/98826030-f8147180-2413-11eb-9217-3a72bee95cd8.png">

Si haces click en importar aparecerá lo siguiente en la pantalla de tu interfaz de Postman:

<img width="359" alt="Captura de Pantalla 2020-11-11 a la(s) 11 50 27" src="https://user-images.githubusercontent.com/37157550/98826128-1bd7b780-2414-11eb-866b-865a414ca668.png">

Luego simplemente seleccionas una consulta y la ejecutas:

<img width="1439" alt="Captura de Pantalla 2020-11-11 a la(s) 11 51 16" src="https://user-images.githubusercontent.com/37157550/98826245-39a51c80-2414-11eb-9d7d-b0319efe4db8.png">
