### ISSUE TITLE
Duda ruta messages entre dos ids

### ISSUE THREAD

**Issue by Skablop** [IIC2413/Syllabus-2020-2#366]
Hola,

En el enunciado de la entrega 4 dice que se puede usar una ruta como  `/messages?id1=57&id2=35` , al usar esta ruta en la app, me devuelve a la misma pagina que entrega todos los mensajes. Trate quitando el símbolo `?` de la ruta y funcionó bien. 
¿Por qué pasa eso?

Saludos.

**Comment by juanreutter** [comment]
Ni idea, el protocolo de las url especifica que el caracter '?' te dice que empieza la parte de la query (acá el protocolo, es un clásico de la historia https://tools.ietf.org/html/rfc3986#section-3.4). 
Usualmente los browsers son tolerantes a las fallas (como que no hay auna ?), pero la API es un poco raro que las tolere.

**Comment by ridiazcampos** [comment]
¡Holaaaa! Como dice el profesor, el "?" es súper importante para la query (de hecho los test serán a esa ruta con el "?", así que estaría súper que se pudiera solucionar!). 

Ahora, puede que el siguiente dato freak dé alguna idea para reordenar la forma en que la api está enviando a la ruta🍀

Supongamos tenemos una función del estilo:
```
@app.route("/ruta")
def funcion():
   # algo
```

Y por ejemplo se envía un `GET` a */ruta?id=1*, esta efectivamente me llevará a `funcion`, ahora, ¿Cómo obtenemos este parámetro? ¡Súper fácil! Con `request.args.get`, entonces por ejemplo podríamos tener nuestra función como:

```
@app.route("/ruta")
def funcion():
   id = request.args.get("id", False)
   return json.jsonify({"id entregada": id}) 
```

Podemos notar que si agregamos un segundo parámetro a la función, en caso de que no encuentre a "id", esta variable va a valer este agregado.

Entonces podríamos preguntarnos: ¿Cuál es la relación con el problema? Esto nos permite personalizar nuestra función dependiendo de qué id se ingresa (o si se ingresa algún id👀).

¡Puede que esto vaya por ahí! Si nada que ver, nos puedes comentar por aquí (quizás va en otra dirección el asunto jaja). 

¡Muchos saludos y ánimos! ¡Con todo!+🍀

**Comment by Skablop** [comment]
Hola,

Al final el problema era que al obtener los datos de la query, me los entregaba como string y los necesitaba como int. Ahora está solucionado, muchas gracias!

**Comment by isidonoso** [comment]
Holaa @Skablop , 

Con mi grupo estamos teniendo el mismo problema, ¿Cómo pides el id en la ruta para generar la consulta? Hemos intentado tipo "/messages?1&2" o "/messages?id1=1&id2=2" y nos retorna la consulta con todos los mensajes. 

Graciaas.

**Comment by ridiazcampos** [comment]
¡Hola @isidonoso! 

¡La segunda manera debería funcionar! Ahora, resulta que esta consulta es algo distinta, pues compartirá ruta con `/messages` :O ¿cómo es esto? Ocurre que `?` nos permite agregar parámetros a la misma ruta, 
es de esta forma que podrían compartir la misma función en nuestra api flask :D ¿cómo obtenemos estos parámetros? La función de más arribita puede que les sirva en este caso! Esta es una forma de obtenerlos, puede que hayan más :D

 En #372 dejé un comentario hace poquito en donde habría un miniejemplo de lo que podría hacer `?` o `#` (podría copiar y pegarlo, pero si pueden ir para allá estaría fantástico :D).

¡Esooo! Si esto no responde mucho a la duda, o si hay más problemillas relacionados, nos pueden seguir comentando aquí! (O abrir nuevas issues también es válido :D).

¡Mucho éxitooooo! saludines 🍀
