### ISSUE TITLE
No puedo conectarme a mongo grupoxx

### ISSUE THREAD

**Issue by Mjtala** [IIC2413/Syllabus-2020-2#367]
Trato de conectarme a mongo -u grupo19 -p grupo19 gray.ing.puc.cl/grupo19 - authenticationDatabase admin pero me tira este error y no se cómo arreglarlo. Feliz si alguien pudiera ayudarme.
:(
![Captura](https://user-images.githubusercontent.com/62020259/98866322-81936600-244b-11eb-8e64-edad67166c49.PNG)

**Comment by fjlopez7** [comment]
Intenta corriendo el comando:

mongo -u grupo19 -p grupo19 gray.ing.puc.cl/grupo19

**Comment by Mjtala** [comment]
funcionó muchas gracias!
