### ISSUE TITLE
Duda Post

### ISSUE THREAD

**Issue by CatalinaFloresP** [IIC2413/Syllabus-2020-2#368]
Hola, cuales son los atributos que nos pasan cuando creas un nuevo mensaje? y que es lo que hay que validar de esos atributos?

**Comment by arpincheira** [comment]
Hola, te recomiendo ver las consultas de pruebas subidas al repositorio para que te hagas una idea de lo que se podría estar entregando en esos tipos de request. Con respecto a la validación, deberías fijarte principalmente que el mensaje enviado posee todos sus campos  y de  evitar que un usuario no existente envíe o reciba mensajes

**Comment by maormeno** [comment]
> Hola, te recomiendo ver las consultas de pruebas subidas al repositorio para que te hagas una idea de lo que se podría estar entregando en esos tipos de request. Con respecto a la validación, deberías fijarte principalmente que el mensaje enviado posee todos sus campos y de evitar que un usuario no existente envíe o reciba mensajes

Pero dentro de la validación debemos considerar casos como que la "date" sea "ACEITUNA" en vez de algo en el formato "YYYY-MM-DD" y retornar el error asociado, o que "long" sea "Agustin", etc??? o podemos asumir que los mensajes que vienen con todos los atributos van a venir bien???

**Comment by arpincheira** [comment]
Ah... buen punto... en ese caso también deberían hacer una validación simple, que long y lat sean números y de que las fechas estén en el formato correcto.

**Comment by maormeno** [comment]
Ok, gracias!
