### ISSUE TITLE
Problemas flask

### ISSUE THREAD

**Issue by Juampisaez** [IIC2413/Syllabus-2020-2#369]
Hola, he tenido un par de problemas para ejecutar flask. Ya instale "pip install pipenv" pero al ejecutar "pipenv install flask pymongo" me muestra un value error 
![image](https://user-images.githubusercontent.com/48323752/98868594-26637280-244f-11eb-926d-384dd436fb26.png)

Me pasa lo mismo al ejecutar "pipenv install", hay forma de solucionarlo? no puedo avanzar en la entrega :(

**Comment by Juampisaez** [comment]
![image](https://user-images.githubusercontent.com/48323752/98874549-3bdd9a00-2459-11eb-9865-b1807dae1c7e.png)
Me aparece esto al ejecutar pipenv install

**Comment by fjlopez7** [comment]
El problema al parecer es python. Debes tener más de una versión de python instalada. En esta [issue](https://github.com/pypa/pipenv/issues/4334) de la librería, hablan de este mismo problema. La idea sería eliminar alguna de estas versiones.

**Comment by Juampisaez** [comment]
Lo acabo de revisar, el tema es que al ejecutar python --version en consola, solamente me aparece una. No entiendo muy bien como solucionarlo, si me pudiesen ayudar por zoom o discord lo agradeceria mucho.

**Comment by fjlopez7** [comment]
Voy a estar en discord en una sala de ayuda.

**Comment by Juampisaez** [comment]
oka

**Comment by Juampisaez** [comment]
Ya lo pude solucionar! gracias por la ayuda

**Comment by macagamerre** [comment]
Hola! tengo el mismo problema. Incialmente tenía dos versiones de python, eliminé la anterior y volví a instalar pip y pipenv pero me sigue arrojando el mismo error ¿cómo lo solucionaron?

**Comment by fjlopez7** [comment]
El problema era por tener instalado gurobi, que instala varias versiones de python con anaconda. La forma de resolver esto fue instalando anaconda.

**Comment by macagamerre** [comment]
No entendí :( no tengo instalado gurobi ni anaconda y solo tengo instalada la versión 3.9 de python. Debería descargar anaconda y gurobi??

**Comment by fjlopez7** [comment]
Te recomiendo no descargar esas librerías, no son necesarias para este curso. Lo mejor sería borrar la versión de python y tratar nuevamente instalando (trata de instalar la versión 3.7 o la  3.8). Para ver cuantas versiones de python tienes lo puedes corroborar con py -0. Si sigues teniendo problemas te puedo ayudar por discord.

**Comment by Juampisaez** [comment]
@macagamerre el problema mío fue que había desinstalado anaconda hace mucho tiempo y algunas cosas quedaron instaladas por detrás, lo que hice fue borrar todo lo que fuera de Python (TODO) y luego instalar anaconda, y sigui este link https://docs.anaconda.com/anaconda/install/uninstall/, hice el paso b y luego me fui a la carpeta donde estaba instalado anaconda, borre las carpetas env y pckts (algo así) y luego ejecute el uninstall. (Realiza esto si tú problema era ese y se te debería arreglar al querer instalar nuevamente Python)

**Comment by macagamerre** [comment]
Hola, reinstalé todo usando python 3.8 y no funciona 😢

**Comment by fjlopez7** [comment]
busca si en esta ruta C:\Users\<tu usuario>\AppData\Local\Programs\Python\ si tienes más versiones de python. En estas carpetas al parecer están los ejecutables de las librerías.

**Comment by macagamerre** [comment]
![image](https://user-images.githubusercontent.com/12416081/99189703-388c2c00-2741-11eb-84cb-f19a894055b5.png)

Solo tengo la version 3.8 instalda
Ya intenté desistalando pipenv y virtualenv como administrador y volviendolo a instalar.

Cuando pongo `pipenv --version` en consola funciona bien.
El problema es al ejecutar `pipenv install` pq busca la un path a python 3.9 que ya no existe. 
Revisé los PATH de las varables de entorno y están correctos hacia la versión 3.8
No sé qué más hacer 😞

**Comment by fjlopez7** [comment]
Dado que esto te atrasando mucho en realizar esta entrega te recomiendo que instales pymongo y flask de forma local. 
O sea con: 
````` cmd
pip install pymongo flask
`````

Dile a tu grupo que prueben el correcto funcionamiento con pipenv.
