### ISSUE TITLE
Duda relevancia desired

### ISSUE THREAD

**Issue by CatalinaFloresP** [IIC2413/Syllabus-2020-2#370]
Hola, que pasa si tengo dos búsquedas, y ambas cumplen los requerimientos (requirements), pero sólo una cumple lo deseado (desired), ¿Se despliegan ambas? Porque si es así, sería irrelevante tener un ítem deseado (todo esto bajo el supuesto de que lo que tenga la palabra forbidden no se va a mostrar).
O desired/required se refiere al orden de desplegamiento de los mensajes?

**Comment by arpincheira** [comment]
Hola, 
la idea de las frases deseables es que ayuden a mongo a ordenar los resultados de la búsqueda según un **score**, que dependerá de cuantas coincidencias de frases deseables tenga el texto. [Documentación](https://docs.mongodb.com/manual/text-search/).  De todas formas, si un mensaje con una frase está en desired pero que no posee una frase que está en required entonces no se debería mostrar.

En resumen, lo que deben hacer es asegurar que los mensajes retornados tengan **todas las frases requeridas**, **ninguna palabra prohibida** y ordenados según coincidencia con las frases deseables. La gracias es que Mongo hace todo esto por sí solo. Solo deben entregarle el string para buscar.

**Comment by Skablop** [comment]
¿Esto no contradice los resultados de las consultas que nos entregaron?  Porque ahí hacen consultas solo con desired y estas igual entregan resultados.

**Comment by arpincheira** [comment]
No, porque en el caso de que solo se entreguen palabras o frases en desired, estas actuarían como un criterio de búsqueda básico que adicionalmente ordenaría los resultados según el score obtenido
