### ISSUE TITLE
Duda Text Search y ruta de mensajes intercambiados

### ISSUE THREAD

**Issue by gfcataldo** [IIC2413/Syllabus-2020-2#372]
Hola! Escribo porque tengo dos dudas:

1. Hicimos la consulta para la parte de text search y funciona perfecto en la consola. Sin embargo, en Python nos devuelve una query vacía. ¿Por qué podría ser esto? Creemos que el string de la consulta lo construimos bien (con los \" y - donde son necesarios), así que estamos medio estancados aquí. No me atrevo a poner código, pero díganme si podríamos hablarlo por interno por favor.

2. En la parte de obtener los mensajes intercambiados por dos usuarios, nos funciona la consulta si usamos la ruta `"/messages/id1=<int:uid1>&id2=<int:uid2>"` (con backslash) pero no nos funciona con `"/messages?id1=<int:uid1>&id2=<int:uid2>"` (signo de interrogación). Con lo segundo nos devuelve todos los mensajes de la base de datos. ¿A qué se podría deber esto y cómo se puede solucionar?

De antemano muchas gracias.

**Comment by eavivanco** [comment]
Me pasó lo mismo! Lo pudiste solucionar?

**Comment by gfcataldo** [comment]
No he podido :(

**Comment by ridiazcampos** [comment]
¡Holaaa! ¿Han podido solucionarlo? :O (sorry la demora uwu)

Intentaré responder :D

1. ¡Qué extraño! :O Por el momento no se me ocurren muchas cosas, pero una pequeña lista para chequear!
    * Las comillas de dentro de la búsqueda tienen un `\` antes. Por ejemplo: `\"palabra\"`.
    * Ver que las búsquedas efectivamente sean las que queremos, esto podría ser imprimiéndolo antes.
    Y síiii, ¡gracias por no subir código! Me pueden enviar un correo (ridiaz2@uc.cl :D) si quieren! No hay problemita :D

2. ¡Perfecto! ¡Súper buena idea! Resulta que el `?` nos sirve para añadir parámetros a una ruta. ¿Cuál es la gran diferencia con utilizar `/`? Esta última crea una nueva ruta a partir de estos parámetros, mientras que la primera conserva la ruta original. Podemos ver por ejemplo que podríamos redirigirnos a esta misma ruta agregando un parámetro random: [https://github.com/IIC2413/Syllabus-2020-2/issues/372?busqueda=hola](./372?busqueda=hola). Vemos que nos redirige sin cambios, pero eventualmente GitHub podría haber dicho "Si me entregan el parámetro `búsqueda`, voy a resaltar los comentarios que tengan esta palabra", ¡y podría funcionar!. Parece ser que algo similar ocurre con `#`, pues por ejemplo podríamos [destacar este comentario](https://github.com/IIC2413/Syllabus-2020-2/issues/372).

    Entooooonces, ¿de qué nos sirve saber esto y cómo puedo ocuparlo a nuestro favor? Resulta que `python` tiene en su librería `flask` a la función `request.args.get` que nos permite obtener los parámetros dados a partir de `?` por ejemplo, entonces en el ejemplo anterior, podríamos haber llamado a la función y entregándole `busqueda` para conseguir la palabra `hola`. Es así como esto nos da la posibilidad de obtener argumentos personalizables, además, nos permite personalizar el comportamiento de una ruta, que nos será muy útil, pues `/messages?id1=1&id2=2` nos llevará de hecho a la misma ruta `/messages`, que nos debería mostrar todos los mensajes, es decir, ambas funcionalidades comparten ruta.

Quizás un poco enredada mi explicación jaja pero pueden seguir comentando para responder :D 
Perdón nuevamente por la demoraaaa.

¡Muuuuuuucho éxito y ánimos! Estaré prestando atención a esta issue y al correo por si acaso, saludines :D 🌱

**Comment by figarcia3** [comment]
Hola! Tengo el mismo problema, no reconoce el caracter de - para las consultas de forbidden y me entrega un conjunto vacío cuando realizo consultas con ese atributo en particular. Que puede ser?

**Comment by ridiazcampos** [comment]
¡Holaaaa @figarcia3! Oooooh, esto es importante 👀. 

Resulta que al solo entregar forbidden **la consulta en mongo retornará vacío** pues no le estamos indicando nada que sí queremos que busque. Ahora, **en nuestra api** queremos que si solo le entregamos forbidden entregue **todos los mensajes, menos aquellos que contengan estas palabras**. 

¿Cómo podemos realizar esto? Necesitamos tratar este caso particular dentro de nuestra función, esto lo podemos cumplir a partir de búsquedas con funciones en `pymongo` y con la ayuda de `python` de forma que nos entregue el filtro que queremos :D 

¡En resumen! Además de realizar la búsqueda clásica, este caso particular deberá ser tratado un poco más allá del text-search, para que de esta forma, nos permita retornar los mensajes con este filtro.

¡Cualquier duda nos pueden seguir comentando! ¡Mucho éxito!
