### ISSUE TITLE
duda resultados consultas con required

### ISSUE THREAD

**Issue by mmunoz12** [IIC2413/Syllabus-2020-2#373]
Hola! Estaba revisando los resultados de las consultas que dieron en el excel, y dice que el GET3.4 debiese dar como resultado los mensajes 136, 145 y 267. Quedé con la duda de si el mensaje 267 esta bien, ya que el mensaje dice: "Hola! Quiero jugar Pokémon. Bai." y no cumple con las palabras required que se pide en el body que son: ["quiero jugar Megaman", "Bai"]. Esta bien o existe un error? de antemano muchas gracias!

**Comment by arpincheira** [comment]
Hola, efectivamente había un error, muchas gracias por notarlo, ahora se encuentra actualizado el archivo
