### ISSUE TITLE
Consulta importar datos con tilde

### ISSUE THREAD

**Issue by Skablop** [IIC2413/Syllabus-2020-2#374]
Hola,

Al importar datos que tienen tilde, quedan con caracteres con encoding de la forma `\u00` dentro de la base de datos. ¿Esto podría generar un problema al hacer las búsquedas por texto? ¿Si es así, cómo se puede arreglar?

Saludos.

**Comment by fjlopez7** [comment]
Podrías enviar una foto de como se ven los mensajes en la consola?

**Comment by Skablop** [comment]
Hola,

En la consola se ven normales:

`{
        "mid" : 52,
        "message" : "Te cuento que: Descubrí que sobre las nubes vuela el aliento. Me despido, salu5.",
        "sender" : 5,
        "receptant" : 245,
        "lat" : -27.374641,
        "long" : -90.276865,
        "date" : "2020-08-03"
}`

pero al buscar el resultado en el navegador se ve asi:

`    {
    "date": "2020-08-03", 
    "lat": -27.374641, 
    "long": -90.276865, 
    "message": "Te cuento que: Descubr\u00ed que sobre las nubes vuela el aliento. Me despido, salu5.", 
    "mid": 52, 
    "receptant": 245, 
    "sender": 5
  }`

por lo que creo que es algo del encoding del navegador o algo así, pero no estoy seguro.

Saludos.

**Comment by fjlopez7** [comment]
Al parecer el problema esta en el código. Al retornar el json se deben trabajar con otro encoding. 
Intenta agregar esto:
```python
app.config['JSON_AS_ASCII'] = False
```
