### ISSUE TITLE
Your branch is ahead of 'origin/master' by 6 commits.

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#375]
Hola, estoy tratando de hacer push en mi repo para subir archivos pero no me deja, me dice Your branch is ahead of 'origin/master' by 6 commits. Hago git pull y me dice que esta todo en orden. Que puedo hacer al respecto ?
![image](https://user-images.githubusercontent.com/62180259/99014829-4ae44b00-2532-11eb-882d-3176bccf8cfe.png)

**Comment by arpincheira** [comment]
Hola, ese problema que estás teniendo la verdad posee varias soluciones, el tema es que tu actualmente posees 6 cambios realizados localmente en tu repositorio que no han sido añadidos al repositorio remoto, si quieres puedes ver [esta página](https://stackoverflow.com/questions/16288176/your-branch-is-ahead-of-origin-master-by-3-commits) donde hablan sobre el tema.

De todas formas aquí te dejo dos posibles soluciones:
### Solución 1
```
git pull --rebase
```
Esta función pondría tus commits al final de la cola y te permitiría realizar tus cambios como los últimos cambios realizados al repositorio. Más información [aquí](https://sdqweb.ipd.kit.edu/wiki/Git_pull_--rebase_vs._--merge)

### Solución 2

```
git fetch
```

Lo que haría este comando es actualizar tu repositorio local con los cambios externos permitiéndote entonces poder hacer el pull request que deseas, de todas formas te dejo [aquí](https://git-scm.com/docs/git-fetch) la documentación sobre este comando
