### ISSUE TITLE
Error mongo import

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#376]
Hola, estoy tratando de subir los archivos a mongodb y me aparece este error :/. Que puedo hacer para solucionarlo ?

![image](https://user-images.githubusercontent.com/62180259/99018378-aca7b380-2538-11eb-9ce2-e5b57ba64fc9.png)

**Comment by tago470** [comment]
teni que instalar los database tools en la misma carpeta donde teni mongo.exe, mongod.exe, etc.
https://www.mongodb.com/try/download/database-tools acá descargai los tools donde esta "import"
