### ISSUE TITLE
Error Unauthorized

### ISSUE THREAD

**Issue by tago470** [IIC2413/Syllabus-2020-2#377]
Anteriormente pude hacer consultas desde la consola pero ahora no me reconoce como admin nose porqué, y me tira el siguiente error al correr "use usuarios" -> "db.usuarios.find().pretty()":
Error: error: {
        "ok" : 0,
        "errmsg" : "not authorized on admin to execute command { find: \"system.user\", filter: {}, lsid: { id: UUID(\"07e7b998-a2d7-43c3-92ea-70033ad20e7c\") }, $db: \"admin\" }",
        "code" : 13,
        "codeName" : "Unauthorized"

**Comment by mariajoseguerrero** [comment]
Hola, me paso lo mismo. Lo pudiste arreglar?

**Comment by tago470** [comment]
Holaa sii no hay q usar el comando use antes! Solo ejecutas db.usuarios.find()

Enviado desde mi iPhone

**Comment by mariajoseguerrero** [comment]
Gracias! Ahi me funcionó
