### ISSUE TITLE
Problema subiendo usuarios a mongo

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#378]
Hola, estoy usando este comando para subir mensajes y usuarios a mongo. Al utilizarlos me dice que fueron ejecutados correctamente, sin embargo, al ir al servidor de mongo y poner show collections solo me muestra mensajes (siendo que ya subi usuarios).

![image](https://user-images.githubusercontent.com/62180259/99072221-5e270300-2592-11eb-966a-d3378de3fd88.png)

Por otro lado, tengo una duda conceptual. De que sirve correr mongod en una terminal y luego mongo en otra ? Es necesario hacer esto para que casos ? Cuando trabajo con el archivo de pyhton por ejemplo debo hacer esto ?

**Comment by dsepulveda3** [comment]
Me meti a ver el contenido de mensajes.json entregado por el curso (archivo que esta en e syllabus) y contiene esta info

![image](https://user-images.githubusercontent.com/62180259/99072899-aabf0e00-2593-11eb-8fa9-1aa4d27d4c87.png)

El tema es que al hacer db.mensajes.find().pretty() en mongo me aparecen cosas diferentes:

![Uploading image.png…]()

**Comment by arpincheira** [comment]
Hola, resulta ser que con tu comando de importación estás sobrescribiendo la colección mensajes con los datos de los usuarios. Piensa que el _flag_ ```--collection``` que utilizas en el comando debe estar seguido con el nombre que deseas para dicha colección, por lo que deberías poner ```--collection usuarios``` cuando quieras importar los datos de los usuarios y ```--collection mensajes``` cuando importes los datos de los mensajes, envés de usar ```--collection mensajes``` para ambas(que es lo que estás haciendo actualmente).

**Comment by dsepulveda3** [comment]
Perfecto, gracias profe. 
Una ultima preguntita conceptual. De que sirve correr mongod en una terminal y luego mongo en otra ? Es necesario hacer esto para que casos ? Cuando trabajo con el archivo de pyhton por ejemplo debo hacer esto ?
