### ISSUE TITLE
Instalacion pipenv

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#379]
Hola, estoy tratando de instalar pipenv desde visual studio y me aparece este error:

![image](https://user-images.githubusercontent.com/62180259/99087745-e1078800-25a9-11eb-9446-f1d7dfb2d2be.png)

Lo busque en internet y vi que se solucionaba yendo a las variables de entorno y agregando esto:

![image](https://user-images.githubusercontent.com/62180259/99087835-ff6d8380-25a9-11eb-884d-1e31c843e1cb.png)

Sin embargo sigue sin funcionarme

**Comment by IgnacioPorte** [comment]
Me pasa lo mismo

**Comment by fjlopez7** [comment]
Intentaron con:

pip3 install pipenv

**Comment by IgnacioPorte** [comment]
![asd](https://user-images.githubusercontent.com/62029630/99125391-b5ed5a80-25e2-11eb-96c9-83889f4f6275.png)
yo ya hice el pip install pero después cuando corro el siguiente comando no me funciona

**Comment by fjlopez7** [comment]
Intenta esta solución que se menciona en este [link](https://stackoverflow.com/questions/46041719/windows-reports-error-when-trying-to-install-package-using-pipenv) en stackoverflow.

**Comment by IgnacioPorte** [comment]
![11111](https://user-images.githubusercontent.com/62029630/99136672-21482400-2605-11eb-9f6c-dba537eb8a80.png)
me funcionó el link que me mandaste, pero ahora me tira otro error

**Comment by fjlopez7** [comment]
Según lo que encontre pordría ser que necesitas ejecutar la powershell como administrador y correr el comando:
``````cmd
pip install virtualenv
``````

**Comment by IgnacioPorte** [comment]
Tampoco me funciona

**Comment by fivaldivia** [comment]
Hola, me sale el mismo error, mis compañeras de trabajo ya hicieron el archivo pipfile, pero al correr pipenv install me sale el mismo error. @IgnacioPorte lo pudiste solucionar? Ya trate con el comando pip install virtualenv y tampoco funciona @fjlopez7

**Comment by IgnacioPorte** [comment]
No, no puedo ni crear el entorno ni meterme como tu dices.

**Comment by arpincheira** [comment]
Hola @fivaldivia, @IgnacioPorte, dado el tiempo que les queda para la entrega les recomiendo que instalen directamente las librerías a utilizar al interior del proyecto y trabajen así. Si bien **es requisito tener un pipfile** que permita definir las dependencias y crear el entorno de trabajo, no hay problema en que trabajen localmente sin utilizar un entorno virtual.

Saludos
