### ISSUE TITLE
Como correr mongodb en mac?

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2413/Syllabus-2020-2#380]
Hola! No estoy entendiendo bien como correr mongodb en mac, en la ayudantia lo explicaban para windows y no encuentro una explicacion, en la pagina de instalacion salen las siguientes opciones:

To run MongoDB (i.e. the mongod process) as a macOS service, issue the following:

brew services start mongodb-community@4.4

To run MongoDB (i.e. the mongod process) manually as a background process, issue the following:

mongod --config /usr/local/etc/mongod.conf --fork

To stop a mongod running as a background process, connect to the mongod from the mongo shell, and issue the shutdown command as needed.

No entiendo a que se refieren y no se cual usar :(

**Comment by rieg-ec** [comment]
hola, yo ocupo mongo en mac y hago esto:

1. ejecuto "brew services start mongodb-community@4.4" en terminal
2. me conecto desde la terminal con el comando "mongo"

**Comment by eavivanco** [comment]
Cacharon como solucionarlo? A mi me sigue tirando error :( 
![WhatsApp Image 2020-11-13 at 11 35 29](https://user-images.githubusercontent.com/54007753/99262708-0f30d600-27fd-11eb-8b4e-05c789486fe5.jpeg)

**Comment by rieg-ec** [comment]
segun yo ahi sale que está funcionando, y cuando haces mongod denuevo te dice que el port esta en uso. Probaste conectandote con "mongo"?

**Comment by eavivanco** [comment]
Cuando sigo los pasos que mencionaste, no me tira error, 

1.ejecuto "brew services start mongodb-community@4.4" en terminal
2.me conecto desde la terminal con el comando "mongo"

pero cuando después pongo el comando "mongod" me sale el error,

¿En mac es suficiente poner "mongo" para empezar a usarlo en la consola?

**Comment by rieg-ec** [comment]
"mongod" es para iniciar mongo como daemon, si ya tienes mongo corriendo te tirará error como te pasó ahi. Para conectarte se usa "mongo" sin la "d"

**Comment by eavivanco** [comment]
Gracias!
