### ISSUE TITLE
Entrega 4 GET text-search desired score

### ISSUE THREAD

**Issue by allullk** [IIC2413/Syllabus-2020-2#381]
Tal como se explicitó en la Issue #370 para ordenar según desired debemos guiarnos por la siguiente documentación https://docs.mongodb.com/manual/text-search/ para aquello debemos generar un score que se imprimirá, hemos buscado muchas formas de no imprimir este score mientras ejecutamos el sort
¿Importa si imprimimos el score?

**Comment by arpincheira** [comment]
Hola, podrías probar utilizando esto:
```
db.collection.find({ $text: { $search: "hola" } }, {"_id": 0}, { score: { $meta: "textScore" } }).sort( { score: { $meta: "textScore" } } )
```
donde collection es la colección de datos donde quieres realizar el text search y ver si el ouput es equivalente al que deseas pero sin el score

**Comment by allullk** [comment]
Gracias Andrés, el código que enviaste recién me funciona cuando le hago el siguiente cambio:
db.collection.find({ $text: { $search: "hola" } }, {"_id": 0,  score: { $meta: "textScore" } }).sort( { score: { $meta: "textScore" } } )
cuando pongo "_id": 0,  score: { $meta: "textScore" } dentro de unas mismas llaves

Fuera de eso, cuando utilizo este código solo me funciona desde el cmd, cuando lo pongo en python no me funciona de ninguna manera he probado poniendo las comillas en todos los lugares que se necesitan he probado también quitando comillas y nada funciona, la api me tira errores internos cuando intento utilizar la funcionalidad de score de mongo, lo extraño es que no hay ningún error cuando hago lo mismo sin ocupar python, escribiendo la sentencia directamente en mi cmd mientras estoy conectado al servidor de mi grupo.

Necesitamos ayuda porque hemos intentado de todo y nos quedamos sin ideas, hemos buscado exhaustivamente en internet y no hemos encontrado nada al respecto.

**Comment by csmeneses** [comment]
Me pasa lo mismo, en la consola ningún problema, pero al hacerlo desde python con postman aparece el siguiente error:
`TypeError: if no direction is specified, key_or_list must be an instance of list`

:(

**Comment by danckoo1** [comment]
creo que ese error se soluciona con lo que discuten acá [https://stackoverflow.com/questions/23689635/pymongo-sort-with-metadata](url) 👍

**Comment by csmeneses** [comment]
Buenísimo, ahí funcionó. Muchas gracias!

**Comment by rieg-ec** [comment]
Hola, por lo que entiendo al usar sort( { score: { $meta: "textScore" } } ) se ordenará según que tantos match hay con { $text: { $search: "hola" } }, pero no hay una manera de hacer text search con un set de inputs, y ordenarlo segun otro set de inputs (desired). Lo que retornará esto entiendo que no nos sirve pues el orden no depende del campo "required". Si me equivoco corrijanme, pero está mal decir que mongo no tiene la capacidad de hacer esto? habría que hacer el sort únicamente con python o no?
