### ISSUE TITLE
Consulta text search parámetro desired

### ISSUE THREAD

**Issue by Skablop** [IIC2413/Syllabus-2020-2#382]
Hola,

Al hacer text search, el parámetro  desired ¿cómo funciona respecto a frases u oraciones?. Por ejemplo, si la frase  `Viste las noticias?` está en desired, se me ocurren las siguientes cosas:

- Se busca la frase completa (aunque como no es requisito si no está no importa).
- Se buscan todas las palabras de la frase por separado.

¿Qué es lo correcto? Saludos

**Comment by arpincheira** [comment]
Hola, dado que desired funciona a partir de un score, la idea sería buscar todos los mensajes que posean palabras que estén presentes en los componentes de búsqueda de desired. En otras palabras, si se hace una búsqueda por desired como **único criterio** deben retornar los mensajes que contengan **al menos una** de las palabras de entre todas las frases deseadas. Es un OR lógico entre las palabras deseadas.

A continuación dejo  la [documentación](https://docs.mongodb.com/manual/text-search/) en la que se ejemplifican los 3 casos en el caso de que tengas dudas:

- Frases deseadas: lo que pasa en la sección de `$text Operator`
- Frases requeridas: lo que pasa en la sección `exact phrase`
- Palabras prohibidas: lo que pasa en la sección `term exclusion`

Además, debo mencionar que **required** es mucho más prioritario que desired en el caso de que se encuentren juntas, pero de todas formas los resultados deberían estar **ordenados según el score** que es lo que hace finalmente desired.

**Comment by Skablop** [comment]
Hola,

Gracias por la respuesta. Tengo un problema al considerar las frases en desired solo con el $text Operator como dices.
En la consulta GET 3.3 de Postman que nos dieron, me entrega más resultados de los que debería. Estuve revisando y me parece que el problema recae en que en la lista dada en el ejemplo esta la frase "P y NP", adjunto pantallazo del comando.

![Screenshot (3)](https://user-images.githubusercontent.com/20783702/99199625-3779ef80-277f-11eb-904a-f8a79faa4825.png)

**Comment by macavarelau** [comment]
Hola! Tuve el mismo problema que mi compañero, y ahora que actualizaste el excel, nos salieron **todos** los outputs. Sin embargo, al menos a nosotros, además de los que agregaste, nos salen los mensajes **212** y **246** que también cumplen con tener un "y". ¿Será posible que te hayan faltado esos? porque no veo otra razón de por qué nos salen. Gracias!

**Comment by arpincheira** [comment]
Efectivamente, los agrego al tiro, lamento mucho las molestias

**Comment by MINGOD24** [comment]
Hola, 
Nos sucede que cuando hacemos el text search con desired, consulta 3.3, nos entrega los mismos mensajes pero en distinto orden al que esta en el drive. 
![image](https://user-images.githubusercontent.com/62083817/99551085-35d84380-299a-11eb-8fd7-ee5b459e348a.png)
Como se ve en la imagen, el mensaje 231 tiene una vez más "y" que el 5, por lo que debiese estar bien que tenga mayor score. Puede ser que exista un error en el drive?
