### ISSUE TITLE
problema con búsqueda de letra

### ISSUE THREAD

**Issue by amparostevens** [IIC2413/Syllabus-2020-2#383]
Hola, 

Por alguna razón al buscar un mensaje con la letra "a", esto no retorna nada a pesar que si hay mensajes con este contenido. Qué puede estar pasando y cómo solucionarlo? Pasa con otras letras como u o i?

Gracias!

**Comment by fjlopez7** [comment]
Tu duda tiene que ver con que ``a`` es una Stop Word`. Te recomiendo revisar la respuesta de la issue #384.
