### ISSUE TITLE
Duda 'Stop Words'

### ISSUE THREAD

**Issue by nicoguz** [IIC2413/Syllabus-2020-2#384]
Hola!
Estaba probando los ejemplos que nos dieron para el text search y hay uno que explicitamente pide como palabra forbidden 'no'.
Mi duda está en que como se trata de una stop word al buscar mensajes que hagan match con 'no' mongo las omite, retornando todos los mensajes. Debemos 'desactivar' de alguna manera las stop words para estos casos? o asumimos que así es como debe funcionar nuestra API?

**Comment by arpincheira** [comment]
Hola, en primer lugar debes considerar que las consultas de prueba entregadas son lo más cercano a un testing de funcionamiento de la API que van a tener, por lo que tu API debería retornar el output esperado.

Ahora, yo recomendaría que desactivaran las stop words cambiando el idioma por defecto a none al momento de crear el index

**Comment by nicoguz** [comment]
Pero si hago esto se desactiva el stemming también no?
Lo probe así y funciona perfecto para las stop words pero al momento de buscar frases como 'cuento' no me retorna 'cuentos' :( 
Debería dejarlo así?

**Comment by arpincheira** [comment]
Hola, si mal no recuerdo el enunciado no exige en ningún momento stemming, te recomiendo de todas formas basarte en los resultados expuestos en las consultas de pruebas para poder probar la correctitud de tu API luego de esta corrección

**Comment by arpincheira** [comment]
Hola, @nicoguz, analizando la situación presentada en la issue #399 he tomado la siguiente decisión en términos de la evaluación:

"_**No se realizará ningún test que posea stop words en desired, al igual que no se solicitarán solo las letras a, i, u al momento de realizar una consulta. Pero el stemming SI se considerará**_". De todas formas, somos conscientes del malentendido que pude haber provocado, por lo que lo tendremos en consideración al momento de realizar la corrección y/o recorrección.

Lamento mucho los malentendidos que pude haber generado al haberme precipitado con la respuesta, espero que haya quedado claro el criterio final.

**Comment by ceosorio** [comment]
Hola!

De acuerdo a lo que dices podríamos entonces esperar stop words en forbidden?
