### ISSUE TITLE
Duda frases en desired

### ISSUE THREAD

**Issue by nicoguz** [IIC2413/Syllabus-2020-2#385]
Hola!
Al ir probando distintas formas de buscar lo que piden en textsearch me di cuenta que mongo no acepta combinación entre frases y palabras a menos que las frases estén si o si. Es decir si me piden buscar 'Hola que tal' o 'shrek' en desired, mongo no va a mostrar los resultados que tengan solo 'shrek'. Una forma que pense para solucionar esto es simplemente buscar por separado cada palabra o frase que nos entreguen pero si hago eso el 'score' que calcula mongo sería incorrecto (solo se calcularía para cada frase por separado).
También he buscado formas de hacer 'or' en el textsearch pero parece que eso solo se puede hacer con regex :(.
Aiuda plssss :(((((

**Comment by arpincheira** [comment]
Hola, acabo de contestar la issue #382 donde hablo un poco más del tema por si le quieres echar un ojo
