### ISSUE TITLE
Duda validez de un mensaje

### ISSUE THREAD

**Issue by MINGOD24** [IIC2413/Syllabus-2020-2#386]
Hola, para crear un mensaje se señala que debe ser valido, para esto, ¿hay que verificar los tipos de los datos? ¿O podemos suponer por ejemplo que si se debe entregar un string se entregará un string?

**Comment by arpincheira** [comment]
Hola te recomiendo ver la issue #368 en donde se habla más a fondo del tema, cualquier duda pregunta nomás
