### ISSUE TITLE
pipenv con distintas versiones de python

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2413/Syllabus-2020-2#387]
Hola! Con mis compañeros tenemos diferentes versiones de python (3.7 vs 3.9) entonces el pipenv no nos deja entrar a ambos, cuando le ponemos que sea 3.7 a mi me deja y a el no, y cuando le ponemos 3.9 no se nos conecta a ninguno (a mi me tira error por la version distinta y a el le dice que esta creado pero no se le conecta)

Que debemos hacer? borrar python e instalar la misma version? siento que eso va en contra de la idea del enviroment que es poder trabajar con versiones distintas :/ 

Alguien mas tuvo este problema?

**Comment by fjlopez7** [comment]
Tiene que hacer un modificación en el pipfile. 
Que sería: 
`````python 
python_version = "python 3"
`````
Lo obtuve de esta [issue](https://stackoverflow.com/questions/51492423/pipenv-specify-minimum-version-of-python-in-pipfile) en stackoverflow.
