### ISSUE TITLE
Syntax error de '$' en main.py Entrega4

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#388]
Holaa.
Tenemos un problema de `SyntaxError` por el símbolo `$` . En el jupyter Notebook de MongoDB hay consultas donde ocupan esta syntaxis. Puede ser que en python no funcione así?.
![image](https://user-images.githubusercontent.com/59337116/99206309-d7dd0d80-2799-11eb-85db-ee637b76d03c.png)
![image](https://user-images.githubusercontent.com/59337116/99206350-eb887400-2799-11eb-9945-1918798915a3.png)
Gracias!

**Comment by fjlopez7** [comment]
Es muy probable que para solucionar el error deben cambiar ``$and`` por ``"$and"``
