### ISSUE TITLE
Duda text search

### ISSUE THREAD

**Issue by sebaelsaca** [IIC2413/Syllabus-2020-2#389]
Hola! Tengo un par de consultas sobre el text search ya terminado. La función la implemente por completo en pymongo pero en el "desired", "required" y "forbidden" al buscar las palabras tomar por igual las mayusculas, minusculas, exclamaciones y tildes. Por lo tanto si busco "estas" en cualquiera de los criterios me puede aparecer el resultado: "Estás!". Está permitido que sea así o hay que volverlo case sensitive y que vea tildes y exclamaciones?

**Comment by ridiazcampos** [comment]
¡Holaaaaaa! No es necesario que se preocupen de esto! :D 

Efectivamente las funciones de `pymongo` nos permiten agregar estos parámetros para que la búsqueda sea case sensitive y diacritic sensitive, ¡pero está súper sin agregar estos parámetros! 

Pueden utilizar las consultas de prueba de guía :D si llegaran a notar alguna inconsistencia con lo que originalmente tienen planeado, pueden comentárnoslo por aquí o en otra issue!

¡Mucho éxitoooo!
saludines🍀
