### ISSUE TITLE
Duda formato de entrega

### ISSUE THREAD

**Issue by macavarelau** [IIC2413/Syllabus-2020-2#390]
Tengo varias dudas!

1. Es necesario hacer un .gitignore? Si lo es, qué archivos debería ignorar? solo el pycache o todo lo que no sea el main.py y el readme?
2. Cuando dicen main.py de forma comprimida junto a un readme, se refieren a subir un .zip en la carpeta Entrega4 que contenga estos dos archivos?
3. Existe alguna forma de verificar que, al hacer git pull en el servidor @codd..., realmente tenga mis archivos correctos? ej: revisar el readme de alguna forma.

Muchas gracias!

**Comment by ridiazcampos** [comment]
¡Holaaaaaa! Vamos a las preguntas :D

1. Si quieren agregan un .gitignore, sería súper útil no subir el `__pycache__`, ahora, es súper importante que además del `main.py` y el `readme`, incluyan también todo archivo `.py` adicional utilizado por ustedes, y el `Pipfile` (el `Pipfile.lock` si quieren también lo dejan, pero podrían no incluirlo si lo prefieren :D).

2. ¡Ambas opciones son válidas! El readme puede estar incluido en el zip o en la misma carpeta de la Entrega 4 (con ambas opciones podremos acceder :D )

3. ¡Síiii! Esto lo pueden realizar a partir de *filezilla*, en ese caso pueden ingresar los datos en las casillas correspondientes, y luego podrán navegar por las carpetas :D la otra forma es a partir de `ssh` de la misma forma que se conectan a su bases de datos, (`ssh grupoXX@codd.ing.puc.cl` solo que sin ingresar a `postgres`. Entonces, una vez ingresada su contraseña, podrían por ejemplo escribir `ls` y `cd` para navegar por las carpetas :D 

¡Cualquier otra duda nos pueden seguir comentando por aquí!
¡Mucho éxito y ánimo!🌱
