### ISSUE TITLE
Ruta Consulta /message con dos Id`s 

### ISSUE THREAD

**Issue by cncosta** [IIC2413/Syllabus-2020-2#391]
Hola, en la entrega sale que se deben respetar las rutas entregadas en la pauta. En la consulta /message en donde se dan un id1 y id2 como parámetros  sale que el url es ```/messages?id1=57&id2=35```. Es posible usar un url tipo ```message/id1/id2```. De no poderse, ¿cómo se hace para usar el primer tipo de url?.

**Comment by ridiazcampos** [comment]
¡Holaaaa! Resulta que esta consulta forma parte de la misma ruta :D En #372 hace poquito comenté más de esto por si quieres revisarlo! Pero, en resumen, con la ayuda de `request.args.get` de `flask` pueden obtener estos parámetros dados a partir del `?`, y de esta forma personalizar su búsqueda dependiendo del valor de estos parámetros (o la inclusión de estos en la query 👀).

¡Cualquier duda nos puedes seguir comentando!
¡Mucho éxito y ánimooooo!🌱

**Comment by cncosta** [comment]
¡Gracias!
