### ISSUE TITLE
Query con forbbiden

### ISSUE THREAD

**Issue by macagamerre** [IIC2413/Syllabus-2020-2#392]
Hola, estuvimos teniendo problemas con la consulta 3.5 y 3.9 ya que nos retorna vacío. Leyendo la documentación de $text de mongo y encontré lo siguiente:
![image](https://user-images.githubusercontent.com/12416081/99316283-d9aedb80-2842-11eb-8655-b03425f1f4f2.png)

En ambas consultas la query en la búsqueda entra como solo negaciones, así que creemos que a eso se debe el error pero no sabemos cómo solucionarlo. Intentamos agregandole espacios a la query pero no funcionó. Intentamos agregando (hardcodeando) un "Y" a la query y sí funciona. ¿Algún tip? 👀

**Comment by ridiazcampos** [comment]
¡Holaaaaaaa! ¡Esto es importante, gracias por notarlo!

Resulta que, efectivamente como nos comentas, la búsqueda en mongo nos retornará vacío (pues solo le estamos entregando lo que no queremos que retorne, pero no le damos pistas de qué cosas sí queremos). Ahora, **en nuestra api queremos una funcionalidad distinta** que podría servirnos mucho! Queremos que retorne todos los mensajes, menos aquellos que contengan estas palabras, ¿cómo solucionarlo? Necesitamos tratar este caso de forma independiente a los demás :D esto a partir de, por ejemplo, búsquedas en `pymongo`, y con la ayuda de `python` obtener los resultados que queremos.

Posiblemente hay varias formas de realizar esta funcionalidad :D Pero un **súper hint** 👀:

 *¿Cómo podríamos obtener los mensajes que **sí incluyen** las palabras que se dan en forbidden?* y, *¿cómo podríamos utilizar este conjunto para tener el filtro?*

¡Cualquier duda nos pueden seguir comentando por aquí!
¡Mucho éxito!
saludines 🌱

**Comment by macagamerre** [comment]
Perfectoo, gracias!! 🙌
