### ISSUE TITLE
Sobre el formato al entregar errores

### ISSUE THREAD

**Issue by Skablop** [IIC2413/Syllabus-2020-2#393]
Hola,

Cuando hay error de input del usuario, ¿debemos mostrar el error en algún formato especial? 

¿Algo así como un diccionario `{"success" : False}`, o da lo mismo mientras se muestre bien la información respectiva?

Saludos.

**Comment by ridiazcampos** [comment]
¡Holaaaaa! Esto pueden personalizarlo como ustedes prefieran :D 

El estilo de ese ejemplo está súper! Ahora, **es muuuuuy importante que sí o sí sea un json** (al igual que cuando retornan los mensajes). ¿Por qué? Esto le sería muy útil a una página que vaya a utilizar su api, podría por ejemplo revisar si "success" está en el diccionario, y por ejemplo si agregamos un "message_error" al diccionario, podríamos saber posibles razones por las que nos da el error :D 

En resumen, mientras sea un json y sientan que les puede servir la forma de retornar el error, estará súper bien :D 

¡Mucho éxitooooo y ánimo!🌱
