### ISSUE TITLE
Mostrar toda la información del mensaje

### ISSUE THREAD

**Issue by francodonati** [IIC2413/Syllabus-2020-2#394]
Hola! tengo una duda respecto al último punto de GET básico. Piden mostrar los mensajes intercambiados entre dos usuarios mediante la ruta /messages?id1=x&id2=y, ¿aquí debemos mostrar sólo el mensaje o toda la información de la base de datos donde se encuentra este mensaje?

**Comment by ridiazcampos** [comment]
¡Holaaa! Idealmente toda la información :D Ahora, lo que es **muuuuy importante** es que incluyan sí o sí la *mid*, pues esta servirá para identificarlos :D ¡Pero mientras más información entreguen mejor! Un ejemplo podría ser que para una aplicación que llegue a utilizar su api puede que le sirva mucho saber su fecha de envío, o si el usuario que lo envió fue por ejemplo el de id1 o el de id2. 

¡Nos puedes seguir comentando aquí cualquier otra duda si quieres!
¡Mucho éxito! 🌱
