### ISSUE TITLE
Entrega  4 get text-search problema con score y sort() 

### ISSUE THREAD

**Issue by belenramirezv** [IIC2413/Syllabus-2020-2#395]
Hola! estoy pegada en ordenar los mensajes mostrados por score descendiente. Mi problema está en que al correr la consulta en la consola me funciona perfectamente y me muestra únicamente los mensajes con las palabras deseadas y en orden descendiente. En cambio, al correr el código en postman y localhost, me muestra los 290 mensajes, sin un atributo score y no ordenados. Por qué pasa esto? He tratado distintas maneras y no me funciona. Tampoco me sale un error.  
Segui los pasos de [https://docs.mongodb.com/manual/text-search/](url).

**Comment by arpincheira** [comment]
Hola, te recomiendo ver la issue #381, en ella se habla un poco más del tema por lo que te podría servir.

**Comment by belenramirezv** [comment]
Si me guíe por esa issue. 
Lo raro es que en la consola me funciona y en postman no. :/
