### ISSUE TITLE
Duda importar datos al servidor

### ISSUE THREAD

**Issue by fbarrosalcalde** [IIC2413/Syllabus-2020-2#396]
Hola, para importar los datos, nos fuimos al directorio donde están los datos de la entrega en la cmd de windows y pusimos el comando de la ayudantía pero nos dice que el comando mongoimport no está definido. Qué podemos hacer para que nos funcione? Gracias!

**Comment by arpincheira** [comment]
Hola, te recomiendo revisar las issues #376 y #360 en donde se habla más del tema. Cualquier duda pregunta nomás

**Comment by fbarrosalcalde** [comment]
Ahí nos funcionó, gracias!
