### ISSUE TITLE
Mongo command not found

### ISSUE THREAD

**Issue by sluchsinger** [IIC2413/Syllabus-2020-2#397]
Hola, no me reconoce el comando mongo pero ya esta agregado a las variables de entorno, que puede ser?

**Comment by arpincheira** [comment]
Hola, revisaste la issue #355? En ella hablan varias personas de distintos problemas que tuvieron luego de instalar mongo, hay varias respuestas por lo que te recomiendo verla y ver si algo de lo que se menciona ahí te sirve.
