### ISSUE TITLE
version de mongo

### ISSUE THREAD

**Issue by rieg-ec** [IIC2413/Syllabus-2020-2#398]
Hola, me di cuenta que el servidor usa la versión 4.0.21 de mongo. Para el text-search, estoy usando $function, que es parte de aggregate, pero se introdujo en la version 4.4. Existe la posibilidad de actualizar el servidor? Si no es así, de que manera se podría asignar scores de acuerdo al campo desired? por lo que entiendo no hay una manera de hacerlo tal cual piden en el enunciado sin recurrir a $function. Se puede hacer con python pero me parece bastante ineficiente hacerlo así :(

**Comment by arpincheira** [comment]
Hola, no se puede actualizar el servidor, te recomiendo revisar las Issues porque por ahí se dejaron algunas pistas sobre como realizar desired, saludos

**Comment by rieg-ec** [comment]
Ok, gracias!
