### ISSUE TITLE
Duda stemming en palabras forbidden

### ISSUE THREAD

**Issue by mmunoz12** [IIC2413/Syllabus-2020-2#399]
Hola! tengo una duda con la respuesta que se dio en la issue #384. Como dices, no se exige stemming, sin embargo, en los resultados expuestos de las consultas, no se están tomando en cuenta los mensajes que contienen las palabras "cuentos" y "canciones", siendo que en forbidden se encuentran las palabras "cuento" y "canción". Con mi grupo tenemos que sólo se cuenten los mensajes que no contienen las palabras exactas en forbidden, sin stemming (cambiamos el idioma de PyMongo a None). Por lo tanto, nuestros resultados no coinciden con los del excel ya que aparecen dos mensajes más que contienen las palabras "canciones" y "cuentos".

**Comment by naviera** [comment]
Tengo la misma duda, para que lo puedan revisar más rápido, al tener idioma None, en en la request GET 3.5, se obtendrían los mensajes de mid 154 ("También vi unos de **cancion**es salu3") y mid 238 ("El único mounstuo aquí eres tú! Tú y esos personajes de **cuento**s de hadas que arruinan mi mundo perfecto").

Aunque "cancion" y "cuento" están en las palabras prohibidas, al no tener idioma configurado (como se sugiere en la issue [#384](https://github.com/IIC2413/Syllabus-2020-2/issues/384#issuecomment-727590931) ), no se consideran sus plurales.

**Comment by arpincheira** [comment]
Ya, efectivamente considerándolo bien fue un problema mío escribir ese supuesto, al momento de escribir la pauta nunca consideré las stop words y sus consecuencias, por lo que lo oficial es lo siguiente:

"_**No se realizará ningún test que posea stop words en desired, al igual que no se solicitarán solo las letras a, i, u al momento de realizar una consulta. Pero el stemming SI se considerará**_". De todas formas, somos conscientes del malentendido que pude haber provocado, por lo que lo tendremos en consideración al momento de realizar la corrección y/o recorrección.

Nuevamente, lamento mucho los malentendidos que pude haber generado al haberme precipitado con la respuesta, espero que haya quedado claro el criterio final. 

P.D.: Una forma de revisar que esté todo bien es que los outputs obtenidos por su api sean aquellos que están en los test case entregados, si no me equivoco deberían estar todos bien actualmente y cualquier duda que tengan pregunten nomás.

Saludos

**Comment by mmunoz12** [comment]
Gracias por responder. Entonces, solo para verificar, **no** debemos dejar el idioma/lenguaje como **None**? para que de esta forma sí se tomen los plurales.

**Comment by arpincheira** [comment]
Efectivamente
