### ISSUE TITLE
Duda consulta 6 del control 1

### ISSUE THREAD

**Issue by Juampisaez** [IIC2413/Syllabus-2020-2#4]
Hola, queria saber a que se refiere en la consulta 6 cuando dice "el/los tour/s m´as caro/s". Al decir caros se refiere a que la degustacion es premium o que el precio del tour. En este ultimo caso, desde que precio consideramos que es "caro"
Gracias!

**Comment by arpincheira** [comment]
Hola,
cuando se hace referencia a que algo es "caro" al interior del control se hace referencia al precio, entonces la respuesta a tu primera pregunta es que nos referimos al precio del tour.

Con respecto a la segunda pregunta, el enunciado dice que todas las consultas deben funcionar para cualquier instancia y no solo la presentada en el enunciado, por lo que asumir un precio específico no estaría cumpliendo con esta condición.

A modo de **Hint** te podría decir que la idea es que desarrolles un método para poder comparar los elementos de las tablas con el objetivo de conseguir los más caros, o en otras palabras, aquellos que posean un valor más alto que el resto.

Espero haberte ayudado.

**Comment by figarcia3** [comment]
Ejemplo. Tengo 3 autos:

auto 1: 200 clp
auto 2: 300 clp
auto 3: 400 clp

Cuales son los más caros de estos autos?

**Comment by arpincheira** [comment]
Hola, 
como dije anteriormente, uno a partir de los datos que tu entregas puede decir que la respuesta es el auto 3, de todos modos, esto estaría incumpliendo la norma que dice **todas las consultas deben funcionar para cualquier instancia y no solo la presentada en el enunciado**, por ende no puedo definir un precio específico para determinar cual es más caro. 

Lo que si se puede hacer, es buscar una manera de **Comparar** los precios de los autos, no te puedo decir exactamente como lo debes hacer, pero por ahí está la respuesta a tu pregunta @figarcia3.

Espero haberte ayudado.
