### ISSUE TITLE
text-search GET

### ISSUE THREAD

**Issue by rieg-ec** [IIC2413/Syllabus-2020-2#400]
Hola, al abrir las consultas de prueba en postman me di cuenta que para text-search son todas GET. No hay problema si nosotros usamos POST?

**Comment by arpincheira** [comment]
Hola, deben utilizar GET y no POST pues el objetivo de los request son completamente diferentes, piensa que al momento de solicitar un resultado no estás añadiendo nada a la base de datos y por ende estarías infringiendo las normas de los métodos de petición HTTP, sin mencionar que sería contra intuitivo para alguien utilizar un post envés de un get al momento de hacer una solicitud de información.

Se que esto último no se ve tan a fondo en este ramo y se profundizará más en Tecnologías y Aplicaciones web IIC2513, de todas formas te dejo [aquí](https://developer.mozilla.org/es/docs/Web/HTTP/Methods)  una página de internet por si quieres saber un poco más del tema

**Comment by rieg-ec** [comment]
Entiendo la convención para GET y POST, pero cuando se quiere mandar información en el body de la request lo que he leido es que no se debe usar GET, como se discute aquí https://stackoverflow.com/questions/978061/http-get-with-request-body y también se especifica aquí https://tools.ietf.org/html/rfc7231#section-4.3.1 . Sé que en este caso no habrán mayores problemas, pero lo proponía más que nada para seguir las convenciones. Gracias por la respuesta.
