### ISSUE TITLE
ruta /message/:id

### ISSUE THREAD

**Issue by rieg-ec** [IIC2413/Syllabus-2020-2#401]
Hola, noté que para obtener un mensaje en especifico, se usa GET /messages/:id, pero para borrar un mensaje en especifico, se usa DELETE /message/:id. Se podría ocupar la misma ruta para tenerlo más ordenado? es decir, GET y DELETE en /messages/:id?

**Comment by arpincheira** [comment]
Hola, no puedes utilizar otras rutas a las solicitadas por el enunciado porque esto incumpliría las normas solicitadas y puede generar inconvenientes al problema de realizar la corrección.

**Comment by rieg-ec** [comment]
Gracias por la respuesta
