### ISSUE TITLE
Duda stop words

### ISSUE THREAD

**Issue by naviera** [IIC2413/Syllabus-2020-2#402]
En la issue #399 se aclaró que se tomará en cuenta el stemming, por lo que no deberíamos usar language none, y que para el campo desired de las text search no se utilizarán stop words.
El problema es que las stop words en otros campos igual causan problemas, ya que al buscarlas ya sea como frase o como palabra no aparecen.
En la issue #392 se sugirió encontrar los mensajes con las palabras del campo forbidden, para saber cuáles son los mensajes que no se deberían mostrar, pero no hay forma buscar esos mensajes si una palabra si es stop word (ej: request GET 3.9, la palabra "no" es forbidden).

**Comment by arpincheira** [comment]
Hola, debes considerar que lo que ustedes deben lograr es manejar la API de tal forma que logren resultados parecidos a los de los test de prueba, los resultados de estos fueron realizados a partir de una API construidas bajo los mismos supuestos a los que ustedes estás supuestos y el día de hoy fueron corroborados con dos API adicionales para corroborar que esto fuera correcto, por lo que todos los problemas que pueden ser causados por las stop words están considerados al momento de hacer la corrección. Es por esto que te sugiero ver si es que tu API retorna los mismos resultados que los esperados y checkear que la palabra "no" no sea solamente un distractor en lo que respecta a la pregunta.

**Comment by naviera** [comment]
Gracias por responder. a qué te refieres con que "todos los problemas que pueden ser causados por las stop words están considerados al momento de hacer la corrección"? y qué significa que "no" sea un distractor?

**Comment by danckoo1** [comment]
@arpincheira me surgió la misma duda sobre la palabra "no", como se supone que la busquemos como forbbiden si es una stop word. Ya que según entiendo la idea es que usemos steaming en las palabras forbidden, la unica forma de lograrlo es mediante text search, por que regex se queda corto en ese ambito, entonces al poner "no" (o "algo -no") dentro de la búsqueda jamas la encontrará.
Espero se entienda la duda, saludos!
