### ISSUE TITLE
Duda Postman GET3.1 Entrega 4

### ISSUE THREAD

**Issue by Zetaku1** [IIC2413/Syllabus-2020-2#403]
En el request GET 3.1 de Postman que busca enviar un empty body, nos lanza bad request al momento de testear. Sin embargo esto suponemos que tiene que ver con Postman, debido a que al cambiar los headers y remover el tick de  content-type: Application/Json funciona bien.
El error suponemos que ocurre debido a que postman busca un json por el header que esta por default, pero luego como hay un empty body, nos tira error al intentar identificar un json.

**Comment by danckoo1** [comment]
Solo se que la excepción se levanta cuando en python haces `request.json` pero jamas se envió un json en el body, por lo que para no tener problemas podrías capturarlo mediante try/except 👀

**Comment by Zetaku1** [comment]
Si! tenía que ver con eso, muchas gracias!

**Comment by cncosta** [comment]
A nosotros nos sirvió esto : https://flask.palletsprojects.com/en/master/errorhandling/
