### ISSUE TITLE
text search con frases multi-palabras

### ISSUE THREAD

**Issue by bpardobravo** [IIC2413/Syllabus-2020-2#405]
Hola, no tengo muy claro como debería quedar el string de los text search cuando tienen frases required vs cuando tienen frases desired.
Por ejemplo, cuales son las diferencias del string si se busca: 
1) required: ["pan", "tomate", "me hace feliz"]
2) required: ["pan", "tomate"], desired: ["me hace feliz"]
3) desired: ["pan", "tomate", "me hace feliz"]
o quizás estoy obligado a hacer más de un find?
Busqué en https://docs.mongodb.com/manual/text-search/ , pero solo tienen un ejemplo con frase.

En el mismo ámbito: cómo se maneja una frase forbidden? por ejemplo si hay forbidden: ["pan", "tomate", "me hace feliz"], el string es "-pan -tomate -"me hace feliz"" o "-pan -tomate -me -hace -feliz" ?

**Comment by tavalenzuelag** [comment]
Tengo la misma dudaa!!

**Comment by dweinstein1** [comment]
Tengo exactamente la misma duda!

**Comment by mariajesusbraun** [comment]
Hola! Las frases se toman como si fueran una sola palabra, Es decir, si tenemos:

`required: ["pan", "tomate", "me hace feliz"]`

Entonces el string sería` "\pan \tomate \"me hace feliz""` .

Por otro lado, recuerden que cuando sólo hay forbidden, deben pensar en alguna forma de responder la consulta usando idealmente una única request a la base de datos. Pueden usar python para manejar ese caso.
