### ISSUE TITLE
Error amigable

### ISSUE THREAD

**Issue by Baelfire18** [IIC2413/Syllabus-2020-2#406]
Hola como debe ser el error amigable que tire la API?
Nosotros teniamos que retornara codigo HTML en H4 en caso de error pero el `formato_checker.py` dijo que no debía ser así y respondemos con json así `{"success": False, "Error": "No existe un mensaje con este mid"}`, tambien dice fallar (No se encontraron mensajes o se recibió un error amigable). 
Como es un ejemplo del error amigable??

**Comment by ridiazcampos** [comment]
¡Holaaaaa! 
¡Significa que la segunda opción la lee correctamente! El programa primero revisa por un `json`, en caso de que no lo encuentre, dará este "error". En caso de que les aparezca *No se encontraron mensajes o se recibió un error amigable*, significa que la consulta puede haber retornado por ejemplo una lista vacía, o se detectó mensaje que sí puede reconocer!😄 (así que bkn!)

¡Me faltó agregar eso en el readme! O agregar un "Resultado amigable" antes del mensaje :D Muchísimas gracias por notarlo y por la pregunta. En resumen 👀 los momentos en los que idealmente habría que cambiar el formato sería cuando retorna "Error: ...", o cuando no se pudo encontrar los mensajes/usuarios que estaban buscando (también les va a decir qué atributos se encontraron, idealmente retornen todos también :D).

¡Cualquier otra duda pueden seguir preguntando por aquí o en otra issue!
¡Mucho éxito y ánimooooo!:D🌱

**Comment by Baelfire18** [comment]
@ridiazcampos Perdón, creo que no entendí como debe ser el formato del error amigable

**Comment by ridiazcampos** [comment]
Me enredé intentando aclararlo jajaja 😂 El segundo que planteas en json está bien :D básicamente el mensaje "No se encontraron mensajes o se recibió un error amigable" no lo redacté muy bien, quizás podría ser: "Se recibió un error amigable (Bien!), o se encontró un conjunto de resultados vacíos (por ejemplo una lista vacía)".

Así que si les da el segundo mensaje (No el que dice "Error: ..."), significa que está muy bien! :D

Sorry el enredooooo, gracias por tanto 🌱🍀
