### ISSUE TITLE
Resultados consultas

### ISSUE THREAD

**Issue by zaertis0** [IIC2413/Syllabus-2020-2#407]
Respecto a la consulta GET3.5 con lenguaje en "None" al no tener stemming se agregaban los mensajes 154 y 238 tal como lo explicaron en #399, por lo que quedo la duda si es que faltan estos resultados en el excel o hay que arreglar el stemming para el caso de lenguaje en "None".

**Comment by arpincheira** [comment]
Hola, efectivamente sucede esto, es ese el motivo por el cual puse ese **hint** en el anuncio de sidding en donde se recomienda reducir lo máximo posible las consultas a la base de datos,(**hint** estaba destinado para aquellas consultas sólo con forbidden o con forbidden y user Id).

Saludos

**Comment by zaertis0** [comment]
Sigo teniendo una duda porque si es que no se agregan esos dos mensajes a los resultados de la 3.5 en la 3.8 no debería estar el mensaje 261 ya que esta prohibida la palabra Bai pero existe la palabra Bailé. Por lo que quiero verificar que lo que me dices es especifico para los casos de solo forbidden y forbidden con user Id

**Comment by arpincheira** [comment]
Perdón, fue mala mía, revisé el output nuevamente y se me olvidó modificar la respuesta en el idioma none

**Comment by zaertis0** [comment]
Hola, @arpincheira puedes realizar el cambio que te falto realizar para el GET3.5 en el excel en la hoja de los None ya que solo lo hiciste en la hoja de español.
