### ISSUE TITLE
Problema text-search con palabras cortas

### ISSUE THREAD

**Issue by Gianluc139** [IIC2413/Syllabus-2020-2#410]
Hola,
resulta que al realizar consultas de busqueda de texto de palabras cortas como "no" y "me", incluso directamente desde la terminal en mongo, no devuelve nada, y en cambio cuando se usan palabras mas largas funcionan perfectamente. Como nos ocupamos de esto? Gracias.

**Comment by arpincheira** [comment]
Hola, efectivamente esas palabras no aparecen pues son stop words, de hecho [aquí](https://github.com/Mickael-van-der-Beek/mongo/blob/d4b38917b2314403642176c2ad6253a84b4e4c9f/src/mongo/db/fts/stop_words_english.txt) puedes ver un listado más detallado de las stop words. Ahora, existen múltiples maneras de lidiar con las stop words y es parte de la entrega que vean cual les acomoda más.

Saludos

**Comment by Gianluc139** [comment]
ok, gracias!
