### ISSUE TITLE
Consulta 3.9

### ISSUE THREAD

**Issue by MINGOD24** [IIC2413/Syllabus-2020-2#411]
Hola,

En la consulta 3.9 en el Excel (en ingles) no aparece la 282 pero a nosotros si nos aparece, me imagino que es porque es una stop word, entonces está bien que nos aparezca?

**Comment by arpincheira** [comment]
Hola, se ha revisado el caso y no, no está bien que no les aparezca pues la stop word en cuestión se encuentra en forbidden y deberían ser capaces de manejarlas de alguna manera

**Comment by MINGOD24** [comment]
@arpincheira sorry pero no me queda claro. Tu dices que esta mal que no me aparezca, pero a mi si me aparece, en el excel no aparece. Me confundi jajajja

**Comment by arpincheira** [comment]
Hola, me expresé mal, la idea es que **no les aparezca**. Perdón por el malentendido
