### ISSUE TITLE
formato_checker.py

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2413/Syllabus-2020-2#413]
Hola! realicé todos los pasos del readme, pero al ejecutar python formato_checker.py me tira muchos syntax errors, y al ejecutar python3 formato_checker.py me tira el siguiente error
![Captura de pantalla 2020-11-23 a la(s) 16 14 19](https://user-images.githubusercontent.com/48481963/100004918-f731f700-2da6-11eb-8ee8-e09f2483543e.png)
Que puedo hacer?

**Comment by ridiazcampos** [comment]
¡Holaaaa! No sé en realidad cuál está siendo el error :O pero puede ser que pipenv no esté instalado o no esté instalado con ese nombre, ¡pero no se preocupen! Pueden ocupar el comando:

```
python3 formato_checker.py -pipenv -api
```

En este caso, la idea es correr su api en otra consola :D (esto porque le agregamos `-api` que evita que el mismo script lo abra -pues puede que también de un error al intentar abrirla en el entorno virtual-).

Algunas otras recomendaciones :D 
* Verificar que está el `Pipfile` en la misma carpeta que el `main.py` y `formato_checker.py`.
* Verificar que pipenv está instalado, esto con `pipenv -v`, si no funciona, quizás es otro comando, si es así, es posible editar `default_pipenv` en el `formato_checker.py`.
* Ver si a otro integrante de su grupo le funciona :D si esto no es así, me pueden enviar un correo a ridiaz2@uc.cl para ver qué onda!


¡Mucho éxito!🌱

**Comment by beatrizacuna** [comment]
lo primero funcionó!! muchas gracias <3
