### ISSUE TITLE
Control 3: Duda enunciado

### ISSUE THREAD

**Issue by zaertis0** [IIC2413/Syllabus-2020-2#414]
Hola, respecto a la vista(tabla) ComunaLimpia(id, nombre) esta debe ser guardada en el archivo municipios.db ??

**Comment by TamaraCucumides** [comment]
Hola, si, es super recomendable que la tabla quede guardada así en caso de que tengamos que volver a correr tu archivo, no tengamos que crearla nuevamente.

**Comment by jrrosas** [comment]
Hola! Con respecto a esa vista tengo un problema :(
En el enunciado dice que la vista debe tener 286 comunas, pero resulta que hay algunas de esas comunas que no tienen presupuesto. Mi pregunta es si se consideran o no las comunas sin presupuesto en ```ComunaLimpia(id, nombre)```.
