### ISSUE TITLE
Error al importar pandas

### ISSUE THREAD

**Issue by iankreisberguc** [IIC2413/Syllabus-2020-2#450]
Hola no he podido solucionar este error al importar pandas.
![image](https://user-images.githubusercontent.com/62029738/100911781-6d70e080-34ae-11eb-982e-a228bd62d090.png)

**Comment by TamaraCucumides** [comment]
dice que es un problema en la instalacion de numpy. Puedes probar reinstalando numpy

**Comment by iankreisberguc** [comment]
Ya encontré la solución en stack-overflow, por si a alguien le pasa el problema es la versión de numpy, hay q desinstalar e instalar la versión anterior con:
pip uninstall numpy
pip install numpy==1.19.3
