### ISSUE TITLE
Problemas con corr() en Control3

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#453]
Holaa.

Tengo un `dataframe `que tiene como atributos `plata` y `porcentaje` y que al aplicarle el método `corr()`;
![image](https://user-images.githubusercontent.com/59337116/100928970-b2544180-34c5-11eb-8916-9c6bd058e1c0.png)

Me imprime lo siguiente;
![image](https://user-images.githubusercontent.com/59337116/100928748-5ee1f380-34c5-11eb-83d6-43bebef64867.png)
Se supone que debería darme la correlación para  `plata` y `porcentaje`, pero sólo me da la de `plata`. 

Luego pruebo con lo siguiente;
![image](https://user-images.githubusercontent.com/59337116/100930570-09f3ac80-34c8-11eb-87c4-a4f0f6c610a4.png)
Y me imprime esto;
![image](https://user-images.githubusercontent.com/59337116/100930613-1a0b8c00-34c8-11eb-86cb-403101c6df97.png)

Y ahí estaría el error, pero no entiendo por qué no reconoce `porcentaje` si es parte de `df4`. Cuando imprimo las columnas me tira esto;
![image](https://user-images.githubusercontent.com/59337116/100930836-65259f00-34c8-11eb-8476-7f2e8863047c.png)

Antes de esto había graficado y me lo tiraba sin ningún problema. A qué puede deberse este error?

**Comment by zaertis0** [comment]
Tienes los datos como dtype = "object" y deberian ser int, trata de cambiarlos :)

**Comment by Camila-sty** [comment]
Para cambiarlo hice lo siguiente;
![image](https://user-images.githubusercontent.com/59337116/100933130-a5d2e780-34cb-11eb-83dd-c17fba8bbe81.png)
Me tira un error;
![image](https://user-images.githubusercontent.com/59337116/100933179-b84d2100-34cb-11eb-9348-b42fe4cb51d8.png)
Está bien el comando que uso?

**Comment by Camila-sty** [comment]
Para cambiarlo hice lo siguiente;
![image](https://user-images.githubusercontent.com/59337116/100934059-f4cd4c80-34cc-11eb-8225-eaa84dfc7195.png)
Me retorna esto;
![image](https://user-images.githubusercontent.com/59337116/100934091-0151a500-34cd-11eb-902a-00e42635e0af.png)
.....
![image](https://user-images.githubusercontent.com/59337116/100934132-10d0ee00-34cd-11eb-8ff3-3bd7694e40dc.png)

Me sigue tirando lo mismo. Está bien el comando para hacer el cambio del dtype?

**Comment by TamaraCucumides** [comment]
Hola, que pasa si haces df4.describe() ?

**Comment by Camila-sty** [comment]
Ahora me funcionó @TamaraCucumides !!
Muchas gracias 😄
