### ISSUE TITLE
Duda en Funcionalidades para la PDI - Entrega 5

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#465]
Hola.

Con mi grupo tenemos la siguiente duda; el rango de fecha desde y hasta que se piden las tenemos que usar para la selección de los mensajes y/o para los puertos en los que ha estado el capitán?.

Gracias!

**Comment by arpincheira** [comment]
Hola, solamente para la selección de los mensajes. Recuerda que las coordenadas que deben utilizar para el mapa vienen en los mismos mensajes y no de los puertos en los que ha estado el capitán.
