### ISSUE TITLE
Consulta 1 de Entrega 1 (grupo impar)

### ISSUE THREAD

**Issue by vsantelicest** [IIC2413/Syllabus-2020-2#47]
Hola! Me surgió una duda con respecto a la respuesta que debemos entregar en la primera consulta de la Entrega 1 del proyecto. No entiendo si hay que hacer una proyección solo del nombre y ciudad de cada puerto, o proyectar la relación "puerto" completamente, porque esto último no tendría sentido. Gracias!

**Comment by vblopez** [comment]
Hola! @arpincheira a que te refieres con toda la informacion de los puertos ? por enunciado entiendo que el puerto tiene nombre, ciudad y region, pero por como lo planteas me da a entender que hay más info y que quizas por ejemplo debiese incluir el personal del puerto, las instalaciones, etc.. Gracias

**Comment by arpincheira** [comment]
Hola, cuando digo **toda la información de los puertos** no me refiero a nada en específico, de hecho, en lo que respecta a esta entrega, la moderación que hagan va a depender completamente de ustedes. Si no me equivoco, esta semana les van a pasar en clases las normas para poder hacer un buen diagrama entidad relación y a partir de eso podrás corroborar si tus sospechas son o no correctas @vblopez. 

Espero haber contestado a tu pregunta.
