### ISSUE TITLE
[Control 1] consulta 2

### ISSUE THREAD

**Issue by fivaldivia** [IIC2413/Syllabus-2020-2#5]
Hola, me surgió la duda de si en la consulta 2: "encuentra los nombres de los tours que visitan una viña de la Quinta Región, o una viña  de la décima Región" se asume que un tour va solo una vez a cada región? o si no sería que visitan por lo menos 1 vez. No se si se entiende.
Gracias!

**Comment by TamaraCucumides** [comment]
Hola!

Sii un tour visita 3 viñas de la misma región, se asume que visita esa región. Si un tour no visita ninguna viña de alguna región, entonces no visita esa región. ¿Eso contesta tu duda? Avísame!!

**Comment by tomasur** [comment]
Si se entiende! pero debemos asumir para el ejercicio que un mismo tour perfectamente puede visitar viñas en distintas regiones?

**Comment by danustilovsky** [comment]
Hola! No puedes asumir nada. Puede pasar que los tours solo visiten una sola region o multiples. Tu consulta debe funcionar para ambos casos.

**Comment by tomasur** [comment]
y cuando me dice, "aquellos tours que visitan una viña en la quinta región", son aquellos tours que visitan solamente una viña? excluyendo aquellos tours que visiten dos o más?

**Comment by Mjtala** [comment]
siiii esoooo lo de tomasur

**Comment by agustin-rios** [comment]
Hola!

Que un tour visite más de una viña en la misma región no deberia excluirlo de la consulta. Avísenme si les sirve

**Comment by tomasur** [comment]
gracias, esa era la pregunta, si estábamos excluyendo a solo una viña o no
