### ISSUE TITLE
Soporte de esquema

### ISSUE THREAD

**Issue by nbarriav** [IIC2413/Syllabus-2020-2#50]
Hola,
Quería saber como se corregirá el que nuestro esquema soporte las consultas dado que solo tenemos que escribir el álgebra relacional sobre las tres primeras. Por ejemplo, en la consulta 6 sobre filtrar un mes, postgre cuenta con una función para extraer meses de fechas. Puedo tomar en cuenta aquello para ver si mi esquema soporta la consulta?

**Comment by arpincheira** [comment]
Hola, yo te recomiendo idealmente tomar todas las consultas para poder realizar el mejor esquema posible, de todas formas te recomiendo echarle un ojo a la issue #49, puede que el **hint** te sea de utilidad.
