### ISSUE TITLE
ssh: connect to host codd.ing.puc.cl port 22: Connection timed out

### ISSUE THREAD

**Issue by lzalaquett** [IIC2413/Syllabus-2020-2#52]
Hola, trato de conectarme al servidor pero no me deja. 
Ingreso el comando `ssh grupo36@codd.ing.puc.cl` pero se demora mucho y termina saliendo: `ssh: connect to host codd.ing.puc.cl port 22: Connection timed out
`.

Me pasó lo mismo cuando me traté de conectar al servidor de Sistemas operativos y redes.

**Comment by arpincheira** [comment]
Hola, estoy tratando de averiguar la causa, apenas sepa algo avisaré por esta issue.

**Comment by tiaresagredo** [comment]
me pasa lo mismo :(

**Comment by anamanzana** [comment]
me pasa lo mismo :c

**Comment by arpincheira** [comment]
Seguimos trabajando para ustedes.... Apenas sepa algo voy a avisar por esta issue

**Comment by arpincheira** [comment]
Ahora está funcionando el servidor
