### ISSUE TITLE
Servidor, git

### ISSUE THREAD

**Issue by Baelfire18** [IIC2413/Syllabus-2020-2#53]
Hola queria ver si entendi bien la primera opción del servidor.
Uno de conecta desde la terminal al servidor, incia secion con la clave, luego coencta su repositorio de github con el servidor. Y ese pasa a ser un reposiotio local del servidor.
Entonces a la hora de subir las cosas: debo clonar mi repo en una carpeta en mi PC, hacer git add, commit y push y luego conectarme al servidor para hacer git pull y ahí estaría entregado? Es así como funciona?

**Comment by arpincheira** [comment]
Hola, efectivamente los pasos a ejecutar son aquellos que mencionas, adicionalmente puedes ver la issue #44, en donde se habla de recomendaciones para el trabajo continuo en el proyecto usando los repositorios de git.

Espero haber respondido tu duda
