### ISSUE TITLE
Permisos astilleros y carga o descarga

### ISSUE THREAD

**Issue by nbarriav** [IIC2413/Syllabus-2020-2#56]
Hola,

Puede pasar que se entreguen dos permisos con la misma fecha para un mismo barco pero de distinto tipo?, es decir, que un barco tenga permiso de astilleros y  otro de carga o descarga para el mismo día en el mismo puerto.

**Comment by arpincheira** [comment]
Hola, 
si con fecha te refieres a que ocurren al mismo día, podría ser... todo dependería en si se demoran más de un día en descargar o cargar el barco y mandarlo a reparar o a una mantención.  Si tu pregunta va dirigida al uso de la fecha como primary Key para los permisos, no creo que sea lo más preciso.

Saludos

**Comment by nbarriav** [comment]
Mi pregunta va a que si se decide hacer el esquema con dos tablas distintas para los dos tipos de permisos, podría ocurrir que los id, la fecha, el puerto y barco en ambas tablas calzaran quedando como distinto las caracteristicas que se añaden ( descripcion o la fecha de salida). Sin embargo, para mostrar todas las veces que ha atracado un puerto estas caracteristicas serían excluidas pudiendo quedar dos tuplas con la misma información y por consiguiente quedaría solo una

**Comment by arpincheira** [comment]
Hola, lo que puedes hacer es encontrar la forma en que los id de los permisos no coincidan y que no quede solo una tabla con valores nulos, dado que para cierto tipo de permiso importa cierta información, para el otro tipo importa otra información y ambos comparten **un atributo en común**. No puedo decir mucho más pero espero que esa información te sea de utilidad
