### ISSUE TITLE
[Entrega 1 - Impar] Duda con respecto a cierres de instalaciones

### ISSUE THREAD

**Issue by ceosorio** [IIC2413/Syllabus-2020-2#57]
Hola!

En los cierres de las instalaciones se mencionan las reaperturas. Nuestra tabla debe tener en cuenta la cantidad de días que están cerradas las instalaciones y si hay algun personal distinto que las reabra? O sólo debemos enfocarnos en lo que respecta a los cierres?

**Comment by arpincheira** [comment]
Hola, 
efectivamente deberían contar con un registro de reaperturas de las instalaciones. No se si sea necesario tener un registro de cuanto tiempo están cerradas dado que se tiene el tiempo de cierre y el de reapertura y con eso se puede calcular. Con respecto a lo del personal encargado de la reapertura, no es necesario que se preocupen por eso, pueden considerar que es la misma persona encargada del cierre, puesto que este implica un proceso que incluye el momento de cierre y el momento de apertura de la misma.

Espero haber contestado tus dudas

**Comment by ceosorio** [comment]
Perfecto, muchas gracias! 😄

**Comment by lewebe** [comment]
@arpincheira Hola, entonces el jefe de cierre de instalaciones es por cierre o por instalación? Por ejemplo, en mi instalación 1 tendré siempre el mismo jefe aunque le haga 3 mantenciones (cierres y reaperturas)? O tendré un jefe distinto para cada cierre y reapertura, aunque la instalacion sea la misma?
