### ISSUE TITLE
Error de conexion con el host

### ISSUE THREAD

**Issue by gianlucafalcone** [IIC2413/Syllabus-2020-2#58]
Hola, con mi compañero ambos hemos intentado conectarnos al ssh como sale en el tutorial para comenzar, pero a ambos no sale "ssh: connect to host codd.ing.puc.cl port 22: Connection timed out", ya lo hemos intentado varias veces.

**Comment by jerrymendoza** [comment]
@gianlucafalcone Hola, es problema del servidor... estamos trabajando :construction:

**Comment by gianlucafalcone** [comment]
oka, gracias.

**Comment by arpincheira** [comment]
Ahora está funcionando el servidor
