### ISSUE TITLE
Formato Entrega 1

### ISSUE THREAD

**Issue by itmunoz** [IIC2413/Syllabus-2020-2#59]
El pdf de la entrega 1 se debe hacer en Word, Latex o a mano? O da lo mismo como en el control?

**Comment by arpincheira** [comment]
Hola, 
A decir verdad, el formato da lo mismo, en lo personal preferiría que no fuera a mano debido a que pueden haber malentendidos al momento de corregir. Por lo que recomendaría que, en el caso de hacerlo a mano, verifiques que el documento sea entendible.

**OjO** lo que si importa es que el archivo lo subas correctamente a la **ruta especificada** y que sea en **PDF.**
