### ISSUE TITLE
Duda pregunta 2 control 1

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#6]
La pregunta dice encontrar los nombres de los tours que visitan una viña de la quinta región O una viña de la décima región. Mi duda está en el "o", debo retornar dos tablas con el álgebra relacional, una para la quinta región y otra para la décima, o sea, dos "expresiones" diferentes ?? O una tabla con las dos regiones

**Comment by TamaraCucumides** [comment]
Hola!

La idea es que en la misma tabla retornes las viñas que visitan la quinta region + las viñas que visitan la decima region. Puedes hacer una expresión para cada una de las consultas y luego juntar las tablas.
