### ISSUE TITLE
entrega 1 impares fecha salida carga descarga

### ISSUE THREAD

**Issue by allullk** [IIC2413/Syllabus-2020-2#60]
Con respecto a la relación Permisos en la entrega 1 para grupos impares ¿la fecha de salida para la carga y descarga podría ser entregada en algún caso? ¿Podría ser esta no nula?

**Comment by arpincheira** [comment]
Hola, 
la fecha de salida para la carga y descarga no se les va a entregar nunca, dado que significa una mayor cantidad de datos a considerar dentro de su sistema y por ende un mayor costo, siendo que no poseen una gran utilidad. Además, recomiendo no crear atributos en tablas que puedan tener valores Nulos.

Espero haber contestado tu duda.

**Comment by allullk** [comment]
Muchas gracias Andrés. En base a esto, en el caso de que en una tupla un atributo sea nulo, ¿este utiliza la misma cantidad de memoria que un atributo no nulo de la misma relación?

**Comment by arpincheira** [comment]
Hola, 
a decir verdad mi respuesta anterior fue bastante simplificada, el tema que mencionas ha generado una gran cantidad de controversia y si quieres leer al respecto te recomiendo mirar [este link](https://stackoverflow.com/questions/4229805/how-much-disk-space-is-needed-to-store-a-null-value-using-postgresql-db).
