### ISSUE TITLE
Entrega en semana universitaria

### ISSUE THREAD

**Issue by JosefaPaz** [IIC2413/Syllabus-2020-2#62]
¡Hola!

Esta semana por calendario académico es la semana universitaria, por ende no deberían haber evaluaciones académicas, respecto a esto, ¿Se cambiará la entrega del proyecto que está fijada para este viernes?

Gracias y que estén muy bien 😸

**Comment by arpincheira** [comment]
Hola,
Muchas gracias por avisarnos sobre el tema, hemos discutido con el cuerpo docente y decidimos postergar la entrega al **Lunes 1 de Agosto a las 20:00 hrs**, en unos momentos voy a enviar el comunicado oficial a través de sidding.
