### ISSUE TITLE
No me deja poner la branch "master" por defecto

### ISSUE THREAD

**Issue by lewebe** [IIC2413/Syllabus-2020-2#63]
![image](https://user-images.githubusercontent.com/62037289/91076880-256c3300-e60e-11ea-9a1f-f5e0d97ce105.png)
Hola, al tratar de configurar el repositorio en el servidor, me muestra este mensaje. Estoy siguiendo los mismos pasos que se hicieron en la ayudantía

**Comment by danustilovsky** [comment]
Hola!

Podrias intentar lo que aparece [https://medium.com/@selynna/hi-andrey-it-probably-means-that-the-master-branch-on-your-machine-is-not-tracking-the-master-d603b65d3fa](aqui). Si no funciona vuelve a comentar y vemos que otra cosa podria ser.

**Comment by lewebe** [comment]
![image](https://user-images.githubusercontent.com/62037289/91085428-6d458700-e61b-11ea-86be-e92572056396.png)

Hola, ejecuté lo que decía la pagina y ahora me tiró este otro error :(

**Comment by lewebe** [comment]
![image](https://user-images.githubusercontent.com/62037289/91085708-d9c08600-e61b-11ea-8995-0d3e3efe7e05.png)
Corrí `git checkout -b master` y ahora me tira esto 😢

**Comment by danustilovsky** [comment]
@lewebe Enviame un correo (diustilovsky@uc.cl) para que te pueda ayudar mejor!

**Comment by danustilovsky** [comment]
Si alguien tiene un problema similar, para poder conectarse a git debe haber al menos un archivo. Generalmente la opcion mas simple es generar un readme.md.
