### ISSUE TITLE
donde trabajar con PosgreSQL

### ISSUE THREAD

**Issue by lzalaquett** [IIC2413/Syllabus-2020-2#64]
Hola, tengo la duda de donde tenemos que trabajar con postgresql. 
Para crear tablas y etc. tenemos que hacerlo desde el servidor? o podemos hacerlo en nuestro pc y luego pushearlo nuestra repo y hacerle pull al servidor? 

Porque, como funcina con usuarios, no se si eso es valido.

**Comment by danustilovsky** [comment]
Hola! 

Para la entrega 1, recomiendo que trabajen en postgrsql directo desde el servidor. Mas adelante en el curso se vera como trabajar postgresql desde otras plataformas.

**Comment by lzalaquett** [comment]
Muchas gracias!!
