### ISSUE TITLE
Duda consulta 3 grupo par

### ISSUE THREAD

**Issue by edovtp** [IIC2413/Syllabus-2020-2#65]
Hola, en la consulta número 3 para grupos pares dice "que hayan atracado en Valparaíso", se refiere a que la ciudad sea Valparaíso, la región sea Valparaíso, o ambas?

Mi duda también surge ya que son los grupos impares quienes modelan puertos, donde se señala que deben tener un nombre, una ciudad y una región, así que estoy incluyendo solo el id del puerto en los atraques, y no sé si eso está correcto o debo pensar solamente en el enunciado que me corresponde.

**Comment by juanreutter** [comment]
Claro, solo debes pensar en el enunciado que te corresponde, la idea es que por el contexto se entiende que es el puerto de Valparaíso. Entonces ¡vas a tener que guardar más que un solo id para el puerto!

**Comment by edovtp** [comment]
Muchas gracias, me quedó claro. Tengo otra duda con respecto a las demás consultas, a qué se refiere con que el esquema deba soportarlas?, se refiere a que pese que solo las primeras tres son pedidas en álgebra relacional, debería ser capaz de escribir las últimas igual en álgebra relacional? o es algo que se verá en la próxima clase?

**Comment by juanreutter** [comment]
Te las vamos a pedir en SQL para la entrega2. Es para que las uses como guía para hacer tu esquema, pero de todas formas les vamos a enseñar a hacer esquemas en algunas semanas más, así que si se equivocan acá solo les va a significar un poco de tiempo nomás.
