### ISSUE TITLE
Entrega 1 Impar jefe de instalaciones

### ISSUE THREAD

**Issue by lewebe** [IIC2413/Syllabus-2020-2#66]
Hola! El jefe de instalaciones del que se habla en **Personal** es el mismo que está a cargo de los cierres de la instalacion?

**Comment by juanreutter** [comment]
No necesariamente, no se especifica eso en particular.

**Comment by lewebe** [comment]
Gracias! Y el de cierre de instalaciones siempre será el mismo? Si tengo mi instalación 1 que se cierra 3 veces (cierre y reapertura), el encargado será las 3 veces la misma persona?

**Comment by juanreutter** [comment]
Tampoco se especifica eso en particular, así que no necesariamente.
