### ISSUE TITLE
Duda sobre las Navieras

### ISSUE THREAD

**Issue by mariagonthier** [IIC2413/Syllabus-2020-2#67]
Hola! 
En el enunciado de los grupos pares no me queda claro si un buque puede pertenecer a más de una naviera? Existen buques que no pertenezcan a ninguna Naviera?
Gracias ! :)

**Comment by juanreutter** [comment]
Hola, puedes asumir que los buques pertenecen a lo más a una naviera. 

Sobre si siempre tienen una naviera o no, no está especificado en el documento, y es una muy buena pregunta! Por un lado, vamos a ver que la modelación es más simple cuando se asumen que todos tienen naviera. Pero por otro lado, cuando eliminas una naviera, ¿que se hace con la información de la naviera en los buques? 

Este problema no tiene una mejor solución, para esta entrega me basta con que hayas pensado en eso, puedes asumir lo que prefieras.

**Comment by mariagonthier** [comment]
Gracias!!!!! 😜😜😜
