### ISSUE TITLE
Duda Proyecto Grupo Par

### ISSUE THREAD

**Issue by Pablok98** [IIC2413/Syllabus-2020-2#68]
Hola! Quería hacer una pregunta super breve. En el enunciado sobre el esquema (grupo par), en la sección de **Buques** , uno de los atributos dice que es _están registrados en algún país_ , podría ser el caso de que no esté registrado en ningún país?

Gracias!

**Comment by castrillini** [comment]
No existe el caso en que un buque no esté registrado en ningún país. Es decir, TODOS los buques están registrados en algún país

**Comment by Pablok98** [comment]
Ok, gracias :)
