### ISSUE TITLE
Duda sobre atributos de las tablas en Entrega 1

### ISSUE THREAD

**Issue by Juampisaez** [IIC2413/Syllabus-2020-2#69]
Hola, tengo la duda en la interpretacion de los atributos de las relaciones. Para la correccion se consideraran los datos que pongamos en el esquema que desarrollamos?
Saludos,

**Comment by juanreutter** [comment]
No, ni las tablas ni las tuplas. Es solo para que te familiarizes con los comandos para insertar datos.

**Comment by Juampisaez** [comment]
Perfecto, gracias!
