### ISSUE TITLE
Base de datos clase profesor

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#7]
Hay alguna posibilidad de que nos suban la base de datos usada por el profesor en la clase? Para poder ingresarla a relax y practicar
![image](https://user-images.githubusercontent.com/62180259/90696792-f25f2380-e24a-11ea-8d59-4e16dfd1bcea.png)

**Comment by TamaraCucumides** [comment]
Hola, 
se nos cayó el link donde la teniamos guardada. 
Debiese ser mas o menos sencillo que ustedes puedan crear sus propias instancias para practicar (esto es super útil para que revisen también las consultas del control)

Puedes revisar aquí sobre cómo hacer y cargar una instancia: https://dbis-uibk.github.io/relax/landing
