### ISSUE TITLE
Probando Psycopg2

### ISSUE THREAD

**Issue by macavarelau** [IIC2413/Syllabus-2020-2#70]
Hola, tengo un problema. Cuando trato de probar que efectivamente psycopg2 se conecta al servidor de postgres y uso el código en python:

import psycopg2

try:
    conn = psycopg2.connect(
        database='exampleDB',
        user='macarena',
        host='localhost',
        port=5432,
        password=''
    )

Me tira el siguiente error:

[Running] python -u "/home/macarena/Escritorio/UC/Bases de Datos/psql.py"
Hubo un problema :c
fe_sendauth: no password supplied

[Done] exited with code=0 in 0.346 seconds

Me dice que no ingresé contraseña cuando nunca le puse, y de hecho, dicen en la guía que dejemos el password como un string vacío. Llevo horas tratando de solucionarlo y no encuentro nada.

Gracias!

**Comment by Vicerc** [comment]
Prueba con esto:
conn = psycopg2.connect("dbname=exampleDB user=macarena")

**Comment by macavarelau** [comment]
Super! me funcionó! muchas gracias :) 
Sabes por qué se produce el error anterior? Es decir, si no tengo contraseña, tendría que crearme una o algo así para que funcione?

**Comment by Vicerc** [comment]
Por lo que estuve investigando en Ubuntu (que es el SO en el que estoy) el archivo pg_hba.conf viene configurado de la siguiente manera:

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5

Básicamente esto significa que si utilizo como host a localhost va a solicitar un método de autentificación md5 (requiere una contraseña), mientras que si no utilizas el parámetro host se utilizará el valor predeterminado que es UNIX y el método de autentificación será peer (no requiere contraseña) :avocado: 

No tendrás problemas en el curso con esto y no necesitas crear ninguna contraseña, sólo recuerda que no debes entregar el parámetro host cuando utilices el comando connect de psycopg2 :smiley:
