### ISSUE TITLE
Patentes de los buques

### ISSUE THREAD

**Issue by amparostevens** [IIC2413/Syllabus-2020-2#71]
Hola!
 Quería saber si se puede asumir que las patentes de los buques son únicas e irrepetibles. También si son letras, números o nosotros decidimos qué tipo de dato es.
Tengo la misma duda con los pasaportes del personal, se puede asumir que son únicos?

**Comment by juanreutter** [comment]
Puedes asumir que son únicos, y piensa que son strings. Incluso si son números, si no los vas a sumar o restar (y no te importa gastar unos bits más por tupla), es mejor usar strings para este tipo de datos.

**Comment by amparostevens** [comment]
Gracias! 😄
