### ISSUE TITLE
Creacion Esquemas

### ISSUE THREAD

**Issue by Ajbarros1** [IIC2413/Syllabus-2020-2#72]
En el enunciado dicen "Construir un esquema (preliminar, no será evaluado) que contenga solo las tablas y los
nombres de los atributos.". Estos esqumas los tenemos que hacer en alguna página en especial o se pueden hacer en word?

**Comment by juanreutter** [comment]
Hola, tienen que crear tablas en la base de datos (el miércoles van a aprender como), y subir un pdf con el esquema + las consultas.

**Comment by juanreutter** [comment]
Y ponerle una tupla a las tablas también

**Comment by Ajbarros1** [comment]
Pero ese es otro paso o no? Porque ademas dice "Ingresar a su base de datos en el servidor, crear una de sus tablas e ingresar al menos una tupla."

**Comment by juanreutter** [comment]
Claro, el esquema entero lo pones en un word, o cualquier cosa que puedas imprimir a pdf.

**Comment by Ajbarros1** [comment]
Perfecto, gracias!
