### ISSUE TITLE
Relaciones Entrega 1

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2413/Syllabus-2020-2#73]
Holaaa, una duda... para crear las relaciones se espera que creemos tablas que relacionen otras tablas, como por ejemplo la tabla "actuo_en" que se uso en las clases ? (esta relacionaba los id de los actores y las peliculas).

De antemano muchas gracias

**Comment by arpincheira** [comment]
Estas tablas que mencionas se denominan tablas de relación y por lo general se utilizar o se declaran cuando uno posee atributos que sean importantes y se desprendan de la misma. En el caso del proyecto y la entrega 1, lo ideal sería que no declaren tablas de este estilo para esta entrega, dado que existen varias maneras para poder conectar tablas entre ellas(y que verán más adelante).

Espero haber contestado tu duda
