### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by Baelfire18** [IIC2413/Syllabus-2020-2#74]
Hola, como hago que estos archivos
```
 .bash_history
 .bash_logout
 .bashrc
 .cache/
 .profile
```
esten dentro del .gitginore?
intente con `touch .gitignore` y luego `echo "{nombre}" > .gitignore`
Aún así con git status me sale que siguen estando, por lo que el gitignore no los esta haciendo "ser invisible". Da lo mismo si no lo pongo??

**Comment by danustilovsky** [comment]
Hola, Te recomiendo abrir el archivo .gitignore en algun editor de texto y poner directamente los elementos de la lista para revisar que este quedando bien. Despues de hacer eso, git deberia detectarlo automaticamente.

**Comment by arpincheira** [comment]
Hola, lo que dice Dan es correcto, una de las maneras más fáciles de crear y editar el .gitignore es a través de editores de texto, lo otro que podrías hacer pero que no recomiendo es en la consola poner ```nano .gitignore``` lo que te permitirá editar el documento directamente por la consola.

Con respecto a la importancia del .gitignore es que evitas subir el caché al repositorio, lo que al trabajar en conjunto a alguien más evita tener problemas al hacer merge o push(dado que no todos van a tener el mismo caché que tu).

En el caso de que ya hayas hecho git add, puedes revisar [este link](https://stackoverflow.com/questions/30227858/gitignore-exclude-specific-file) y si quieres saber un poco más de git ignore, siempre puedes revisar su documentación [aquí](https://git-scm.com/docs/gitignore). Personalmente te recomiendo visitar también [esta página](https://www.atlassian.com/git/tutorials/saving-changes/gitignore) dado que tiene todo mucho más claro.

**Comment by Baelfire18** [comment]
@arpincheira lo cree desde mi repositorio local del desktop, pero al parece habia modificado el .gitignore,
![image](https://user-images.githubusercontent.com/50716449/91191488-d9c79100-e6c2-11ea-8b0d-13f8f712a57a.png)
me recomiendas escribir `git stash` antes del gitpull? esto no afectará los archivos que escribi antes y solo afectará al .gitignore, cierto??

**Comment by arpincheira** [comment]
Hola, lo que ahí sucede es que posees dos versiones de .gitignore y ambas poseen texto diferente, ahí puedes hacer el git stash, lo que guardaría entonces los cambios realizados en tu gitignore de forma local y revertiría de cierta forma los cambios que habías hecho de manera externa al gitignore.

Una buena práctica es que en tu gitignore incluyas al mismo archivo gitignore, esto evitaría este tipo de problemas y permitiría que cada persona de tu grupo pueda tener su gitignore personal enfocado en los archivos de caché que ha ido creando.

Con respecto a tu pregunta, creo que solo afectaría al gitignore

**Comment by Baelfire18** [comment]
Muchas gracias men!
