### ISSUE TITLE
Duda: cuántos atributos mostrar al momento de mostrar buques

### ISSUE THREAD

**Issue by mariagonthier** [IIC2413/Syllabus-2020-2#75]
Hola!
Cuando nos piden que mostremos los buques no sabemos si con mostrar los atributos que nosotros definimos para buque basta, y eso considera mostrar el id de buques, o si tenemos que mostrar todos los atributos/características de este? (ej: si el buque es pesquero mostrar que tipo de pesca hacen)
Gracias!!!

**Comment by arpincheira** [comment]
Hola, una de las gracias de esta entrega es que sepan identificar los distintos atributos que el enunciado les entrega para las diversas identidades que pueden identificar al interior de este. A modo de **hint** les puedo decir que, si les están dando el tipo de un dato que sirve para describir un objeto que puede llegar a ser importante, lo más probable es que este sea un atributo a considerar de este objeto. 

Espero haber solucionado tu duda.
