### ISSUE TITLE
Duda enunciado

### ISSUE THREAD

**Issue by josejimenezp** [IIC2413/Syllabus-2020-2#76]
Hola,
Quería saber si cuando piden "Muestre todos los puertos" (lo mismo para jefes) se nos pide que mostremos solo el nombre del puerto/jefe o todos los atributos de la tabla puertos/jefe.

**Comment by arpincheira** [comment]
Hola,
las operaciones que realizan para responder las consultas van a ser dependientes del esquema que ustedes definan. De todos modos sería correcto tanto mostrar toda la información de los puertos o de los jefes como sus nombres y sus identificadores(dado que pueden existir dos personas con el mismo nombre pero que sean distintas, así que se requiere alguna manera de distinguirlas).

Espero haber resuelto tu duda.
