### ISSUE TITLE
Error Git remote add origin

### ISSUE THREAD

**Issue by CristobalUrzua** [IIC2413/Syllabus-2020-2#77]
Buenas, 

Con mi compañera de grupo hicimos mal un git remote add origin, ya que creímos que se tenía que hacer rellenando el link "
![image](https://user-images.githubusercontent.com/62025012/91236450-e91bfe00-e705-11ea-9517-06109db8574d.png)
". Pero nunca creamos un repositorio personal. 

Ahora que sí creamos uno, y al hacer git remote add origin la consola nos dice "fatal: remote origin already exists." y no sabemos qué hacer.

Como que hicimos un git remote add origin de un link que no existía. 

Espero su respuesta,

Gracias

**Comment by Vicerc** [comment]
Holaa!
Para eliminar un repositorio de tu lista git remote debes utilizar el siguiente comando:

```git remote rm <repo-name>```

Si no conoces el <repo-name>, puedes utilizar el siguiente comando para obtener una lista de las conexiones remotas que tienes con otros repositorios:

```git remote```

Luego de esto deberían poder agregar su repositorio, avísame si les funcionó!

**Comment by arpincheira** [comment]
Hola, lo otro que podrían hacer es remover la carpeta .git que se crea cuando hacen el ```git init```, esta de cierta forma guarda los comandos de git que han utilizado hasta el momento, por lo que al eliminarla ya no tendrían configurado el servidor para estar conectado a ese repositorio inexistente.

Para remover el .git deben hacer:
```rm -R .git```o ```rm -R -f .git```

Luego van a tener que volver a inicializar git con ```git init``` y una vez hecho esto pueden volver a hacer el 

```git remote add https://github.com/<my user>/<my-repo-name>```
