### ISSUE TITLE
Nombre Repositorio

### ISSUE THREAD

**Issue by francisca0308** [IIC2413/Syllabus-2020-2#79]
Hola! Qué pasa si el nombre que le pusimos al repositorio es BasesDeDatos_GXX en vez de grupoXX? Lo que pasa es que al momento de crearlo, no había ninguna especificación al respecto, sin embargo, después encontramos este requerimento. ¿Es necesario cambiarle el nombre al repositorio? Y de serlo, ¿Cómo se hace?

Desde ya, muchas gracias

**Comment by arpincheira** [comment]
Hola, el nombre que tenga su repositorio da lo mismo dado que deben hacer un git init y no un git clone(en el que si se crearía una carpeta con ese nombre en el servidor), lo único que le pedimos es que sea privado y que dentro del servidor tengan una capeta llamada **Entrega1**.

Espero haber solucionado tu duda
