### ISSUE TITLE
atributo fecha grupo par

### ISSUE THREAD

**Issue by LucaSpiniello** [IIC2413/Syllabus-2020-2#80]
Para manipular el año de una fecha en álgebra relacional sirve el comando % de SQL?, ya que en la pregunta 3 nos piden que el buque haya atracado el año 2020 y no veo otra forma de extraer de la fecha en formato DD/MM/AAAA el año .

**Comment by agustin-rios** [comment]
Hola!

La mejor forma de trabajar fechas en sql es comparando datos del tipo time. Para mayor entendimiento del tema te dejo los siguientes links:

[https://docs.microsoft.com/en-us/sql/t-sql/functions/date-and-time-data-types-and-functions-transact-sql?view=sql-server-ver15](url)

[https://sql.dokry.com/cmo-puedo-comparar-el-time-en-sql-server.html](url)

Espero te sirva!

**Comment by aundurraga** [comment]
Hola! @agustin-rios tenemos la misma duda!  Entendemos como hacer la consulta en sql, pero no como aplicarlo a álgebra relacional. Existe alguna manera de obtener el año de una fecha en álgebra relacional?

**Comment by JaviGuzman** [comment]
Hola! Una duda con respecto a esto, los links que enviaste @agustin-rios , estos son de sql, pero necesitamos trabajar las fechas en álgebra relacional. No sé cómo podemos extraer solo el año de la fecha entera en álgebra relacional, no se puede ocupar el "%" de sql?
Gracias!

**Comment by arpincheira** [comment]
Hola Javi, si quieres una pista de como trabajar con fechas en álgebra relacional, te recomiendo ver la issue #92. lamentablemente no te podemos decir mucho más pues no podemos dar la respuesta. De todos modos espero que te ayude a averiguar aquello que debes hacer. 

Y no, no se puede acceder directamente al año en álgebra relacional y no es buena práctica hacer una columna año(pese a que a veces uno esté tentado en hacerlo).

Te deseo muchísima suerte en esta entrega
