### ISSUE TITLE
[SQL] Error en SQL

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2413/Syllabus-2020-2#81]
Hola! Me aparece este error cuando trato de ejecutar el siguiente comando y no se  a que se debe:
![Captura de pantalla (36)](https://user-images.githubusercontent.com/62029138/91353318-17a6e100-e7b9-11ea-83c4-f85458528626.png)
La tabla con la que trabajo es la siguiente:
![Captura de pantalla (35)](https://user-images.githubusercontent.com/62029138/91353475-5046ba80-e7b9-11ea-810f-24f302ca02f2.png)

**Comment by Vicerc** [comment]
Holaa! Tienes que escribir ```%%sql``` al comienzo de cada bloque en el que quieras escribir código sql.

Saludos!

**Comment by RonaldoSosa** [comment]
Sii era debido a eso , gracias !!!!

**Comment by Vicerc** [comment]
De nadaa :smiley:
