### ISSUE TITLE
Erro en canal de dudas discord

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#82]
Hola, me meto a discord y no me aparece ninguna sección de dudas en el link con el servidor que enviaron, como puedo hacer para que estos aparezcan?
![image](https://user-images.githubusercontent.com/62180259/91356098-1b3c6700-e7bd-11ea-8989-74f880cd41cf.png)

**Comment by fjlopez7** [comment]
ve a reglas y reacciona al comentario de Sub-zero(Bot)
