### ISSUE TITLE
Problema de conectarse al servidor

### ISSUE THREAD

**Issue by pedroherreraj** [IIC2413/Syllabus-2020-2#83]
Hola, hago "git pull origin master" me tira el siguiente error. Que puedo hacer?. El repositorio ya lo cree

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by arpincheira** [comment]
Hola, uno de los motivos por los que puede pasar eso es que el repositorio que creaste sea privado y que las credenciales que ingresaste sean erróneas, creo que [aquí](https://docs.github.com/en/github/authenticating-to-github/error-permission-denied-publickey) hablan más en deatalle sobre el tema así que te podría servir.

Avísame si te sirve y recuerda que nos encontramos hasta las 18:20 resolviendo dudas por discord
