### ISSUE TITLE
Duda Repositorio entrega 1

### ISSUE THREAD

**Issue by fbesoainp** [IIC2413/Syllabus-2020-2#84]
Hola! Quería saber si tenemos que crear la carpeta entrega1 en el directorio grupoxxx@codd: ~$ o tenemos que crear una carpeta /grupoXX/ y ahi crear la carpeta entrega1??

**Comment by arpincheira** [comment]
Hola, lo que debes hacer es crear la carpeta **Entrega1** dentro de la entrada a tu servidor, **no** se pide añadir una carpeta de **grupoXX** 

Espero haber contestado tu duda
