### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by based-on-what** [IIC2413/Syllabus-2020-2#85]
Hola a todos, estaba intentando vincular mi repositorio privado que creé para este ramo en la PowerShell, pero obtuve el mensaje de error que está en el título, ¿a qué se debe? De momento no hay ningún archivo en el repositorio privado, y de momento soy el único miembro de este.

¿Qué se puede hacer? Saludos y gracias.

**Comment by danustilovsky** [comment]
Hola,

Algunas veces hay problemas si el repositorio esta vacio, por lo que recomiendo que le agregues un readme y luego vuelvas a intentar. Al ejecutar que comando te aparece el error?

**Comment by arpincheira** [comment]
Hola, complementando un poco la respuesta de Dan, lo otro que podría suceder es que no has utilizado el comando ```git init```, por lo que actualmente no cuentas con la carpeta oculta denominada .git, te recomiendo que ejecutes ese comando antes de hacer cualquier otra de las operaciones de git al interior del servidor, recuerda que puedes ver [la ayudantía](https://drive.google.com/file/d/1E_0X6rLSObBOl758yfAVFFeG6ngiytCS/view?usp=sharing), la [wiki](https://github.com/IIC2413/Syllabus-2020-2/wiki/Tutorial-Servidor-y-Base-de-Datos-Postgresql) o [esta guía](https://github.com/IIC2413/Syllabus-2020-2/blob/master/Proyecto/Entrega1/Gu%C3%ADa_para_entrega1.pdf) para obtener más información.

Saludos

**Comment by based-on-what** [comment]
@arpincheira @danustilovsky 

Gracias! Efectivamente me faltó escribir `git init`, después de escribir `git remote -v` obtuve el link del repositorio dos veces (push) y (fetch)

**Comment by JaviGuzman** [comment]
Hola, siguiendo la misma duda, donde se debe agregar el .gitignore? Hay que crear un repositorio local en el computador y clonarlo con el repositorio de GitHub, y luego en esa carpeta crear el .gitignore?
Que al hacer esto, me aparece el mismo error de fatal: not a git repository (or any of the parent directories): .git
Luego puse el comando git init, pero aun así no me deja subir el archivo .gitignore (todo esto no lo estoy haciendo conectada al servidor, o debo hacerlo estando conectada al servidor?)

**Comment by arpincheira** [comment]
Hola, la idea es que tu añadas tu archivo .gitignore en la parte más externa de tu repositorio, en este caso **en tu repositorio** al finalizar esta entrega podrías tener **Entrega1**(Con el informe en formato pdf) y un archivo **.gitignore**.

Con respecto al procedimiento que debes hacer para esta entrega, este consiste en lo siguiente:
1. Creas un repositorio de GitHub
2. Clonas tu repositorio en tu computador
3. Al repositorio clonado le añades los archivos que requieras(en este caso la carpeta Entrega1 con el informe al interior de esta y si quieres un .gitignore).
4. Te conectas al servidor
5. Una vez ahí realizas el git init
6. Luego haces git remote ```add origin https://github.com/<my-user>/<my-repo-name> donde <user>``` es tu usuario y <my-repo-name> es el nombre del repositorio que quieres subir
7. Verificas que esté bien usandoo ```git remote -v```
8. Automatizas el proceso de git pull/push/add usando ```git branch -set-upstream-to=origin/master master
9. git pull(para subir los archivos que tenías en tu repo)
10. Disfrutas de tu nuevo repositorio conectado al servidor

En el caso de que quieras saber que archivos añadir a .gitignore, aquí te dejo unas recomendaciones:
```
.bash_logout
.bashrc
.cache/
.gitconfig
.profile
.ssh/
```

Y, si por buenas prácticas quieres evitar que el gitignore vaya moviéndose de un lado a otro, utiliza el comando ```nano .gitignore``` al interior del servidor y añade la línea ```.gitignore```. Esto va a hacer que no se suba tu archivo nuevamente a tu repositorio pese a que lo edites.

No se si respondí correctamente tus dudas, si no fue así avísame por aquí nomás, estaré atento para poder responderte
