### ISSUE TITLE
[SQL] Duda Guía SQL

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2413/Syllabus-2020-2#87]
Hola! En la guía de SQL , en el paso 26  nos indican esto
![Captura de pantalla (48)](https://user-images.githubusercontent.com/62029138/91375918-e561a780-e7e9-11ea-8137-10651e776f73.png)
Sin embargo al intentar ejecutar dichos comando me tiran el siguiente error
![Captura de pantalla (50)](https://user-images.githubusercontent.com/62029138/91376140-6c168480-e7ea-11ea-97e6-c57d8f253f76.png)
Creí que era debido al "Rating" así que lo reemplacé por crating(así esta nombrado ese atributo en la tabla Capitanes) pero me tiro un error también
![Captura de pantalla (51)](https://user-images.githubusercontent.com/62029138/91376260-af70f300-e7ea-11ea-8808-dacb140e20b4.png)

**Comment by arpincheira** [comment]
Hola, probaste quitando el paréntesis redondo?

Avísame si te sirve

**Comment by RonaldoSosa** [comment]
Quitando los paréntesis se solucionó , muchas gracias!!!!
