### ISSUE TITLE
Utilizar todos los items como columnas independientes

### ISSUE THREAD

**Issue by faaceituno** [IIC2413/Syllabus-2020-2#88]
En el enunciado par se pide realizar un esquema y se entregan distintos atributos que se deben tener en cuenta. Mi pregunta es si cada item (navieras, buques, personas, atraque y prox. itinerario) deben ser columnas independientes, ya que me parece que el item proximo itinerario y sus atributos pueden formar parte de BUQUES, añadiendole a este los atributos proximo_puerto y fecha de llegada sin la necesidad de crear una columna nueva.

Es posible realizarlo de esa manera o proximo_itinerario debe ser una columna aparte?

**Comment by danustilovsky** [comment]
Hola! 
Me parece que estas confundiendo columnas y tablas. Una tabla representa una entidad o elemento que puede contener muchos valores. Por ejemplo, Una tabla _personas_ puede tener las columnas _nombre, apellido, rut, direccion_. Si ademas se tiene una tabla Perros que contiene informacion sobre diferentes perros (nombre, raza, edad), tendriamos que tener una tabla extra que permita relacionar a los perros con las personas (dueños), dado que el juntar toda la informacion en una sola tabla haria que tuvieramos mucha informacion redundante. 

Entonces en la entrega debes generar tablas que te permitan contener toda la informacion de los diferentes "items" (donde las columnas serian la informacion que deseas almacenar) y agregar tablas que te permitan hacer la relacion de ser necesario (puede que no lo sea).
