### ISSUE TITLE
Duda tabla próximo itinerario grupo par

### ISSUE THREAD

**Issue by mpbascunan** [IIC2413/Syllabus-2020-2#89]
Holaa, al intentar crear el esquema nos surgió una duda en la tabla Próximo itinerario acerca de la descripción que se menciona que se debe guardar del puerto, ¿qué tipo de información de este se guarda? ¿sus atributos? ¿o sólo un string que lo describa?

**Comment by arpincheira** [comment]
Hola, efectivamente es algo bastante complicado lo que vendría siendo la información que se guarda del puerto, yo te recomendaría que consideres todo lo necesario para poder contestar las dudas de álgebra relacional que se encuentran y que incluyen esta información(como lo es la consulta 3) y que escribas una justificación de los supuestos que realices. 

Espero haber respondido tu duda.
