### ISSUE TITLE
Operadores

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2413/Syllabus-2020-2#9]
Hola, tengo una duda, existe algun operador que compara verticalmente las tuplas ?, de no ser asi, en el control puedo definir un operador, por ejemplo ASC (de ascendente) para hacer las consultas ? (algo asi como un supuesto).

De antemano, muchas gracias.

**Comment by arpincheira** [comment]
Hola, lamento la demora, los operadores que vieron en clases son suficientes para poder resolver todas las consultas que se encuentran en el control, de todos modos, a modo de **Hint** te puedo decir que podrías considerar utilizar la misma tabla más de una vez para una consulta(para realizar esto deberías crear una tabla igual pero con otro nombre).

Con respecto a tu duda de definir operadores del tipo ASC no está permitido dado que estaría fuera de lo que viene siendo la lógica del Álgebra relacional.

Espero haberte ayudado.

**Comment by DiegoPibe** [comment]
oka, muchas gracias !!!
