### ISSUE TITLE
Enlazar Carpeta con Repositorio

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2413/Syllabus-2020-2#90]
Hola! Tengo un problema , lo que pasa es que elimine el  repositorio inicial con el que había enlazado la cuenta de grupo y cuando intente enlazarlo con uno nuevo que acabo de crear no me funciona , cual seria la forma correcta de hacerlo.
![Captura de pantalla (53)](https://user-images.githubusercontent.com/62029138/91564847-41721c00-e90f-11ea-967e-75a8663ab8f3.png)

**Comment by arpincheira** [comment]
Hola, prueba utilizando el comando ```rm -R -f .git```eso debería eliminar la carpeta .git que tienes oculta en tu usuario del servidor.

Avísame si funciona.

**Comment by RonaldoSosa** [comment]
Si ahora pude enlazarlo nuevamente , gracias !!
