### ISSUE TITLE
[Entrega 1] Problema al hacer git commit 

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2413/Syllabus-2020-2#91]
Hola!Luego de clonar el repositorio creado intente subir la Entrega 1 , intente subir toda una carpeta, pero al momento de hacer el git commit me aparece el siguiente mensaje, y cuando intente hacer git push no ocurrió ningún cambio en el repositorio
![Captura de pantalla (54)](https://user-images.githubusercontent.com/62029138/91573692-f65b0780-e914-11ea-8be5-252fe5e38c6b.png)

**Comment by arpincheira** [comment]
Hola, creo que podría ser porque estás tratando de subir la carpeta sin ningún archivo en su interior, si ese es el caso, podrías probar añadiendo un archivo como un README.md e intentar subir nuevamente la carpeta pero con este nuevo archivo.

Avísame si te funciona.

**Comment by RonaldoSosa** [comment]
Si con eso ya me funcionó, sin embargo, tengo otro problema el cual es que al intentar hacer git pull origin master en power shell este me tira este mensaje 
![Captura de pantalla (55)](https://user-images.githubusercontent.com/62029138/91578848-c0b81d80-e918-11ea-8885-7508de0dd846.png)
y también como se ve en la imagen no me aprece la nueva carpeta ""Entrega1

**Comment by arpincheira** [comment]
Hola, em ... a lo que me refería antes era que al interior de Entrega1 pusieras un archivo denominado ```README.md```.

Lo que sucede en tu imagen es que probablemente tienes dentro del servidor un archivo denominado README.md y en tu repositorio tienes uno con el mismo nombre, por lo que hacer el ```git pull origin master``` te advierte que el archivo en el servidor y en tu repositorio van a colisionar y se va a sobrescribir uno de los dos. Para evitar eso debes eliminar uno de los archivos, una manera es con git rm <nombreArchivo>

**Comment by RonaldoSosa** [comment]
Si lo que pasa es que al momento de crear el repositorio se creo ese README.md , en la carpeta de Entrega 1 tambien habia un README.md el cual cree debido a la indicación anterior, quite ese README.md ,el de la carpeta Entrega 1 y en su lugar subi un PDF , sin embargo no me permite borrar el README.md que se creo al crear al repositorio 
![Captura de pantalla (57)](https://user-images.githubusercontent.com/62029138/91587144-602edd80-e924-11ea-8e73-8858a7ef2a49.png)
