### ISSUE TITLE
[Entrega 1] Atributo Fecha de Ingreso para la tabla Atraques

### ISSUE THREAD

**Issue by BenjaLepe** [IIC2413/Syllabus-2020-2#92]
Hola! tengo una duda con respecto a la Entrega 1, cuando debemos hacer una consulta sobre el año de en que un Buque ingresa a un Puerto, como podemos obtener únicamente el año de ingreso con **algebra relacional**? Ya que la fecha de Ingreso tiene Día / Mes / Año.

**Comment by arpincheira** [comment]
Hola, te recomiendo revisar la issu #80, ahí hablan sobre el tema y dan un **hint** que te podría ser útil

**Comment by DiegoPibe** [comment]
Hola, yo vi esa issu #80 y ahí los links que dejaron solo explican como comparar fechas en sql, pero a nosotros nos piden específicamente hacer la consulta con álgebra relacional, entonces estoy un poco perdido, no se si hay que hacer esa consulta con lenguaje sql o álgebra relacional.

**Comment by arpincheira** [comment]
La consulta la deben hacer en álgebra relacional, lo importante de esa issue era lo que dijiste de **comparación de fechas**, ahora lo que deben buscar(no se los puedo decir a priori dado que les estaría dando la respuesta) es:

Existe alguna manera de poner condiciones para filtrar filas de una tabla dentro de álgebra relacional?(para poder hacer la comparación de fechas)

**Comment by BenjaLepe** [comment]
@arpincheira  Perdón, pero sigo sin entender como filtrar según el año en algebra relacional. Lo que se me había ocurrido era dividir la columna fecha de ingreso, en 3 columnas diferentes pero lo encuentro super poco eficiente :( 

Como puedo filtrar las filas solo por el mes o el año de la fecha sin fijarme en el día? Porque como dijo @DiegoPibe la issue permite hacerlo en SQL, pero en algebra relacional es super básico como para pasar el date a float.

**Comment by BenjaLepe** [comment]
@arpincheira  Buena ya caché como hacerlo, gracias 👍
