### ISSUE TITLE
[Entrega 1] No deja Ingresar Password

### ISSUE THREAD

**Issue by Molin1234** [IIC2413/Syllabus-2020-2#93]
Hola resulta que al intentar establecer conexión con el servidor en la PowerShell utilizo ssh grupo54@codd.ing.puc.cl, luego me pide ingresar la contraseña pero no me deja escribir, solo apretar enter.

Pensé que era problema del PowerShell así que descargue Putty, y el mismo problema, al pedir la contraseña no puedo escribir nada.

**Comment by castrillini** [comment]
Hola, generalmente al escribir la contraseña no se muestra en la terminal. Pero sí se está escribiendo.
Avisas cualquier cosa!

**Comment by Molin1234** [comment]
Aaa vale jaja muchísimas gracias!
