### ISSUE TITLE
duda consultas 2 y 3

### ISSUE THREAD

**Issue by mmunoz12** [IIC2413/Syllabus-2020-2#94]
Hola! tengo unda duda con respecto a lo que se pide en estas consultas. Cuando se pide  que se  "muestre todos los buques...", se refiere a que debemos entregar solo los atributos que resultaran de la tabla` Buques ` (y con sus filtros pedidos) o que se entregue todo lo que resulte del cruce entre las tablas a utilizar?? Espero que se haya entendido, gracias!.

**Comment by fjlopez7** [comment]
Debes mostrar todos los atributos que tengas en tu tabla de Buques. 
Como se menciona en el enunciado: 

![imagen](https://user-images.githubusercontent.com/42160988/91620320-9b99ce00-e95d-11ea-9f73-c205b201d3d3.png)
