### ISSUE TITLE
nombres columnas

### ISSUE THREAD

**Issue by rieg-ec** [IIC2413/Syllabus-2020-2#95]
Hola!, me surgio una de duda: que conviene mas en el caso de que varias relaciones tengan un atributo con el mismo nombre (ej. 'nombre'), diferenciar al crearlas (ej. que en los barcos sea nombre_barco, en las instalaciones sea nombre_instalacion) o en caso de necesitar hacer join renombro las columnas?

**Comment by mariajesusbraun** [comment]
Hola! Creo que te convendría diferenciarlas al crearlas, pero puedes hacer lo que te acomode más a ti.
