### ISSUE TITLE
Subir archivos al repositorio de GitHub desde PowerShell Windows 10

### ISSUE THREAD

**Issue by based-on-what** [IIC2413/Syllabus-2020-2#96]
Hola a todos, tengo serias dudas sobre cómo proceder después de conectarme al repositorio privado, usé el comando "set origin to master" o algo así, pero no logro entender bien cómo subir archivos, en el vídeo el ayudante abre una nueva ventana en PowerShell, pero yo no tengo esa opción (uso Windows 10), finalmente subí desde la página de github la carpeta de Entrega1
![ayuda3](https://user-images.githubusercontent.com/62000495/91650255-315f5700-ea4b-11ea-9c9b-b7026ad9a7ef.PNG)
![ayuda2](https://user-images.githubusercontent.com/62000495/91650256-32908400-ea4b-11ea-9787-efa7e634df87.PNG)
![ayuda1](https://user-images.githubusercontent.com/62000495/91650257-33291a80-ea4b-11ea-878c-19320afe0575.PNG)
Al momento de conectarme no sé cómo proceder, no sé si conviene "desconectarme" del repositorio desde powershell y empezar de 0 o no, siento lo neófito pero no logro ver bien cómo subir correctamente archivos desde PowerShell.

Gracias.

**Comment by danustilovsky** [comment]
Hola, 

Yo hice la ayudantia. En el caso de la ayudantia, solo abri otra terminal por comodidad. Pero el procedimiento para subir los archivos es el siguiente:

1.  Crear el repositorio privado de github para tu grupo
2. Hacer git clone en tu computador, copiar los archivos necesarios y subirlos a tu repositorio (git add/commit/push)
3. conectarte a tu servidor desde la terminal y seguir el tutorial de la wiki del curso para poder linkiar tu repositorio con la carpeta principal del servidor.
4. Una vez que hayas hecho todo lo anterior, puedes trabajar en el servidor como si fuera un repositorio, por lo que si deseas copiar en el servidor aquello que pusheaste desde tu computador, basta con hacer *git pull*, y todos los cambios se deberian ver reflejados.

Avisame si te queda cualquier duda!

**Comment by based-on-what** [comment]
> Hola,
> 
> Yo hice la ayudantia. En el caso de la ayudantia, solo abri otra terminal por comodidad. Pero el procedimiento para subir los archivos es el siguiente:
> 
> 1. Crear el repositorio privado de github para tu grupo
> 2. Hacer git clone en tu computador, copiar los archivos necesarios y subirlos a tu repositorio (git add/commit/push)
> 3. conectarte a tu servidor desde la terminal y seguir el tutorial de la wiki del curso para poder linkiar tu repositorio con la carpeta principal del servidor.
> 4. Una vez que hayas hecho todo lo anterior, puedes trabajar en el servidor como si fuera un repositorio, por lo que si deseas copiar en el servidor aquello que pusheaste desde tu computador, basta con hacer _git pull_, y todos los cambios se deberian ver reflejados.
> 
> Avisame si te queda cualquier duda!
> 
> PD: La terminar que utilizo en la ayudantia es "Windows terminal" que se descarga desde la store y permite, entre otras cosas muy bacanes, abrir multiples tabs.

Hola, esto hice:
![ayiuda32](https://user-images.githubusercontent.com/62000495/91664924-44603e80-eac0-11ea-8809-283eaa002520.PNG)
Ya me perdí en esto :/

**Comment by danustilovsky** [comment]
Hola! 

Vamos por partes:

-  Cuando hiciste git branch --set-upstream-to=origin/master master eso funciono y en pocas palabras le dijiste al servidor que al hacer pull quieres que te traiga lo que esta en la branch master del repositorio.

- Cuando hiciste git branch --set-upstream-to=origin/origin master eso  no funciono porque no existe una branch origin. 

- Al hacer git pull, el servidor te esta avisando que ingresaste mal los datos de tu cuenta de git. 

Ahora deberias volver a hacer git pull y asegurarte de ingresar bien los datos. Una vez hecho eso, utiliza el comando "ls" para ver los archivos que hay en el servidor. Deberian aparecer los que pusheaste desde tu computador al repositorio.

**Comment by based-on-what** [comment]
> Hola!
> 
> Vamos por partes:
> 
> * Cuando hiciste git branch --set-upstream-to=origin/master master eso funciono y en pocas palabras le dijiste al servidor que al hacer pull quieres que te traiga lo que esta en la branch master del repositorio.
> * Cuando hiciste git branch --set-upstream-to=origin/origin master eso  no funciono porque no existe una branch origin.
> * Al hacer git pull, el servidor te esta avisando que ingresaste mal los datos de tu cuenta de git.
> 
> Ahora deberias volver a hacer git pull y asegurarte de ingresar bien los datos. Una vez hecho eso, utiliza el comando "ls" para ver los archivos que hay en el servidor. Deberian aparecer los que pusheaste desde tu computador al repositorio.

Gracias nuevamente @danustilovsky , acabo de conectarme correctamente y subir los archivos desde el computador localmente.
