### ISSUE TITLE
Error al hacer git add

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2413/Syllabus-2020-2#97]
Hola hice esto como se dice en la ayudantia
![image](https://user-images.githubusercontent.com/62180259/91665106-3fe85580-eac1-11ea-8257-2f2ae7cf5d1c.png)

Luego procedí a ir a mi carpeta que cree en mi computador con el mismo nombre que la de mi repositorio y me tira este error
![image](https://user-images.githubusercontent.com/62180259/91665062-09aad600-eac1-11ea-8265-1ea31b6ada53.png)

No entiendo como linkear el repositorio que cree "ProyectoBD" con la carpeta que cree en mi computador "ProyectoBD", pense que se linkeaba al tener el mismo nombre las carpetas, no es asi ??

**Comment by danustilovsky** [comment]
Hola, para que las carpetas esten conectadas no basta que tengan el mismo nombre.

Lo primero que debes hacer _git clone_ de tu repositorio en tu computador. Una vez hecho eso, agregas los archivos o carpetas que quieras dentro de el y debes seguir los pasos tipicos para agregar archivos a un repositorio:  git add - git commit - git push.
Una vez hecho esto, todos los archivos que pusheaste quedan guardados en tu repositorio, para revisar esto pueden meterte por internet a git y al revisar tu repositorio deberian aparecerte.

La segunda parte tiene que ver con el servidor. Lo que vimos en la ayudantia solo se debe hacer una vez ( git init, git remote add ...). Por lo que veo, tu servidor ya tiene linkeado un repositorio git en origin, por lo que te aparece el error. 

Este comando deberia mostrarte informacion de que es lo que tiene linkeado: _git remote show origin_, para que puedas ver si es tu repositorio. Si eso esta bien, deberias poder hacer git pull origin master y descargar los archivos del repositorio al servidor

**Comment by dsepulveda3** [comment]
Buena perfect, ya lo hice
![image](https://user-images.githubusercontent.com/62180259/91665961-585b6e80-eac7-11ea-9587-6c1c5e980065.png)

Ahora como puedo saber donde quedo esa carpeta clonada en mi computador?
Después de cachar donde esta la carpeta clonada, puedo mover esta carpeta dentro de otra en mi computador sin ningún problema ?

**Comment by danustilovsky** [comment]
Por lo que veo, hiciste el clone en tu servidor, que no es lo que debias hacer, dado que como explicamos en la ayudantia te va a traer problema con el nombre de las carpetas. Por lo que te recomiendo borrarlo.

Lo que debes hacer es: 

- Ocupar git clone en tu computador privado para poder pushear los archivos a tu repositorio.
- Ocupar lo visto en la ayudantia (tercera opcion/ git init) para poder subir tus archivos al servidor.

Al hacer git clone en tu computador la carpeta se guardara en el lugar donde este abierta la terminal, por lo que te recomiendo utilizar el comando "cd" para moverte hasta la carpeta donde quieres dejar la carpeta y luego ejecutar el comando git clone.

Con respecto a la segunda pregunta, no hay problema en mover carpetas dentro del computador.

**Comment by dsepulveda3** [comment]
ufff ya dale jajaj. Estoy entero confundido.
Como borro el clone que le hice al servidor ?
Que clone debo hacer entonces ? No estoy entendiendo eso.

**Comment by danustilovsky** [comment]
Para borrar el git clone del servidor ocupa este comando: "rm -rf <nombre-repositorio>".

Para hacer el git clone en tu computador:

1. abrir la terminal y moverte hasta la carpeta donde quieras dejar la carpeta del repositorio
2. utilizar git clone <link repo>

Con eso ya queda clonado en tu computador y puedes subir archivos usando git add/commit/pull.

Para la parte del servidor, te recomiendo seguir el paso a paso en la [wiki](https://github.com/IIC2413/Syllabus-2020-2/wiki/Tutorial-Servidor-y-Base-de-Datos-Postgresql#opci%C3%B3n-1-utilizar-un-repositorio-de-git)

**Comment by JaviGuzman** [comment]
Hola, tengo una duda parecida. Estaba tratando de subir la entrega1, pero al hacer git pull en el servidor me aparece esto
![Captura de Pantalla 2020-08-31 a la(s) 16 53 48](https://user-images.githubusercontent.com/48359777/91767685-8bc2f980-ebaa-11ea-96ac-1a43d04880ed.png)
Pero al poner el comando de git branch, aparece que 
![Captura de Pantalla 2020-08-31 a la(s) 16 55 56](https://user-images.githubusercontent.com/48359777/91767881-d80e3980-ebaa-11ea-9e08-cc45f5968af0.png)
Luego puse el comando git remote show origin y apareció
![Captura de Pantalla 2020-08-31 a la(s) 16 56 30](https://user-images.githubusercontent.com/48359777/91767950-ec523680-ebaa-11ea-81dc-514e50f3cbb3.png)

No se qué estamos haciendo mal, por si nos podrían ayudar a subirlo por favooor

**Comment by arpincheira** [comment]
Hola, una duda, copiaron la línea tal cual aparece en la consola?

Porque si es así prueben escribiendo ```git branch --set-upstream-to=origin/master master``` y avisen si les funciona

**Comment by JaviGuzman** [comment]
No, puse el mismo link que escribiste recién

**Comment by arpincheira** [comment]
y si prueban con ```git pull origin master```?

**Comment by JaviGuzman** [comment]
Me apareció esto, no se si está bien
![Captura de Pantalla 2020-08-31 a la(s) 17 17 56](https://user-images.githubusercontent.com/48359777/91769729-ead63d80-ebad-11ea-8223-4badf986cddd.png)

**Comment by arpincheira** [comment]
Efectivamente, ahora si haces ls deberían aparecer los archivos de tu repositorio, ahora, para no tener problemas a futuro les recomiendo hacer ```git branch --set-upstream-to=origin/master master```.

**Comment by JaviGuzman** [comment]
Graciaaas! Una duda aparte. Se subieron hartos archivos de prueba que estabamos utilizando. Cómo hago para eliminarlos del servidor?

**Comment by arpincheira** [comment]
Hola, lamento mucho la demora(me acaba de llegar la notificación del mensaje), pueden hacerlo borrando los archivos del repositorio que tienen clonado, subir los cambios y hacer un pull desde el servidor.

Otra manera es haciendo un ```git rm -R(si es una carpeta) <nombreArchivo>```. En el caso de que los quieran borrar del servidor y no del repositorio, el comando que les recomiendo es ```rm -R(nuevamente solo si es una carpeta) -f <nombreArchivo>```.

Espero que les sirva.
