### ISSUE TITLE
Cómo deslinkear una carpeta

### ISSUE THREAD

**Issue by Camila-sty** [IIC2413/Syllabus-2020-2#98]
Hola.
Resulta que tengo una duda. Cuando cree la carpeta en mi repositorio, lo hice mal, pero me di cuenta cuando debía escribir "git pull origin master", pero ya había linkeado esta carpeta llamada "proyecto". Al crear la nueva carpeta, empecé el procedimiento de nuevo con esta nueva carpeta llamada "BDD", pero no puedo porque está linkeada con la carpeta "proyecto", la cual ya la eliminé de mi repo. 
![image](https://user-images.githubusercontent.com/59337116/91666080-1e3e9c80-eac8-11ea-87b6-a91c398f5daa.png)
cómo puedo deslinkear esta carpeta "proyecto" que ya no existen en mi repositorio?

**Comment by danustilovsky** [comment]
Hola! los datos de git se guardan en .git, una carpeta que se crea automaticamente. Por lo que si deseas eliminar los datos de lo hecho con respecto a git hasta el momento en tu servidor debes de eliminarla y empezar de nuevo. 

Para hacer eso, este comando deberia servir: "rm -rf .git"

**Comment by Camila-sty** [comment]
pero donde ejecuto ese comando?

**Comment by danustilovsky** [comment]
En la carpeta home de tu grupo. Es donde te deja el servidor una vez que te conectas.
